### ISSUE TITLE
Daily (unstable) builds?

### ISSUE THREAD

**Issue by LowLevelMahn** [NationalSecurityAgency/ghidra#1019]
to easily test if problems that occure are maybe already fixed in master

for example: i want to test the DOS MZ fixes and other stuff

**Comment by ryanmkurtz** [comment]
People who are interested in daily testing have just been building Ghidra themselves, which should be pretty easy to automate once you get it building for the first time.  This is actually more valuable to us since it also tests the build on a wide variety of platforms, instead of just our limited set.  That is our recommended course of action.

**Comment by LowLevelMahn** [comment]
i don't get your rational because your official release is of equal value (limited set)
would you recommend to build the releases also by myself or just grab the build from the homepage?

i was just talking about feature tests, not platform tests

**Comment by ryanmkurtz** [comment]
In addition to what I said, there would be a lot of overhead in providing daily unstable builds, because we don't even have that ourselves internally at the moment.  One of the nice benefits of going open source is so we don't have to do this in order for people to test our latest stuff, which is very much a moving target.  I think it's been working so far.

Of course I agree it would be better if there were daily unstable builds, but everything comes at a cost, and putting the infrastructure in place to support this would take away from something else.  We would rather spend the time and energy in improving the build, and addressing as many feature/fixes as possible.

To answer your question about the releases, I recommend you just grab the build from the homepage (unless of course you actually want to test the build).

**Comment by LowLevelMahn** [comment]
> Of course I agree it would be better if there were daily unstable builds, but everything comes at a cost, and putting the infrastructure in place to support this would take away from something else.

that makes it clear

i will try to build ghidra on my own later: are there any build instructions for win 7 x64 - i can't find any description

**Comment by ryanmkurtz** [comment]
Yes, those are the instructions to use.  The key things for building on Windows is you need Visual Studio 2017.  When you install it make sure to enable/install the Windows 8.1 SDK (it's a checkbox in the VS17 installer program).  You also need to install bison and flex, and rename the binaries according to the DevGuide instructions.

**Comment by LowLevelMahn** [comment]
thanks
