### ISSUE TITLE
PIE base address to 0

### ISSUE THREAD

**Issue by bannsec** [NationalSecurityAgency/ghidra#1020]
**Is your feature request related to a problem? Please describe.**
Irritating and confusing sometimes when default base is not loaded in at 0...

**Describe the solution you'd like**
Default PIE binaries should have a default base of 0x0.

**Describe alternatives you've considered**
Ability to rebase after opening (can't find how to do this).

**Additional context**
Had been getting very confused when reversing a CTF challenge about why Ghidra's addresses seemed to be very off compared to where I'd find them in the running binary (accounting for ASLR and all that). Later discovered that it's due to a default base address of 0x1000. Not sure why this was chosen, but attempting to use offsets in Ghidra's output for a running program now requires also subtracting that 0x1000 first prior to using the value. This seems unnecessarily complicated. Base at 0 for those binaries that don't have a set base seems to be common with other tools such as IDA and makes sense when attempting to use the values from static reversing in dynamic analysis.

**Comment by astrelsky** [comment]
I'm not sure if either of these are actually what you are referring to. It appears that you can change 'ELF Original Image Base' by going to edit -> options for 'binary_name' -> Program Information and the field is there.
When adding the binary to ghidra (where you select the binary Format, language, destination folder, etc.) after clicking the options button there is a field to change the Image Base.

**Comment by bannsec** [comment]
Right. So here's an example of what I'm talking about:

PIE Binary:
 - IDA Image Base: 0x0
 - radre2 Image Base: 0x0
 - Ghidra Image Base: 100000

I'm unsure why such a base was chosen in any case for Ghidra. For instance, if I am debugging a PIE process and would like to look at an offset that I discovered using Ghidra, instead of examining module_base + offset, it becomes module_base + offset - 100000.

I guess i just don't see the advantage of requiring an extra step in calculating the running address.

**Comment by astrelsky** [comment]
> Right. So here's an example of what I'm talking about:
> 
> PIE Binary:
> 
> * IDA Image Base: 0x0
> * radre2 Image Base: 0x0
> * Ghidra Image Base: 100000
> 
> I'm unsure why such a base was chosen in any case for Ghidra. For instance, if I am debugging a PIE process and would like to look at an offset that I discovered using Ghidra, instead of examining module_base + offset, it becomes module_base + offset - 100000.
> 
> I guess i just don't see the advantage of requiring an extra step in calculating the running address.

You can also change the image base through the Program interface.

Running currentProgram.setImageBase(toAddr(0), False) in the python window should get the job done.

**Comment by ghidra1** [comment]
For ELF import, a non-zero image base is suggested when a preferred non-zero image can not be determined from the load image.  Various analyzers currently avoid speculating about low value constants which may or may not be an address.  Identification of memory references is more reliable when an image is imported to a higher address since low value non-address constants are quite common in code.  As pointed out by @astrelsky the import image base can be set via the import options panel.

**Comment by crashingstatic** [comment]
This is beyond annoying and has been for YEARS. Ghidra's devs should be ashamed that such an easy fix has been a bug for as long as it has. This issue is still open and unresolved.

You should also implement relative addressing WITHIN the symbols for PIE. This isn't exactly a new feature considering PIE has been around for over 20 years now.

Here a script in the meantime that will rebase your PIE ELFs:
https://gist.github.com/crashingstatic/69aff7ded30558d600cc52231ce5c0d0

**Comment by astrelsky** [comment]
> This is beyond annoying and has been for YEARS. Ghidra's devs should be ashamed that such an easy fix has been a bug for as long as it has. This issue is still open and unresolved.
> 
> You should also implement relative addressing WITHIN the symbols for PIE. This isn't exactly a new feature considering PIE has been around for over 20 years now.
> 
> Here a script in the meantime that will rebase your PIE ELFs: https://gist.github.com/crashingstatic/69aff7ded30558d600cc52231ce5c0d0
> 
> Note the use of the term "Duct-taping" in the code comments.

You are **wrong**. Setting the image base to 0 is **a terrible idea**. You should be able to tell whether a value is a pointer or an integer by looking at it in the listing.

**Comment by ghidra1** [comment]
> This is beyond annoying and has been for YEARS. Ghidra's devs should be ashamed that such an easy fix has been a bug for as long as it has. This issue is still open and unresolved.
> 
> You should also implement relative addressing WITHIN the symbols for PIE. This isn't exactly a new feature considering PIE has been around for over 20 years now.
> 
> Here a script in the meantime that will rebase your PIE ELFs: https://gist.github.com/crashingstatic/69aff7ded30558d600cc52231ce5c0d0
> 
> Note the use of the term "Duct-taping" in the code comments.

@crashingstatic that was rather harsh.  As backed by @astrelsky comment this is the reason we avoid basing at 0 (which is also arbitrary) since it makes it more likely that a pointer offset will be impossible to distinguish from a simple constant or pointer-relative offset.  With an individual file import, users may specify an image base option of 0 if  they choose to.

**Comment by crashingstatic** [comment]
Okay that was a little mean: Ghidra is a great product that I love and use every day and I appreciate all the work that gets put into it by both volunteers and employees alike.

However, Ghidra should be smart enough to determine if the file has PIE enabled at which point it could display relative addresses as relative addresses rather than displaying an incorrect address starting at base 0x10000. Basing at 0 **is** a duct-taped solution (note the use of "duct-taping" in the code comments of the script I posted). The actual fix would be having Ghidra do whatever it wanted under the hood to make the constants distinguishable from pointers, but have it display relative offsets when it detected that it was dealing with PIE.

This **is** an annoying issue, especially when you're analyzing thousands of files with this same issue.

**Comment by astrelsky** [comment]
> Okay what I said was a little mean: Ghidra is a great product that I love and use every day and I appreciate all the work that gets put into it by both volunteers and employees alike.
> 
> However, Ghidra should be smart enough to determine if the file has PIE enabled at which point it could display relative addresses as relative addresses rather than displaying an incorrect address starting at the arbitrary base of 0x10000. Basing at 0 **is** a duct-taped solution (note the use of "duct-taping" in the code comments of the script I posted). The actual fix would be having Ghidra do whatever it wanted under the hood to make the constants distinguishable from pointers, but have it display relative offsets when it detected that it was dealing with PIE.
> 
> This **is** an annoying issue, especially when you're analyzing thousands of files with this same issue.

The **real address** is the address is determined by whatever loads the executable into memory. Since Ghidra is the one loading the executable in this context, the arbitrary address it chooses (which you are free to override), **is the correct address**.
