### ISSUE TITLE
GUI performance

### ISSUE THREAD

**Issue by partoftheworlD** [NationalSecurityAgency/ghidra#104]
Once in a while, there is a problem worsening the responsiveness of GUI. There are no errors, any dependence, the problem happens after 10-50 minutes or 2 hours. Is there any solution of the problem? 

Thanks.

**Comment by Ristovski** [comment]
Are you sure a view like the "Defined Strings" view isn't getting updated by you changing something? Since that would require a re-sort of the strings etc.

I can not replicate your issue, I just closed my Ghidra session of 3+ hours and I noticed no UI performance regressions out-of-the-blue.

**Comment by partoftheworlD** [comment]
> Are you sure a view like the "Defined Strings" view isn't getting updated by you changing something? Since that would require a re-sort of the strings etc.

Thanks for answer. Of course, i used only disassembler listing.
Here's a video with default preset.
https://www.youtube.com/watch?v=jAWcVpYcPjs

**Comment by chrismiller** [comment]
You could try allocating more memory to Ghidra. If the JVM starts to run low on heap it will trigger a lot of garbage collections which might result in the behaviour you're seeing. This might be normal, or might be due to a memory leak in Ghidra that slowly causes the heap to fill up over time, depending on what functionality you're using. You can get stats on Ghidra's garbage collection by running "jstat -gc <pid> 1000" from the jdk/bin directory.

**Comment by partoftheworlD** [comment]
Well, after testing, it turned out it's a problem with rendering only in WIndows. In MacOS and Linux GHIDRA works fine.
