### ISSUE TITLE
DevGuide.md is not available on Contributors Guide

### ISSUE THREAD

**Issue by Kaitouiet** [NationalSecurityAgency/ghidra#11]
**Describe the bug**
Link does not exist to dev guide

**To Reproduce**
1. Go to https://github.com/NationalSecurityAgency/ghidra/blob/master/CONTRIBUTING.md
2. Scroll down to 'Getting Started'
3. Click on developer's guide

**Expected behavior**
Page Not Found.

**Screenshots**
![image](https://user-images.githubusercontent.com/38592544/53848865-f11d3680-3f83-11e9-9570-258708cdc564.png)

**Environment:**
 - Browser: Chrome

**Additional context**
It may be already known but just heads up.

**Comment by ctubbsii** [comment]
Thanks for the heads up, @Kaitouiet ; This issue should be automatically resolved as the repository gets populated with code/docs. I'm going to close this for now, because I don't think we need to track this right now. However, please feel free reopen if the issue persists after the code/docs are added to the repo.
