### ISSUE TITLE
Typos in error messages

### ISSUE THREAD

**Issue by hadess** [NationalSecurityAgency/ghidra#1114]
There are 2 typos, both of which are visible in the running software, which you can find by [doing a search](https://github.com/NationalSecurityAgency/ghidra/search?q=installion&unscoped_q=installion).

"installion" should be "installation"

https://github.com/NationalSecurityAgency/ghidra/blob/49c2010b63b56c8f20845f3970fedd95d003b1e9/Ghidra/Framework/Project/src/main/java/ghidra/framework/plugintool/dialog/ExtensionTableModel.java#L129

https://github.com/NationalSecurityAgency/ghidra/blob/49c2010b63b56c8f20845f3970fedd95d003b1e9/Ghidra/Framework/Project/src/main/java/ghidra/framework/plugintool/dialog/ExtensionTableProvider.java#L129

**Comment by Hardcore-fs** [comment]
Can a start be made on pulling all constant textual entries out into a separate java/system file that references standard string names.
it's going to make two things easier.
1. Checking for grammatical & spelling errors.
2. allowing drop in language packs.

**Comment by dragonmacher** [comment]
This is a resource intensive effort, which is not likely to make the top of our priority list.   I have seen others use Python to hack together a solution to achieve this effect at runtime, without changing the Java code base.   Such a script could be put together and shared by the external community.  Unfortunately, I cannot point you to an example of such a script.

**Comment by kant2002** [comment]
What if you will be just gatekeepers for such changes, but not do them themselves ?

**Comment by dragonmacher** [comment]
That would depend upon how complicated any given pull request is.  Something at this scale could touch a very large portion of the code base, making it very expensive for us to integrate/test/support.

I hope that some features and workarounds will be implemented and shared by the community.  This would allow the tool to grow in areas that cannot or have not gotten to.

**Comment by Hardcore-fs** [comment]
Yes , you are not kidding... it is a  large refactor....
Possibly  A start could be made  on new items to tie it in.. then as text strings are updated it could be migrated over
Just requires  someone to say yep this is how we want to do it... then perhaps some community members could get involved... to go thru and do the clean up...

**Comment by dragonmacher** [comment]
I18n is probably the right idea.

Most of our menus items, popup menus and buttons are built through one since class, the DockingAction.   It is possible that code could be added to this one class that would allow a lookup into a mapping file, using the action's name, to find alternate display text for menu items and button descriptions.    I imagine a change such as this will touch very little code, but would cover a large number of UI widgets.

What this would not cover are the various dialog messages used throughout the system.  Those would probably have to be edited directly, which is much more work.
