### ISSUE TITLE
Reduce Entries Saved In History Buffer

### ISSUE THREAD

**Issue by ebfe2326** [NationalSecurityAgency/ghidra#1115]
**Is your feature request related to a problem? Please describe.**
The history buffer that allows you to go back and forth between previous selected instructions contains so many entries that it makes it nearly unusable.  It seems to save every address you select that is in a new code block instead of just important addresses. 

**Describe the solution you'd like**
I recommend updating the history buffer to just save addresses where the user double clicks **and** the address changes.  In essence, I believe this option should be updated to match all of the other competing tools such as Ida Pro.

The primary use case for the history buffer is to go back and forth between functions the user has visited, and to a lesser extent, data variables, graph edges that were clicked to be followed, etc.

I've tried my best but can't think of any use case where you would need or want to visit every code block that has been selected.  With the current setup, the history buffer often gets filled within a single function you are analyzing so that you either can't even get back to the parent function, or it takes 5 minutes of traversing the history buffer.

Fixing this is a user interface issue would relieve a significant pain point in using ghidra to reverse engineer files.  The way it works now, there are so many instances where the history buffer gets filled so you can't find the function you came from and if you check the cross references, the parent function may not have been named yet making it extremely difficult to figure out where you came from.

**Describe alternatives you've considered**
I've thought about increasing the history buffer size in the Tool Options and trying to write a Ghidra script that would traverse the history buffer automatically until it found the previous function, but it is less than ideal to need a script for such a basic and commonly used capability.  I also am not sure the API even supports this ability.

**Comment by dragonmacher** [comment]
This is a tough feature to get right.  It will probably require tool options so that users can tailor it to their specific needs.

IIRC, we only place the current location onto the history stack when the user initiates a 'go to' to jump to a new location.   This allows you to go back to the location from which you jumped, but does not place every clicked location on the stack, making this a sort of hybrid approach.  (It is possible that the Function Graph is not behaving as expected; it should be using the hybrid approach.)


Of the top of my head, based on user feedback, I could see these possible use cases:

- Track every location change
- Track only function changes
- Track each location left from a navigation action (Go To Dialog, double-click, etc)
- Some form of one of the above, also tracking any edit location

Ghidra can certainly be updated to handle any/all of these use cases, having them co-exist with the use of tool options.  For us to get this right, we really need to understand the workflow(s) supporting each use.

**Comment by ebfe2326** [comment]
So i did a bit of testing.  It's a little hard to tell for sure with just preliminary testing, but I think it might be a bug in the history on the graph view.  I tried analyzing a few functions in the flat view, and the history buffer doesn't get nearly as full.  It seems like there were still a few times where some addresses got saved that weren't due to me performing a navigation action, etc. but they were minimal.  It's hard to say for 100% sure without it working, but I think if the history buffer worked in the graph view the same as in the flat view, it would be a decent workflow.

Given that this looks more like a bug now than a feature request, am i able to change this issue to a bug issue for the history buffer for the graph view and leave it open, or should i close this out and open a new issue?

Also, is there way to access the history buffer via script?  I can try to work around the bug in the graph view that way in the meantime.  I feel like I should be able to parse the util.HistoryList to find the last entry that is in a different function, but i'm not quite sure how to call this HistoryList?

**Comment by dragonmacher** [comment]
> or should i close this out and open a new issue?

I think this issue is as good a place as any.  

It sounds like a bug a face value.   It could be that the Function Graph was trying to track all separate visited nodes.  If that is the case, then we can re-think when to track the locations.

As far as the HistoryList editing goes, we will have to make an assessment of value for the work required.

**Comment by dragonmacher** [comment]
For this request we added an option to the Function Graph to not save the location for every vertex visited.  That option is off by default.
