### ISSUE TITLE
What is the meaning of this logo?

### ISSUE THREAD

**Issue by suparek** [NationalSecurityAgency/ghidra#115]
![image](https://user-images.githubusercontent.com/9245996/54006593-edaec880-4198-11e9-9c4a-fa545be1cde5.png)

**Comment by ctubbsii** [comment]
I'm curious about this, too. It looks kind of like an [Ouroboros](https://en.wikipedia.org/wiki/Ouroboros) in the shape of the [symbol for infinity](https://en.wikipedia.org/wiki/Infinity_symbol), or [lemniscate](https://en.wikipedia.org/wiki/Lemniscate) (∞).

I think the thing I like about this logo the most (artistically speaking) is that I can't tell whether it is eating its own tail, or constructing itself from its own fire-breath. I hope that was an intentional design choice... because it's a cool idea.

**Comment by neitsa** [comment]
For those who missed it, the binary in the picture also spells "Hello World!":

```
>>> # each byte is an ASCII character
>>> l = ["0",
	 "1",
	 "00",
	 "1000",
	 "0110",
	 "010",
	 "1011",
	 "0110",
	 "00110",
	 "11000",
	 "11011",
	 "110010",
	 "000001",
	 "010111",
	 "011011",
	 "1101110",
	 "0100110",
	 "11000110",
	 "01000010",
	 "0001"]
>>> s = "".join(l)
>>> "".join([chr(int(s[i*8:(i*8)+8], 2)) for i in range(len(s) // 8)])
'Hello World!'
```
Nice "easter egg"!

**Comment by soufianefariss** [comment]
That's a pretty cool logo no lie.

**Comment by StepS-** [comment]
Here's another possible explanation https://twitter.com/richinseattle/status/1104477805650145280

**Comment by marcushall42** [comment]
This particular logo is new with the 9.0 release..
Of course, it really needs 3 heads..
