### ISSUE TITLE
Adding support for MOS 6510 arch

### ISSUE THREAD

**Issue by zeroKilo** [NationalSecurityAgency/ghidra#1151]
Hi,
ghidra already supports the MOS 6502 cpu, so I used that as a basis for a C64 prg loader. Now obviously the C64 uses a MOS 6510, which is an upgraded version of the 6502 and so I would like to expand the 6502 definitions to include all new 6510 opcodes, preferably as new arch.

![Example](https://i.imgur.com/H8KjNeu.png)

for example here it stops at address 0x082E with unknown opcode 0x25, which would be an "AND" opcode. How would I go about doing this? Where can I find more information about processor definitions?

Thanks for your time, best regards

EDIT: I just noticed that 0x25 actually IS part of the 6502 opcode table, so this would be a bug too

**Comment by GhidorahRex** [comment]
That instruction (0x25 f8) disassembles fine (you can check by right-clicking on it and selecting Disassemble). It looks like the issue is with the flow from the JMP command going to an unknown label.

If you're interested in learning about processor definitions, you can view the support documentation in docs/languages/index.html in your ghidra install.

**Comment by zeroKilo** [comment]
Well i tried context menu aswell as hotkey D, it doesnt want to disassemble, but will try again later. Thanks for the link too.

**Comment by GhidorahRex** [comment]
It's currently defined as a data value (undefined1) - if it is data, then it shouldn't be disassembled as code, but if not, you should clear the data then try to disassemble.

**Comment by Hardcore-fs** [comment]
> Well i tried context menu aswell as hotkey D, it doesnt want to disassemble, but will try again later. Thanks for the link too.

Ghidra can be a bit stubborn, once its got an idea about a section of data.
Select the area, then right click-> select one of the "clear XXX" options, to  dissociate the data with a type.. then attempt to re-dissasemble the data.

The only real oddity on the 6510 is the fact that you can bank the ram & fool about with the "datasette"... due to the use of  "6502  unallocated cpu pins" being reassigned in the 6510.
The instruction set is the same.  even the  "undocumented" opcodes should be the same.
for the MOS part
so.. that saved you a job...

**Comment by zeroKilo** [comment]
thanks this helped! now it can disassemble the opcode, I just had to press C to clear it as you said
![Screenshot](https://i.imgur.com/xkUlfEY.png)

as you can see there are still opcodes missing, 0xEB is actually an illegal opcode according to the [6502/6510/8500/8502 Opcode matrix](http://www.oxyron.de/html/opcodes02.html) but it could still be named (SBC imm) or is there a rule that ghidra should not support illegal-but-used opcodes?

**Comment by Hardcore-fs** [comment]
I'd be really worried about any programmer relying on illegal opcodes.
Ideally they should be supported , but as something you have to decode by hand , (perhaps with them marked in red) , 
Since it would require a "human" mind to decide if they were actually "code" and not data...
Then there is the issue of them NOT always behaving the same on different masks with the same cpu number. (A group of us did an analysis some 35 years ago on the 6502 & variants..)
The only time you are really going to come across them is in software protection schemes... but I always found other methods obfuscation better.

**Comment by zeroKilo** [comment]
well I was more interested in demo code, they use alot tricks to get their effects done. anyway I see what you mean, but I have no idea how to add it to ghidra. something like a contextmenu option that says "decode as illegal opcode blablabla" or as you said mark it red or add a comment. someone should make a new ticket with this as suggestion. 
generally I guess I can close this ticket, because I was asking about general support of 6510 and that seems to be there.

**Comment by Hardcore-fs** [comment]
I was more out of respect for the sheer beauty of the thing.... just using it with cut & paste to test  illegal instructions.
But how cool would it be to have an actual silicon simulation for tracing code....
