### ISSUE TITLE
Call convention

### ISSUE THREAD

**Issue by oshogbo** [NationalSecurityAgency/ghidra#1159]
Where can I find some documentation about adding new call conversion to ghidra?

**Comment by astrelsky** [comment]
Conversion as in you want to change what is being called or a new calling convention?

**Comment by oshogbo** [comment]
I want to create a new calling convention. Sorry for misspell.

**Comment by astrelsky** [comment]
> I want to create a new calling convention. Sorry for misspell.

No problem, I just had to ask because the answer would differ greatly.

I don't think there is any existing documentation on the cspec files. If there are @mumbel might know where to find them.

In the meantime you can learn a lot by looking at existing .cspec files and looking at the grammar file for cspec. Specifications for the calling convention definitions starts here. https://github.com/NationalSecurityAgency/ghidra/blob/d081700b0c834a310dcfc0af1a9b1a8e3dfe7bdf/Ghidra/Framework/SoftwareModeling/data/languages/compiler_spec.rxg#L297

**Comment by mumbel** [comment]
#472 may help

**Comment by astrelsky** [comment]
> #472 may help

That's perfect. I wonder why they are not generated along with the rest of the documentation.

**Comment by saruman9** [comment]
I think, the issue can be closed.

**Comment by oshogbo** [comment]
Thanks.
