### ISSUE TITLE
MDMang doesn't support Thread Safe Static guard variables

### ISSUE THREAD

**Issue by Zhentar** [NationalSecurityAgency/ghidra#1162]
**Describe the bug**
MDMang is not able to demangle symbol names for compiler generated thread safe static guard variables. `__unDName` is not able to demangle these symbols correctly either, but the structure is somewhat documented from the other direction thanks to Clang's msvc compatible mangling at https://github.com/llvm/llvm-project/blob/722b61892454b3217d73ec486e52156c5a92b5b3/clang/lib/AST/MicrosoftMangle.cpp#L3342

**To Reproduce**
Find an example mangled symbol that starts with `$TSS` (for one example, http://msdl.microsoft.com/download/symbols/perf_dynamic.dll/91A6CB6CF000/perf_dynamic.dll 
contains `?$TSS0@?1??GetCategoryMap@CDynamicRegistrationInfoSource@XPerfAddIn@@SAPEBU_ATL_CATMAP_ENTRY@ATL@@XZ@4HA`)
**Expected behavior**
The symbol is demangled. The `$TSS0@` should be parsed as a special name rather than as a template parameter, with the `0@` apparently being an `@` terminated, unencoded decimal index.

I don't think there's there's a canonical representation, but ``XPerfAddIn::CDynamicRegistrationInfoSource::GetCategoryMap(void)'::`2'::`thread safe local static guard'`` seems like a reasonable choice.

**Comment by ghizard** [comment]
I agree that it seems that the "template" area is being overloaded with specialized types.  If I change the second character ('$') to 'x', then it gets parsed as a standard C++ object, and I can see how the rest falls out in parsing: ```int `public: static struct ATL::_ATL_CATMAP_ENTRY const * __ptr64 __cdecl XPerfAddIn::CDynamicRegistrationInfoSource::GetCategoryMap(void)'::`2'::xTSS0```

Thanks for the llvm reference.  I'll have to study it to see what other specializations might intersect into the template or other areas and to learn a lot more about the format from this "documentation," which I hadn't looked at before. (I've been meaning to get back to MDMang, but have been busy with PDB lately).

Since the resulting demangled sequence (with a fix for the specialization) would result in an integer data type with label, would you expect anything different to be applied to a program other than what is normally done for the resulting data type (int or whatever other type falls out)?

Is this just one of many other issues that you might have had for this binary?

**Comment by Zhentar** [comment]
I had the usual issues with the auto-analysis (not applied consistently, mangled name labels left on many functions), but that's the only mangled name MDMang couldn't parse. The dll is tiny, only about 200 mangled names total, so that one couldn't kind of stood out.
