### ISSUE TITLE
Filter external functions in ExportFunctionInfoScript

### ISSUE THREAD

**Issue by briannab16** [NationalSecurityAgency/ghidra#1172]
I am currently using the ExportFunctionInfoScript in order to export a list of function and address pairs, but I have noticed that the list includes external functions (e.g. functions in libc) and I was wondering if there is a way to filter out the external functions so that only functions directly in the binary are being exported to the list?

**Comment by dragonmacher** [comment]
You can add a check in the script to skip external functions:

```
if (f.isExternal()) {
       continue;
}
```

**Comment by briannab16** [comment]
Thank you! It turns out, my problem wasn't actually that it was printing external functions it was printing out all the thunk functions, so I just used the check for that instead.  Do you know why the compiler creates thunk functions for all of the external functions?

**Comment by dragonmacher** [comment]
Typically the thunk functions are created so that the library can be dynamically linked, often lazily as needed.  Sometimes thunks are created to serve as trampolines, such as allowing a function call to perform an intermediate jump(s) to get to a function at an address is too large for an instruction to jump to directly.

[https://en.wikipedia.org/wiki/Thunk](url)
