### ISSUE TITLE
MDMang doesn't support $$V template arguments

### ISSUE THREAD

**Issue by Zhentar** [NationalSecurityAgency/ghidra#1220]
**Describe the bug**
MDMang is not able to demangle this string:
`??$Make@VProjectorViewFormats@Output@Host@DataModel@Debugger@@$$V@Details@WRL@Microsoft@@YA?AV?$ComPtr@VProjectorViewFormats@Output@Host@DataModel@Debugger@@@12@XZ`

However, if you remove the `$$V`, MDMang produces the correct output:
`class Microsoft::WRL::ComPtr<class Debugger::DataModel::Host::Output::ProjectorViewFormats> __cdecl Microsoft::WRL::Details::Make<class Debugger::DataModel::Host::Output::ProjectorViewFormats>(void)`

The `$$V` has no impact on the output of `undname`. From the LLVM mangler, it seems to represent an empty template parameter pack.

**Comment by ghizard** [comment]
This one will be easier to fix than #1162. We already handle $$$V and it seems that $$V is the VS2015 equivalent. 

I need to deal with other considerations for #1162, as it requires investigation on its encroaching into template space.  What happens if a template name causes a collision that requires backing up to an earlier point before progressing. For that, I’d like to look at other cases.
