### ISSUE TITLE
Decompiler pcode manipulation over GhidraScript

### ISSUE THREAD

**Issue by akostenev** [NationalSecurityAgency/ghidra#1225]
Hi, see [DropAllVarNodes script](https://github.com/akostenev/ghidra/blob/master/ghidra_scripts/DropAllVarNodes.java).

I'm trying to change pcodes and their varnodes to generate a other decompiler output.
The AST contains basically all `LOAD` instrunctions whos varnodes i want to exchange with other values. However, even if all inputs/outputs are nulled over `setInput` and `setOutput`, the resulting decomiler output is `equal` to the old decompiler output.

Q: How can i manipulate the pcode of a decompiled funtion and display them in the decompiler output?

If it's not possible to do over a script, is there a way to extend the decompiler with another `transformation`?

**Comment by astrelsky** [comment]
I think the reason it doesn't work is because the decompilation isn't cached in any way. I noticed from working on a pcode injection library implementation for ghidra-emotionengine that each time you go to a function it gets re-decompiled.

IMO varnodes are not useful in any way. Especially since the ones you get from the function interface and from pcode are raw varnodes meaning the contain no value. The only way I've managed to get any value and use from varnodes is through the use of the SymbolicPropagator class and the ContextEvaluator. There are some examples in ghidra scripts specifically the one for fixing up linux syscalls.

Also as a side note if you have a Function invoking getBody will return an AddressSetView containing all the addresses contained in the function. I'm not sure what you intended but the address sets created on lines 36 and 38 only contain one address.

If you really want to manipulate pcode you should take a look at pcode injection.  You can inject pcode per a specific userop or with a call fix up.

If you do manage to discover a way of doing it to just a specific pcode instance please let me know.  I've been looking for a way to resolve virtual member accessing for my c++ class analyzer for quite some time now.

**Comment by akostenev** [comment]
It seems that the decompilation actions are applied on the disassembler site with updates in the database, e.g. by [SymbolDatabadeAdapter](https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/database/symbol/SymbolDatabaseAdapter.java).

So their is no way to change the decompilation output without changing the database, which is not suprising actually.

To specify my task, here one example.

I want to progate LOAD instructions that load constant values from the memory.

![Snippet](https://user-images.githubusercontent.com/38352382/68949867-466c4180-07bb-11ea-97ad-631af8307a9b.PNG)

Now, i know the value for address register `a9` is `0x8016D340` which i also saved with the `setRegisterValues` action.
`a2` points therefore to `0x8016db68` and `a15` later on to the hword `C3C3h`

```
a9 = 0x8016D340
a2 = a9[0x828]
a15 = a2[0xa22] = C3C3h
```

This works fine in the disassembler output as you see in the picture above.
The disassembler outputs the following c-code which looks great!:
```
  ppuVar24 = &PTR_DAT_8016d340;
  puVar22 = (undefined *)0xd0009dc0;
  if ((((((*(short *)(PTR_DAT_8016db68 + 0xa22) < _DAT_d0001852) &&
         (_DAT_d0001852 < *(short *)(PTR_DAT_8016db68 + 0xa20))) &&
        (*(short *)(PTR_DAT_8016db68 + 0xa26) < _DAT_d00019aa)) &&
       (((_DAT_d00019aa < *(short *)(PTR_DAT_8016db68 + 0xa24) &&
         (*(short *)(PTR_DAT_8016db68 + 0xa2a) < _DAT_d0001ab6)) &&
        ((_DAT_d0001ab6 < *(short *)(PTR_DAT_8016db68 + 0xa28) &&
         ((*(short *)(PTR_DAT_8016db68 + 0x594) < _DAT_d0001940 && (DAT_c0001170 == '\x01'))))))))
      && (DAT_c0001179 == '\0')) && (DAT_d000afb5 == '\0')) {
    DAT_d000afb4 = DAT_c0001170;
```

However, i search a way to replate `*(short *)(PTR_DAT_8016db68 + 0xa22)` by a global symbol, e.g. 
```short _FuncCalXyz = 0xC3C3;```, which superseeds the pointer arithmetic.
Is there a way to implement this task, either in the Java or C++ backend?

E.g. similar to the [RetypeVariableAction](https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Features/Decompiler/src/main/java/ghidra/app/plugin/core/decompile/actions/RetypeVariableAction.java) which replaces a variable and all its uses by a global symbol.

**Comment by emteere** [comment]
If you mark a memory location as constant, the decompiler will trust the value in memory and propagate the value read from the location as constant.  You can also mark an entire section of memory as ReadOnly and the decompiler will do the same.

If you set the value of A9 at the start of the function, the decompiler will propagate that as a constant as well.  But will only propagate register settings that are set at the start of a function.

**Comment by akostenev** [comment]
@emteere this solves my issue.

**Comment by astrelsky** [comment]
@emteere I could be mistaken,  but I think only certain DataTypes will be resolved. If I remember correctly from looking at the decompiler code,  Structures are not resolved.
