### ISSUE TITLE
搞个中文版行不行，make a chinese version?

### ISSUE THREAD

**Issue by 350030173** [NationalSecurityAgency/ghidra#1300]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by astrelsky** [comment]
This repository is maintained by the National Security Agency which is a United States government agency. Considering this the suggestion is unlikely to be implemented especially since it would require a lot of work. 

However, it would be nice to have language files of some sort to allow for easier translation of menus and such. Could be helpful for foriegn allies such as Japan, South Korea,  etc. If a reason for implementing such a thing would be needed. I'm really just speculating things though.

**Comment by ryanmkurtz** [comment]
Unfortunately we do not have the resources to do this.
