### ISSUE TITLE
Necessity of Configure Project Task per build

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#1331]
Is the Configure Project task necessary to be run for every single task? Even running gradle clean causes the following output:
```
> Configure project :
Searching for latest Visual Studio and required components...
  -> Installation Directory: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
  -> VCTools Version (default): 14.24.28314
  -> SDK Directory (default): C:\Program Files (x86)\Windows Kits\10\
  -> SDK Version (default): 10.0.18362.0
  -> SDK Version (override): N/A
```

**Comment by ryanmkurtz** [comment]
Yes, we need that to run in the Gradle configuration phase, which is independent of the specified task.

**Comment by astrelsky** [comment]
> Yes, we need that to run in the Gradle configuration phase, which is independent of the specified task.

I see. Ok it was just out of curiosity because it seemed pointless to be run while cleaning and during tasks for non-native builds. Thank you.

**Comment by kant2002** [comment]
@ryanmkurtz I want to ask more detailed question. Why in general you rely on the writing functions in the Gradle, and seems to be under utilize ability to use tasks, and make gradle handle dependency tree between tasks, instead of manually make sure order of build execution.

For example if you have task `configureVS` and which will set global properties, then all native projects can be dependent on this task.

It is not so interesting for this particular case, but for assembling release it's can give you more benefit. it is unnecessary complicated, in my opinion. 

Would be interesting to hear how do you view all that. For sure you have your reason,s but it's not quite obvious why you have current build structure.
