### ISSUE TITLE
MDMang produces incorrect demangling of hashed symbol names

### ISSUE THREAD

**Issue by Zhentar** [NationalSecurityAgency/ghidra#1344]
I have a symbol file that contains two unusual symbols:

```
?catch$0@?0???@f4873c94f485cd6716c2319fc51ac714@@4HA
??@f4873c94f485cd6716c2319fc51ac714@
```
(from: http://msdl.microsoft.com/download/symbols/perf_pofx.pdb/86dc62bc8c6e50836f2f1414bcf3f8fe1/perf_pofx.pdb )

From which MDMang produces:
```
`int f4873c94f485cd6716c2319fc51ac714::ERROR UNKNOWN OPERATOR TYPE'::`1'::catch$0
f4873c94f485cd6716c2319fc51ac714::ERROR UNKNOWN OPERATOR TYPE
```

Conveniently, Clang can once again provide us a good explanation of what's happening! https://github.com/llvm/llvm-project/commit/febb27283d8209d31b80d4b575aa4381931fcb75 explains that when a mangled symbol name would be longer than 4096 characters, it is instead emitted as a `??@`, `@` wrapped MD5 hash. 

I don't know what would be a good way to present them, but at the least dropping the `::ERROR UNKNOWN OPERATOR TYPE` would be an improvement.

**Comment by ghizard** [comment]
Thank you once again for providing details on MDMang issues.

The second symbol is a nested item in the first.  I'm considering putting the single quotes (backward and forward ticks) along with a special identifier as such (for the second symbol):
```
`HashedObjectf4873c94f485cd6716c2319fc51ac714'
```
Since the first symbol has a nested name (which happens to be the second symbol object), it also gets these single tick marks, and would look like this:
```
int ``HashedObjectf4873c94f485cd6716c2319fc51ac714''::`1'::catch$0
```

What do you think about these?

I supposed they would be subject to change once I get more time to take a bigger look these symbols and others (including the other unfinished MDMang issue that still exists) that could make use of insights from LLVM Clang.

Another component to processing these symbols is in determining how Ghidra should apply them to a program.  For this, a PDB with symbols is not necessarily enough to follow the possibly processing paths.  This happens in MDMangGhidra, which currently assumes there is an MDQualifiedBasicName, which will no longer be the case.  I have an approach where I'm modifying MDObjectCPP, adding new methods such that those assumptions do not need to be true.  I'm not extremely happy with how I've approached it, but think I have something that will hopefully work without breaking things.  I'll have to see what additional testing I can do to prevent unforeseen breakage.

**Comment by Zhentar** [comment]
I'm not a fan of the "Object" part of that - If I came across that, I would assume that "HashedObject" is referring to the actual data at that address rather than the label itself. "HashedSymbol" or "HashedLabel" might be better, but I would favor simply giving less to [mis]interpret - such as `` `Hashed_f4873c94f485cd6716c2319fc51ac714' `` or even just `` `f4873c94f485cd6716c2319fc51ac714' ``

**Comment by ghizard** [comment]
I understand.  I had misgivings of saying Object, since that is such an overloaded term... I only put it because that is how I have these symbols depicted internally at the point where the modifications would need to take place (these objects have names and types, etc. in their hierarchy).

Of the suggestions you have given, I'm working on using the latter.
