### ISSUE TITLE
Parallel Stream Usage and Ghidra's Threading

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#1411]
I don't fully understand how ghidra's threading is implemented or much about parallel processing in general yet. I figured it would be a good idea to ask this before littering my code with with the following:

Here type is a TypeDescriptorModel instance.
<pre>
private static final Pattern PATTERN = Pattern.compile("vftable(?!_meta_ptr)");

private static boolean vftableSymbolFilter(Symbol t) {
	return PATTERN.matcher(t.getName()).matches();
}

private List<Address> getVftableAddresses() {
	final SymbolTable table = type.getProgram().getSymbolTable();
	return StreamSupport.stream(
		table.getSymbols(type.getDescriptorAsNamespace()).spliterator(), <strong>true</strong>)
			 .filter(RttiModelWrapper::vftableSymbolFilter)
			 .map(Symbol::getAddress)
			 .sorted()
			 .collect(Collectors.toList());
}
</pre>

I know that parallel streams use the common ForkJoinPool and that ghidra has its own GThreadPool but I would like to know for certain if this would cause me any trouble or slowdown.

Also is there a way to get a stream that would use a ghidra thread pool that may be better to use?

**Comment by dragonmacher** [comment]
The short answer is that we generally do not use parallel streams.  We do have a fairly robust framework for parallel programming when we need to run tasks in the background to prevent the UI from locking-up.

> but I would like to know for certain if this would cause me any trouble or slowdown.

For streams (and any task) you should base your concurrent usage on observed deficiencies.  With streams, depending on the data, parallel streams can actually be slower, due to the overhead of thread management.  You should profile your code above with and without streams to see the difference.  (It seems like your code above is CPU-bound, which suggests that using threads will not improve the performance much.).

> Also is there a way to get a stream that would use a ghidra thread pool that may be better to use?

I know of no way to have Streams use a particular thread pool, such as those used by Ghidra.

> I don't fully understand how ghidra's threading is implemented

Generally, we have the UI elements share a thread pool when using background threads.  Analysis uses a single background thread, with some analyzers parallelizing their work when they use I/O (such as the Decompiler, which uses sockets).  Finally, there are background commands and tasks triggered directly by user actions that are run one-at-a-time using a single background thread.   We do not have many parts of the code base that use parallel processing, other than using a single background thread to ensure that the UI does not lock-up.   We have taken the approach to model our concurrent programming as simply as possible.  This usually means that our core code base does not directly create threads, but instead uses one of our built-in concurrent APIs.   Further, we only tend to use parallel background threads when there is a demonstrated improvement in performance.

**Comment by astrelsky** [comment]
Thank you for the detailed explanation. While it wasn't with the above example I had tried enabling the parallel stream to filter out 1000+ potential Rtti1Model Addresses (std::exception is referenced everywhere) and it didn't seem to help any. It took about as much time to filter them as it did for ProgramMemoryUtil to search through the memory. It probably isn't worthwhile anyway when dealing with any database objects since they have thread locks.
