### ISSUE TITLE
Recommended Metal Look and Feel with Inverted Colors Makes Checked Boxes Difficult to See / Suggest CDE Motif As Alternative

### ISSUE THREAD

**Issue by BYEMAN** [NationalSecurityAgency/ghidra#142]
**Describe the bug**
When setting the colors to inverted, the program suggests the Metal Look and Feel. However, check boxes are very difficult to see with the Metal Look and Feel and inverted colors. The CDE/Motif Look and Feel, however, is very clear when using inverted colors so I'd recommend making that the default suggestion when selecting Use Inverted Colors.

**To Reproduce**

Edit|Tool Options|Tool
- Check Use Inverted Colors
--- When selecting Use Inverted Colors, a dialog box will appear suggesting the Metal look and feel

**Environment (please complete the following information):**
 - OS: Windows 10 in a modern.ie VM in VirtualBox
 - Java Version: JDK 11.0
 - Ghidra Version: 9.0 build public

**Comment by ryanmkurtz** [comment]
Since we have no real control over how things look when the color scheme gets inverted, each look and feel has something imperfect about it.  I agree that the checkboxes are difficult to see, but CDE/Motif also doesn't look that dark, which is what most people want out of the feature.  This really comes down to personal preference, so in the absence of a clear best choice for everyone, we are going to keep the suggested look and feel as-is.

**Comment by M-a-r-k** [comment]
Try adding these lines to the launch.properties file:
```
VMARGS=-Dswing.metalTheme=steel
VMARGS=-Dswing.boldMetal=false
```
