### ISSUE TITLE
RISC-V: Custom CSR instruction are not recognized

### ISSUE THREAD

**Issue by bluewww** [NationalSecurityAgency/ghidra#1466]
**Describe the bug**
Ghidra doesn't recognize e.g. `7c029073` as custom CSR instruction. The disassembly will stop at that point. The riscv-privileged-v1.10 manual, p.8 shows that this sequence can be interpreted as a CSR instruction to a custom register.

**To Reproduce**
Dissassemble any binary containing the sequence `7c029073` in the text section (aligned to 4 bytes).

**Expected behavior**
I would expect the disassembly to be `csrw    0x7c0,t0`. This is e.g. what `objdump -d` does.

**Environment (please complete the following information):**
 - OS: Opensuse Tumbleweed
 - Java Version: 11.0
 - Ghidra Version: 9.2 DEV

**Comment by mumbel** [comment]
I wasn't sure exactly how to handle these during implementation.  basically it does resolve to a CSR instruction, but then since 0x7c0 is not a defined register (at the time of writing/currently/custom/etc...) my SLEIGH does not resolve it and I guess fails to disassemble it.

`riscv.reg.sinc` has a bunch of attach variable lines that are mostly unresolved that would need to have a value attached.  0x7c0 is empty, so when running `DebugSleighInstructionParse.java` plugin, it looks fine until it hits `csr_7C`.

Ghidra team any hints on this sort of thing?  I guess every field be filled in with a dummy variable and resolved/overwritten in the pspec (similar to to PPC spr registers/tables maybe) or just left as a immediate for custom?

**Comment by GhidorahRex** [comment]
@mumbel, both options could be used to resolve the issue. Which one to pick depends on how many dummy registers there are to be filled. If it's a manageable number, that would probably be the preferable technique.

**Comment by mumbel** [comment]
Around ~250 registers currently in git, and 0x1000 slots, but that range does have gaps

**Comment by mumbel** [comment]
@bluewww 

There might still be some possible improvements, but just made a PR to address this.

My Ghidra now has:
`73 90 02 7c     csrrw      zero,csr7c0,t0`

Not sure if this needs to be an immediate value or if this pseudo named CSR is okay (just did `csr%03x`) and then replaced the ~250 or so from the pdf with their name

**Comment by bluewww** [comment]
I just build ghidra-9.2-dev with your patch applied and compared the the disassembly of some binaries of ghidra with `objdump -d -M no-aliases`. The `.text` section disassembles properly now (as far as I can tell by my visual inspection), thanks!

Regarding the naming of the second argument of an unknown `csr*` I personally prefer it how `objdump` does it, but this is just my opinion.

**Comment by mumbel** [comment]
Thanks for testing.   The immediate value vs named is a question of implementation that I didn't know... basically how to mix numbers and the named names in SLEIGH.  Do you know if objdump only prints numbers or would it insert for example `misa` instead of `0x301`

yeah aliases are a big todo, `riscv.instr.sinc` has the remaining :'(  I addressed/added a few where zero wasn't playing nice with ghidra.

**Comment by mumbel** [comment]
@bluewww   was just reviewing this, and realized I was doing something pretty silly and never exporting the registers, only displaying them.  The decompiler would probably look really weird with that.  Also noticed I had some commented CSR instructions due to some unknown errors in sizing, but those seem to error free now and I have added them back in.

**Comment by bluewww** [comment]
@mumbel indeed I haven't looked really at the decompilation output. Do you want me to test something specifically?

**Comment by mumbel** [comment]
Oh, sorry no, just more of an FYI as it was a significant oversight on my part.

**Comment by ghidra1** [comment]
#2333 has been merged.  Does that merge resolve this issue?

**Comment by ghidra1** [comment]
#2333 has been merged.  Does that merge resolve this issue?

**Comment by mumbel** [comment]
@ghidra1 you should be okay to close

**Comment by emteere** [comment]
Fixed with PR #2333 release for 9.2 and master
