### ISSUE TITLE
ARM BE8 Relocations are not handled correctly.

### ISSUE THREAD

**Issue by jonwilson030981** [NationalSecurityAgency/ghidra#1494]
**Describe the bug**
In ARM BE8 architecture, whilst the data segment is in big endian, the code remains in little endian. The ARM relocator (https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Processors/ARM/src/main/java/ghidra/app/util/bin/format/elf/relocation/ARM_ElfRelocationHandler.java) does not take this into account. It reads and writes values using getInt() from the "Memory" object (which is configured as big endian) without specifying an endian parameter when handling fix-ups which are being applied to instructions.

e.g.

			 case ARM_ElfRelocationConstants.R_ARM_JUMP24:
			case ARM_ElfRelocationConstants.R_ARM_CALL:
			case ARM_ElfRelocationConstants.R_ARM_GOT_PLT32:
				int oldValue = memory.getInt(relocationAddress);
				newValue = (int) (symbolValue + addend);

				newValue -= (offset + 8);   // PC relative, PC will be 8 bytes past inst start

				// is this a BLX instruction, must put the lower half word in bit24
				// TODO: this might not appear on a BLX, but just in case
				if ((oldValue & 0xff000000) == 0xfb000000) {
					newValue = (oldValue & 0xfe000000) | (((newValue >> 1) & 1) << 24) |
						((newValue >> 2) & 0x00ffffff);
				}
				else {
					newValue = (oldValue & 0xff000000) | ((newValue >> 2) & 0x00ffffff);
				}
				memory.setInt(relocationAddress, newValue);
				break;

This block of code should access the memory object as follows:
				 int oldValue = memory.getInt(relocationAddress, false);
				 memory.setInt(relocationAddress, newValue, false);

**To Reproduce**
Load an ARM BE8 image (compiled with the -mbe8 flag to gcc) which contains a fix-up such as R_ARM_CALL. A call instruction should start with the byte 0xEB on ARM. As a result of using the incorrect endian-ness, the last byte of the instruction is preserved rather than the first. This results, not only in an incorrect relocation, but also, often an invalid instruction.

The following is a useful reference for correct implementation of some types of relocation:

https://github.com/torvalds/linux/blob/master/arch/arm/kernel/module.c

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Java Version: 11.0
 - Ghidra Version: 9.0.4, 9.1.1 and HEAD.

**Comment by ghidra1** [comment]
We will need to double-check relocation handling for all the mixed-endian languages.  This was clearly an oversight on or part.

**Comment by WorksButNotTested** [comment]
We can use the implementation of relocations carried out by the Linux kernel when loading modules as a template:
https://github.com/torvalds/linux/blob/master/arch/arm/kernel/module.c

We can see that it makes use of the macros:
__mem_to_opcode_arm
__opcode_to_mem_arm

These are defined here:
https://elixir.bootlin.com/linux/v4.4/source/arch/arm/include/asm/opcodes.h#L103


#ifdef CONFIG_CPU_ENDIAN_BE8

#define __opcode_to_mem_arm(x) ___opcode_swab32(x)
...

#else /* ! CONFIG_CPU_ENDIAN_BE8 */

#define __opcode_to_mem_arm(x) ___opcode_identity32(x)
...

#endif /* ! CONFIG_CPU_ENDIAN_BE8 */

...
#define __mem_to_opcode_arm(x) __opcode_to_mem_arm(x)
...

These macros are used when fixing up relocations in the .text section, but are not required when processing relocations within the data section. This is because on ARM BE8 systems, data access is big-endian whilst instructions are encoded in little-endian. Similar marcros are defined and used when accessing Thumb code which uses 16-bit rather than 32-bit words (Note that some Thumb instructions are formed of 2 words). Looking through the use of these macros, we can see that this inversion is necessary for the following relocation types:

R_ARM_PC24
R_ARM_CALL
R_ARM_JUMP24
R_ARM_MOVW_ABS_NC
R_ARM_MOVT_ABS

R_ARM_THM_CALL
R_ARM_THM_JUMP24
R_ARM_THM_MOVW_ABS_NC
R_ARM_THM_MOVT_ABS

Looking at the ARM_ElfRelocationHandler we can see that the following relocation types are supported:


ARM_ElfRelocationConstants.R_ARM_PC24
ARM_ElfRelocationConstants.R_ARM_ABS32
ARM_ElfRelocationConstants.R_ARM_REL32
ARM_ElfRelocationConstants.R_ARM_LDR_PC_G0
ARM_ElfRelocationConstants.R_ARM_ABS16
ARM_ElfRelocationConstants.R_ARM_ABS12
ARM_ElfRelocationConstants.R_ARM_ABS_8
ARM_ElfRelocationConstants.R_ARM_THM_JUMP24
ARM_ElfRelocationConstants.R_ARM_THM_CALL
ARM_ElfRelocationConstants.R_ARM_THM_PC8
ARM_ElfRelocationConstants.R_ARM_GLOB_DAT
ARM_ElfRelocationConstants.R_ARM_JUMP_SLOT
ARM_ElfRelocationConstants.R_ARM_RELATIVE
ARM_ElfRelocationConstants.R_ARM_JUMP24
ARM_ElfRelocationConstants.R_ARM_CALL
ARM_ElfRelocationConstants.R_ARM_GOT_PLT32

The following shows the relocation types in table 4-9:
https://static.docs.arm.com/ihi0044/g/aaelf32.pdf

Thus the following need adjustment:
[X] ARM_ElfRelocationConstants.R_ARM_PC24
[ ] ARM_ElfRelocationConstants.R_ARM_ABS32
[ ] ARM_ElfRelocationConstants.R_ARM_REL32
[X] ARM_ElfRelocationConstants.R_ARM_LDR_PC_G0
[ ] ARM_ElfRelocationConstants.R_ARM_ABS16
[X] ARM_ElfRelocationConstants.R_ARM_ABS12
[ ] ARM_ElfRelocationConstants.R_ARM_ABS_8
[X] ARM_ElfRelocationConstants.R_ARM_THM_JUMP24
[X] ARM_ElfRelocationConstants.R_ARM_THM_CALL
[X] ARM_ElfRelocationConstants.R_ARM_THM_PC8
[ ] ARM_ElfRelocationConstants.R_ARM_GLOB_DAT
[ ] ARM_ElfRelocationConstants.R_ARM_JUMP_SLOT
[ ] ARM_ElfRelocationConstants.R_ARM_RELATIVE
[X] ARM_ElfRelocationConstants.R_ARM_JUMP24
[X] ARM_ElfRelocationConstants.R_ARM_CALL
[X] ARM_ElfRelocationConstants.R_ARM_GOT_PLT32 (= 27 = R_ARM_PLT32)


For these relocation types, instead of using:
int oldValue = memory.getInt(relocationAddress);
memory.setInt(relocationAddress, newValue);

We can instead provide the additional endian parameter to those functions which we can retrieve from:
program.getLanguage().getLanguageDescription().getInstructionEndian();

**Comment by WorksButNotTested** [comment]
See #2068

**Comment by ghidra1** [comment]
Merged pull request for 9.2
