### ISSUE TITLE
Any Bugfix planned for Issue #19 (Corrupted Export)

### ISSUE THREAD

**Issue by fedqx** [NationalSecurityAgency/ghidra#1501]
Issue #19 Is still present in Ghidra v9.1.1 (Tested on Ubuntu 18.04, OpenJDK version "11.0.6" 2020-01-14,  GCC version 7.4.0). Currently,  the only way to overcome this issue is Importing binary in Raw binary format but, This makes reversing programs harder even for experienced programmers. And even prevents some programmers from using Ghidra because of this issue.

Is there any Bugfix planned? I personally like Ghidra and want to use it, But especially this bug prevents me too from using it as my go-to tool. It would be awesome if a developer can fix this issue.
Thanks!

**Comment by astrelsky** [comment]
It appears that the memory map returned by program.getMemory() has "holes" in it.

```
MemoryMapDB@0x9e "[00100000, 001002a7]
 [001002a8, 001002c3]
 [001002c4, 001002e7]
 [001002e8, 00100307]
 [00100308, 00100343]
 [00100348, 001007f7]
 [001007f8, 00100f6d]
 [00100f6e, 00100fd1]
 [00100fd8, 00101067]
 [00101068, 001059e7]
 [001059e8, 00105c87]
 [00106000, 00106016]
 [00106020, 001061ef]
 [001061f0, 001061ff]
 [00106200, 0010e5a0]
 [0010e5a4, 0010e5ac]
 [0010f000, 0010f978]
 [0010f97c, 00110877]
 [00110878, 00114177]
 [00114178, 0011430f]
 [001157c8, 001157d7]
 [001157d8, 001157df]
 [001157e0, 00117db7]
 [00117db8, 00117fb7]
 [00117fb8, 00117ff7]
 [00118000, 001180f7]
 [001180f8, 0011811f]
 [00118120, 0011879f]
 [00119000, 00119167]
 [.comment::00000000, .comment::00000025]
 [.debug_abbrev::00000000, .debug_abbrev::00000d2c]
 [.debug_aranges::00000000, .debug_aranges::00001ccf]
 [.debug_info::00000000, .debug_info::00011c71]
 [.debug_line::00000000, .debug_line::00004736]
 [.debug_macro::00000000, .debug_macro::00003c0a]
 [.debug_ranges::00000000, .debug_ranges::00001cbf]
 [.debug_str::00000000, .debug_str::0001ad86]
 [.shstrtab::00000000, .shstrtab::00000180]
 [.strtab::00000000, .strtab::0000691f]
 [.symtab::00000000, .symtab::000050e7]
 [_elfSectionHeaders::00000000, _elfSectionHeaders::000009bf]"
```

Maybe this would be fixable by checking for the missing bytes and padding appropriately.

**Comment by fedqx** [comment]
@astrelsky Can a Script/Setting (or community made solution) solve this issue? Or the fix only depends on developers' mercy?

**Comment by astrelsky** [comment]
> @astrelsky Can a Script/Setting (or community made solution) solve this issue? Or the fix only depends on developers' mercy?

It is an open source project. Contributions are welcome. Normally I would have attempted to fix it last night,  but both my eyes and head were no longer cooperating if you know what I mean. I'll likely look into fixing it myself later today.

**Comment by fedqx** [comment]
@astrelsky Thank you! If you can fix it, can you inform me about it?

**Comment by astrelsky** [comment]
> @astrelsky Thank you! If you can fix it, can you inform me about it?

Of course. I'll mention you if/when I submit a pull request for a fix.

**Comment by ryanmkurtz** [comment]
It would be fairly easy to script for simple cases.  You would simply grab the `FileBytes` object from each `MemoryBlock` (Ghidra 9.1 or later) and using the original bytes and modified bytes, reconstruct the file.  You would need to reference the relocation table to make sure you are writing the original bytes for each relocation, not the modified bytes.  Any other modified bytes you write that differ from the original bytes would have to be assumed to be intentional changes by the user (to change the behavior of the binary).  

Of course, if you make any drastic changes to the memory map like moving, adding, or removing blocks, things break down quickly.  And, you would have to go in and make sure that that loader you are writing this for doesn't make any other modifications to the bytes (other than relocations).  If it does, you would want to use the original bytes for those changes too.  

It would be hard to write one script/exporter to do all of this generically across all loaders/file formats, but it should not be hard to whip up a proof of concept for your own cases.

**Comment by ghidra1** [comment]
Please see comment on #19.  The Binary Exporter is working as designed for the use cases it was intended for.  Maybe it should be renamed to avoid confusion about its' intended use.

**Comment by astrelsky** [comment]
> Please see comment on #19. The Binary Exporter is working as designed for the use cases it was intended for. Maybe it should be renamed to avoid confusion about its' intended use.

This is probably a good idea. I have submitted #1505 which creates an ElfExporter and PeExporter. They do what was believed the binary exporter would do. I have made them separate so it would be possible to do things such as recreate symbol tables and stuff in the future.

**Comment by ghidra1** [comment]
I am closing this ticket and deferring the issue to #1505 as an enhancement/improvement.
