### ISSUE TITLE
Modal CodeBrowser dialogs are activating FrontEnd window

### ISSUE THREAD

**Issue by ryanmkurtz** [NationalSecurityAgency/ghidra#1503]
I have a `FrontEnd` on **monitor 1** and a `CodeBrowser` on **monitor 2**.  I have another app open on **monitor 1** that I need to look at while looking at the `CodeBrowser` on **monitor 2**.  When a modal opens from the `CodeBrowser` (memory map actions, file choosers, etc.) the `FrontEnd` on **monitor 1** activates, hiding my other app.  I just reactivated my app to get it in front of the `FrontEnd`, but it's happening enough now to make me want to open an issue.  

**Environment (please complete the following information):**
 - OS: Ubuntu 19.10
 - Java Version: Amazon Corretto 11.0.6
 - Ghidra Version: 9.2-DEV dc16f29

**Comment by saruman9** [comment]
Also in my case all dialog windows opens in old position of `CodeBrowser` window. For example:
1. Open `CodeBrowser` window on **monitor 1**.
2. Move `CodeBrowser` window on **monitor 2**.
3. Open dialog window, for example, `Go To ...`.
It will be opened on **monitor 1**, but if you move it to **monitor 2**, then next time it will be opened on **monitor 2**.

I know, it's another issue, but maybe it will be fixed with this issue.

**Comment by saruman9** [comment]
@ryanmkurtz, sorry for flooding there, but I want to post fix for tiling window manager. I think these things are interconnected.

- OS: ArchLinux (Linux 5.4.3-arch1-1)
- WM: i3-wm 4.17.1-1
- Java Version: OpenJDK Java 11.0.5
- Ghidra Version: dc16f29

When you open dialog windows with `DropDownSelectionTextField` (autocompleter), then you lost focus of completion list and description (see Fig. 1).

![problem](https://user-images.githubusercontent.com/4244396/73726778-2eb0b380-4741-11ea-8ab6-a88ec05cea0f.png)
> Fig. 1. Focus was lost

I fixed the issue by adding setting to i3 configuration file (see Fig. 2):
```
for_window [class="Ghidra"][window_type=dialog] focus
```

![ok](https://user-images.githubusercontent.com/4244396/73726966-96ff9500-4741-11ea-83ba-6af042f0ebed.png)
> Fig. 2. Fixed

Perhaps this will be useful for another people, who use tiling WMs or for NSA developers who can solve the problem, because I could not find a solution, only fix for i3.

**Comment by dragonmacher** [comment]
The original issue (all windows raising above other non-Java windows)  is caused by Java raising all windows when the modal is shown.

The second issue (dialogs initially not appearing over a tool moved across monitors)  may have been fixed (I cannot reproduce it).

The third issue (the `DropDownSelectionTextField`'s windows not staying on top) seems to be very specific to the given platform (I cannot reproduce it)
