### ISSUE TITLE
Scalar search signed/unsigned issue

### ISSUE THREAD

**Issue by ryanmkurtz** [NationalSecurityAgency/ghidra#1558]
I have a code unit that looks like this:

`MOV byte ptr [ESP + 0x24], 0xcc`

If I select that code unit and do a scalar search on my selection, looking for the _Specific Scalar_ `0xcc`, it doesn't find it.  However, if I look for the _Specific Scalar_ `-52`, it finds it.

**Comment by adamopolous** [comment]
If you right-click on that instruction and select "Instruction Info", does the type of that operand say "SCAL"? If not, it won't be found in a scalar search. Another way to check: if you select that instruction and open the instruction search dialog (Search->For Instruction Patterns), then filter out all scalars (select the blue 'S' on the toolbar), I bet that operand stays the same, because it's not seen as a scalar. 

I suppose this is a bit of a semantic issue. Internally that item isn't stored as a SCAL type but obviously as a user you don't care; if it looks like a duck and quacks like a duck, it's a scalar (I think that's how that saying goes).

**Comment by astrelsky** [comment]
> If you right-click on that instruction and select "Instruction Info", does the type of that operand say "SCAL"? If not, it won't be found in a scalar search. Another way to check: if you select that instruction and open the instruction search dialog (Search->For Instruction Patterns), then filter out all scalars (select the blue 'S' on the toolbar), I bet that operand stays the same, because it's not seen as a scalar.
> 
> I suppose this is a bit of a semantic issue. Internally that item isn't stored as a SCAL type but obviously as a user you don't care; if it looks like a duck and quacks like a duck, it's a scalar (I think that's how that saying goes).

That would only make sense if it didn't find it when searching for `-52` which is `0xcc` as a signed byte. Additionally it also finds it when searching for `-0x34`. I'm only speculating, but I'm wondering if it is ruling it out when searching for 0xcc because its unsigned value requires 2 bytes to fit in a signed value which is obviously larger than a byte. Pure speculation though, I haven't actually looked into the cause only reproduced it.

**Comment by ryanmkurtz** [comment]
I confirmed it's a SCAL.  This is more of an issue of it being an unsigned byte, but the scalar search is searching for signed bytes, or something like that.

**Comment by ryanmkurtz** [comment]
Here is a simpler example:

`OR EDX, 0xffffffff`

Searching for `0xffffffff` results in no matches, but searching for `-1` finds it.

**Comment by adamopolous** [comment]
Got a fix for this - we'll be rolling it out soon

**Comment by pabx06** [comment]
hi.
**in ARM8t big endian a 32bit scalar like 0xdeadbeef in two parts:**
```
        40e6e034 f6 4b 65 ef     movw       r5,#0xbeef
        40e6e038 f6 cd 65 ad     movt       r5,#0xdead

```
```
Instruction Summary
-------------------
Mnemonic          : movw
Number of Operands: 2
Address           : ram:40e6e034
Flow Type         : FALL_THROUGH
Fallthrough       : 40e6e038
Delay slot depth  : 0
Hash              : e28f0c88

Input Objects:
   const:0x0, const:0xbeef
Result Objects:
   r5, tmpNG, tmpZR
Constructor Line #'s:
   instruction(1503), movw(2547), ItCond(270), 
   Immed16(394)

Byte Length : 4
Instr Bytes : 11110110 01001011 01100101 11101111
Mask        : 11111011 11110000 10000000 00000000
Masked Bytes: 11110010 01000000 00000000 00000000

Instr Context:
   LRset(01,01)        == 0x0
   TMode(00,00)        == 0x1
```
![image](https://user-images.githubusercontent.com/4013370/115480217-5a3a9380-a24a-11eb-9253-f881f269811c.png)


**trying to search for it:**
-  `0xdead` first half
![image](https://user-images.githubusercontent.com/4013370/115480348-9a9a1180-a24a-11eb-9728-5bf11069ad8d.png)
![image](https://user-images.githubusercontent.com/4013370/115480532-f6fd3100-a24a-11eb-9479-8d2b84a080ea.png)

- `0xdeadbeef` the whole thing
![image](https://user-images.githubusercontent.com/4013370/115481196-5a3b9300-a24c-11eb-9ac2-3381b7ee6a61.png)

look like the issue still open for ARM two instructions scalar or is it signedness issue. the decompiler handle those no problems whatsoever 
![image](https://user-images.githubusercontent.com/4013370/115481066-0e88e980-a24c-11eb-91c3-b45aee347c27.png)


i am running:
![image](https://user-images.githubusercontent.com/4013370/115481457-ef3e8c00-a24c-11eb-87ab-dbd25541294f.png)
