### ISSUE TITLE
x64 array offset display seems wrong

### ISSUE THREAD

**Issue by AGDCservices** [NationalSecurityAgency/ghidra#1564]
**Describe the bug**
the way an array offset in x64 files is displayed seems to be wrong.  In the screen shot shown, there is an array element being referenced.  The array base is stored in R10 and the array offset is stored in RAX.  I would expect the instruction at 0x14000154a to be `movzx edx, [rax + r10]` instead of `movzx edx, [rax + r10*offset s_a01b...]`  because r10 is the address of the string, multiplying r10 by the string base again would seem to make the array base incorrect.  My best guess is the "*" symbol was meant to be the "->" symbol, but i'm not positive. 

**Screenshots**
Note the R10 register at the bottom of the screenshot.  R10 is the offset of the string and should not be multiplied by the string offset.
![image](https://user-images.githubusercontent.com/57851463/75103381-cd556500-55c7-11ea-8a99-c846957c8af5.png)

**Environment (please complete the following information):**
 - OS: windows 10
 - Java Version: openJDK 12
 - Ghidra Version: 9.1.2

**Comment by yuriks** [comment]
I noticed what I believe to be the same issue. Spurious references are added to memory operands when their index value can be determined by the analysis, which generates very confusing output:
![image](https://github.com/NationalSecurityAgency/ghidra/assets/341401/a506e815-7ec2-4400-b529-d1c0373abf31)

In that screenshot, all of the `offset DAT_1420b8390` and `offset DAT_1420b83a0` in reality have a value of `0x1`, but they are incorrectly displayed on the listing because of the memory reference.

 * OS: Windows 10
 * Java Version: OpenJDK Runtime Environment Temurin-17.0.11+9 (build 17.0.11+9)
 * Ghidra Version: 11.0.3

**Comment by emteere** [comment]
That is definitely an issue.  Looking at the code, it is replacing the scalar with the reference string if part of the scalar matches the address for values masked by 0xff, 0xffff, and 0xffffffff.  There are other checks done as well, but I think it is over-achieving, especially when the value is so different than the address itself.

I think this was an attempt to make the assembly code that would be needed to create the scalar value for the reference.
I think in practice the "->" on the whole operand would be better when it is not the actual address scalar value like is done for a register reference.
