### ISSUE TITLE
Implementing Parallel instructions in SLEIGH

### ISSUE THREAD

**Issue by meromwolff** [NationalSecurityAgency/ghidra#1600]
Hey,

How would you implement two instructions that execute in parallel? This means, for instance, that they can both fetch values at the same time from the same register (meaning that modeling them to execute one after each other could produce a wrong decompilation). What SLEIGH "features" would you think can be useful in this scenario? Iv'e tried looking in all the other SLEIGH files available but i couldn't find a clue regarding my question.

Thanks!  all help will be appreciated.

**Comment by astrelsky** [comment]
https://ghidra.re/ghidra_docs/api/ghidra/program/model/lang/ParallelInstructionLanguageHelper.html

You can then add `<property key="parallelInstructionHelperClass" value="java.package"/>` to the `.pspec` file. However it should be noted that I don't think anything ever loads this class and did nothing the last time I checked. It was a few months ago though.

**Comment by meromwolff** [comment]
First of all thanks for the fast reply!

So if indeed nobody loads this class, i guess these modifications wont get reflected in the decompiler even if i implement such a class? 
My other big problem is that from looking at this class, it seems not to be exactly what i need.
My scenario is that i have a constant sized instruction of 32 bits. These 32 bits could contain in some instructions a "mini instruction" in the **upper** 16 bits. In that case, the mini-instruction is executed in parallel with the "regular" instruction encoded in the **lower** 16 bits.
Because of that i wondered if there is something in SLEIGH itself i could implement in a .sinc file...

**Comment by astrelsky** [comment]
> First of all thanks for the fast reply!
> 
> So if indeed nobody loads this class, i guess these modifications wont get reflected in the decompiler even if i implement such a class?
> My other big problem is that from looking at this class, it seems not to be exactly what i need.
> My scenario is that i have a constant sized instruction of 32 bits. These 32 bits could contain in some instructions a "mini instruction" in the **upper** 16 bits. In that case, the mini-instruction is executed in parallel with the "regular" instruction encoded in the **lower** 16 bits.
> Because of that i wondered if there is something in SLEIGH itself i could implement in a .sinc file...

Unfortunately there is currently no sleigh implementation. It appears you can only show in the listing that 2 different instructions execute in parallel.

**Comment by meromwolff** [comment]
That's too bad - you would think they could add a SLEIGH directive like the delayslot() one...
Until then it appears it will take A LOT of manual work to implement parallel instructions in any instruction set.

**Comment by emteere** [comment]
You might be able to use shadow registers for computed values into registers, and then add a commit to copy the shadow registers or temporary values into real registers that occurs when both operations have finished.

:op || mini-op  is op & mini-op & ..... commit {
    build op;
    build mini-op;
    build commit();
}
The commit would need a mechanism to know what registers should be affected possibly stored in context bits.

You could just split the "op" instruction into a compute and commit phase.  The mini-op results would be over-written by the op results if they both write to the same register, however since the op has already accessed the possibly overwritten register, the operation should be correct.

mini-op: epsilon is no-mini=1 {}
mini-op: "mini" is non-mini=0 & x & y {
}

:op^mini-op  is op & mini-op  {
    compute-stuff...
    build mini-op;
    commit-stuff...
}

Alot depends on how the instructions are made parallel I would think.

**Comment by meromwolff** [comment]
@emteere  thanks for the detailed answer!
I guess you would be glad to know that's basically what i eventually implemented more or less :)
