### ISSUE TITLE
"Defined Strings" are generated every session

### ISSUE THREAD

**Issue by TheAifam5** [NationalSecurityAgency/ghidra#1622]
**Describe the bug**
"Defined Strings" are generated every new session on a specific binary. Other binaries showing strings right away. First version of the binary shows the strings right away, but the second version takes much longer to show them.

**To Reproduce**
There is no known way to reproduce it.

**Expected behavior**
"Defined Strings" should override the string cache when user clicks on refresh button.

**Environment (please complete the following information):**
 - OS: ArchLinux
 - Java Version: OpenJDK 13.0.2
 - Ghidra Version: 9.2 2020-Mar-07 1826 6266b18e429b3a3498e433c151ec2f6a55dfda65

**Additional context**
I would like to have a ability to clear the string cache manually or rebuild it and save with the project.

**Comment by dev747368** [comment]
The "Defined Strings" table is re-loaded each time the binary is opened, or even when switching between tabs if you have multiple binaries open at the same time.
The contents of the table currently are not persisted.  This behavior is typical of most Ghidra UI components, ie. the data type tree, symbol tree, etc.  Really big binaries that populate these UI components can take some time to finish loading.
If this helps you understand the situation better, could you re-state your issue, because I'm not sure what you are intending.

**Comment by TheAifam5** [comment]
When the strings are not precached then the issue does not exists :D
