### ISSUE TITLE
Instruction Pattern Search-Edit Bytes Input Mode mismatch

### ISSUE THREAD

**Issue by ChrisMGeiger** [NationalSecurityAgency/ghidra#1675]
**Describe the bug**
Instruction Pattern Search-Edit Bytes dialog defaults to displaying in binary but the Input Mode shows as "hex"

**To Reproduce**
1. Select a range of instructions
2. Go to "Search->For Instruction Patterns"
3. Click the "Enter Bytes Manually" button to launch the "Edit Bytes" dialog

**Expected behavior**
* "Input Mode" should default to "binary"
* Changing "Input Mode" should convert bases

**Screenshots**
![image](https://user-images.githubusercontent.com/2438380/77538712-897ba700-6e76-11ea-8ee1-195c18ec24c4.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: 11.0.4
 - Ghidra Version: 9.1.2

**Comment by GhidorahRex** [comment]
Switching the default to binary is a one-line fix.

Changing the behavior of the input mode to convert bases is more significant. Except we already have code to convert the base when the radio buttons are clicked. But we're not properly updating the behavior because the inputMode gets updated before we check if the inputMode changed.
