### ISSUE TITLE
Expected CPU and memory requirements?

### ISSUE THREAD

**Issue by chrismiller** [NationalSecurityAgency/ghidra#176]
I've been trying for a few days now to analyse a 32MB ARM Cortex R4 ROM (a digital camera firmware) using various settings, but every time I have attempted it Ghidra has eventually crashed (OutOfMemory) or hung after several (up to 12 or more) hours of analysing. During the analysis, the memory usage fluctuates from a few hundred MB up to the maximum (which I suspect is causing a lot of swapping and garbage collection), and CPU fluctuates from saturating one core to saturating all 8 (4+4 with hyperthreading), making the PC virtually unusable for a large part of the time. Note that IDA can analyse the ROM in a few minutes without issue.

I have 16GB of RAM and a Core i7 4790K CPU. I've set MAXMEM=14G and I've tried increasing Decompiler Max Payload to 200.

Question: Is this normal? Is there anything I can do to analyse this ROM, or do I simply need more CPU and RAM?

I can't attach the project/ROM here but could supply it to you offline if that is helpful.

**Comment by dragonmacher** [comment]
You system settings seem more than adequate.  

Generally, analysis time is proportional to the size of the binary.   Large binaries (~100MB) can take hours, or even days, to analyze. 

I believe you are encountering a degenerate case in this instance.   In order to make progress on analysis for this binary you can try disabling various analyzers before you perform the initial analysis.   Using this debugging approach will not only allow your analysis to finish (minus the disabled analyzers), but it will also allow you to identify the broken analyzer(s).

**Comment by chrismiller** [comment]
Thanks for the information. I had already tried a few combinations of individual analysers with some success, but haven't worked through them methodically to narrow down the problem. I will do so and report back if I find anything others may find helpful. One thing I wasn't sure of - does the analysers are run affect the final result?

**Comment by ghidra007** [comment]
Try turning off the stack analyzer and any of the decompiler analyzers. They can take a long time and you can always run them later as one-shot analyzers or even individually per function. It is possible that the decompiler is having problems and trying the maximum amount of time for each function before timing out.

**Comment by emteere** [comment]
Running for days is rather unusual.  Your ROM isn't that large.  After about 1/2 hour on a large image I start to question if something has gone wrong.

Is there a particular analyzer that is taking alot of time?  You can see that in the lower right hand corner during analysis, or better yet, by canceling analysis with the red button in the lower left corner.  In the console for the Project manager, the times of each analyzer has taken thus far will be dumped.

For ARM Thumb binaries, the compiler can use the BL instruction for long jumps when the function is particularly large.  If this is occurring, It could cause incorrect analysis, but usually not a time issue.  There is a script you can use that will attempt to clean up the issues and you may want to use that to clean up the long jump BL's.  It tries to detect the issues automatically and fix them, but it isn't always successful.  You can select the instructions that belong in one function and run the script.  Any BL's that branch to locations within the selected area will be changed to a JUMP instead of a CALL.  The script is Fix_ARM_Call_JumpsScript.

Also, non-returning functions can cause issues.  If one function falls into the next function, for example when a call to stack_check_fail() is the very last instruction, then that can cause time issues.  There is an analyzer that will detect these situations.  In certain situations, it can be the cause of time issues as it attempts to fix the damage from functions that have been detected as non-returning.

**Comment by chrismiller** [comment]
Thank you @ghidra007 and @emteere, that's really helpful advice. I'll try everything you suggest, though it will likely be a week or so before I have a chance to do so. One other thing I will mention is that once the analysis has been running for a long time and my PC starts to "bog down" (likely due to garbage collection and paging?), the Ghidra GUI tends to become non-responsive. Trying to stop the analysis at this stage by clicking on the red X doesn't generally have any effect unfortunately. I'll try reducing the maximum heap a bit to see if that prevents excessive paging at least.

**Comment by emteere** [comment]
At that point, I'd cancel the the analysis and look at what went wrong, or evaluate what is taking alot of time.  If the cancel monitor is unresponsive, some thing is most likely stuck in a loop without a cancel monitor.  If you have many windows up I would take them down, (call graph, data types, symbol table open).  All the views will attempt to update themselves occasionally when the program changes.  If there is a large amount of data displayed, it will bog down on the continued update or with the data structures necessary to display the information.
