### ISSUE TITLE
uint32_t/uint64_t sizes are compiler specific

### ISSUE THREAD

**Issue by Arcnor** [NationalSecurityAgency/ghidra#179]
The sizes for (supposedly fixed width) types `uint32_t/uint64_t` and others are compiler specific, which IMHO they should not be. I understand that `uint` or `ulong` will be compiler specific, but fixed width types should be exactly that, fixed.

**Comment by emteere** [comment]
Two different variants were parsed, one for 32-bit and one for 64-bit because of the way the types were defined in the header files for the data types you mention (as well as others).  The definitions are as parsed from the header files.

I would agree they should always be fixed.  Unfortunately within the header files for the 64-bit type definition for uint64_t  is defined as ulong, since ulong is 64-bit on a 64-bit system, and as "long long" which would be 64-bit on both 32-bit system and a 64-bit system.

The Ghidra Data Type manager tries to store data types in a generic form such that the data type organization rules for the particular compiler can be specified.  The tag in the hover field that says (compiler specific) is a note that the compiler specification for your program could normalize the data type to the size of the data type for the compiler spec used for your program when the data type is added to your program.

**Comment by Arcnor** [comment]
I'm far from an expert in C/C++, but by parsing the headers, won't the definition of `uint32_t` (as an example) be tied to the definition of that particular platform (like Linux, if they were originally parsed from there) and/or compiler, instead of being independent? (like the standard expected)

I mean, I'm sure `uint32_t == uint` is a valid definition for my platform, but it breaks when I try to analyze code for other platforms (like MSDOS).

**Comment by emteere** [comment]
Yes compiling the header files from a particular platform can cause some issues.  In most cases the data organization settings can take care of mapping the data type for your platform.  If the header files are written correctly, using common data types, then the data organization can work.  The example from linux header files you mention has two different definitions for 32 versus 64.  The included clib and clib64 parses work generally.

For MSDOS, you would be using 16-bit data organization definitions, so the uint would be potentially chaged to a different size.  If working with a binary on MSDOS, I would try to get the header files for that platform and parse them instead of relying on the general ones included.  A possible enhancement could be to find a header files for a 16-bit version of the standard clib and include a clib16 data archive that would work in most cases for 16-bit clib based code.

Internal structures that aren't always organized the same way or include the same fields can be incorrect as well.  For example the FILE data structure may have a different internal definition based on the platform.

You are correct that parsing the header files with the exact compiler and compiler settings is the only way to be certain everything matches up.  An alternate mechanism that is not always a perfect matching data definitions would be extracting the data types information from any provided debug information.  The data type mapping to compiler settings gets much worse with bitfields as well as packing based on the compiler internal choices and compile time settings.

Another example is function signatures, they can be mapped to the actual binary in many ways by the decompiler.  Function signatures are also stored in a generic way, and an attempt is made to map them to the functions they are applied to.

So the choice to include the clib and clib64 base definitions is a compromise in providing solid useful data type information versus 100% correct for all cases.  If you use the included LINUX based CLIB and CLIB64 data type archives, keep the potential for data size issues in mind.

**Comment by Arcnor** [comment]
Thank you for your very complete answer, I really appreciate the effort you put into your responses.

The key bit for me from your responses is that we should not always rely on the provided types but use our own when it makes sense, which is nice to know, I'll do that for my targets when it makes sense, thanks.

I'll close this then, given that it's not really a bug, but "by design".
