### ISSUE TITLE
Ghidra can't be launched on Windows with a "!" in the path

### ISSUE THREAD

**Issue by GitGitHubUser** [NationalSecurityAgency/ghidra#1817]
If Ghidra is located in a directory with a "!" sign in it - it won't run, it just shows an error that it can't locate LaunchSupport class and that it can't find a suitable JDK version. Windows 10. Easily reproduceable.

**Comment by ryanmkurtz** [comment]
Most likely the sample problem as #1726.

**Comment by quosego** [comment]
https://github.com/NationalSecurityAgency/ghidra/blob/4ca92075412d7c951352449d0024ee85a52a2dcf/GhidraBuild/LaunchSupport/src/main/java/LaunchSupport.java#L80

I suggest handling special characters by converting to a URI then obtaining the path. 

```
File installDir = new File(installDirPath).toURI().normalize().getPath();
```

Reference: https://www.eclipse.org/eclipse/platform-core/documents/path_changes.html

**Comment by ryanmkurtz** [comment]
This particular problem lives in ghidraRun.bat, which is a Windows batch script.

**Comment by xiaoyinl** [comment]
The problem is that in a Windows batch script, after you enable delayed expansion by `setlocal enabledelayedexpansion`, the ! sign becomes a special character. If the Ghidra directory contains `!`, then the variable `SUPPORT_DIR` contains a `!`. When you use `%SUPPORT_DIR%`, its value would be incorrect. Thus, `INSTALL_DIR`, `CPATH`, etc. are all incorrect.

I am not so sure how to fix it though, since delayed expansion is needed here and I don't know how `!` in a variable can be escaped.

**Comment by topia** [comment]
I tackled this issue, but unfortunately, there is no "simple" solution for it.

As its description, `setlocal enabledelayedexpansion` expands `!something!` notations AFTER expanding `%something%`, `%num` and `%char`.
I think I can avoid it by replacing any usages of `%something%` with `!something!`, but my idea is partially wrong. There are no delayed-expansion versions of `%num`/`%char` notations, so I can't replace all path handlings.

After I spend some time, I think we have three options for this problem.

1. not support any paths/arguments containing `!` - leave this ticket as open, or close as wont fix
2. disable delayed expansion for `%num`/`%char` temporarily with `endlocal`, and use `!something!` for all expansions in delayed expansion
3. enable delayed expansion for required places only, especially inline variable modification in `for` and `if`, and keep usages of `%something%` as is.

For the 2nd or 3rd option, [parse arguments](https://github.com/NationalSecurityAgency/ghidra/blob/894ab9515f9d8ddc30feb6137e57917869e823cc/Ghidra/RuntimeScripts/Windows/support/launch.bat#L47-L55) may contain `!`, we need to re-write it with a bit hacky-way(`call :subroutine "%%a"` with double-quote nightmare).
In addition, I think switching delayed expansion is a bit complex, so it has negative effects on maintainability.

What do you think? Maybe I can try some modifications in my spare time.

**Comment by gtackett** [comment]
I don't know much about PowerShell, but would a launcher script in PowerShell be able to deal with odd pathnames more flexibly?

**Comment by topia** [comment]
> I don't know much about PowerShell, but would a launcher script in PowerShell be able to deal with odd pathnames more flexibly?

Yes, I think so. if we can depend on PowerShell, we should be able to handle it more easily.

**Comment by xiaoyinl** [comment]
@topia I tried the option 3. The change I made is in PR #3125. It seems to work fine with path that contains "!".

**Comment by ryanmkurtz** [comment]
Note that in addition to issues with `launch.bat`, paths containing `!` are also a pervasive problem within the JVM as well, due to `!` being used as the jar-separator in a path.  Even gradle is affected by it.  For these reasons, Ghidra will not support `!` in paths to the Ghidra installation/source repo.  I will add some checks in the launch scripts, as well as some documentation in the Installation Guide which will make the error more obvious to the user.  We'll consider these changes the fix for this issue.
