### ISSUE TITLE
Problem parsing or applying PDB information: Bad name

### ISSUE THREAD

**Issue by Mitsos101** [NationalSecurityAgency/ghidra#182]
**Describe the bug**
After applying [this patch](https://github.com/NationalSecurityAgency/ghidra/issues/94#issuecomment-471240696) to be able to load chrome.exe.pdb (latest version, can be retrieved using `symchk` from https://chromium-browser-symsrv.commondatastorage.googleapis.com/). The generated XML file is [chrome.exe.pdb.xml.zip](https://github.com/NationalSecurityAgency/ghidra/files/2958626/chrome.exe.pdb.xml.zip).
The following error appears: ![Bug screenshot](https://i.imgur.com/LeT505p.png)

**To Reproduce**
1. Apply [this patch](https://github.com/NationalSecurityAgency/ghidra/issues/94#issuecomment-471240696) to `Ghidra/Features/PDB/src/cpp/symbol.cpp`, rebuild the project, and move `build/os` to `os`.
2. Import and load `chrome.exe` in Ghidra.
3. Perform auto-analysis.

**Expected behavior**
This error doesn't appear, and symbols are loaded normally.

**Screenshots**
See above.

**Attachments**
See above.

**Environment (please complete the following information):**
 - OS: Windows 10 amd64
 - Java Version: 11.0.2
 - Ghidra Version: 9.0

**Comment by kant2002** [comment]
This is related to following code

https://github.com/kant2002/Ghidra/blob/94bde3f72129983d213ce6ae1f6a7fb8d5f646bd/Ghidra/Features/PDB/src/main/java/ghidra/app/util/bin/format/pdb/PdbParserNEW.java#L1226-L1237

Error produced by the following fully qualified name
`base::internal::BindState<`lambdaat../../base/threading/thread_task_runner_handle.cc:73:7',scoped_refptr<base::SingleThreadTaskRunner>,base::internal::UnretainedWrapper<base::SingleThreadTaskRunner>,std::unique_ptr<base::RunLoop::ScopedDisallowRunningForTesting,std::default_delete<base::RunLoop::ScopedDisallowRunningForTesting>>>`

In that place name of the data type want to be placed in the hierarchy, and there assumption that hierarchy does not want to have / to be in the name of the hierarchy. Basically that piece of code does not work for C++ names which could be rather complicated in nature. 

I see 2 issues with this piece of code:
- Namespaces incorrectly deduced. String split does not work reliable
- When having file name in the escaped lambda name, it does not work for Category name (issue in the `new CategoryPath(CategoryPath parent, String name)` constructor, since name has `/` in the name of the symbol.

**Comment by Mitsos101** [comment]
Hello @kant2002, it seems that this issue has not been fixed in the latest release. As a workaround, do you happen to know what changing `DELIMITER_CHAR` (No "Bad name" exception) and `NAMESPACE_DELIMITER` (namespaces will still be incorrectly deduced) would break?

**Comment by ghizard** [comment]
This issue will track with #94 with regard to forward slash characters in the name.
