### ISSUE TITLE
Script related: UNCONDITIONAL_CALL and FALL_THROUGH edges seems wrong

### ISSUE THREAD

**Issue by tosanjay** [NationalSecurityAgency/ghidra#1829]
Hi,
When using SimpleBlockModel() class, each CALL instruction is also treated as controlflow jump and therefore, we get a new edge with the called function as destination of the edge. But then, we also have a FALL_THROUGH flowtype with the destination as the next instruction. This seems not right as CALL is like a unconditional jump and therefore, there should not be a fall though edge.

Ideally speaking, the next basic block starting from the next instruction after the CALL instruction should have an incoming edge from the called function (more technically, the last basic block containing RET of the called function). So, am I missing something?

**Comment by emteere** [comment]
The current block models are not single execution flow block models.  The models are meant to be extended for different purposes with other types of models where this flow behavior could be factored in.

In order to have the models work as you would like the blocks in the called function would need to be duplicated since the function could be called by multiple locations.  The return block would then need to be linked back to both call locations.  Unless the models are also changed to duplicate the blocks, just changing the flow links would not be correct.

For a single static flow block model, the flow of the blocks could be traversed and the call/fall-thru collapsed as you wish, or the model could be extended to do the collapsing within the model.

**Comment by tosanjay** [comment]
Hi, I understand. As per my need, I could do it by following the call and creating an artificial return edge per call. I also liked the that control-flow has type info (e.g. TERMINATOR), which helped a lot to have a very precise info.
