### ISSUE TITLE
zext PCode instruction causing issues with decompilation

### ISSUE THREAD

**Issue by janjiblack** [NationalSecurityAgency/ghidra#1850]
I recently switched from 9.0.1 to 9.1.2 and I'm having an issue where my zext/sext PCode instructions are causing an issue in the decompiler view. This happens when the instructions in my disassembly use registers that are then used in a conditional branching instruction. This is a custom architecture.

In the decompiler view I get the following warning:
/* WARNING: Removing unreachable block (ram, <address>) */

The instructions in my sinc file look like this:
ZeroExtend...
{
   local data = IREGISTER[0,8];
   OREGISTER = zext(data);
}

BranchNotEqual...
{
   if (REGISTER1 != REGISTER2) goto ADDRESS;
   goto inst_next;
}

Resulting PCode in the disassembler:
REGISTER1 = INT_ZEXT *[register]0x3:1
$Ud70:1 = INT_NOTEQUAL REGISTER1, REGISTER2
CBRANCH *[ram]ADDRESS:4, $Ud70
BRANCH *[ram]ADDRESS2:4

**Comment by emteere** [comment]
Did this work in 9.0.x?

For the unreachable code warning, you can try turning off the option Edit->ToolOptions...Decompiler->Analysis->EliminateUnreachableCode.
When this occurs the decompiler is seeing something as a constant and removing the block of code.  You'll then most likely see things like:
```
if (true) {
    return 0;
}
or
bvar3=false;
...
...
if (!bvar3) {
...
```
Hopefully this will shed some light on the code that is being removed, and why.

**Comment by janjiblack** [comment]
Yes, it did work in 9.0.x. And plus this is way too many instances where a branch comparision is preceeded by an instruction that requires some extension that this is happening. Hopefully this isn't confusing for removing var names and such, but here's an example of the difference when I just turn the zext into an AND instruction:

9.0.x:
void Func(byte param_1, uint param_2, uint param_3)
{
    int var1;
    int var2;
   (&ADDR_1)[param_1] = 0;
   ...
The EliminateUnreachableCode unchecked:
void Func(byte param_1, uint param_2, uint param_3)
{
    int var1;
    int var2;
    if (true)
       (&ADDR_1)[param_1] = 0;
   ...
With changing INT_ZEXT to INT_AND:
void Func(byte param_1, uint param_2, uint param_3)
{
    int var1;
    int var2;
    if (param_3 == '\x01')
       (&ADDR_1)[param_1] = 0;
   ...

Another issue i just found while looking for that example is this:
With INT_ZEXT:
(*(code*)ADDR(param_1, param_2 >>0x18);
With INT_AND:
(*(code*)ADDR(param_1, param_2 & 0xff);

Changing to AND fixes some of the problems, but for a few of my instructions i need to add a zext(x == y) for the return and for sext() that's a little more difficult of a workaround

**Comment by janjiblack** [comment]
As an additional update to that snippit of code, I have 4 functions calling the example function. Of those 4, a constant of 0 is param_3 in two and the other two are based on other parameters.

**Comment by emteere** [comment]
Is your processor LE or BE?
Either there was a bug fixed of bug created in 9.1.
Are you trying to get the upper bits of a register, or are you trying to take the low byte of a register?
Try using:
local data = IREGISTER:1;

**Comment by janjiblack** [comment]
I tried doing the IREGISTER:1 before and it makes no difference.
The processor is big for instructions and little for data. I've set endian="little" and instructionEndian="big" in the .ldefs file and "define endian=big" in the slaspec file. I'm trying to get the low byte.

**Comment by janjiblack** [comment]
Oh I just realized there was a change in the ldefs file at the same time the upgrade to 9.1.2. endian was "big" and instructionEndian was not set, causing the need for manual endian changes with data in the .sinc file. So maybe this is an issue with how the differences in endianness is treated?

**Comment by emteere** [comment]
If your data is LE, then that is definitely the issue.
The *[register]0x3:1 address means that the byte at offset 0x3 in the register address space is being accessed.  If your register, say R0. starts at 0x0, then this is the fourth byte of the register.  So if the machine is LE data, then the byte that should be accessed is *[register]0x0:1.

If it worked correctly before, that was probably a bug that was fixed with the bitfield access.  It sounds vaguely familiar that a bug with the bitfield access was fixed.  I'd have to study the changes to see if it affects this.

_instructionEndian_ is only added for the ARM processors.  If you don't set it, it takes on the endianess declared in the .slaspec.  I don't believe it has the effect you are hoping for.  I don't see it being worked into the sleigh processor to support a LE data and BE instruction matching.  I think it is more of a declaration for solving ELF import issues.  It should only matter if you declare it, and then it will affect FID files and other accesses.  It is actually flagged as an error if the instructionEndian declared in the .SLASPEC (.sla when compiled), and the .ldefs file differ.
The endian setting in the .slaspec is the most important to get right.  It affects the endianess of the instruction matching, storage endianess in registers, and access to sub-pieces of registers, loading/storing values from memory.  If you have mixed endian instructions/data, you have to be really careful.
The ARM supports LE/BE data, but the instructions are always LE.  So all the patterns are set up to be correct through careful working of the tokens for LE.
Many processors that are LE/BE supported have the instruction endianess and the data endianess set the same when a program is compiled for the processor.

If your processor has BE instructions, and LE data, I would set the .slaspec to LE and carefully do the token matching for the instructions and their fields.  You could make the instruction BE, but they you will have to carefully track down data issues like this if you are accessing sub-pieces, and issues will creep into other places.

You could get away with what you are doing very carefully but anything that exposes the endianess of local variables and registers within the slaspec has to be carefully scrutinized.  If this is the only place, you could use:
   
local data:1 = IREGISTER(3);
or
local data:1 = IREGISTER[24,8];

which should truncate the least significant 3 bytes and grab the high byte (really the low byte) of the register.

The way I look at it, sleigh is always one endian.  Ghidra can be somewhat manipulated in how values are loaded and stored from memory as you are doing with the endianess setting.

It might be possible to add a real data endian and instruction endian into the .slaspec, such that values encoded into endian sensitive access would work correctly.  And where they differ, add checks/errors (subpiece, memory mapped registers, overlapping sub-register access (AH,AL,AX...).
If you copy the full value out of memory and into a register there isn't a problem.  Issues like this don't occur, and the endianess can be set by the .ldefs file.

**Comment by janjiblack** [comment]
Unfortunately it's far from the only instance. Turning everything into little would make a massive mess of the token matching; immediate tokens that, say, look for bits 0-21 will need to be split up and have to be manually added together causing just as much decompiler junk as manually changing the endianness of all data references in the pcode.

I do find it odd that zext of a byte in this case causes the decompiler to auto remove code, but that performing an AND that would affects the same bits(the big endian registers being treated a little) are not removed. Is the AND operation not being optimized by the decompiler or is it treating it as if it was big?

Either way, utilizing instructionEndian is 90% of what I've wanted since I started writing the pcode for this architechure. Before I close this just to be sure, are locals also treated in the data endianness? EG. when I'm taking the result of a boolean comparison in the pcode should I store the local result in bit 0 or bit 28?

**Comment by emteere** [comment]
I feel your pain.  The arm thumb was a struggle originally with careful token management.

Dead code removal on constant evaluation is a must for the decompiler.  The decompiler calculates that top value of the register is zero and if you zext() a value that is always zero the conditions can be evaluated on a constant and are always true or false.
We've thought about adding a black hole detector for the decompiler where large swaths of pcode that should be part of the data flow is not part of the dataflow.  There actually is a script that attempts to do this CompareFunctionSizesScript.  I like DecompilerBlackHoleDetection better.

If you take sub-pieces of the unique, it would do the same thing.
The endianess comes in if you are trying to get at the sub-parts of a larger value.
If you are computing a boolean you can just zext(bv != 0).  I don't think you would need to specially store the values in the local result.

**Comment by janjiblack** [comment]
Hmm... Is there a writeup of how far the constant detection goes? I've kinda narrowed down where all of my other problems are, they all are values created by shifting constants in the pcode, shouldn't be too hard to transform the shift values to. 
Thanks for the help
