### ISSUE TITLE
new processor interrupt vector support

### ISSUE THREAD

**Issue by simeonpilgrim** [NationalSecurityAgency/ghidra#1855]
I am implementing support for the Fujitsu FR process, and trying to nicely solve support for the INT instruct.

If I follow the x86 model and pcodeop
`define pcodeop swi;        # for INT instruction`
then I get that nicely in my decompliation, but the FR has a assignable register TBR that is the address of the interrupt vector table. And the TBR is set earlier in the code bring up, so I would ideally like to be able to compute

`tbr_ptr: tab_ea is td_x & c_tbr [ tab_ea = c_tbr + 0x3FC - (td_x * 4); ] { export *[ram]:4 tab_ea; }`

my first idea was to use the context, thus the c_tbr, but I already had a context setup for the PS (processor state) register, and when I made a second I like this:

```
define endian=big;
define alignment=2;
define space ram type=ram_space size=4 wordsize=1 default;
define space register type=register_space size=4;

define register offset=0 size=4 [r0 r1 r2 r3 r4 r5 r6 r7 r8 r9 r10 r11 r12 r13 r14 r15];
define register offset=0x100 size=4 [pc ps tbr rp ssp usp mdl mdh];

define context ps
  ilm4=(20,20)
  s_f=(5,5)
  i_f=(4,4)
;
define context tbr
  c_tbr=(0,31)
;
```
I get an error:
`Duplicate symbol name: i_f (previously defined at fr.sinc:26) (SleighCompile)`

so I added another register with size 16 at the same offset 

```
define register offset=0x100 size=16 [hack_a hack_b];

define context hack_a
    d0_0=(0,31)
    d0=(32,35)
    i_f=(36,36)
    s_f=(37,37)
    d6=(38,51)
    ilm4=(52,52)
    d21=(53,63)
    c_tbr=(64,95)
;
```

took a while to learn I needed to align the packing to get the expected outcome from the assignment. in the move operator.

```
pre_mov_85: is ta_reg_s=0 & ta_reg_i [ c_tbr = ta_reg_i; globalset(inst_next,c_tbr); ] {}
pre_mov_85: is ta_reg_s>0 {}
```
thus for the code
```
        00040060 9f 80 00        ldi:32     0xdfc00,r0
                 0d fc 00
        00040066 b3 00           mov        r0,tbr
```
it shows 
`assume tbr = 0x0`
 and when r0 is later assigned to it swaps to `assume tbr = <UNKNOWN>`
so I cannot workout how to get the value of r0 in the c_tbr verse c_tbr pointing to r0..

but still a 128bit context feel like the wrong way to mange the PS and TBR is there a cleaner way?

Or cleaner method that using a .pspec 
```
    <tracked_set space="register">
      <set name="tbr" val="100"/>
    </tracked_set>
```
which didn't seem to work.

or the epic hard coding of a define in the .slaspec
`@define TBR_ADDR "0xdfc00"`

Version: 9.1 2019-0ct-24 1737
Java: 12.0.1
OS: Windows 10

**Comment by emteere** [comment]
If the TBR can change, it should be a register, and you cannot use it in the "[ disassembly action ]" area because the value is not known.  It should not go into the CONTEXT register.  You can't match against a value that isn't known.

Context should really only be used for configuration or values that flow in disassembly.  If the TBR is set in one routine, say the reset routine, then the disassembly would not flow that value everywhere.  Since it would then become an implicit value that affects every INT instruction.  Also, say you disassemble the INT instruction first, then run across the code setting the TBR.  The INT would not disassemble correctly.

You can initialize it to a base value in the .pspec file, and then either the RE must set the TBR values across memory if different than 0x0, or if the value appears in the code right before the interrupt, then it will compute the destination correctly.  The TBR setting can be detected by an analyzer and either propagated across memory, or just assumed to be that value across memory.  The MIPs does this with the GP register.  It is a bit cumbersome especially if there are multiple settings of the TBR  at different program locations.

For the processor, I would just keep it simple and assume something else will initialize the TBR register.

I would just add the pcode for the TBR table calculation into the pcode for the INT instruction.

**Comment by simeonpilgrim** [comment]
nod, I knew I was over thinking it. I also was trying to get INT work (better than it ever had in IDA) before have 100% coverage of my pcode for all instructions, so flow was often stopped.

I also was want it to be "auto-magically" working, but there is a boot loader that is normal not captured, so setting the processor up "correctly" by default is not possible for this firmware.

So simplify the pcode for the INT to have the math inside it, using the tbr register, and then using the Register Manager to set the TBR for all addresses to be the known value for this firmware, does correctly have the value in the function deomplile window.

```
    local int_ea:4 = tbr + 0x3FC - (td_x * 4);
    set_pc(int_ea);
    call [int_ea];
```

gives:

`puVar1 = (undefined4 *)(*(code *)&PTR_Int40_Handler_000dfefc)();`

tbr = 0xdfc00 here, and td_x is 0x40

which feels rather ungamely, 0xdfefc has ptr 0x040cba which is Int_Handler40 (I named it), is there a way to have the pointer mangling above more clean? aka is there something more I can do in my pcode/sleigh to have this be tidy, or is this just something that the user has to or can clean-up, and if so as a user what might that be?

And thank you for you answers so far, and the tool, it awesome.

**Comment by emteere** [comment]
I believe the PTR_ is coming from the autonaming of the pointer.
If you set the vector table memory area or pointers defined there to constant, it should give you the correct value without the indirect PTR_ label.

I don't think you can solve this in sleigh, since there is indirection in the interrupt.

You could also label the vector table at dfc00 with the correct INT40_Vector.
If you are setting the TBR in the PSPEC, then you can also put the labels there for the interrupt table that match the initial TBR value.
