### ISSUE TITLE
GhidraFileChooser unnecessary ellipses ....

### ISSUE THREAD

**Issue by ryanmkurtz** [NationalSecurityAgency/ghidra#1862]
When I browse into a directory with only a couple of entries, the file names always have unnecessary ellipses:

<img width="590" alt="1" src="https://user-images.githubusercontent.com/5378554/81967057-5d63e300-95e8-11ea-8149-b57427b91d40.PNG">
<img width="590" alt="2" src="https://user-images.githubusercontent.com/5378554/81967063-5e951000-95e8-11ea-8880-33e788a14805.PNG">

If I go into a directory with a lot of files, it looks good:

<img width="590" alt="3" src="https://user-images.githubusercontent.com/5378554/81967081-66ed4b00-95e8-11ea-8f48-fee12b67b63d.PNG">

131228a250c36991d43eb019a5688c0d27f02cef might be relevant.

**Comment by ryanmkurtz** [comment]
Here's another pretty bad case I just came across:

<img width="590" alt="Capture" src="https://user-images.githubusercontent.com/5378554/82905190-8ca41980-9f31-11ea-9f14-218303512270.PNG">

**Comment by dev747368** [comment]
Ryan,
  could you log the width of icons being returned from LocalFileChooserModel.getIcon()'s return "fsView.getSystemIcon(file);" and see if any are not 16 pixels wide?

**Comment by ryanmkurtz** [comment]
Everything is showing as 16.  I should also mention that I'm on a HiDPI monitor and Windows is rescaling everything.

**Comment by saruman9** [comment]
Similar issue in the Active Project window :
![2020-06-23_21-01-25](https://user-images.githubusercontent.com/4244396/85438642-d7e33380-b594-11ea-8629-642a69f3e96d.png)

But it is not depends from the length of name, because I can see long names:
![2020-06-23_21-04-55](https://user-images.githubusercontent.com/4244396/85439013-35778000-b595-11ea-9598-d209132caa31.png)

Version of Ghidra: bdbbca3

After applying the patch by @ryanmkurtz (#1902):
![after](https://user-images.githubusercontent.com/4244396/85439633-e2ea9380-b595-11ea-99c2-ccadef506820.png)
and
![after_1](https://user-images.githubusercontent.com/4244396/85439671-f0078280-b595-11ea-98c2-f87c4cfd416c.png)
 
- OS: GNU/Linux
- Java Version: openjdk 11.0.7

**Comment by ryanmkurtz** [comment]
That is #1858.  It's a different problem.

**Comment by saruman9** [comment]
Oh, sorry. I remembered, that there was a similar issue, but I was mistaken.

**Comment by dev747368** [comment]
@ryanmkurtz  I can dup on win10 when I change my scaling to 2x in the os's display settings.  Its also interesting that the icon for the folder changes when the scaling is enabled.  (a pretty "open" folder icon vs plain flat folder icon)

**Comment by ryanmkurtz** [comment]
Weird.  Do you think #1902 is an acceptable solution?

**Comment by saruman9** [comment]
> Weird. Do you think #1902 is an acceptable solution?

The solution wraps filenames it the Active Project window ([see above](https://github.com/NationalSecurityAgency/ghidra/issues/1862#issuecomment-648330841)). It is normal?

**Comment by ryanmkurtz** [comment]
The solution should not have changed anything about the Active Project window.

**Comment by dev747368** [comment]
Fixed by c759dd1609acf1c25cd2c5888e9a62b0c06b36a7.
