### ISSUE TITLE
Support force loading of PDB files

### ISSUE THREAD

**Issue by gamozolabs** [NationalSecurityAgency/ghidra#189]
Currently if the program you are looking at has no RSDS/debug section you cannot apply a PDB to it through the interface. It'd be nice if we could get a popup like "This PDB does not match your target program, would you still like to load it?"

This is helpful for when you have a PDB file for a program but that program has had it's RSDS information removed.

**Comment by cravensbrayn** [comment]
Got bamboozled by each comment made

**Comment by ghizard** [comment]
I was tempted to change this "bug" to "enhancement," but there was a basic capability to do what you ask in Ghidra already, but it was broken, so "bug" was still pertinent.  The fix for what was broken is in Ghidra 9.1, which came with GT-3209 (the commit mistakenly referenced GT-3029), and we feel the fix also fixed issues #198 and #1024.  These issues saw odd errors because the broken logic attempted to validate the XML that did not exist when the pdb.exe validation was also employed on a mismatched PDB (when validation fails here, no XML is produced, which caused the XML validation to blow up).  I believe this fix should now present the option you never got to see regarding force-loading the PDB that does not match.

Can you validate that Ghidra 9.1 fixes your issue here?

**Comment by Gh0stBlade** [comment]
Hmm no..... just no...

The issue is this:
![image](https://user-images.githubusercontent.com/6951235/68581460-5957dc80-0470-11ea-976d-c7f430affee7.png)

And it's still present in 9.1 Allow us to load PDBs regardless of having the debug information there or let us add the debug information ourselves somehow.

**Comment by ghizard** [comment]
@Gh0stBlade Got it.  Thanks for clarifying the issue.

There are multiple places where one might want to specify a PDB (e.g., via the "File Load PDB..." and through auto-analysis).  We need to make sure that if the GUID/Signature+Age is not present, that we give the user the opportunity to specify a PDB or perhaps to even specify a mismatched PDB even if we believe there is a matching one available.

I'm curious about adding the ability to specify the PDB for a PE in the Project Manager so that it is known/remembered at the time of analysis... again, even if it does not match or cannot be matched.

**Comment by IgrBn** [comment]
Any status update on this?

**Comment by dev747368** [comment]
Kinda.  Most of our effort is on java native PDB parsing, and this issue with specifying a pdb manually is definitely in our use-case model for how things will shake out with the new code.

**Comment by dev747368** [comment]
Should be addressed in 22675e9f39dd23bb1f0df775ef3cc2c8f22e81a7.  Use File | Load PDB File... and manually select the pdb file.
