### ISSUE TITLE
Variable rename doesn't work

### ISSUE THREAD

**Issue by croghostrider** [NationalSecurityAgency/ghidra#193]
**Describe the bug**
Hi, I have tried to change a variable name in a small binary,
but it does not change the name from all equal variables.
Its create a new variable declaration, see screen capture.
Sorry for my bad English.

**To Reproduce**
![screencapture](https://user-images.githubusercontent.com/8603272/54356058-f9980000-465a-11e9-8609-76003c879c4e.gif)

**Expected behavior**
Change all equal variable names 

**Attachments**
[main.zip](https://github.com/NationalSecurityAgency/ghidra/files/2966299/main.zip)

**Environment (please complete the following information):**
 - OS: Kali 2019.1a (VMware Workstetion Pro on Windows N 10 Pro 64bit)
 - Java Version: 11.0.3
 - Ghidra Version: 9.0

**Comment by emteere** [comment]
The renaming of a variable in the decompiler can be problematic at times.  If you introduce a variable that the decompiler has at the beginning of it's analysis versus a variable it creates as part of data flow analysis, you can end up with differing variables.  The variable merging algorithm can be affected by the initial information of the variable rename.

In your case, I believe the decompiler is correct but not an optimal re-use of the variable.  The variable assigned from the ror8 could be considered as another variable in Static Single Assignment.

What happens if you rename uvar2 to be ror8Value?

**Comment by croghostrider** [comment]
it comes error message "Duplicate name"

**Comment by emteere** [comment]
Duplicate name was not expected.

Can you post the debug Decompiler .xml file?

**Comment by croghostrider** [comment]
Yes, where can I find the file?

**Comment by alexbrooy** [comment]
any news about this issue? I have similair bug: when renaming local var, I don't see it has been renamed. But I get the "duplicate error" when trying to rename again

**Comment by nkaretnikov** [comment]
> any news about this issue? I have similair bug: when renaming local var, I don't see it has been renamed. But I get the "duplicate error" when trying to rename again

Same here. In my case, the problematic variable is a pointer: `*foo = ...`, where I'm trying to rename `foo`.

**Comment by acama** [comment]
Seems like this bug is still alive in 10.1.2

**Comment by antiaim** [comment]
Same for 10.1.4

**Comment by DCNick3** [comment]
I believe one can find the said decompiler XML when clicking this button

![Screenshot_20221214_151136](https://user-images.githubusercontent.com/10363282/207592100-eada7f40-4ba4-4cda-94c3-77e25df7bea1.png)


[Here's](https://github.com/NationalSecurityAgency/ghidra/files/10227831/on_char.zip) decompiler xml (zipped for github) of a function I encountered the bug in

![image](https://user-images.githubusercontent.com/10363282/207595421-1bfac81a-735d-4deb-aaf5-16d4944f3412.png)

Any attempt to rename or retype `puVar1` creates a dynamic (identified by hash rather than an address) local variable (can be seen in the ghidra UI too)

![Screenshot_20221214_153304](https://user-images.githubusercontent.com/10363282/207596347-fcd39450-67c7-430a-b75a-e6cf71c898f1.png)

But later when the decompiler is re-run, it seems that the hash does not match what has been previously calculated and so the variable you see in UI stays the same.

Unfortunately, I don't know enough about how the hash is calculated (and how to debug the decompiler...), so I am kind stuck here.
