### ISSUE TITLE
Getting a PluginTool in Headless Mode

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#1944]
I'm looking to get a PluginTool for use in a test. When extending AbstractGhidraHeadlessIntegrationTest and using TestEnv.launchDefaultTool(Program) I always encounter a HeadlessException. This is obviously solved by extending AbstractGhidraHeadedIntegrationTest instead, but I don't actually have a need for the Code Browser. Is there a tool I can get in headless mode to retrieve services with?

**Comment by dragonmacher** [comment]
This is advanced territory, for which there is no guide.

The short answer is that you can do something like this on your own, but you may have to pave your own way.   We have examples of headless tests that use tools sparingly.  See uses of `FakeDockingTool`.  However, to use this, you must configure it yourself.    In your case, you would have to somehow register the services you need with the tool so that you can later retrieve them.   The point of doing this would be to have a fast test that allows you to configure the fake tool to use dependency injection in your system under test.

The hard part with doing the above is that you will probably have to create custom test services, as opposed to using the normal plugins available in Ghidra.  The issue is that most plugins will probably have a dependency on Swing that will cause a headless exception.

As a historical note, we have never correctly/fully separated the notion of plugins and services.   Currently, most services are defined by plugins, which are usually dependent upon the UI.   However, it would make more sense to me if there was also a notion of generic services that exist in both headless and UI environments.   This would allow clients to easily create scripts that work in both environments.   This was the idea behind the `ServiceProvider` interface.   We use that interface in many places instead of `PluginTool` to allow for things like dependency injection in tests.   

As we grow, we create more fake versions of UI concepts for testing, but the library of these items is not yet robust.

**Comment by astrelsky** [comment]
It is probably simpler to just use the headed integration test as I don't have a large amount of test cases.
