### ISSUE TITLE
Python Script GetByte() returns Signed values

### ISSUE THREAD

**Issue by oziphantom** [NationalSecurityAgency/ghidra#1969]
**Describe the bug**
call getByte() from the flat API in python with an address that points to a value 0x80-0xff. You will get a negative number in response. 

**To Reproduce**
open a project
make a python script
locate a memory location that is in the range of 0x80-0xFF and call
print(str(getByte(toAddr(<your address here>))))

**Expected behavior**
getChar should return -127<128 and getByte should return 0<255

**Screenshots**

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: 11.6
 - Ghidra Version: 9.1.2

**Additional context**

**Comment by ryanmkurtz** [comment]
`getByte()` returns a Java `byte`, which is a 1-byte signed value.  Java can sometimes make things like this complicated because it doesn't have unsigned variables.  You typically have to use the next larger variable type and mask off the parts you aren't trying to return.  This would require a breaking change to the scripting API, which is typically reserved only for extreme circumstances.  I wouldn't expect it to change for this type of problem.

**Comment by assumenothing** [comment]
As a workaround, the following Python functions can be used to get unsigned integers of different sizes:
```python
def getUByte(address):
    b = getByte(address)
    return b if b >= 0 else b + 0x100

def getUShort(address):
    s = getShort(address)
    return s if s >= 0 else s + 0x10000

def getUInt(address):
    i = getInt(address)
    return i if i >= 0 else i + 0x100000000

def getULong(address):
    l = getLong(address)
    return l if l >= 0 else l + 0x10000000000000000
```
