### ISSUE TITLE
InstructionSearchApi search method returns only the first found instruction

### ISSUE THREAD

**Issue by amohar** [NationalSecurityAgency/ghidra#2036]
**Describe the bug**
Disclaimer: I'm very new to Ghidra and I might be doing some really stupid mistake, so I'm sorry if that's the case.

I'm trying to use `InstructionSearchApi` to search for all instructions in a given address range. The plan is to get all the instructions and then filter to get only the "JMP" instructions. I don't want to use instruction search UI, I want to use a function that will return the results immediately, thus the use of  `search` method.

The error is I always get only the first found instruction. In my example, I'm setting the start address to the beginning of a function and end address to the function's end. I get the first instruction - XOR in the case on the screenshot below. When I start moving start address upwards (to skip the first instruction and move to the next one), the returned instruction changes to the second one, the third one, etc. but there is always a single instruction returned. From the function description, I would expect it to return all the instructions in the address space.

**To Reproduce**
I'm using a slightly modified `InstructionSearchScript.java` script. This is my method that is called from the run:
```private void testSearcher()
{
  AddressFactory addressFactory = currentProgram.getAddressFactory();
  Address cststart = addressFactory.getAddress("004006a0");
  Address cstend = addressFactory.getAddress("004006ca");
  AddressSet addrSet = addressFactory.getAddressSet(cststart, cstend);

  InstructionSearchApi searcher = new InstructionSearchApi();
  try
  {
    List<Address> results = searcher.search(currentProgram, addrSet.getFirstRange());
    for (Address addr : results)
    {
      Instruction instr = getInstructionAt(addr);
      println(instr.toString());
    }
  }
  catch (InvalidInputException e)
  {
    e.printStackTrace();
  }
}
```

1. Set the `cststart` to start address of any function in the opened program
2. Set the `cstend` to end address of that same function
3. Run the script

**Expected behavior**
I want to see the list of all the instructions in that function in the script output.

**Observed behavior**
I see only the first instruction and no any additional errors or anything that would imply there was an error in the execution.
This was tested on two different binaries.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/3844154/85784251-620fd100-b728-11ea-9262-74bdfc4999f4.PNG)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: 12.0.2
 - Ghidra Version: 9.1.2

**Comment by astrelsky** [comment]
@amohar What is occurring here is that the InstructionSearchApi is searching the entire program for instances of the bytes comprising the provided AddressRange. Since your program contains only one exact copy of the bytes comprising "entry" the result is a list of the single address 004006a0.

I don't see a way to limit the search range of the InstructionSearchApi. However, if you know the address range in advance I would suggest using [Listing.getInstructions(AddressSetView, boolean)](https://ghidra.re/ghidra_docs/api/ghidra/program/model/listing/Listing.html#getInstructions(ghidra.program.model.address.AddressSetView,boolean)).

If you were to change `AddressSet addrSet = addressFactory.getAddressSet(cststart, cstend);` to `AddressSet addrSet = addressFactory.getAddressSet(cststart, cststart);` you would likely get a large number of results.

**Comment by amohar** [comment]
Thank you so much @astrelsky , I had a hunch I was doing something wrong! And thanks for the explanation. Your solution is working like a charm.
