### ISSUE TITLE
16 byte/128 bit varnodes in decompilation

### ISSUE THREAD

**Issue by beardypig** [NationalSecurityAgency/ghidra#206]
Is it possible to type 128 varnodes as some kind of `int128` - I haven't been able to work out if it is possible. 

I'd like to make decompilations of instructions that work on 128 bit registers look sane :)

**Comment by ghidra1** [comment]
I believe 128-byte varnodes can be supported although constants beyond 64-bit are not.   You may need to develop a new builtIn datatype which extends the AbstractIntegerDataType.

**Comment by beardypig** [comment]
Appears to be `int16` and `uint16`, which seems a bit strange as these are usually the names for 16 bit integers... 🤷‍♂️ 

Still gives strange decompilations though 😭

**Comment by ghidra1** [comment]
I removed my previous comment (should have read the title again).  Sorry for the confusion.  Varnodes are always sized in bytes so that got me thinking in bytes.  It appears you found the correct builtIn types.  Our type naming can get confusing because there is inconsistency in our use of bit vs byte sizes.   As previously mentioned note that the decompiler can only handle 64-bit constants and constant computations.

**Comment by beardypig** [comment]
Thanks @ghidra1. Any specific reason why the limit is 64bit, or was it an arbitrary decision?

**Comment by ghidra1** [comment]
The internal decompiler implementation uses a 64-bit primitive to retain all varnode offsets, including constants which are also represented by a varnode in the "const" space.   At the time of the design larger primitive values may not have been standardized/available across C compilers and Java is limited to a 64-bit primitive.

**Comment by beardypig** [comment]
Gotcha, that makes sense. Are there any plans to implement 128 bit support? Or do you know of a work around?

**Comment by ubitux** [comment]
See also https://github.com/NationalSecurityAgency/ghidra/issues/249
