### ISSUE TITLE
analyzeHeadless analyzing random files? 

### ISSUE THREAD

**Issue by TylerKann** [NationalSecurityAgency/ghidra#2072]
In terminal i run the following in an attempt to use ghidra headless analyzer (w/ bridge): 
`ghidra_9.0.1/support/analyzeHeadless ghidra_9.0.1/support/ test -import "$(pwd)/" pyrogenesis -scriptPath /ghidra_scripts -postscript ghidra_bridge_server.py`

I have specified my project, my file (pyrogenesis), and the script to run after. However, when I run the script, it seems to just analyze a random file.  I am not sure if this is an issue with ghidra headless or ghidra_bridge. Either way,  has anyone had this issue before?

**Comment by mumbel** [comment]
Why are you using 9.0.1?
Why are you using `ghidra_9.0.1/support/` for your project_location, that seems wrong
Completely ignoring why you're using pwd like this, `"$(pwd)/" pyrogeneis` and `"$(pwd)"/pygrogenesis` are very different, yours seems wrong.
Your ghidra_scripts files is in your `/` directory, that seems wrong?

**Comment by TylerKann** [comment]
@mumbel thanks I will have to try that. I am a not good/new to cli/ghidra/linux/many more so not surprising if it's a trivial error. Also, I dont know why i am using 9.0.1, I installed it just in June, not sure why it installed an out of date one.

**Comment by TylerKann** [comment]
@mumbel where should my project location be? This part always confuses me. I dont really know what my 'project' is.

**Comment by ryanmkurtz** [comment]
A project is basically just a database that Ghidra uses to store all of your imported/analyzed programs.  I typically just store my programs in a directory at ~/ghidra_projects.  You can store it anywhere, but like @mumbel said, it's probably best to store it outside of the Ghidra installation directory.

As for your ghidra scripts, if you store them in ~/ghidra_scripts, you don't need to specify the -scriptPath parameter, as Ghidra knows to look in ~/ghidra_scripts automatically.  

I also suspect your problem is the extra space between "$(pwd)/" and pyrogenesis, like @mumbel  said.
