### ISSUE TITLE
:Decompiler:compileDecompileLinux64ExecutableDecompileCpp task failed

### ISSUE THREAD

**Issue by jobermayr** [NationalSecurityAgency/ghidra#2166]
On latest git master:
https://scans.gradle.com/s/cac5l2hxi27ey

**Comment by astrelsky** [comment]
Couldn't find gcc

**Comment by jobermayr** [comment]
> Couldn't find gcc

Thanks for the hint.

It seems like ghidra / gradle have hidden problems with GCC 10.

It works when using Clang:

```
diff --git a/Ghidra/Features/Decompiler/build.gradle b/Ghidra/Features/Decompiler/build.gradle
index 9e43eee56..d99f6c966 100644
--- a/Ghidra/Features/Decompiler/build.gradle
+++ b/Ghidra/Features/Decompiler/build.gradle
@@ -396,6 +396,15 @@ model {
 			} // end sources (sleigh)
 		}
 	}  // end components
+
+	toolChains {
+		clang(Clang) {
+			path "/usr/bin"
+		}
+		gcc(Gcc) {
+			path "/usr/bin"
+		}
+	}
 	
 	binaries {
 		all{ b ->
```

**Comment by jobermayr** [comment]
I assume it is a duplicate of https://github.com/gradle/gradle/issues/15803

**Comment by ryanmkurtz** [comment]
Are you using a locale like described in that ticket?  If so, if you switch it to `en_US.UTF-8`, does it work?

**Comment by jobermayr** [comment]
> $ export | grep LANG
> declare -x LANG="de_DE.UTF-8"
> declare -x LANGUAGE=""
> $ LC_MESSAGES=en gradle buildGhidra
> [...]
> BUILD SUCCESSFUL in 3m 14s

Clearly a duplicate of upstream issue and also some sort of issue #1316.
Is there an easy workaround to force _LC_MESSAGES=en_ by default with _gradle buildGhidra_ to avoid such issues once for all?

**Comment by ryanmkurtz** [comment]
Not that I can see.  `gradle.properties` doesn't seem to support setting environment variables, and you can't do it globally once inside the `build.gradle` file.

**Comment by ryanmkurtz** [comment]
The only action we can really take for this ticket is to output a more descriptive warning if we detect a locale that gradle cannot properly support at this time.

**Comment by xiaoyinl** [comment]
How about documenting this issue in README.md and DevGuide.md? Add a sentence like: "If your system locale is not English, set the environment variable `LC_MESSAGES=en` before running Gradle tasks `gradle buildGhidra` and `gradle buildNatives`."

**Comment by xiaoyinl** [comment]
@ryanmkurtz I think the note about `LC_MESSAGES=en_US.UTF-8` should also be added to README.md, since users who just want to build the latest master branch don't need to read DevGuide.md. Also isn't it better to set this env in the `Ghidra/RuntimeScripts/Linux/support/buildNatives` script, so that users don't have to set it manually by running `LC_MESSAGES=en_US.UTF-8 ./buildNatives`?

**Comment by ryanmkurtz** [comment]
One of my goals with the README is to keep it as short and simple as possible.  I don't think it's the appropriate place for platform specific workarounds to uncommon build issues (I am assuming it's uncommon since we've only had 1 report of this failure in all the years we've been open source).  I could tweak the sentence that follows the build commands in the README to make it more clear that if these commands failed, to check out the Known Issues section of the DevGuide for possible assistance. 

My thinking was similar for the buildNatives script, added with philosophy that we prefer the user control their own environment when possible.  This was also somewhat justified by this failure not being common.  I will think more about this case though.

**Comment by xiaoyinl** [comment]
>  I could tweak the sentence that follows the build commands in the README to make it more clear that if these commands failed, to check out the Known Issues section of the DevGuide for possible assistance.

I agree.

> My thinking was similar for the buildNatives script, added with philosophy that we prefer the user control their own environment when possible. This was also somewhat justified by this failure not being common. I will think more about this case though.

If passing `LC_MESSAGES` env to gradle doesn't have other side effect, I would prefer the script setting it automatically. (This is just my opinion.)

Also if the build failure occurs whenever the locale is non-English, it may not be uncommon. There was another report #1316 which is the same issue as this one.
