### ISSUE TITLE
EmulatorHelper bad uninitialized register warnings

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#2213]
**Describe the bug**
Running the EmulatorHelper will produce wrong warnings when the function is preserving "unaffected" registers.

**To Reproduce**
1. Use the Emulator and step through instrutions which preserve "unaffected" registers.
2. See a warning `WARN  Uninitialized register read at {Address}: {"unaffected" register}  (EmulatorHelper.java:704)`

**Expected behavior**
The EmulatorHelper should not warn about uninitialized "unaffected" registers being stored on the stack.

**Environment (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.19041.450]
 - Java Version: 14.0.2
 - Ghidra Version: 9.2 c1095fe9383b153fffdfa7453679512124a60d87

**Comment by ghidra1** [comment]
Are you instantiating your own EmulatorHelper instance of using the processor test framework?

**Comment by astrelsky** [comment]
> Are you instantiating your own EmulatorHelper instance of using the processor test framework? It would be simple enough to add an option to the instantiation.

Is this intended for testing? I was actually trying to use this to emulate a function. It is producing a warning everytime a save register is preserved on the stack which doesn't need any initialization. Am I misusing this?

**Comment by ghidra1** [comment]
The warnings can be ignored.  If unexpected results occur the warnings can be useful in identifying the cause.  Just because the register is specified in the cspec as unaffected does not mean that it is not important to an operation.  There are cases where such a register must be properly initialized before emulation is started (e..g, MIPS `gp` register).  We live with these warnings all the time during our processor module testing and only pay attention to them when troubleshooting.  

If you like you can set your own `MemoryFaultHandler` via the `EmulatorHelper.setMemoryFaultHandler` method.
