### ISSUE TITLE
M68000: decoding jump tables

### ISSUE THREAD

**Issue by lab313ru** [NationalSecurityAgency/ghidra#226]
It would be great to decode jump tables automatically. Now it just ignores bytes.
![изображение](https://user-images.githubusercontent.com/7189309/54613651-1faf0d00-4a6c-11e9-9cb5-44f8a6a03d37.png)

In IDA it looks like this:
![изображение](https://user-images.githubusercontent.com/7189309/54613757-51c06f00-4a6c-11e9-9b5d-1f5fb665c2e1.png)

**Comment by lab313ru** [comment]
Other example (IDA):
![изображение](https://user-images.githubusercontent.com/7189309/54614428-70733580-4a6d-11e9-8cbe-6cef049df0a7.png)

Ghidra:
![изображение](https://user-images.githubusercontent.com/7189309/54614497-8f71c780-4a6d-11e9-9433-2ca2d33f9c98.png)

**Comment by emteere** [comment]
Since the switch has no guard, you have to do a little more work.  Normally given good data flow and a guard, the decompiler will get the switch statement.

There is an example in one of the advanced tutorials.  However, I doctored your example to have good code at the cases.

On the jump (A0), choose _References->AddEdit.._. from the popup.
A dialog to edit the references will appear.
Create the pointers in the table.
Select the table of pointers
_Select->Forward References_
Drag the selection of the destination cases onto the _AddEdit…_ dialog.
Make sure the reference type is **CONDITIONAL_JUMP.**
Put the cursor on the JMP and run the **SwitchOverride** script.

Yeah, it isn't automatic, but you could create a script to do it.  If you have a lot of them.
The decompiler does label the value that reaches the switch.  At one time it just put the address for each overridden case.
There is code that attempts to create the switches based on computation and guessing the size of the table, but the decompiler is usually very good at it that it isn't necessary.

```
                             undefined  FUN_00000504 ()
             undefined         D0b:1          <RETURN>
                             FUN_00000504
        00000504 30  38  aa  bc         move.w     (WORD_ffffaabc ).w,D0w                           = ??
        00000508 e5  40               asl.w      #0x2 ,D0w
        0000050a 20  7b  00  04         movea.l    (0x510 ,PC ,D0w *0x1 ),A0
                             FUN_00000504::override::jmp_0000050e::switch
        0000050e 4e  d0               jmp        (A0 => FUN_00000504::override::jmp_0000050e::cas
        00000510 00  00  06  0c         addr       FUN_00000504::override::jmp_0000050e::case_1
        00000514 00  00  08  ec         addr       FUN_00000504::override::jmp_0000050e::case_4
        00000518 00  00  06  e6         addr       FUN_00000504::override::jmp_0000050e::case_2
        0000051c 00  00  09  aa         addr       FUN_00000504::override::jmp_0000050e::case_5
        00000520 00  00  07  88         addr       FUN_00000504::override::jmp_0000050e::case_3
        00000524 00  00  05  68         addr       FUN_00000504::override::jmp_0000050e::case_0
        00000528 00  00  0b  2a         addr       FUN_00000504::override::jmp_0000050e::case_6
        0000052c 48                  ??         48h    H
```

```
undefined2 FUN_00000504(void)
{
                    /* WARNING: Switch is manually overridden */
  switch(WORD_ffffaabc << 2) {
  case 0:
    return 1;
  case 4:
    return 2;
  case 8:
    return 4;
  case 0xc:
    return 5;
  case 0x10:
    return 6;
  case 0x14:
    return 7;
  case 0x18:
    return 0xb;
  }
}
```
Also, if you can copy and paste the bytes for your examples as a string of bytes, it greatly decreases the diagnosis time as the bytes can be copied and pasted without typing them in  ;-)

**Comment by lab313ru** [comment]
Thank you for your extended manual! It is helpful.
