### ISSUE TITLE
M68000: Adding xrefs for PC-relative commands

### ISSUE THREAD

**Issue by lab313ru** [NationalSecurityAgency/ghidra#228]
For example, IDA creates XREF for the following instruction:
![изображение](https://user-images.githubusercontent.com/7189309/54616226-6acb1f00-4a70-11e9-9dad-10bd04cdbd99.png)

And Ghidra - doesn't:
![изображение](https://user-images.githubusercontent.com/7189309/54616286-7e768580-4a70-11e9-9ae3-2762c17bc1a7.png)

**Comment by emteere** [comment]
What is the instruction at 1555e4 that created the reference?  What happens in the FUN_001faf44?  It must use D0w in some way.

The constant reference analysis tries not to create a reference until an actual access to memory is made, the value is stored, or the value is passed into a function.  The use of the PC in this way could just be a PC relative reference to something relative to the PC.

Obviously you could create the reference by hand, create a script to add the reference to all instructions using the PC register, or override the 68k analyzer to look for this instruction.

Is the function at 1faf44 really a function?  If not you can override the JMP flow back to a jump and then re-analyze.  The function was created because either there are calls to 1faf44, or the shared return analyzer with the contiguous function option was turned on.

If 1faf44 uses the data in D0w as a switch table, then you can inline the function, and the reference to the table and the targets of the switch will be created.

I realize this isn't the exact answer you were looking for, but there can be reasons not to turn every reference that seems to be a reference into one.

**Comment by lab313ru** [comment]
Problem is that this instruction reads into `D0w` depending of `D0w` value (index) for the table of words (`move.w`) that is relative to PC, so even if the next call doesn't use the result D0w, reference to the words table must be created, because the instruction reads values from there.

**Comment by emteere** [comment]
Seems like the analyzer is not trusting small offset values.  I'll take a look at the code.  There is a new setting, however it is set to 256 in the processor module so your value should pass the test.

The same code at higher memory will create a reference.

        80000074 30 38 aa bc      move.w     (DAT_ffffaabc).w,D0w
        80000078 e3 40                asl.w      #0x1,D0w
        8000007a 30 3b 00 08      move.w     (DAT_80000084,PC,D0w*0x1),D0w                  
        8000007e 4e f9 00            jmp        LAB_001faf44.l
                          1f af 44
                             DAT_80000084                                                 XREF[1]:     8000007a(R)  
        80000084 72               ??         72h    r

**Comment by lab313ru** [comment]
In Sega Mega Drive (the code is from that system) has the image base equal to 0.

**Comment by lab313ru** [comment]
It is also cannot find references like that:
![изображение](https://user-images.githubusercontent.com/7189309/54649363-f1a4e980-4aba-11e9-836d-588a628dbad1.png)

You can see, that there is reading to `D0b`, using `D1w` and `A0` as table address.
