### ISSUE TITLE
ghidra scripting: how to distinguish between function and global symbol

### ISSUE THREAD

**Issue by Ruturaj4** [NationalSecurityAgency/ghidra#2311]
I have a following program:

```
int b2[4];
int foo()
{
  static int b2[10];
  b2[5] = 4;
}
int main()
{
  static int b2[10];
  int b[5];
  b[0] = 1;
  b2[9] = 4;
  int *ptr = b;
  int c = *(ptr + 10);
  foo();
  return 0;
}
```

I want to distinguish between different b2 arrays defined in functions foo, main and globally. I can collect all the symbols using:

```
symbols = set(currentProgram.getSymbolTable().getAllSymbols(True))
    for s in symbols:
        print(s.getName())
```

But, there is no way to distinguish between static (in functional namespace) and global symbols.

Ghidra GUI shows me something like:
b2.1913 <- main , b2.1917 <- foo, b2 <- global.

Thus I can easily distinguish between these symbols using GUI.

Thanks in advanced for your help.

**Comment by astrelsky** [comment]
Since it is static and cannot be seen outside of the function you could check the references to the symbol address. It should be limited to an initializer/deinitializer (if any) and the function.

This isn't as easy to do as it would be for a local variable where its parent namespace is the function. Unfortunately there isn't really anything to tie the static symbol to the function, the compiler just mangles the symbol and hides it outside of the function scope.
