### ISSUE TITLE
Overriding AbstractDemanglerAnalyzer to replace the DemanglerAnalyzer

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#2317]
The help documentation for the Demangler Analyzer states the following:

"The Demangler Analyzer is designed to be extensible. You can extend `ghidra.app.plugin.core.analysis.AbstractDemanglerAnalyzer` to add your demangler analyzer callback. This allows you to precisely control which demanglers get called, as well as which options are used."

This is either incorrect or is not functioning as intended. If I extend `AbstractDemanglerAnalyzer` both the `GnuDemanglerAnalyzer` and my demangler analyzer are present. Shouldn't only one `AbstractDemanglerAnalyzer` be present?

**Comment by dragonmacher** [comment]
The way this was restructured now allows for *multiple* simultaneous demanglers to appear in the menu.   By doing this, the user can pick which demangler(s) they would like to run.   (Admittedly, it may be a mistake that the demanglers are not mutually exclusive.)     This setup allows the users to have more control over how we demangle, since they can pick ours, theirs, or some combination of both over repeated analysis.

**Comment by astrelsky** [comment]
I see. I just wasn't certain if this was intentional or not. Especially since if the Demangler interface is implemented then the correct one would get run anyway.
