### ISSUE TITLE
[question] Sleigh: how to specify variable length instructions?

### ISSUE THREAD

**Issue by esaulenka** [NationalSecurityAgency/ghidra#2365]
I am working on STM8 processor module.
It is a 8-bit MCU with a rich set of addressing modes for each instruction.

For example, change sign instruction `NEG` have several opcodes:
```
   40        - NEG A
   30 xx     - NEG shortmem
72 50 xx xx  - NEG longmem
... and so on
```
here 4 LSB bits - operation type ('NEG') and 4 MSB bits - operand type. Operand type also encoded by optional prefix.
Operand may be encoded by 0, 1, or 2 bytes, so there can be used an ellipsis operator:
```
operand: A is op4_4=4 & A { ... }
operand: imm8 is op4_4=3 ; imm8 { ... }

:NEG operand is op0_4=0 ... & operand { ... }
```

But I dont know, how specify third case (with prefix) in the same table.
The problem is that there can be 4 different prefixes, and writing 5 (+ no prefix case) almost identical tables for each operation looks redundant.

For reference: nice overview in wiki https://en.wikipedia.org/wiki/STM8

**Comment by ghidra1** [comment]
Prefix bytes which affect many different instructions should generally be handled via `^instruction` constructors and set corresponding fields in the `contextreg` defined by slaspec/sinc file.  the x86 `ia.sinc` file has examples of this.  When possible, It is best to incorporate a phased pattern approach with `^instruction` due to the recursion allowing the use of the `-l` sleigh compile option (preferred).   You may need to properly constrain the prefix context field(s) for those instructions which do not permit prefix bytes.  

Your third case would likely incorporate transient `contextreg` field(s) set by `^instruction` prefix constructor(s). 

NOTE:  You may not be able to use a single operand sub-constructor since your NEG constructor pattern will conflict with other instructions (e.g., IRET).  Due to the sparse encoding of addressing modes you may need separate NEG constructors for each.

NOTE: When the time comes, you may need to model the stack pointer as 24-bits to match the size of the mem space.

NOTE: This is a very incomplete example and may have some flaws...  
`
define space code type=ram_space size=3 default;
define space mem type=ram_space size=3;
define space register type=register_space size=4;

define register offset=0x0000 size=1 [ A ];

define register offset=0x2000 size=4   contextreg;
define context contextreg
  phase=(0,0)  # 0:initial, 1:instruction-parse
  prefix=(1,2)   # 0:none, 1: 0x72, 2:0x90, 3:0x92)
;

define token op (8)
  op0_8=(0,7)
  op7_1=(7,7)
  mode=(4,6)
  op0_4=(0,3)
;

define token data8 (8)
  imm8=(0,7)
;

define token data16 (16)
  imm16=(0,15)
;

:^instruction is phase=0 & op0_8=0x72 & instruction [ prefix=1;  phase=1;]  { }
:^instruction is phase=0 & op0_8=0x90 & instruction [ prefix=2;  phase=1;]  { }
:^instruction is phase=0 & op0_8=0x92 & instruction [ prefix=3;  phase=1;]  { }
:^instruction is phase=0 & instruction [ phase=1;]  { }

ShortMemB: "$"^imm8 is imm8 { export *[mem]:1 imm8; }
LongMemB: "$"^imm16 is imm16 { export *[mem]:1 imm16; }

:NEG ShortMemB is op0_4=0 & mode=3 & op7_1=0 & prefix=0; ShortMemB { ... }
:NEG A                 is op0_4=0 & mode=4 & op7_1=0 & prefix=0 { ... }
:NEG LongMemB is op0_4=0 & mode=5 & op7_1=0 & prefix=1; LongMemB { ... }

`

**Comment by ghidra1** [comment]
I revised my response above regarding the breakout of an instruction operand into a sub-constructor.  The decision to do this can be rather involved based upon a number of factors (see below).  The use of sub-constructors is preferred when possible to achieve re-use by multiple instructions.  Sub-constructor use can also help to identify the bounds of an operand representation and allow operands to correspond to an absolute memory address.  In your case, NEG, NEGW, CPL, AND, OR and XOR could all share the use of `OperandRW8` although some may only use it for read purposes.

- Excluding pattern bits from an instruction constructor for use in a sub-constructor can cause the instruction constructor pattern to be ambiguous with other constructors making it sensitive to ordering within the file.  Ambiguous instruction constructor patterns should be avoided if possible.  Compiling with the sleigh `-l` option will detect ambiguous pattern conflicts.
- All cases of a given sub-constructor must be uniform in nature (e.g., same varnode export size and intended access use (R, W, or R/W)).  It is generally difficult to achieve a sub-constructor suitable for both read and write use as I did above with `OperandRW8` (e.g., those that modify state such as register indirect post-increment). 
- Exporting unique local variables should be avoided when possible in favor or a register, constant or memory address to aid markup and analysis.  You can't avoid in some cases (e.g., indirect addressing).

**Comment by esaulenka** [comment]
Thank you very much, this is what I needed!

Your tips about sub-constructors are not in the documenation, please consider adding them there.
Thank you again for detailed response.

**Comment by ghidra1** [comment]
I always felt we needed a " Sleigh Best Practices / Style Guide" for writing _slaspecs_ but has yet to happen.

**Comment by esaulenka** [comment]
If someone else faces with same problem, here is working example:
```
define endian=big;
define alignment=1;
define space RAM type=ram_space size=3 default;
define space register type=register_space size=4;

define register offset=0x0000 size=1 [ A ];
define register offset=0x0000 size=2 [ _ X Y SP ];
define register offset=0x0100 size=3 [ PC ];

define register offset=0x2000 size=4   contextreg;
define context contextreg
  phase=(0,0)  # 0:initial, 1:instruction-parse
  prefix=(1,2)   # 0:none, 1: 0x72, 2:0x90, 3:0x92)
;

define token op (8)
  op0_8=(0,7)
  op7_1=(7,7)
  mode=(4,6)
  op0_4=(0,3)
;

define token data8 (8)
  imm8=(0,7)
;

define token data16 (16)
  imm16=(0,15)
;

:^instruction is phase=0 & op0_8=0x72 ; instruction [ prefix=1;  phase=1;]  { }
:^instruction is phase=0 & op0_8=0x90 ; instruction [ prefix=2;  phase=1;]  { }
:^instruction is phase=0 & op0_8=0x92 ; instruction [ prefix=3;  phase=1;]  { }
:^instruction is phase=0 &              instruction [ phase=1;]  { }

ShortMemB: "$"^imm8 is imm8 { export *:1 imm8; }
LongMemB: "$"^imm16  is imm16 { export *:1 imm16; }

OperandRW8: A        is prefix=0 & mode=4 & A { export A; }
OperandRW8: ShortMemB is prefix=0 & mode=3; ShortMemB { export ShortMemB; }
OperandRW8: LongMemB  is prefix=1 & mode=5; LongMemB { export LongMemB; }

:NEG OperandRW8 is (op0_4=0 & op7_1=0) ... & OperandRW8 { 
   local result:1 = -OperandRW8;
   #setResultFlags(result);
   OperandRW8 = result;
}
```

The main difference is `;` instead of `&` in `instruction` tables.

**Comment by ghidra1** [comment]
As mentioned before you will likely need to expand your stack pointer SP to match the size of underlying address space (3-bytes) for proper behavior with decompiler when the time comes.  It does not handle zext/sext very well when de-referencing stack pointer.  As a working example you could omit the unused registers.

Not sure if you intended this example to reflect STM8 which I thought was a Harvard Architecture (separate code and data spaces).

**Comment by ghidra1** [comment]
Tips about context:
- Non-transient/stored context (`globalset` is used): should be defined starting at offset 0 before transient context.  Once language is released to the wild existing stored context field definitions should not be changed, doing so may require a major language revision with old language translator to facilitate upgrades.  In some cases it may be possible to leverage language property `resetContextOnUpgrade` with minor language revision if clearing all context is OK.   New non-transient/stored context fields can be added immediately after existing non-transient/stored context fields.
- Transient context (`globalset` NEVER used): are safe to change or remove but should be placed after non-transient context fields.
- Size of `contextreg` be a multiple of 4 bytes due to the underlying storage implementation (multiples of Java `int`).
- Context fields should never span a 4-byte boundary.  This limits the largest context field to 32-bits.  Since internally context fields will get packed/moved during compilation I find it useful to add reserved filler fields in bit-range gaps which may be required to ensure that a field does not span a 4-byte boundary.  This idiosyncrasy used to hold true and I believe still does, although has no impact for a 4-byte `contextreg`.
- I wish `noflow` was the default as it is almost always applicable to non-transient/stored context.  Fortunately for transient context it has no real impact.

**Comment by esaulenka** [comment]
> you will likely need to expand your stack pointer SP

Ok, I will check this moment. Now operations with the stack look messy.

May be would be better to split specifications to "16-bit addresses" and "24-bit addresses". Most instructions use 16-addressing, X and Y registers are 16-bit too. I didnt investigate, what C compilers do for large devices, but small ones, which have less than 64K memory, didnt use set of far instructions (there is standard set of _call/jump/return far_ and only one _load far_).

> STM8 ... was a Harvard Architecture

No, it is von-Neumann device. Memory map can be found in [reference manual](https://www.st.com/resource/en/reference_manual/cd00190271-stm8s-series-and-stm8af-series-8bit-microcontrollers-stmicroelectronics.pdf) (page 30)  

Thanks for explanation about contextreg. It is not obvious from docs, that 'noflow' attribute applies always in my case.

**Comment by ghidra1** [comment]
> Thanks for explanation about contextreg. It is not obvious from docs, that 'noflow' attribute applies always in my case.

It really only applies to non-transient/stored context.  Your example above only utilize transient context.

**Comment by ghidra1** [comment]
> No, it is von-Neumann device. Memory map can be found in [reference manual](https://www.st.com/resource/en/reference_manual/cd00190271-stm8s-series-and-stm8af-series-8bit-microcontrollers-stmicroelectronics.pdf) (page 30)

This seems to differ from the STM* [reference manual](https://www.st.com/content/ccc/resource/technical/document/programming_manual/43/24/13/9a/89/df/45/ed/CD00161709.pdf/files/CD00161709.pdf/jcr:content/translations/en.CD00161709.pdf) (Section 4.3, page 19)

**Comment by esaulenka** [comment]
Physically it have two buses, but from programmer's point of view, there is only one address space. 
It is stated in second sentence in this section.
