### ISSUE TITLE
Saving multiple Auto-Analysis presets

### ISSUE THREAD

**Issue by find0x90** [NationalSecurityAgency/ghidra#2385]
Is there a way to save different configurations of auto-analysis settings? I usually try to run with the default settings but if the target is large I start turning things off to speed it up. It would be useful to save a preset for full auto-analysis, one with a few things turned off, and one with minimal analysis.

**Comment by dragonmacher** [comment]
There is no way to do this now.   There have been talks about having 'Analysis Recipes', which would facilitate this sort of saved settings, but it is not considered a high priority task at this time.

The closest thing we have to this now is to use scripting to configure the analyzers and then to trigger analysis.   You would have to write the script yourself.  Then, instead of running analysis from the UI, you would run your script.

**Comment by find0x90** [comment]
Thanks! I've been using the script approach for now, I'll continue doing that.
