### ISSUE TITLE
GhidraScript ask* methods remove monitor component

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#2398]
**Describe the bug**
Utilizing one of the GhidraScript askString, askFile, etc methods will prevent the task monitor component from being displayed.

**To Reproduce**
Run the following script:

```java
//@category issues

import ghidra.app.script.GhidraScript;

public class IssueScript extends GhidraScript {

	@Override
	public void run() throws Exception {
		String str = askString("title", "message");
		int count = Integer.MAX_VALUE;
		monitor.initialize(count);
		monitor.setMessage(str);
		for (int i = 0; i < count; i++) {
			monitor.checkCanceled();
			monitor.incrementProgress(1);
		}
	}
	
}
```

**Expected behavior**
The task monitor component window should be displayed.

**Environment (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.19041.572]
 - Java Version: 15
 - Ghidra Version: 9.2_DEV 3c683ae770cf495deb32588202b00b88e125a4a4

**Comment by jpleasu** [comment]
Wow, aggressive script :-)

Testing with Java 11, it seems ok.  The monitor dialog doesn't get focus if I start the script by double clicking in the script manager, but it's next in z-order.

If you insert a `Thread.sleep(10)` in the loop, do you get the same behavior?

**Comment by dragonmacher** [comment]
We have made quite a few tweaks to dialog modality recently.   There may be some fallout from that.

**Comment by astrelsky** [comment]
> Wow, aggressive script :-)
> 
> Testing with Java 11, it seems ok. The monitor dialog doesn't get focus if I start the script by double clicking in the script manager, but it's next in z-order.
> 
> If you insert a `Thread.sleep(10)` in the loop, do you get the same behavior?

Same behavior.

After starting the script, don't submit any text into the `askString` until the cancel popup comes up and conveniently blocks your view of the askString input box.
![Capture](https://user-images.githubusercontent.com/46897303/97030638-0b2ad480-152d-11eb-831e-0bd53ad1cdde.PNG)

**Comment by pabx06** [comment]
i am hitting the same bug here.
I thought the script execution finished so i re-run the script over the previous one. i have no clue how many script thread i had so closed an relaunched ghidra

May be disable the Green arrow button  to run scripts while the previous script thread is not finished yet ?
also what would happens if you double click fast enough the green arrow ?

**Comment by pabx06** [comment]
> We have made quite a few tweaks to dialog modality recently. There may be some fallout from that.

it can only be a good thing :+1:

**Comment by jpleasu** [comment]
To put a little more detail to what @dragonmacher said, this bug is a result of attempts to choose a sensible parent for each dialog when its created.

In this case, the scripting Task will open the chomping bits dialog after a small delay.. the delay prevents the creation of dialogs for short lived tasks.  The problem here is that the task dialog is created _after_ the ask dialog, so the task dialog is assigned the ask dialog as its parent.  When the ask dialog is closed, the task dialog is closed.

The simplest fix for this issue is to change the parenting rules to prevent "ephemeral" windows (like dialogs) from becoming parents.  I think that should come soon.
