### ISSUE TITLE
Demangling plugin takes 10000x longer to run than c++filt.

### ISSUE THREAD

**Issue by reedacartwright** [NationalSecurityAgency/ghidra#2509]
**Describe the bug**
Demangling takes up nearly 50% of an analysis. When analyzing a large binary (348M), demangling took nearly 17 hours. When running c++filt on the symbols, the demangling took 5 seconds. I don't know if the demangling is the slow part, or the parsing of the demangled symbols is slow, but I'm pretty sure its possible to improve upon 17hours of runtime.

**To Reproduce**
Analyze a binary using the headless analyzer.

**Expected behavior**
Demangling plugin should not take 10000 times longer to run than c++filt.

**Screenshots**
Here's the summary generated by the headlessAnalyzer.

```
INFO  -----------------------------------------------------
    ASCII Strings                             37.024 secs
    Apply Data Archives                       28.438 secs
    Call Convention ID                      4007.589 secs
    Call-Fixup Installer                      58.454 secs
    Create Address Tables                     65.811 secs
    Create Address Tables - One Time          23.231 secs
    Create Function                            0.093 secs
    DWARF                                    493.461 secs
    Data Reference                           210.108 secs
    Decompiler Switch Analysis                64.303 secs
    Decompiler Switch Analysis - One Time     97.362 secs
    Demangler GNU                          61055.993 secs
    Disassemble                                0.004 secs
    Disassemble Entry Points                 386.449 secs
    ELF Scalar Operand References            127.020 secs
    Embedded Media                             2.056 secs
    External Entry References                 24.018 secs
    Function ID                              246.700 secs
    Function Start Search                     47.003 secs
    Function Start Search After Code          66.765 secs
    Function Start Search After Data          67.162 secs
    GCC Exception Handlers                   999.807 secs
    Non-Returning Functions - Discovered     359.799 secs
    Non-Returning Functions - Known           10.845 secs
    Reference                                267.469 secs
    Shared Return Calls                       34.386 secs
    Stack                                    925.578 secs
    Subroutine References                    112.665 secs
    Subroutine References - One Time           0.000 secs
    x86 Constant Reference Analyzer        53839.531 secs
-----------------------------------------------------
     Total Time   123659 secs
-----------------------------------------------------
```

**Environment (please complete the following information):**
 - OS: Linux (Arch Linux, running kernel 5.4.77-1-lts) 
 - Java Version: openjdk 11.0.8 2020-07-14
 - Ghidra Version: 9.2

**Comment by dragonmacher** [comment]
> I don't know if the demangling is the slow part, or the parsing of the demangled symbols is slow, but I'm pretty sure its possible to improve upon 17hours of runtime.

My guess is that the demangling, which consists of [calling the native demangler; parsing the demangled output, and applying the type information], is bogging down in the follow-on analysis triggered by applying the type  information.

348M is a large binary, in terms of its impact on auto-analysis runtime.   Is the binary in question a publicly available binary?

**Comment by reedacartwright** [comment]
I'm reverse engineering the Bedrock Dedicated Server for Linux, available from here: https://www.minecraft.net/en-us/download/server/bedrock

Specifically this version: https://minecraft.azureedge.net/bin-linux/bedrock-server-1.16.100.04.zip

**Comment by astrelsky** [comment]
The size is definitely contributing. It has taken more than an hour to import and is still going.

**Comment by reedacartwright** [comment]
Yeah, importing takes over an hour. I also had to raise the heap limit in analyzeHeadless to 8G.

**Comment by astrelsky** [comment]
So after 6 hours and still importing I'm deciding to cancel it. I wanted to know if #2214 fixed it and was hoping it was related to #1770 but I'm not able to check because my laptop is a potato.

**Comment by gsuberland** [comment]
Looking at how this has been implemented, I can see why it is slow. Here's a rough overview of the flow:

* DemangleAllScript iterates the symbol table, creating a DemanglerCmd instance per symbol and applying it.
* DemanglerCmd iterates through all registered demanglers to find the first one which can demangle the symbol, then calls demangle on it.
* The demangler instance (in this case GnuDemangler) calls into GnuDemanglerNativeProcess in order to service the demangling request.
* GnuDemanglerNativeProcess launches the demangler process if it hasn't already, and acquires stdin/stdout.
* The symbol name is written to stdin with whatever additional parameters are needed, and stdin is flushed.
* The external tool parses the input, demangles the symbol, and prints back out via stdio (again with a flush).
* The result is read back from stdout.

This means that for every symbol in the program there's a stdio write, a flush, a context switch to the external process, a stdio write, a flush, a context switch back to ghidra, and a stdio read. If I recall correctly, all of these operations involve a syscall transition, too.

One solution would be to modify cp-demangle.c in DemanglerGnu in order to turn it into a dynamic library that can be called into, to entirely avoid the stdio slowness. This could be done fairly quickly (albeit slightly hackily) by replacing stdio putchar/fputs/fflush calls with wrappers that instead write to a simple buffer in memory that can be passed back to ghidra as a string.

**Comment by reedacartwright** [comment]
Even without modifying the Demangler, maybe sending the symbols in batches and parsing the result would speed things up? C++filt, which the demanger is based on, basically reads a text file and demangles any symbols it finds in the file and doesn't change anything else.

**Comment by dev747368** [comment]
Measure before you try to optimize.  The inefficiencies that @gsuberland listed about how the info is passed to the external process might not be the bottleneck, and improving it might not help.

As a first step, digging into what is happening using something like visualvm to see the hotspots and memory hogs would be a good first step.

**Comment by gsuberland** [comment]
@reedacartwright I considered mentioning batching but there are some limitations to that. You need to know what the stdio buffer size is ahead of time, so you don't send half a symbol over (looking at the demangler code it seems like it processes a symbol whenever the buffer is flushed), and it requires a bunch of API changes within Ghidra. It also doesn't remove the issue altogether, and is likely to still be slow on uniprocessor systems due to the context switching (assuming that is indeed a major bottleneck). I'm also not a fan of having completely different performance profiles for two seemingly-transparent variants of the same API; it puts an unfair expectation on script developers to know about this problem, and all the existing examples will use the singular demangle call.

@dev747368 I completely agree. I brought it up because I've seen this kind of stdio-based IPC design before and it was extremely slow, but it is definitely worth profiling in order to identify where threads are blocking and where CPU time is being spent. I did check that it wasn't spawning a new process on each call (at least when analysing an ELF binary on Win10) in order to exclude that potential bug, but there could easily be a hidden O(n^2) pattern somewhere that I didn't spot. I don't have a Ghidra dev environment at hand, though, otherwise I would've checked that first.

**Comment by dev747368** [comment]
FYI anyone trying to import / analyze the bedrock_server binary, the DWARF analyzer consumes a big chunk of time and should be disabled before analyzing.  There is no DWARF info in the binary and some bad logic was causing the analyzer to (multiple times) re-open the underlying ELF file to try to find .debug_info sections... but each time it does this it takes foreeeevvvvverrrr.

DWARF fix in the pipeline.

**Comment by dragonmacher** [comment]
Also, the import has a degenerate case while processing exported symbols.   Fix for that also in the pipeline.

**Comment by reedacartwright** [comment]
Are either of those fixes likely going to improve demangling or constant reference time?

Different issue but another thing that happened after my last analysis is that the 'Non-Returning Functions - Discovered' analysis identified a whole bunch of std library functions like allocators and basic_string deconstructors as non returning, which requires me to manually repair decompiled functions which use them. It didn't happen with earlier versions of Ghidra.

**Comment by dragonmacher** [comment]
> Are either of those fixes likely going to improve demangling or constant reference time?
> 

No.   I am in the process of profiling the demangling code.   Unless there is a latent bug in that area, the demangling is one of the faster analyzers.   The times you have shown above do not reflect real demangling time, I suspect.   I believe the demangling to be fast relative to overall analysis.    When we 'demangle', we perform follow-up analysis based upon the new information we have.   This follow-up analysis is likely where the time is being spend and not in the actual demangler calls.    That number still seems unreasonably high though, even considering said analysis.

The ConstantPropagatorAnalyzer seems to have encountered a nasty edge case.  I would expect a fix for that in the future.

**Comment by dragonmacher** [comment]
Update:  regarding the demanlging time, it looks like the bulk of that work is taken in the follow-up analysis (about 90%).  There is an odd 10% overhead related to parsing the output of the call to the native demanlger, in order to apply the newfound type information.    I will look into the parsing overhead.

Regarding the overall time taken by the demangler plugin, some back of the napkin math shows this:
61,055 seconds (from above)
1M symbols (just under 1 million symbols to demangle in the binary)
0.061 seconds / symbol

.06 seconds per symbol sounds reasonably fast for: calling the native demangler, parsing the output, applying the type information to Ghidra's database and performing any follow-up analysis that may result from the new type information and discovered functions and data.

This is a large binary.   1M symbol is a lot to process.   16 hours still sounds like more time than should be required to analyze a binary of this size.

**Comment by astrelsky** [comment]
> Update: regarding the demanlging time, it looks like the bulk of that work is taken in the follow-up analysis (about 90%). **There is an odd 10% overhead related to parsing the output of the call to the native demanlger**, in order to apply the newfound type information. I will look into the parsing overhead.

If need be, you could pass a bunch of mangled symbols in batches and then process them in parallel.
![Capture](https://user-images.githubusercontent.com/46897303/108408860-91150e80-71f3-11eb-847d-0dec85e848e4.PNG)

**Comment by ghidra1** [comment]
Note that the ELF import of this binary is improperly processing the .init_array and .fini_array entries which are getting over adjusted for an imagebase change.  I will be putting a fix in for this, but it can be avoided by importing with an imagebase of 0.

**Comment by dragonmacher** [comment]
There are various fixes in the master branch to address the performance issues discussed in this issue.
