### ISSUE TITLE
Ghidra taking too long to open a project

### ISSUE THREAD

**Issue by Natives3000** [NationalSecurityAgency/ghidra#2544]
So I opened ghidra and, hmm take really long to open my project with 0 dlls or things in it, it is only me??

**Comment by dragonmacher** [comment]
Mine seems to be running OK.

**Comment by ghidra1** [comment]
A project "re-opening" while restoring open programs in tools can be delayed by a re-compile of Sleigh language files if the  underlying language module files have been touched.  This is a common occurrence in development with Eclipse when switching branches with git.  Just throwing this out there since I don't know what your working environment is.

**Comment by ryanmkurtz** [comment]
Performance regarding opening projects appears to be working as intended.
