### ISSUE TITLE
6502 import file size capped at 64K - How do I get an overlay with file bytes from other files?

### ISSUE THREAD

**Issue by oziphantom** [NationalSecurityAgency/ghidra#2546]
I'm trying to import a file that has multiple "banks" in it. But the file import only takes the first 64K and in options it won't let you set the size to anything over 64K even though my file is actually 385K. 

I tried splitting the file up into smaller 16K banks and adding then 1 by 1 as files. But then I can't reference the other files in a single memory map, I can select the file it is added as for "File Bytes".

How do I set up memory map and map in over 64K for a 6502 system?

**Comment by quietust** [comment]
If you've got them split into multiple files, you can go to File -> Import File and add each one at the appropriate base address (and be sure to check the "Overlay" flag, otherwise it won't work).

In fact, this also works _without_ splitting the file first, since you can specify the offset+length into the file each time you perform an import (and the Memory Map viewer will show something like "File: <filename>: 0x0", "File: <filename>: 0x4000", "File: <filename>: 0x8000", and so forth).

**Comment by oziphantom** [comment]
If I do File -> Import from the project, i.e the page that has Tool Chest and Active Project shown. I can't not set any overlay flag. The options only gives me 
BlockName
Base Addresss
FileOffset
Length
Apply Processor Labels
Anchor Processor Defined Labels 

If I open the first bin file such that I'm in the Code Browser. Then do File -> Import, I get the exact same options and there is no overlay flag. When I add them here the individual files also show up as separate entries under Active Project. 

If I try to add the whole nes file as one I get this 
![image](https://user-images.githubusercontent.com/7146763/102705928-04c49900-42e1-11eb-8e1b-76b542c36ff3.png)

**Comment by quietust** [comment]
I misremembered - once you've done "Import File" from the Project view (where you should just add one single bank), you want to use "File -> Add To Program", and _that_ one has the "Overlay" checkbox at the top. Again, you'll have to import the banks one at a time, either from their own files or from a single source file with the proper offset+length+baseaddr values.

Also, in case you haven't already done so, unchecking the two "Processor Defined Labels" checkboxes is probably a good idea because those are meaningless on the NES (aside from the NMI/RESET/IRQ vectors, but those are easy enough to set up manually).

**Comment by oziphantom** [comment]
Aha, Thank you for your help.
