### ISSUE TITLE
Folder names are truncated to extremely short lengths in Symbol Tree

### ISSUE THREAD

**Issue by rgov** [NationalSecurityAgency/ghidra#2566]
**Describe the bug**
In the Symbol Tree, under Functions, "folder" names (perhaps these are the object files the symbols come from) are truncated to ridiculously short lengths, like two characters.

**To Reproduce**
Open a Code Browser window for an executable that would create such a hierarchy under the Symbol Tree browser. Make the window wide enough that no truncation ought to occur.

**Expected behavior**
The entire name should be shown, unless the window is narrow, then the truncation should occur at the edge according to text direction.

The tooltip should also show the complete name. Currently it is truncated the same as the displayed title.

**Screenshots**
<img width="497" alt="image" src="https://user-images.githubusercontent.com/108767/102647675-26345200-4134-11eb-8ab8-5a9263d2e71f.png">

**Environment**
 - OS: macOS 10.11.1
 - Java Version: 11.0.2
 - Ghidra Version: 9.2

**Comment by dragonmacher** [comment]
This is part of the 'Organization Nodes' feature.   The truncation is not due to clipping, but to nodes being decomposed into sub-folders (with a limit of 40 children per node max).

IIRC, this used to be optional.   There seems now to be no way to disable or modify this feature.

**Comment by mumbel** [comment]
@rgov  the `Functions` window is an alternative, I prefer it over symbol tree if all I'm doing is looking through functions as it doesn't have to filter/search the other categories.

**Comment by juanandresgs** [comment]
Honestly that folder view in symbol tree sucks, it's just confusing. Disable setting would be nice here.

Ideally, would love to have the ability to personalize a function folder structure to sort out funcs that still need to be analyzed, put together library funcs, etc.

**Comment by ghidragon** [comment]
Trees do not scale well when you have lots of items in the same folder. So if more than some threshold number of items are in a folder (functions and labels), we "organize" them in alphabetical groupings, collapsing empty intermediate folders. So for example, if you had a bunch of functions and they all begin with "abc", instead of having a folder "c" inside a folder "b" inside a folder "a", those are collapsed into a single folder "abc..." (And maybe the "..." adds confusion making it seem like a truncation). Anyway, for better or worse that is how it works. So the original post is not a bug but just a confusing feature. If you have suggestions on how to improve this feature, please submit a new ticket and describe how that feature should work. (We would consider totally re-doing the feature if we can think of a way to actually make it useful and still avoid tree scaling issues. ).

**Comment by juanandresgs** [comment]
thank you for the feedback, I'll submit a feature request. Folder creation and user-generated folder structures are proving *extremely useful* on IDA Pro and would be great to have access on the UI as well as via API for automatic sorting of type libraries and recognized functions, etc.
