### ISSUE TITLE
x86: uint32_t keeps changing to 2 bytes in function signature

### ISSUE THREAD

**Issue by RobertBaruch** [NationalSecurityAgency/ghidra#257]
**Describe the bug**
When editing a function, uint32_t, when formed by AX:BX or CX:DX, keeps changing to 2 bytes.

**To Reproduce**
1. Disassemble TELEN.EXE (from https://www.dosgamesarchive.com/download/telengard/)
2. Go to `1000:ac13`. This is the `idiv32` function.
3. Attempt to edit its function signature to `uint32_t __cdecl16near idiv32(uint32_t x, uint32_t y)` with custom storage, either in the decompilation window or in the listing window. You can initially set the storage for x to AX and BX, and for y to CX and DX. However, any attempt to set the return type to uint32_t and its storage to AX and BX will result in a "too much storage" error, because for some reason Ghidra thinks that a return type of uint32_t is only 2 bytes.

**Expected behavior**
A return type of uint32_t is 4 bytes, and its storage can be allocated to two 16-bit registers.

**Screenshots**
![datatype2](https://user-images.githubusercontent.com/1783950/54887350-5790c880-4e4f-11e9-9fa9-6190abe29023.JPG)
![datatype3](https://user-images.githubusercontent.com/1783950/54887353-5a8bb900-4e4f-11e9-8cbb-6818945546f3.JPG)
![datatype1](https://user-images.githubusercontent.com/1783950/54887355-5cee1300-4e4f-11e9-9db5-825a0d72e998.JPG)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: 11.0
 - Ghidra Version: 9.0

**Comment by emteere** [comment]
Unfortunately you are most likely using a data type archive (clib) that was meant for 32-bit platforms.

The Linux header files that were used to parse the clib data types archive have defined unit32_t in terms of a data type (uint) that can change sizes.  The header files used to parse the clib64 are all 64-bit platform oriented.

You can use dword or sdword which will always be 4 bytes.  If you need to continue using uint32_t, you could delete the uint32_t data type in your program, and then redefine it using dword.  The best course of action is to parse header files that are meant for a 16-bit platform that would have the data types defined as the correct size for that platform.

**Comment by Godzil** [comment]
uint32_t in C99 warrantee you to be 32bit, or that would be a really useless type if it was not. ( https://pubs.opengroup.org/onlinepubs/009696799/basedefs/stdint.h.html ) and that whatever is the bitness of your platform.
If your platform cannot support the size, the typedef should not exist: "Conversely, for each type described herein that the implementation does not provide, the <stdint.h> header shall not declare that typedef name, nor shall it define the associated macros."

But 32bit as 8 and 16 are mandatory the only optional one is 64bit.

Sounds more like a bug in the clib, or something in @RobertBaruch project made Ghidra to parse a uint32_t as a unit16_t which is not normal.

**Comment by d-millar** [comment]
Hey @RobertBaruch,

Am curious if @emteere's explanation made sense to you?  It's definitely a confusing subject, and you're getting burned by the fact that we don't have an archive for 16-bit architectures pre-parsed.  As he explained, the uint32_t type in the generic_clib is defined essentially by "typedef unsigned int uint32_t" and "unsigned int" on your architecture isn't 32-bit.  Arguably, "generic_clib" isn't all that generic, but....not a lot of good alternatives.

If his post wasn't clear enough, http://www.unix.org/whitepapers/64bit.html is not a bad read regarding the history of integer types and might shed some light.  (Note the blank entries for int32 under LP32 and ILP32.  Sigh.)  Regarding the C99 standard, it's relatively clear but sadly not relevant to a lot of processors/compilers, including certainly everything that pre-dated the standard and a large number of current embedded architectures.

In any case, let us know if you think this issue should remain open, if I've muddied the waters, or if you have suggestions as to a different path forward.  Will look around and see if I can dig up a decent set of MS-DOS header files.

Cheers, d

**Comment by RobertBaruch** [comment]
Yeah, it all kinda makes sense. uint32_t is defined as uint in a header file meant to be used in a 32-bit integer system, which is incorrectly used in a 16-bit system. I suppose there aren't any modern header files for 16-bit systems. I'm ok with closing this as, "don't use stdint.h for 16-bit systems, since it wasn't around back then."

**Comment by Godzil** [comment]
There are modern header in DigitalMars C++ 

https://www.digitalmars.com/features.html

Thought in stdint.h,  uint32_t is defined as unsigned long.
I need to check what exactly DMC is doing in DOS16 mode with unsigned long, but I expect it to be 32bit.

By the way, using `int` to try to get a fixed size type is a really bad idea.

By the way the link to unix.org is invalid.

**Comment by d-millar** [comment]
Hi @Godzil,

Couple questions for you....
(1) You mentioned that the "link to unix.org is invalid" - could you clarify.  It is not a 404 for me.  Are you disagreeing with the content?
(2) I can't find any example of stdint.h defining uint32_t as "unsigned long" (checked LLVM, gcc, Windows) - can you supply an example?
(3) Re the original C type being "architecture and compiler dependent", yep, that's kind of the point.  For a data type archive to be useful and accurate in the context of any program, you really really have to pick an archive generated from header files for the same architecture and compiler.  Otherwise, it's basically a best guess on our part.

Best, d

**Comment by Godzil** [comment]
Well for unix.org now it is working. I was getting some sort of a temporary page basically saying "nothing there", so you can forget about that, not sure what happened.

2) DigitalMars C/C++ stdint.h can be found here: https://github.com/DigitalMars/dmc/blob/master/include/stdint.h

And you can find here:

```
/* Exact sizes */
typedef signed char int8_t;
typedef unsigned char uint8_t;

typedef short int16_t;
typedef unsigned short uint16_t;

typedef long int32_t;
typedef unsigned long uint32_t;
```

And this compiler is fairly modern (aka still maintained) and support DOS16, DOS32, WIN16 and WIN32. I don't think so it support 64bit mode, but that's not really it's purpose anyway.

This stdint.h is of course valid only for Digital Mars C.

3) I do agree for generic type like short/int/long but type like uintXX_t should really be fixed in size; not sure how Ghidra is working on that point, but if it has its own internal types with fixed size the intXX_t and uintXX_t should be part of the non compiler dependent one.

I'm not sure to be really clear in my explanation:

C99 clearly define that each of intXX_t and uintXX_t must have a strict size to have types that are not compiler and environment dependent. And as they are not really native type the compiler maker have to set them using typedefs in a way which for that specific compiler make sure they mean exactly what they say depending on how the compiler treat char/short/int/long. 
On the other hand Ghidra should NOT do the same and not rely on a compiler set of header to set theses specific types, so if a user who probably don't know what compiler was used these specific set of C99 types should not have random size because it happen that Ghidra use typedef internally and the current architecture says that `int32_t == int` and `int == 16 bit` so `int32_t == 16bits` that's non sense.

Of course if you parse header that are not meant for an architecture and then get your types wrong that a different story (and would cause issue with real compiler), but C99 type that are standardizes with specific definition, Ghidra should treat them as Builtin types and not defined types.


Hope it makes more sense...

**Comment by d-millar** [comment]
Totally makes sense, and I think we're basically on the same page.  Apologies for not checking out the Digital Mars code immediately - interesting example, definitely not the norm.

You make a good case for adding the C99 types as Builtins.  That might avoid a lot of general confusion.  We have things that are obviously close to being equivalent, e.g the DWord and UnsignedInteger Builtins are defined to be 4 bytes in length (admittedly, not necessarily 32 bits).  The question, I think, is whether adding the C99 types as Builtins will create confusion or conflict with defined types with identical names, but obviously for things like uint32_t with a pretty clear definition adding them might be reasonable.

Will raise this with the team and get back to you.  Thanks!
