### ISSUE TITLE
Can't able to build ghidra DEV having debugger in it.

### ISSUE THREAD

**Issue by ashton2323** [NationalSecurityAgency/ghidra#2588]
I am not able to build ghidra DEV with a debugger in it.

**Comment by ryanmkurtz** [comment]
Do you have the `debugger` branch checked out?  You'll need to provide a lot more specifics about your problem in order to get help.

**Comment by d-millar** [comment]
We can probably help, but, as indicated by @ryanmkurtz, we need a little more to go on.  Things that would help:  what OS are you building on?  did you encounter difficulties at any step in the DevGuide.md instructions?  did you check out the "debugger" branch?  did you see any errors in the post-checkout build steps, e.g. gradle generateProto?  Let us know, and we'll try to walk you through this!

**Comment by Tim---** [comment]
Maybe not related, but I also had an issue building the debugger.
It you checkout the debugger branch from Eclipse, the build works and you can launch Ghidra, but there is no debugger.
This is because the new projects in Ghidra/Debug/ are not imported in Eclipse.

You can try to `gradle eclipse` and import the missing projects into your workspace. In my case it didn't work though (I don't remember why). Since I didn't want to think too hard, I did a fresh git clone, a new eclipse workspace, and it worked like a charm.

Side question to the devs: how do you rebuild Ghidra with Eclipse if you switch to a branch with a lot of changes ? I almost made a script to trash everything and rebuild from scratch, but I guess there is a better way :).

Also, since I am really dumb, I didn't see the debugger at first because it is a new *Tool*. 
In your project window, you can right click on a file and open with Debugger, instead of the default CodeBrowser.

Because if you naively open the CodeBrowser, and check `File > Configure > Debugger` well... you will need a bigger screen.

**Comment by nsadeveloper789** [comment]
When switching among the branches, it's best to do `gradle prepDev cleanEclispe eclipse`, and then `File -> Import` in Eclipse again, you may also want to select-all and refresh in the "Project Explorer." In the case projects are added by the new branch, that usually takes care of it. If projects are removed, you'll need to delete them from Eclipse manually. Check "Delete project contents on disk" too, otherwise Eclipse will litter on your working tree a bit, making it difficult to switch to other branches.

**Comment by ashton2323** [comment]
it worked  this how.

File > Configure > Debugger

thanks for the help.
