### ISSUE TITLE
Generate all instructions from an sleigh spec

### ISSUE THREAD

**Issue by jstaursky** [NationalSecurityAgency/ghidra#2626]
Is it possible to enumerate all possible instructions for a given sleigh spec? That is, rather than feed all possible binary values, can I ask ghidra to output what instructions that it will recognize? I'm guessing some DFS is required of the SLA file, but I was wondering whether this was/has been implemented.

**Comment by nsadeveloper789** [comment]
Not quite. The assembler inverts the sleigh spec to create a mnemonic parser instead of a binary parser. It only exhausts (to a limited depth) the prefixes, i.e., "instruction" constructors that just point back to the root "instruction" table. (mnemonic productions of the form `I -> I`, but that generate a prefix in the machine encoding)

That said, you may find examining the `Assemblers` source useful in figuring out how to do the enumeration you're looking for. The assembler builds a sleigh constructor tree from parsing the mnemonic representation. In theory, you could build "all possible trees" just from enumerating all substitutions for each sub-table, assuming the context expressions can be solved (that machinery is implemented in the assembler as well). After that, it's just a matter of generating the binary instruction (or the mnemonic if that's preferred). You should probably limit yourself to exhausting constructor trees (i.e., instruction forms), since exhausting, e.g., immediate values would be costly and probably of no value.

**Comment by jstaursky** [comment]
Alrighty, that pretty much answers everything. Thanks for the help. Now closing.
