### ISSUE TITLE
Unchecking extension doesn't remove it

### ISSUE THREAD

**Issue by lab313ru** [NationalSecurityAgency/ghidra#2637]
Since some version, all installed plugins are stored in `.ghidra` dir, instead of the Ghdra's installation dir.
Before some version, to remove a plugin I had to just uncheck it in the installed plugins list, and then to restart Ghidra. But since some version, deletion doesn't happen, and the plugin is still physically located in `.ghidra` directory. It only disappears from the plugins list.

**Comment by ryanmkurtz** [comment]
@jpleasu, perhaps 3daeb17 fixed this?

**Comment by jpleasu** [comment]
@ryanmkurtz it's hard to say, but I don't think so.

@lab313ru  When you un-check an extension from the GUI, the effect is renaming a couple of files.  On restart, the existence of those _renamed_ files tells Ghidra to delete the extension.  This hasn't changed since long before some version.

You can check:
1. When you install an extension, `yourextension`, say you should have two files in `~/.ghidra/.ghidra_some.version/Extensions/yourextension`, `extension.properties` and `Module.manifest`.
2. When you  uninstall `yourextension` by unchecking the box, those files are renamed to `extension.properties.uninstalled` and `Module.manifest.uninstalled` respectively.
3. When you restart ghidra, the existence of `Module.manifest.uninstalled` in particular tells Ghidra to delete that directory.

**Comment by ryanmkurtz** [comment]
@jpleasu, those 3 steps you outlined are all working correctly.  The issue is that Ghidra is holding a lock on the jar in the lib directory, and on Windows (which I assume @lab313ru is on), you can't delete the file if the lock is held.  Something must have changed somewhat recently that resulted in the jar being loaded earlier than it used to be.

**Comment by ryanmkurtz** [comment]
That's why I was thinking you implemented 3daeb17 to possibly work around this issue.

**Comment by jpleasu** [comment]
@ryanmkurtz I'd assumed the classpath being assembled wasn't used until _after_ the extensions were cleaned up.. that's wrong though..  blech.  That ought to be fixed.

Actually, I fixed it because I have an extension I retooled as a scripting directory to load dynamically.  While testing I noticed OSGi was complaining about non-existing directories on the classpath.

**Comment by ryanmkurtz** [comment]
Your assumption should be correct...that's the way it used to behave.  I'm not sure what changed yet.  That's why the extensions are deleted so early via the GhidraRun class...before anything should have a chance to load them.

**Comment by ryanmkurtz** [comment]
This is now working in 9.3-DEV.
