### ISSUE TITLE
Assembler: Referring to imported functions does not work correctly

### ISSUE THREAD

**Issue by LunarLambda** [NationalSecurityAgency/ghidra#2670]
**Describe the bug**
I'm making some modifications to a Windows 32-bit PE executable. I want to call an imported library function. From other code in the executable, I can see the instruction I need: `CALL dword ptr [Function]`. This is encoded as `FF 15 <32-bit Address>`.

When assembling an instruction like `CALL dword ptr [ImportedFunctionName]`, the dereferenced address is not correct.
Instead, I have to use 'Go to', go to the imported function, copy the address of the label, and paste it when assembling the instruction

**Screenshots**
What I assembled:
![image](https://user-images.githubusercontent.com/38919842/105235590-26c56b80-5b6c-11eb-94cb-fb0bdc118310.png)
What I got:
![image](https://user-images.githubusercontent.com/38919842/105235750-2fb63d00-5b6c-11eb-8d73-b2f2fec7e447.png)

How I work around it:
![image](https://user-images.githubusercontent.com/38919842/105235853-36dd4b00-5b6c-11eb-9f91-f492016922cb.png)
![image](https://user-images.githubusercontent.com/38919842/105235900-393fa500-5b6c-11eb-8798-e595e78772c4.png)
![image](https://user-images.githubusercontent.com/38919842/105235933-3ba1ff00-5b6c-11eb-906a-623c48a2cc3e.png)
![image](https://user-images.githubusercontent.com/38919842/105235952-3d6bc280-5b6c-11eb-906f-d9a6aff4f6c1.png)

**Environment:**
 - OS: Manjaro Linux
 - Java Version: Not sure
 - Ghidra Version: 9.2

**Comment by nsadeveloper789** [comment]
Looks like it's using its offset from EXTERNAL space (made up) rather than using the offset of a a thunk or pointer from ram space.

**Comment by ghidra1** [comment]
The instruction requires a pointer location (i.e., indirect) not a direct reference location/label.   While it may have produced an invalid offset in the fake EXTERNAL address space (should be corrected), correct this symbol lookup will not resolve your issue since that would produce a direct address for the symbol (if known) instead of the address where the import address table entry is located.

**Comment by LunarLambda** [comment]
I see. I'm not particularly picky as to what address the assembler picks, as long as it generates a valid runtime call.

Perhaps a syntax like `Symbol@IAT` (and similarly, `Symbol@GOT` or `Symbol@PLT` for ELF targets) could be used for disambiguation?

**Comment by ghidra1** [comment]
For now we have eliminated the use of external symbol names when patching an instruction.  Other lookup conventions as you suggest will require more investigation.

**Comment by nsadeveloper789** [comment]
I haven't yet tried this myself, but FWIW, if you manually place the label LoadLibraryA@IAT at 0x004671a4, you should be able to use it in assembly as you'd expect. The tricky bit might be finding the key combo to add the symbol instead of renaming the thunk.

**Comment by ghidra1** [comment]
In the case of the IAT there is not a thunk at that address.  You could write a script to apply these labels on the IAT entries if you choose based upon the external reference.

**Comment by ghidra1** [comment]
In the case of thunks (i.e., ELF .plt) the issue is more complicated since applying a label on a thunk function in the .plt will override the pass-through name from the underlying function.  Although, you can still do it and see if you like the result.

**Comment by nsadeveloper789** [comment]
This should work now, albeit with some caveats: As typed `CALL dword ptr [LoadLibraryA]` still will not work, because the address of `LoadLibraryA` is still in `EXTERNAL` space. The assembler should still no longer permit that syntax. However, Ghidra will automatically place a label like `PTR_LoadLibraryA_deadbeef` at its entry in the IAT or PLT. You can now use that label in the assembly: `CALL dword ptr [PTR_LoadLibraryA` then just use the auto-complete to finish out the address and closing `]`. This also doesn't require you to manually place a label anymore. Once placed, Ghidra should adjust the disassembly display so that you see `[->KERNEL32.DLL::LoadLibraryA]`.
