### ISSUE TITLE
Defining a Charset through Enums.

### ISSUE THREAD

**Issue by frozenLake** [NationalSecurityAgency/ghidra#2714]
**Is your feature request related to a problem? Please describe.**
Currently, without modifying Java code, it is impossible to create a custom charset. While Java does have a number of existing Charsets, I am presently dealing with a program that uses a custom charset. Right now, I am using arrays of a custom "Text" enum, but this is rather clunky, and fails at visualization.

**Describe the solution you'd like**
I would like to be able to import an enum as a charset, or set the display of enums into a string like format.

**Describe alternatives you've considered**
Maybe formatting for charset_info.xml could be expanded to actually define a custom charset? Admittingly, this might be possible, but given the code, it does not appear to be the case.

**Additional context**
I have already searched through existing issues, but one only seems to lead to importing java's StandardCharsets, while the other blindly leads to charset_info.xml, without any context as to how this is useful for the current issue.

**Comment by GMMan** [comment]
From the looks of it, maybe you can implement a new `Charset` and [CharsetProvider](https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/nio/charset/spi/CharsetProvider.html) and add it to `charset_info.xml`. Not sure if editing the XML is even necessary because it seems to add charsets discovered from the JVM, unless the char size is multi-byte. I'll be trying this out later.

**Comment by dev747368** [comment]
In general, the example/custom charset that @GMMan linked seems like the right direction to take.  I'm going to mark the original request as out of scope and close.
