### ISSUE TITLE
Importing JAR (json-simple) not working using Script Manager

### ISSUE THREAD

**Issue by aa-software2112** [NationalSecurityAgency/ghidra#2738]
I am attempting to run a script that uses json-simple. I have 
1. Added the .JAR to the /lib folder
2. Added the .JAR to the classpath (right-clicking on project in eclipse Package Explorer > Libraries > Add External JARS...)
3. Ran the script in Script Manager

This is the error message I get
![image](https://user-images.githubusercontent.com/22150653/107315792-61cd0780-6a65-11eb-8703-50444c27d5bc.png)

I have been trying just about everything to resolve this, and yet I cannot seem to figure it out. Any thoughts on this?

**Comment by ryanmkurtz** [comment]
Are you running Ghidra out of the git repo, or are you running against a prebuilt Ghidra installation with the GhidraDev Eclipse plugin?

**Comment by aa-software2112** [comment]
Hello Ryan,

I am using the prebuilt Ghidra (see the filesystem below)
![image](https://user-images.githubusercontent.com/22150653/107379937-69b79680-6abb-11eb-8935-a26e2bd510c8.png)

And indeed I am running a Script Module within Eclipse

**Comment by ryanmkurtz** [comment]
Are you launching Ghidra via the Eclipse launch configuration?  Or are you launching Ghidra externally from Eclipse?

**Comment by dragonmacher** [comment]
FYE, Ghidra (9.2) now ships with the GSON library.   This library should be a replacement for JSON simple.

**Comment by aa-software2112** [comment]
> Are you launching Ghidra via the Eclipse launch configuration? Or are you launching Ghidra externally from Eclipse?

I am initially launching (opening - double clicking on) Eclipse myself from my desktop shortcut, and later running the script from Ghidra's GUI Script Manager.

I am happy to hear of GSON, however this problem occurs on any JAR I attempt to add to the class path.

**Comment by ryanmkurtz** [comment]
The quickest thing you could try is to just put the jar in one of Ghidra's lib directories, such as `Ghidra/Features/Base/lib`.  Ghidra should automatically add anything in there to its classpath.  If that works and if you are interested, we can give you a more elegant solution.

**Comment by aa-software2112** [comment]
I have just tried your suggestion (the exact dir you mentioned), and tried with and without adding it to the classpath. Both times I received the same error. Do you think I would need to run the script straight out of Eclispe 
 through a run configuration for this to work ?

**Comment by jpleasu** [comment]
It worked for me.  Here's what I did
1. shut down Ghidra
2. copy `json-simple-1.1.jar` to `C:\ghidra_releases\ghidra_9.2.2_PUBLIC\Ghidra\Features\Base\lib`
3. in eclipse, right click on the GhidraScripts project created by the GhidraDev plugin  ->  build path ->  add external archives
![image](https://user-images.githubusercontent.com/1778531/107417775-ed857900-6ae3-11eb-8a7d-41151edc6063.png)
4. navigate to `C:\ghidra_releases\ghidra_9.2.2_PUBLIC\Ghidra\Features\Base\lib\json-simple-1.1.jar` and select.
5. then start using the GhidraDev launch config
![image](https://user-images.githubusercontent.com/1778531/107418251-70a6cf00-6ae4-11eb-9bce-d65e4cfc40a8.png)


it also works if instead of launching from eclipse, I launch Ghidra by running `C:\ghidra_releases\ghidra_9.2.2_PUBLIC\ghidraRun.bat`

**Comment by aa-software2112** [comment]
Fantastic! I think the run configuration was messed up. I created a new one (Ghidra run configuration), and did what you said; finally works.
