### ISSUE TITLE
Right Click->Set Data Type Not present on decompiler

### ISSUE THREAD

**Issue by agnosticlines** [NationalSecurityAgency/ghidra#275]
**Is your feature request related to a problem? Please describe.**
Currently if you right click on a variable on the decompiler, you have an option to retype it, which is fine, but I find myself often going over to the disassembly, finding the variable and changing the type their through the above mentioned menu.

I understand this would only be possible in the prologue of the function in the decompiler, which is fine, just would save some time. Took me an hour or so to figure out the disassembly listing had that option and the decompiler didn't.

Also the keybinds don't work, but that's not as much of an issue.

**Comment by adamopolous** [comment]
There's actually an option in the disassembly to retype the variable, but it's called "Set Data Type" instead of "Retype Variable". 

If you select that option you'll see a list of standard types you can select, or you can select "Choose Data Type" and you'll get the same dialog as if you used the Retype Variable option in the decompiler.

Does that help? It's a bit confusing, I agree. Some consistency with the naming would probably help.

**Comment by dragonmacher** [comment]
Just to clarify, you can retype a variable in both the Decompiler and the Disassembled View (a.k.a, the Listing).   

- Decompiler: Right-click on the variable and choose **Retype Variable**
- Listing: Right-click on the variable and choose **Set Data Type -> Choose Data Type...**

The Listing has the additional option under **Set Data Type** to choose from a menu of commonly chosen types.

Are you asking for the Decompiler to also have this menu of commonly chosen types?

**Comment by agnosticlines** [comment]
Yeah I am. Just to keep consistency. Seems like a small fix but would keep the flow between the two windows.

**Comment by ghidra1** [comment]
Corrected for 9.1 release (Ref: GT-3116)
