### ISSUE TITLE
NullPointerException reading all ARM64 register values from Python

### ISSUE THREAD

**Issue by sporst** [NationalSecurityAgency/ghidra#2773]
```
emuHelper = EmulatorHelper(currentProgram)

for reg in currentProgram.getProgramContext().registers:
    emuHelper.readRegister(reg.getName())

```

When I run this on an ARM64 binary I get:

```
main.py> Running...
Traceback (most recent call last):
  File "/home/sporst/code/ghidrawrapper/main.py", line 16, in <module>
    emuHelper.readRegister(reg.getName())
java.lang.NullPointerException
java.lang.NullPointerException: java.lang.NullPointerException
main.py> Finished!
```

If you're having trouble reproducing this, I can provide the binary.

**Comment by jpleasu** [comment]
`EmulatorHelper` takes a little more setup than that:
```python
from ghidra.app.decompiler import DecompInterface
from ghidra.app.decompiler.component import DecompilerUtils
from ghidra.util.task import ConsoleTaskMonitor
from ghidra.app.emulator import EmulatorHelper;

startAddr = currentAddress;

emuHelper = EmulatorHelper(currentProgram);

# set a breakpoint so the next method doesn't run away
emuHelper.setBreakpoint(startAddr);

# there are other ways to do it, but this is a convenient "set up and run" method.
# Note: we're using the instruction at startAddr as the processor context!
# Typically, this means registers are zeroed
emuHelper.run(startAddr, getInstructionAt(startAddr), monitor);

# now, you can modify the emulated machine state
emuHelper.writeRegister('r0', 0x555)
# emuHelper.writeMemoryValue(...)
# emuHelper.writeStackValue(...)

# (try to) step 3 instructions
for i in range(3):
    addr = emuHelper.getExecutionAddress()
    print('== %s %s == ' % (addr, getInstructionAt(addr)))
    for reg in currentProgram.getProgramContext().registers:
        print('  %s %s' % (reg, emuHelper.readRegister(reg.getName())))

    emuHelper.step(monitor)
```

**Comment by sporst** [comment]
Thank you for the your detailed reply, I really appreciate it. I forgot to mention in my original post that this is a minimal piece of code to reproduce the issue. I get the same behavior while properly emulating code.

**Comment by sporst** [comment]
Yep, it's definitely a program with contextreg. Is there a hard requirement to call run() on the emulator? I have a completely working script that's essentially just:

```
emuHelper = EmulatorHelper(currentProgram)
emuHelper.writeRegister(emuHelper.getPCRegister(), startAddress)

for i in xrange(5000):
   emuHelper.step()

for reg in currentProgram.getProgramContext().registers:
    emuHelper.readRegister(reg.getName())
```
I never run the program, I only step. Everything (memory access, control flow, registers) work perfectly fine but the contextreg value never seems to be set up.

**Comment by jpleasu** [comment]
The requirement is that you set the context register, otherwise your emulation is done with a processor state you haven't specified.  In particular, `contextreg` is defined [here](https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Processors/AARCH64/data/languages/AARCH64instructions.sinc#L1002).  It's components are used throughout the instruction definitions, e.g. `ImmS_LT_ImmR` [here](https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Processors/AARCH64/data/languages/AARCH64base.sinc#L746).

A reasonable way to set the context register is to reproduce what's done by `run` when the incoming `ProcessorContext` doesn't set the context register:
```python
startAddr = currentAddress;

programContext = currentProgram.getProgramContext();
contextRegister = programContext.getBaseContextRegister();
contextRegisterValue = programContext.getRegisterValue(contextRegister, startAddr);

emuHelper = EmulatorHelper(currentProgram)
emuHelper.setContextRegister(contextRegisterValue)
emuHelper.getEmulator().setExecuteAddress(startAddr.getOffset())
```

`run` will set other registers from the incoming `ProcessorContext`, so when we used an `Instruction` its overrides are set. 

Beyond that, `run` calls `continueExecution`.. which essentially steps (via `executeInstruction`) until a "breakpoint" is hit.
