### ISSUE TITLE
NPE VarnodeContext passes null Address to Varnode constructor

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#2787]
https://github.com/NationalSecurityAgency/ghidra/blob/2b08598dbabe6a9c911e712bd928e5f84fb00ee8/Ghidra/Features/Base/src/main/java/ghidra/program/util/VarnodeContext.java#L868-L876

https://github.com/NationalSecurityAgency/ghidra/blob/2b08598dbabe6a9c911e712bd928e5f84fb00ee8/Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/model/pcode/Varnode.java#L50-L56

**Additional context**
This was encountered in an extension issue [here](https://github.com/pedro-javierf/NTRGhidra/issues/7). I went through the initial stack trace and it *should* be impossible.

related to #2785

**Comment by ghizard** [comment]
This fix should be covered with #2785 fix/commit: will just eliminate the null check, which is only pushing the problem elsewhere. As it is, "space" should not be null except due to an error elsewhere.  If it should happen, the NPE will happen in the getVarnode() method instead of the Varnode constructor.
