### ISSUE TITLE
Tool did not accept files: 00000001.app

### ISSUE THREAD

**Issue by zurgeg** [NationalSecurityAgency/ghidra#2803]
**Describe the bug**
Whenever I try to open a file in the decompiler (whether for Gekko PPC (what I'm currently attempting to decompile) or for x86_64) it just complains that "Tool did not accept files: 00000001.app"

**To Reproduce**
1. Open any project
2. Click a file
3. Tool did not accept files: 00000001.app

**Expected behavior**
The file to open normally

**Screenshots**
![image](https://user-images.githubusercontent.com/46549042/109556762-3908c280-7aa5-11eb-85ae-292d51c528b8.png)

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
 - Ghidra Version: 9.2.2
 - JVM Version: Oracle Corporation 15.0.2
 - OS: Windows 10 10.0 amd64
 - Ghidra Origin: ghidra-sre.org

**Additional context**
N/A

**Comment by dev747368** [comment]
I've seen this when the CodeBrowser's tool configuration gets messed up and it doesn't have the basic plugins enabled.

Try opening the tool by itself (ie. clicking on the Green Dragon head tool icon instead of a program), which should bring up your tool window with no program or data.

Go into File | Configure.  Then select "Ghidra Core".  All of the items in the core selection will normally be selected.  If not, your tool's configuration probably has been messed up.

The best way to handle it is to (from the main front end window) delete the Code Browser tool and re-import it from the Tools | Import Default Tool menu.

**Comment by zurgeg** [comment]
![image](https://user-images.githubusercontent.com/46549042/109577614-e2f74780-7ac3-11eb-9cf7-6a9f726b0193.png)
Nope, all checked.

Reinstalled and it... worked??

Still confused as to what the root cause of this issue was, maybe a "Try reinstalling this tool" message along with the "Tool did not accept files" error would be helpful?

**Comment by dev747368** [comment]
@zurgeg - I think you went into the File | Configure for the front end itself, and not the File | Configure in the Code Browser tool that was having the problem.  Easy to get lost in the twisty menus that all look the same.

Yeah, this error needs some TLC so it doesn't leave the user with an unusable Ghidra.
