### ISSUE TITLE
Cannot attach to process when using gdb local debugger

### ISSUE THREAD

**Issue by morganburcham** [NationalSecurityAgency/ghidra#2859]
I am trying to use the debugger to analyze a binary. I am getting strange behavior.

First of all, when I try to target localhost:12345, remote debugging appears to start up fine. However, I get the following message:
"Can't determine the current process's PID: you must name one."

I then try to attach to the process. When I do this, I get the following error:
"Could not attach to process. If your uid matches the uid of the target process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try again as the root user. For more details, see /etc/sysctl.d/10-ptrace.conf
Warning: process <###> is a zombie - the process has already terminated
ptrace: operation not permitted

I have changed the ptrace_scope file appropriately. However, it still does not work. Additionally, when I try to attach, it terminates the process so I can no longer debug.

The other strange behavior I am seeing is dealing with inconsistent behavior. When I try to debug (without attaching to the process), sometimes the threads/register windows will populate and other times they do not. 

Essentially gdb provides no useful information. If I step through, it steps, but I can't see the instruction that was executed. It just tells me the address I'm currently at as I step.  It doesn't do the normal gdb thing and tell me what instruction it is at or highlight the line in the listing window.

Any ideas? Have you observed this behavior?

**Comment by nsadeveloper789** [comment]
I'm having trouble discerning how much of this deals with getting GDB to connect to your target vs getting Ghidra to talk to GDB. It might help if you share the commands you're typing (I presume into the GDB Interpreter window presented by Ghdira), and also how you're launching the target to which you're trying to attach. Are you using gdbserver?

As far as the threads/registers windows populating. The reasons could vary. In order for those windows to populate, you have to "Record" the target into a Ghidra trace file. ATM, Ghidra can only record x86 and ARM targets. Sometimes, due to a timing issue we've been working out, the recording is not automatically started. Navigate to "Inferiors[1]" in the "Objects" window and try selecting "Record" from its toolbar drop-down menu. If the "Threads" window populates, but not the "Registers," try selecting a thread.

For disassembly listings, ensure the "Dynamic Listing" window is visible ("Debugger" menu). The usual (static) "Listing" window is only populated when Ghidra recognizes the target's modules from the set of currently opened/imported program images. You can try navigating to "Inferiors[1].Modules..." in the "Objects" window to see if GDB is able to list your target's modules. Or type `maint info sections ALLOBJ` into the Interpreter. Those should be populated into the "Modules" window, allowing Ghidra to recognize and map them to your open/imported programs. Having that module mapping produces the best user experience.

**Comment by morganburcham** [comment]
I wonder if it is because I have a PPC target.

Currently, I am doing the following commands:
1. qemu-ppc -g 12345 <bin_name>
2. Launch up the binary in the debugger in Ghidra.
3. Go to connect the debugger using IN-VM GNU gdb local debugger
4. In the gdb interpreter in Ghidra: Set the architecture and endianness. 
5. In the gdb interpret: target remote localhost:12345

After this step, I see the message that the current process's PID cannot be determined. I then try to attach to the qemu-ppc process and everything dies.

**Comment by d-millar** [comment]
Hi Morgan,

Sound like you are doing the right things, but, yes, ppc will stop the debugger in its tracks right now.  I've added a new file that should help you out - GdbPowerPCDebuggerMappingOpinion - probably take a day or two before it makes it into the repo.  Once it's there, however, we would love to have you test it out!   Will keep you posted.

Best,
D

**Comment by morganburcham** [comment]
Thanks, that sounds great!

**Comment by d-millar** [comment]
GdbPowerPCDebuggerMappingOpinion added.
