### ISSUE TITLE
"Defined Strings" view during Auto-Analysis slows down the process by magnitudes

### ISSUE THREAD

**Issue by patric-r** [NationalSecurityAgency/ghidra#2889]
**Describe the bug**
If the "Defined Strings" view is open (which is the default), the Auto-Analysis is slowed down by magnitutes (hours instead of minutes).
Most likely, this is caused by constant updates of the view which seem to block (or at least interfere) the Auto-Analysis.
Additionally, a swing timeout (default 20 sec) occurred which might be caused by this as well.

Closing the "Defined Strings" view during Auto-Analysis dramatically speed up auto-analysis.

A clear and concise description of the bug.

**To Reproduce**
1. Take a fairly large binary (tested with a 64bit PE binary only), ideally with a large amounts of Strings
2. Do a full Auto-Analysis and measure the duration.
3. Close without save
4. Open the same binary for another time
5. Do a full Auto-Analysis but immediately close the "Defined Strings" view and measure the duration.

**Expected behavior**
Ideally, Ghidra would either improve concurrent performance (e.g. by using improved synchronisation/data structures) or at least Ghidra should not update the defined strings during Auto-Analysis with such a high frequency.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: Oracle OpenJDK 11.0.2
 - Ghidra Version: 9.2.1
 - Ghidra Origin: official ghidra-sre.org distro

**Comment by dragonmacher** [comment]
IIRC, this view is not open by default.  If you close your tool with the view open then it will be open when you later launch the tool.

We will examine how the table is updating to see if there are any obvious mistakes.    The Symbol Table can also severely affect performance if open during analysis.   We have made some changes to the Symbol Table recently to address this, but the bigger issues will always be present: repeated view updates for widgets that have many records will always slow down performance.  This is especially true in Ghidra right now due to the fact that these widgets and the analysis engine all contend for the same database lock while working.

Our recommendation is to close the Symbol Table (and others like the Defined Strings table) while running a full analysis.

**Comment by dragonmacher** [comment]
I can see a path in the Defined Strings provider that could cause excessive table reloaded.    I will investigate this more.

**Comment by pj58943** [comment]
"Our recommendation is to close the Symbol Table (and others like the Defined Strings table) while running a full analysis."

It might be preferable from a user's perspective to defer updates to these tables while an analysis task is running.  It may not be at all obvious that e.g. a background tab is slowing things down, so many users will be experiencing unnecessarily poor performance.  And if your recommendation is to close the tables anyway, then they're effectively not usable during analysis, so why not let them stay open but be grayed out until the analysis has finished?

**Comment by dragonmacher** [comment]
> And if your recommendation is to close the tables anyway, then they're effectively not usable during analysis, so why not let them stay open but be grayed out until the analysis has finished?

Theoretically possible, but this would limit users that decided they wanted to use the table during analysis, despite the slower performance.  

Also, FYI, we just finished another round of changes for the Symbol Table that fix a handful of performance issues found when using the Symbol Table during analysis.    Considering these recent changes, and those made to the View Strings table, it is much more realistic to use these tables during analysis.   These changes will make it into the next major version of Ghidra.
