### ISSUE TITLE
Generate the control flow graph with java script

### ISSUE THREAD

**Issue by valour01** [NationalSecurityAgency/ghidra#289]
Hello , I refer to the intra-procedure control flow graph, which is the function graph.

I want to use the java script to generate the control flow graph including the basic blocks and the edges. I reviewed the example script in the script manager and also check some APIs. However, I failed to solve it. 

Do anyone know the solutions? Many Thanks

**Comment by d-millar** [comment]
Hi @valour1,

I think the bulk of the code you'll need you'll find in the GraphASTAndFlow script.  The GraphAST script is designed to display the data flow for a single function.  GraphASTAndFlow extends the GraphAST class to add control flow edges (black for single path, red for branch).  The only extra bit you'll need is code for connecting routines.  If you look https://github.com/d-millar/ghidra_pcode_scripts, I've pushed out a couple of scripts that dump more extensive pcode info.  The collectFunctions method walks a call tree in a pretty obvious manner, and the processFunction method extracts a few things like the entry point that should enable you to stitch together an entire control flow graph.

Additionally, if you don't mind clawing through the zipped src files in the distribution, you could pull out the ASTGraphTask.java code from the "Feature/Decompiler/lib/Decompiler-src.zip" and check out the createControlFlowGraph method.

Of note: neither of the scripts mentioned can be run in their current state because we were unable to include our GraphService instantiation for copyright reasons.  We're considering other options, but, in the meantime, included the code which may be useful for folks like yourself.

Cheers, D
