### ISSUE TITLE
How do I clear this Error so that I can read the operand of the disassembled instruction again?

### ISSUE THREAD

**Issue by RobBrooks** [NationalSecurityAgency/ghidra#2898]
Clearly this would ideally be displaying:

LD $c002

but isn't.

Many thanks,

Rob.

![image](https://user-images.githubusercontent.com/17879728/113509074-81574c80-954b-11eb-9209-eac38aaa3f00.png)

**Comment by Danil6969** [comment]
Your example isn't reproducible. I have created a "z80.bin" file and filled it with bytes from your screenshot. Then I've imported it in Ghidra as raw binary both as "z8401x:LE:16:deafault" and "z80:LE:16:default".
I just see "LD A,(DAT_ram_c002)" at ram:7f. You have probably ran some analyzer or loaded from some structured format (ELF or something) and it added some garbage which causes glitches. Try fresh load by loading a raw bin file instead of any format and then do everything sequentially, i.e. one-by-one and not all at once (this includes any analysis, memory remaps, retypes, renames, definitions of globals etc.).

**Comment by ghidra1** [comment]
Can you provide the stacktrace details (click Details >>>) button or get from your log.  

It would appear that AddressMapImpl is performing a case-insensitive check for address space names which seems to be a bug.  Our address space names are intended to be case-sensitive.  

While this sppears to be a bug, you may want to check any overlay spaces you may have created and avoid re-using an existing address space name in a case-insenstive manner (e.g., if `ram` is defined don't create an overlay named `RAM`).
