### ISSUE TITLE
Mach-O 64 Binary Decompilation Issue

### ISSUE THREAD

**Issue by itennenhouse** [NationalSecurityAgency/ghidra#2906]
**Bug description:**
Mach-O 64 bit binaries appear to cause the decompiler to ignore certain variables as demonstrated by the example in the screenshots. Unfortunately, I do not have a mac or a mac vm set up and received the binaries I noted the issue in from a project file, so I cannot easily investigate this. A friend suggested it may be related to issue 1446: https://github.com/NationalSecurityAgency/ghidra/issues/1446
Additionally, I noticed 9.2.2 fixed a Mach-O importer issue, so I wonder if the fix in turn caused this problem.

**Steps to reproduce the behavior:**
Potentially just load and analyze any Mach-O 64 bit binary file, but I can only say for certain the files I was given have this issue.

**Expected behavior**
I would expect the decompiler to correctly keep track of all essential variables. In the example below it should declare local_14 and add a line at the beginning of the inside of the while loop with local_14+=local_10;. Additionally, it should include local_14 in the printf statement.

**Screenshots**
Here is the source code written in c:
![image](https://user-images.githubusercontent.com/59844013/113862239-c5c23280-976d-11eb-8aaf-879360ad1fdd.png)
Here is the disassembly of main and the decompilation:
![image](https://user-images.githubusercontent.com/59844013/113862451-028e2980-976e-11eb-948a-204b7193f372.png)

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
 - OS: Linux x86-64, but the binary is Mach-O 64
 - Java Version: openjdk 11.0.9
 - Ghidra Version: 9.2.2
 - Ghidra Origin: official ghidra-sre.org distro

**Additional context**
I am happy to supply any additional information I can to help, but as I said I am not able to create new binaries for testing.
Additionally, my apologies for any formatting violations or if this issue has already been addressed.

**Comment by ghidracadabra** [comment]
In this case I think the problem is that the decompiler is not using the correct arguments for the call to printf.  In general, variadic functions can cause problems since the arguments can vary from call site to call site.

To fix this, you can right-click on the call to printf in the decompiler window, select "Override Signature", click through the warning, and the enter the correct signature (int printf(char *, int) in this case).

Alternatively, we've recently added an analyzer to handle these cases but it's still under evaluation and so off by default.  To run it, select Analysis->One Shot->Variadic Function Signature Override from the Code Browser.

**Comment by itennenhouse** [comment]
@ghidracadabra Thanks for the fix, worked like a charm! Should I close the issue?

**Comment by ghidracadabra** [comment]
Glad to help!  I'll close it.
