### ISSUE TITLE
Problems encountered in the development of TI C64x decompiler

### ISSUE THREAD

**Issue by xianggechishi** [NationalSecurityAgency/ghidra#2922]
TI C64X processor uses 5 delay slots, so similar to "B loc_xxxx instructions, it will happen after 5 instructions are executed (such as filling "NOP" afterwards), but in the C64X instruction set, his instructions will  There is a case of parallel execution, as shown in the following figure:
![微信图片_20210412102033](https://user-images.githubusercontent.com/48665270/114332879-a6664380-9b79-11eb-8296-ef93c200ce01.png)
When we write /Ghidra/Processors/TI_C64x/data/language/C64x.slaspec, we find that n in the delayslot(n) function can only be a constant (n represents a delay x double word size instruction), and we  When encountering parallel instruction execution, n is likely to be a variable, causing our work to be unable to proceed.

**Comment by ghidra1** [comment]
TI C64x is much worse than you indicate.  Simple delayslot use will not suffice since each instruction has a separate number of delay cycles for its various phases of execution.  With up to 8 instructions per execute packet the full effect of an instruction may not be complete prior to the next execute packet starting its execution.    This ability to properly model this processor exceeds the capabilities of the default Disassembler.

**Comment by ghidra1** [comment]
The delayslot implementation specifies the minimum number of delay slot instruction bytes as you have noted.  The delayslot mechanism is not designed to handle the variability you suggest and would not handle the necessary pcode-weaving this language requires nor the delay cycle variability across instructions beyond an execute packet.
