### ISSUE TITLE
Maximize window at CodeBrowser start

### ISSUE THREAD

**Issue by lab313ru** [NationalSecurityAgency/ghidra#293]
For now CodeBrowser window starts with not maximized window. Is it possible to change this behaviour?

**Comment by dragonmacher** [comment]
Ghidra currently has no way of doing this.

Ghidra will remember window size and location (this info is saved when you close the Code Browser or exit Ghdra).    Although, it may resize the window if you use the entire screen bounds, as would the be case if maximized.

**Comment by justanotheranonymoususer** [comment]
I second this request. It's annoying that it opens full screen but not maximized and not fully centered.
Why was it closed @dragonmacher?

**Comment by dragonmacher** [comment]
> I second this request. It's annoying that it opens full screen but not maximized and not fully centered.
> Why was it closed @dragonmacher?

Simply because it is a low-priority ticket that is unlikely to be fixed in the foreseeable future.

**Comment by justanotheranonymoususer** [comment]
It's an open source project, maybe somebody will submit a PR. Are issues not for tracking stuff? Not all of the 900 currently open issues are likely to be fixed in the foreseeable future, I assume.

**Comment by dragonmacher** [comment]
> It's an open source project, maybe somebody will submit a PR. Are issues not for tracking stuff? Not all of the 900 currently open issues are likely to be fixed in the foreseeable future, I assume.

We have not yet formalized our ticket management policy.  Further, we are a bit behind on addressing the currently open tickets.  You are correct, a large majority of the still open tickets are unlikely to be addressed.

It was a mistake on our part in this ticket to not signal to the community why the ticket was closed.  The community is still welcome to contribute fixes for issues such as this.   If such a PR is approved, we can easily update the state of this ticket.

**Comment by M-a-r-k** [comment]
Could this issue be reopened? I've been looking at the code and it *might* be pretty simple to fix.

In Ghidra/Framework/Docking/src/main/java/docking/RootNode.java there is
```
Element saveToXML() {
    Element root = new Element(ROOT_NODE_ELEMENT_NAME);
    JFrame frame = windowWrapper.getParentFrame();
    Rectangle r = frame.getBounds();
    root.setAttribute("X_POS", "" + r.x);
    root.setAttribute("Y_POS", "" + r.y);
    root.setAttribute("WIDTH", "" + r.width);
    root.setAttribute("HEIGHT", "" + r.height);
    root.setAttribute("EX_STATE", "" + frame.getExtendedState());
```
Extended state includes the window maximized state; see https://docs.oracle.com/javase/8/docs/api/java/awt/Frame.html. So that's already being saved.

For restoring there is:
```
List<ComponentPlaceholder> restoreFromXML(Element rootNodeElement) {
    ...
    int x = Integer.parseInt(rootNodeElement.getAttributeValue("X_POS"));
    int y = Integer.parseInt(rootNodeElement.getAttributeValue("Y_POS"));
    int width = Integer.parseInt(rootNodeElement.getAttributeValue("WIDTH"));
    int height = Integer.parseInt(rootNodeElement.getAttributeValue("HEIGHT"));
    JFrame frame = windowWrapper.getParentFrame();
    Rectangle bounds = new Rectangle(x, y, width, height);
    WindowUtilities.ensureOnScreen(frame, bounds);
    frame.setBounds(bounds);
```
Would simply calling `frame.setExtendedState()` after that to restore the maximized state work?

That could possibly be preceded by `frame.setMaximizedBounds()`, in which case saveToXML() should also be modified to add something like `root.setAttribute("MAX_BOUNDS", "" + frame.getMaximizedBounds())`.

**Comment by M-a-r-k** [comment]
I managed to build Ghidra with the changes outlined below. Now the maximized window state is preserved. The non-maximized window dimensions are also remembered/restored. I removed calls to `WindowUtilities.ensureOnScreen()` in `restoreFromXML()` and `setVisible()` for now, rather than try to modify those functions.

Only tested on Windows 10 with a single screen but it seems to work OK. Bear in mind that I know next to nothing about Java...

The modified RootNode.java is attached.
[RootNode.java_maximized_mod_20211224.zip](https://github.com/NationalSecurityAgency/ghidra/files/7775087/RootNode.java_maximized_mod_20211224.zip)

Changes made were...

In `setVisible()`:
```
Window mainWindow = getMainWindow();
mainWindow.setVisible(state);
// WindowUtilities.ensureOnScreen(mainWindow);
```

In `saveToXML()`:
```
...
JFrame frame = windowWrapper.getParentFrame();
int state = frame.getExtendedState();		// Get current state (may be maximized)
if ((state & JFrame.MAXIMIZED_BOTH) != 0) {	// We are maximized. Want to save un-maximized dimensions
	frame.setExtendedState(state & ~JFrame.MAXIMIZED_BOTH);
}
Rectangle r = frame.getBounds();
if ((state & JFrame.MAXIMIZED_BOTH) != 0) {	// Revert to original state if needed
	frame.setExtendedState(state);
}
root.setAttribute("X_POS", "" + r.x);
root.setAttribute("Y_POS", "" + r.y);
...
```

In `restoreFromXML()`:
```
...
int width = Integer.parseInt(rootNodeElement.getAttributeValue("WIDTH"));
int height = Integer.parseInt(rootNodeElement.getAttributeValue("HEIGHT"));
int state = Integer.parseInt(rootNodeElement.getAttributeValue("EX_STATE"));
JFrame frame = windowWrapper.getParentFrame();
Rectangle bounds = new Rectangle(x, y, width, height);
// WindowUtilities.ensureOnScreen(frame, bounds);
frame.setBounds(bounds);
frame.setExtendedState(state);

List<ComponentPlaceholder> restoredPlaceholders = new ArrayList<>();
...
```

**Comment by M-a-r-k** [comment]
I created a [pull request](https://github.com/M-a-r-k/ghidra-motif_aa/pull/1) in case anyone wants to test my changes.

**Comment by M-a-r-k** [comment]
After building Ghidra from git today, maximized window state does seem to be saved and restored when Ghidra is next launched. However, the non-maximized window dimensions are still being lost as I mentioned [above](https://github.com/NationalSecurityAgency/ghidra/issues/293#issuecomment-1000923708). Should I open a new issue specifically for that?

**Comment by dragonmacher** [comment]
Yes, that would be helpful.   I think the easiest solution for that issue is for us to add an option to not change any saved settings values.  This will allow users to workaround odd OS behavior or edge case we are not handling correctly.

**Comment by M-a-r-k** [comment]
I created issue #5879 for that.
