### ISSUE TITLE
Wrong P-Code for "67 E8" on x86-64

### ISSUE THREAD

**Issue by Enkelmann** [NationalSecurityAgency/ghidra#2976]
The P-Code generated for call instructions with the byte sequence `67 E8 xx xx xx xx` (a call with a addr32 prefix) seems to be wrong for x86-64 binaries: Ghidra generates something like
```
RSP = INT_SUB RSP, 4:8
STORE ram(RSP), 0x10433f:4
CALL *[ram]0x105390:8
```
but the size of the return address pushed onto the stack is still 8 bytes and not 4. In other words, Ghidra seems to misinterpret the effect of the `67` prefix on the call instruction, since it actually has no effect in this situation (as far as I can tell). I confirmed the different actual behaviour of the instruction with gdb on my computer.

Tested with Ghidra version 9.2.2 DEV.

**Comment by GhidorahRex** [comment]
I just want to confirm/clarify what you're stating. The return address pushed onto the stack here should be 8 bytes, not 4. Which is what the processor manual states is the correct behavior.

The behavior on the actual call instructions seems to be correct, but the instruction info seems to suggest that the 67 prefix is setting addrsize=1 rather than addrsize=2, and the actual instruction being executed is the 32-bit one. So I suspect it might be an issue with how the `addrsize` context value is being set.

**Comment by Enkelmann** [comment]
Yes, the return address pushed onto the stack here should be 8 bytes, not 4.

The relevant section of the processor manual (taken from [here](https://www.amd.com/system/files/TechDocs/24594.pdf), page 130 (170 in the PDF)) seems to be the following:
```
In all cases, the rIP of the instruction after the CALL is pushed on the stack,
and the size of the stack push (16, 32, or 64 bits) depends on the operand size of the CALL instruction.

For near calls in 64-bit mode, the operand size defaults to 64 bits.
The E8 opcode results in RIP = RIP + 32-bit signed displacement
and the FF /2 opcode results in RIP = 64-bit offset from
register or memory. No prefix is available to encode a 32-bit operand size in 64-bit mode.
```
So no prefix can change the addrsize for the instruction in 64bit mode. That the `67` prefix is allowed nevertheless, but with no effect on the instruction, seems to be a legacy issue. But it is generated by standard compilers (for padding I suppose).

**Comment by GhidorahRex** [comment]
You're right, this does seem to be an issue. I'll triage this.
