### ISSUE TITLE
License: Was this made by the United States Government?

### ISSUE THREAD

**Issue by Myriachan** [NationalSecurityAgency/ghidra#3]
Was Ghidra made by the United States Government, as defined by [17 USC 105](https://www.law.cornell.edu/uscode/text/17/105)?  If so, the LICENSE file doesn't really make sense.

**Comment by RobRoseKnows** [comment]
See intent.md: https://github.com/NationalSecurityAgency/ghidra/blob/master/INTENT.md

**Comment by ctubbsii** [comment]
Hi @Myriachan,

Thanks for the great question, and to @RobRoseKnows for beating me to the answer.

If interested, there's also some helpful information at https://government.github.io/best-practices/copyright/

**Comment by impredicative** [comment]
The fact that some of the work was done by contractors seems like a bogus argument for not using a public domain equivalent license. Has it been tested in court? After all, the federal government used taxpayer money to pay the contractors.

As of 2015, 1.87% of licenses in use on GitHub were [Unlicense](https://unlicense.org/).[[ref](https://github.blog/2015-03-09-open-source-license-usage-on-github-com/)] The implication that taxpayer-paid contractor developed work cannot use a public-domain equivalent license such as the Unlicense is a solidly bogus one.

**Comment by ctubbsii** [comment]
Questions about how the U.S. Government should license its works are great, but this is not the right forum to debate that topic. Those kinds of questions should probably be resolved at a higher level, rather than within a single project like this, so that any policies coming from those discussions can be applied uniformly across government.

Perhaps the question/feedback area of https://code.gov/ would be a more appropriate location to discuss that topic.
