### ISSUE TITLE
[Debugger] Is it possible to sync data between dynamic and static view on the debugger

### ISSUE THREAD

**Issue by Kingloko** [NationalSecurityAgency/ghidra#3074]
Hey,
I'm playing with the debugger + pcode emulation feature from this commit: 68a9c0a5a37f26e3c5bc1085ee91aa4041ea7510.

In the screenshots below I'm viewing a trace that I recorded earlier today. 
Dynamic:  
![image](https://user-images.githubusercontent.com/6856475/119705350-a454fd00-be26-11eb-9d92-b0e1491667fc.png)   
Static:
![image](https://user-images.githubusercontent.com/6856475/119705375-ab7c0b00-be26-11eb-865b-191b2d7dcb00.png)

Is it possible to tell ghidra to copy the bytes from the static view into the dynamic view? Otherwise the pcode emulator gets stuck when I visit code that wasnt read while debugging.

**Comment by d-millar** [comment]
@Kingloko So, the two views should be in sync if the trace is working and the memory model is present.  Not quite sure what's missing in your case.  Looks like you have memory (sort of) because you have something in the Dynamic view.  That also implies the trace is working.  Any chance the name for you executable in the static listing is not an exact match for the name as listed in the Module view?  If not, you may need to map the executable by right-clicking on the row in the Modules table and choosing the program in the static view.

**Comment by Kingloko** [comment]
hmm, looks like the modules didn't get loaded at all. 
![image](https://user-images.githubusercontent.com/6856475/120000510-e3a75900-bfa0-11eb-9bab-6794e9c0dc9e.png)

**Comment by d-millar** [comment]
Good question - just so I understand your set-up, are you running pure emulation, here?  i.e. you're not connected to any real target?

**Comment by d-millar** [comment]
If you're connected via gdb, the relevant command is "maintenance info sections ALLOBJ nosections".  Presumably, your target does not support this command.  You can, however, define the command in a script and essentially fake out the debugger.  We typically doe this to get memory defined (e.g. "info proc mappings" is missing).  We have a sample script for that in Ghidra/Debug/Debugger/src/main/resources.

**Comment by Kingloko** [comment]
I'm not connected atm, but I can reconnect later and give it another try. 
Thanks for pointing me in the right direction(s). I think I have plenty of stuff to try next, much appreciated!

**Comment by nsadeveloper789** [comment]
So, synchronization is only done for addresses, not bytes or disassembly. If your cursors are synchronized between the views, then Ghidra is correctly mapping your modules to your static images. I'll have to look back at my code, but emulation might defer to static memory when it knows dynamic memory is stale. In any case, it is a feature I have experimented with at one point or another, I just don't remember the current state of the code....
Also, "pure emulation" is not yet supported. To emulation, you at least have to launch a real target. You can emulate within that trace offline, but I'd recommend capturing relevant memory before terminating the target. A kludgy way of doing that, if you don't know the area of interest, is to select all dynamic memory and click the "Capture Memory" button. Don't blame me if that crashes your target, though :) . Emulating online is probably the best way to go, since IIRC, it's smart enough to load bytes from the target if you're extrapolating forward.
