### ISSUE TITLE
Switch to turn off register naming in disassembler

### ISSUE THREAD

**Issue by marcushall42** [NationalSecurityAgency/ghidra#309]
**Is your feature request related to a problem? Please describe.**
In ARM, and probably many other architectures as well, register assignment in the assembly code is very fluid.  Yet, if I name function parameters in the decompiler, r0 through r3 get renamed in the disassembler to correspond with the arguments passed in in these registers.

Typically, these values may be immediately moved to other registers, used, stored in the stack, or whatever, but the r0-r3 register usually does not hold that value very far into the function.

Yet the disassembler constantly calls r0 "fname" or whatever.  This just makes reading the disassembly more difficult because you have to constantly re-think that "fname" currently means "r0", etc., and that conflicts mentally when "fname" is really in r8.

**Describe the solution you'd like**
An option somewhere to turn off the register renaming.  Either on a per-function basis, or per-file, or perhaps just decide not to do it on some architectures.

**Comment by saruman9** [comment]
See `Edit -> Tool Options... -> Listing Fields -> Operands Field -> Markup *`

**Comment by marcushall42** [comment]
Found it..
Ghidra has options for so many things, I expected that it might already be there.  The large number of options sometimes makes it difficult to find which is the right one, but I'm not complaining about that...

**Comment by brandonros** [comment]
![image](https://user-images.githubusercontent.com/8949910/73555616-f4cb6e80-441b-11ea-8d6d-ad236811122c.png)

There is no `Markup *` option in 9.1.1 and I am struggling to turn off these operand labels:

![image](https://user-images.githubusercontent.com/8949910/73555914-6dcac600-441c-11ea-8d45-3ddb1c6516b5.png)

![image](https://user-images.githubusercontent.com/8949910/73555925-77542e00-441c-11ea-8011-1d556b1b0fdb.png)

I'd much prefer to see the `Operand` value instead of the `Labeled` value in the disassembler view. Is this possible?

**Comment by gipi** [comment]
@brandonros I think by ``Markup *`` they mean the options starting with ``Markup``
