### ISSUE TITLE
Windows10/ghidraRun.bat Causes error: Could not find or load main class LaunchSupport

### ISSUE THREAD

**Issue by Charlie-Gallie** [NationalSecurityAgency/ghidra#3108]
Running ghidraRun.bat gives me the error `Error: Could not find or load main class LaunchSupport` regardless of the JDK version I have installed and added to the environment path.

I'm using Ghidra version 9.2.4, but this consists with many 9.X versions. (I haven't tested all 9.X versions)

![image](https://user-images.githubusercontent.com/73857381/120899667-ca4d7f00-c628-11eb-8c15-334bf912d6dc.png)
![image](https://user-images.githubusercontent.com/73857381/120899715-008afe80-c629-11eb-98a3-3f4b3b856653.png)
![image](https://user-images.githubusercontent.com/73857381/120899752-287a6200-c629-11eb-893c-708c0202df76.png)

 - OS: [Windows 10]
 - Java Version: [11.0.11]
 - Ghidra Version: [9.2.4]
 - Ghidra Origin: [ghidra-sre.org]

There is also a `JAVA_HOME` path variable, which has the same value as shown above.

Other solutions including changing the JDK version, changing Ghidra version, and modifying the path in different ways have not worked for me. I appreciate all help.

**Comment by dev747368** [comment]
I don't have any sure fire tips for your situation, but until someone else chimes in:

1) the JAVA_HOME shouldn't have a /bin at the end of it.  But that said, it won't break things as long as the java on the path is good.
2) there have been issues when the ghidra install directory path contained parts that had spaces in the name.  Could you confirm that the redacted username directory in your screenshot is a simple value without any spaces, etc?  I'm pretty sure this was fixed at some point but I'm not sure the version.
3) Could you test if running ghidraRun.bat manually from the cmd line does anything different (like in your screen shot above where you ran java --version), instead of double-clicking the bat file?

**Comment by topia** [comment]
I think this issue is related: #1726; only 10.x branch contains fixes for the issue.

**Comment by Charlie-Gallie** [comment]
As noted by both @topia and @dev747368, the issue was due to the path it was under. I used an exclamation point in the name of a folder which causes the error. I appreciate it very much.

**Comment by ryanmkurtz** [comment]
Duplicate of #1817
