### ISSUE TITLE
How to find the correspond exception handling routine in ghidra

### ISSUE THREAD

**Issue by ratsafalig** [NationalSecurityAgency/ghidra#3130]
assume i have a `.so` file that contain a `throw catch` pair, how can I find the `catch` part of the code in ghidra?

**Comment by Danil6969** [comment]
There should almost always be an unconditional jump through the whole catch code after try clause. There is no such thing as a separate routine for catch clause because it's embedded into routine containing it. But there may also be an additional routine (for e.g. registering Windows SEHs via FS register or saving registers into exception handler's frame) in the function's prologue.
