### ISSUE TITLE
see where gdb is pausing

### ISSUE THREAD

**Issue by exx8** [NationalSecurityAgency/ghidra#3161]
I'm debugging an elf file via the new debugger mode.
I wonder, how do I see the line the debugger is pausing on?
I get an address in the object window, but once I click "display methods"(in the right click menu), nothing happens.
I would like to see the specific line in the listing window (where all the assembly is in).

Thanks!

**Comment by d-millar** [comment]
Hey Eran,

Unfortunately, the "display methods" don't do what you think they do - I can see why you'd expect them to, but....  The "display methods" in the Objects view display any selected sub-tree as a new tree, table, graph, etc. and won't solve your current problem.

Highlighting the current line in the listing window should happen automatically if everything else is working correctly, but admittedly that's a pretty big "if".  To troubleshoot, we may need a little more info, but let me try to give you the big picture.

First, only the Objects view and the Interpreter view are in some sense "on" by default.  The other windows are active only when there is a valid trace being collected.  This is controlled by a setting in the Objects provider and should be set by default, but, if the Objects view is not open to at least the process level, it may not trigger.  I don't think this is your problem, because you've mentioned right-clicking on an address, which makes me think you've opened the tree down to the registers node within a thread.

If the trace is on, the other windows should be populated.  In particular, the dynamic listing window should have valid bytes and be tracking the current instruction pointer.  If this is not the case, it probably means you're working with a target (or version of gdb) for which "info proc mappings" is not defined.  If so, you'll have to define it yourself.  There are a number of postings regarding this, but happy to walk you through it if that's the issue.

If you do have values in the dynamic listing and the other windows besides the Objects and Interpreter windows, then the issue I assume you're having is that the static listing is not tracking the instruction pointer even thought the dynamic listing is.  If so, the likely culprit is that the debugger can't figure out how to map the static view to the current address.  This means either you are missing the module listing (i.e. the Modules window is empty) or the current program in the static view has a different name than the one in the module listing.  In the former case, you'll need to define a different command (one of the "maint" commands - am forgetting which one).  In the latter, you need to right-click on the correct module in the modules listing and manually map it to the program you're looking at.

Apologies for this being such a hassle - we're definitely still working the kinks out of this bit - but let us know which problem you think you're having and we can help you get around it.  

Best,
D

**Comment by daveaitel** [comment]
The Debugger's cursor does move around a bit in the decompiler view...but the line doesn't get highlighted the way the assembly listing does, which is confusing.
