### ISSUE TITLE
[newbie] exporting full call graph of a program

### ISSUE THREAD

**Issue by alex-from-intuita** [NationalSecurityAgency/ghidra#3176]
Hi! 
1- can we use Ghidra to get a full call graph of a program?
I'm using a MacBook pro, Big Sur OS, 1.4GHz Quad Core Intel Core i5
if yes, what specific steps should I take to turn a given input into the graph output?

2-  which programming languages are supported by Ghidra? I guess only those languages where the code can be compiled into one of the file extensions that can be imported? (see attached) 
![Screen Shot 2021-06-30 at 10 40 03 AM](https://user-images.githubusercontent.com/78109534/124006805-892e5d80-d98f-11eb-9d0c-78968bc6a5ec.png)

I picked a random .dmg file to see if I can get the function call graph but so far no luck.

Thank you so much for your help.

**Comment by ghidracadabra** [comment]
1) You can display the call graph of a program via Graph -> Calls from the Code Browser (the window where you see the disassembly and the decompiler output).  If you want to export the graph instead of display it, first set the graph output to the Graph Exporter via Graph -> Graph Output -> Graph Export.  Then, when you select Graph->Calls, a dialog will pop up asking you which format you want the exporter to use.

2)  Asking which programming languages are supported by Ghidra isn't quite the right question, although the programming language used can certainly have consequences.  From the Project Window (the window that appears when you launch Ghidra and shows the files you've imported) Help -> Installed Processors will show which processors Ghidra understands.  In theory, Ghidra can understand an executable file compiled for any of these processors from any programming language (or assembled from handwritten assembly).  Note that that decompiler generally outputs C code so depending on the compiler and source language interpreting what you see in the decompiler window might take some work. Also, if Ghidra doesn't have a loader for a particular file format, you could import the file as a raw binary and start analyzing manually.
