### ISSUE TITLE
Erroneous Decompiler Output 

### ISSUE THREAD

**Issue by huettenhain** [NationalSecurityAgency/ghidra#3185]
**Describe the bug**
The decompiler output is wrong in one observed sample.

**To Reproduce**
I have attached a zip file. It is password-protected with the password `infected` and contains a sample with the SHA-256 hash
```
30cc2f96d2ed05a07d35b10fb916184556213eafd6deea16d588797213332a80
```
It's a training sample, not an actual piece of malware. Open it in Ghidra and inspect the function at offset `00401080`. The decompiler shows the `ExpandEnvironmentStringsA` function receiving the integer argument `0x104` as its second argument.

**Expected behavior**
Ghidra shows that the function `ExpandEnvironmentStringsA` receives a string buffer as the second argument

**Screenshots**
This is my decompiler output:
![image](https://user-images.githubusercontent.com/11869704/124357287-091c2800-dc1b-11eb-8a01-04c2de726ee1.png)

The disassembly shows that this is inaccurate:
![image](https://user-images.githubusercontent.com/11869704/124357316-2650f680-dc1b-11eb-9c16-c1e371bc5501.png)

**Attachments**
[30cc2f96d2ed05a07d35b10fb916184556213eafd6deea16d588797213332a80.zip](https://github.com/NationalSecurityAgency/ghidra/files/6758532/30cc2f96d2ed05a07d35b10fb916184556213eafd6deea16d588797213332a80.zip)

**Environment (please complete the following information):**
 - OS: Windows
 - Java Version: 11.0
 - Ghidra Version: 10.0-Public, also occurs on 9.2.3-Public
 - Ghidra Origin: official ghidra-sre.org distro

**Comment by ghidracadabra** [comment]
My first guess is that the decompiler is getting confused tracking the stack.  Are you certain that the signatures and calling conventions assigned to FUN_00401080 and FUN_00404ed (possibly by default) are correct?

Otherwise, we tend to ignore binaries submitted by users because reasons :)  However, this function looks pretty short and if you post its bytes we can take a closer look.  In the decompiler icon bar, there is a drop-down menu immediately to the right of the camera icon.  If you select "Debug Function Decompilation" it will write out an xml file. The bytes of the function will be near the top of that file.

**Comment by huettenhain** [comment]
Hey @ghidracadabra, that was right on the money, `FUN_00404ed` was a `malloc` and so it should have been `__cdecl` but Ghidra chose `__stdcall`. As you anticipated, this confused its tracking of the stack pointer, which was also visible in the listing view. After making that correction, the stack pointer was tracked correctly throughout the function and the decompiler was able to do its job marvellously:

![image](https://user-images.githubusercontent.com/11869704/124672843-0db13c80-deb8-11eb-975e-1dd6aab5dc58.png)

Lesson learned, tyvm :-).
