### ISSUE TITLE
Crash during ELF import: "Start address must be less than or equal to end address"

### ISSUE THREAD

**Issue by kiler129** [NationalSecurityAgency/ghidra#3198]
**Describe the bug**
Ghidra fails to import the file claiming offsets errors.

**To Reproduce**
1. Attempt to import the file with default settings:

<img width="509" alt="Screen Shot 2021-07-08 at 12 24 54 PM" src="https://user-images.githubusercontent.com/1227834/124965389-b14d3a80-dfe7-11eb-8ab5-6547ce5dba52.png">

The language is set to `x86:LE:64:default:gcc` and the format is naturally an ELF.

**Expected behavior**
File should be imported.

**Screenshots**
Log displayed by the loader:
```
Start address must be less than or equal to end address:  Start 001078f0   end = 001064f0
java.lang.IllegalArgumentException: Start address must be less than or equal to end address:  Start 001078f0   end = 001064f0
	at ghidra.program.model.address.AddressSet.checkValidRange(AddressSet.java:1206)
	at ghidra.program.model.address.AddressSet.add(AddressSet.java:170)
	at ghidra.program.model.address.AddressSet.addRange(AddressSet.java:231)
	at ghidra.program.model.address.AddressSet.<init>(AddressSet.java:79)
	at ghidra.app.util.bin.format.elf.ElfDefaultGotPltMarkup.disassemble(ElfDefaultGotPltMarkup.java:348)
	at ghidra.app.util.bin.format.elf.ElfDefaultGotPltMarkup.processLinkageTable(ElfDefaultGotPltMarkup.java:298)
	at ghidra.app.util.bin.format.elf.ElfDefaultGotPltMarkup.processDynamicPLT(ElfDefaultGotPltMarkup.java:278)
	at ghidra.app.util.bin.format.elf.ElfDefaultGotPltMarkup.processDynamicPLTGOT(ElfDefaultGotPltMarkup.java:157)
	at ghidra.app.util.bin.format.elf.ElfDefaultGotPltMarkup.process(ElfDefaultGotPltMarkup.java:61)
	at ghidra.app.util.bin.format.elf.extend.ElfLoadAdapter.processGotPlt(ElfLoadAdapter.java:301)
	at ghidra.app.util.opinion.ElfProgramBuilder.load(ElfProgramBuilder.java:170)
	at ghidra.app.util.opinion.ElfProgramBuilder.loadElf(ElfProgramBuilder.java:104)
	at ghidra.app.util.opinion.ElfLoader.load(ElfLoader.java:153)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:347)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:83)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:112)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:400)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:351)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
	at ghidra.util.task.Task.monitoredRun(Task.java:124)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

---------------------------------------------------
Build Date: 2021-Jun-21 1239 EDT
Ghidra Version: 10.0
Java Home: /Library/Java/JavaVirtualMachines/amazon-corretto-11.jdk/Contents/Home
JVM Version: Amazon.com Inc. 11.0.11
OS: Mac OS X 11.4 x86_64
Workstation: <censored>
```

**Attachments**
I'm unable to share the binary due to an NDA. However if anyone has questions about the ELF header of it I can provide information about it.

**Environment**
 - OS: macOS 11.4.0
 - Java Version: Amazon 11.0.11
 - Ghidra Version: 10.0 (build PUBLIC, 2021-Jun-21 1239 EDT)
 - Ghidra Origin: https://github.com/NationalSecurityAgency/ghidra/releases/tag/Ghidra_10.0_build

**Additional context**
The ELF is a linux `.so`. There may be a problem in the library loader as this happened to me more times with other binaries when attempting to use "Load External Libraries".

**Comment by ghidra1** [comment]
Since I don't have a sample which exhibits the GOT pointer ordering you are seeing, can you run from Eclipse with the following code change to the method `processDynamicPLT` within `ElfDefaultGotPltMarkup.java`:

Replace the following lines at line 271:
```
if (pltStart == null) {
	pltStart = ptr;
}
pltEnd = ptr;
```
with:
```
if (pltStart == null || pltStart.compareTo(ptr) < 0) {
	pltStart = ptr;
}
if (pltEnd == null || pltEnd.compareTo(ptr) > 0) {
	pltEnd = ptr;
}

```

**Comment by ghidra1** [comment]
If you can supply the offending binary or identify the specific Linux .so file that could expedite a proper fix

**Comment by ghidra1** [comment]
I think my suggested code change above is inadequate.  I believe your section headers have been stripped from the .so file which greatly complicates the proper identification of the `.got.plt` and `.got` memory bounds.  You can check this using `objdump -h <file>` which dumps the section headers if present.   I have identified a problem and dix for the proper bounds determination of the `.got.plt` when section headers are missing.   I am still trying to figure out how best to identify the `.plt` bounds in this case which also has issues.

**Comment by admalledd** [comment]
I am encountering the same error, and indeed the above didn't help. Just caused  another invalid AdressSet checkValidRange exception elsewhere.

For providing a .so/elf file, I know -I- am in the clear for the file I am about to mention, but since I am not a legal wizard I will merely provide high-level reproduction steps:

1. Download firmware for `Zyxel C3000Z` from https://www.centurylink.com/home/help/internet/network-upgrades.html 
2. Using `binwalk -e CZD005-4.16.011.bin` and including `jefferson` tool (for JFFS2) to extract the firmware image
3. find `libcms_cli.so` at `./_CZD005-4.16.011.bin.extracted/jffs2-root/fs_1/lib/libcms_cli.so`
4. The exact error will be `Start address must be less than or equal to end address:  Start 0002ba90   end = 0002529c` in my case.
  * In the case of tested code above, the "new" error down the line was `Start address must be less than or equal to end address:  Start 0002da38   end = 00015930` instead.

**Comment by ghidra1** [comment]
With the sections stripped there is no way to reliably detect the PLT which may or may not contain the external symbols depending upon the compiler conventions.  Our current implementation relies on the relocation table used to fixup the GOT and attempted to use the symbol associated with the GOT entries to locate the PLT.  While the code will discount symbols placed into the EXTERNAL block, the remaining GOT relocation symbols may not be limited to the PLT region making their use unreliable.  

To get you past your import obstacle, I suggest the following changes:

Replace the following lines of code at the end of the `ElfDefaultGotPltMarkup.processDynamicPLTGOT` method:
```
			long lastGotOffset = relocations[relocations.length - 1].getOffset();
			if (lastGotOffset < pltgot) {
				return;
			}

			Address gotStart = defaultSpace.getAddress(pltgot + imageBaseAdj);
			Address gotEnd = defaultSpace.getAddress(lastGotOffset + imageBaseAdj);

			processGOT(gotStart, gotEnd, monitor);
			processDynamicPLT(gotStart, gotEnd, monitor);
```
with...
```
			ElfSymbol[] symbols = associatedSymbolTable.getSymbols();

			long lastGotOffset = pltgot;
			for (ElfRelocation reloc : relocations) {
				long offset = reloc.getOffset();
				int symbolIndex = reloc.getSymbolIndex();
				if (symbolIndex != 0) {
					ElfSymbol elfSymbol = symbols[symbolIndex];
					// FIXME!!
					System.out.println("GOT sym: " + elfSymbol.getNameAsString() + " : 0x" +
						Integer.toHexString(elfSymbol.getInfo() & 0xff) + " : 0x" +
						Long.toHexString(offset));
				}
				else {
					System.out.println("GOT rel: 0x" + Long.toHexString(offset));
				}

				if (Long.compareUnsigned(offset, lastGotOffset) > 0) {
					lastGotOffset = offset;
				}
			}

			Address gotStart = defaultSpace.getAddress(pltgot + imageBaseAdj);
			Address gotEnd = defaultSpace.getAddress(lastGotOffset + imageBaseAdj);

			processGOT(gotStart, gotEnd, monitor);
			//processDynamicPLT(gotStart, gotEnd, monitor);
```
Note that the final call to `processDynamicPLT` has been disable.   While this will prevent the import from failing, it may leave the PLT thunks from being properly marked-up.  If you try this, please let me know how it turns out.

**Comment by ghidra1** [comment]
Oops, I forgot.  The GOT entries prior to having their relocation applied should point the head of the PLT.  I should be able to use this hopefully to identify the full bounds of the PLT region... stay tuned.
