### ISSUE TITLE
Certain modal windows can no longer be closed using Esc

### ISSUE THREAD

**Issue by huettenhain** [NationalSecurityAgency/ghidra#3235]
**Describe the bug**
It is no longer possible to exit certain modal windows using the <kbd>Esc</kbd> button.

**To Reproduce**
Edit the signature of any function and press <kbd>Esc</kbd>.

**Expected behavior**
The modal dialog closes, equivalent to pressing the button with caption "Cancel".

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: 11.0.9
 - Ghidra Version: 10.0.1-PUBLIC
 - Ghidra Origin: official ghidra-sre.org distro

**Comment by larsborn** [comment]
Not sure if this is related, but given that it's about dialogs and keycode handling I'll post it anyway (lmk if I should create a separate issue instead): It was possible to use the "Set Equate" with the Keyboard only:

* when it opens, start typing until the desired name shows up
* use the up/down arrow keys to select the entry
* hit return to close the dialog and confirm the selection

Since the recent update, the return key instead selects the next cell in the table (similar to the tab key).

**Comment by dragonmacher** [comment]
Any sense of when this was broken, whether by date, version or commit?

**Comment by huettenhain** [comment]
I went back to 9.2.4-PUBLIC and <kbd>Esc</kbd> does not close the modal in that version either. I am beginning to doubt my sanity. I suggest we treat this as a feature request, not a regression.

**Comment by dragonmacher** [comment]
> I am beginning to doubt my sanity. 

The flexibility of human memory makes the world more interesting.

**Comment by gtackett** [comment]
> > I am beginning to doubt my sanity.
> 
> The flexibility of human memory makes the world more interesting.

I’m pretty sure you’ve posted that here before. 😁

**Comment by dragonmacher** [comment]
> Since the recent update, the return key instead selects the next cell in the table (similar to the tab key).

This is an interesting regression that happened when another bug was fixed.  We should be able to fix this easily.

> I went back to 9.2.4-PUBLIC and Esc does not close the modal in that version either. I am beginning to doubt my sanity. I suggest we treat this as a feature request, not a regression.

It turns out, in most of the fields of this dialog you can press `ESC` to close the dialog.  For example, pressing escape closes the dialog if the cursor is in the function name text field.   The default focus for this dialog is the top text area.  The escape key does not work when focus is in that field.   We will look into this.
