### ISSUE TITLE
Ghidra Help Window is Frozen while a Ghidra Popup is Open

### ISSUE THREAD

**Issue by TheMatt2** [NationalSecurityAgency/ghidra#3260]
**Describe the bug**
If a popup window is open in Ghidra, either settings, loading screen, or script generated popup, then the Ghidra Help menu is frozen, and the user can not scroll, click, or search.

**To Reproduce**
1. Open a Project in Ghidra
2. Open the Ghidra Help Menu. Help -> Contents
3. Open Analysis Options. Analysis -> Auto Analyze
4. Observe that the Ghidra Help window is now unresponsive.

Various other steps can be done instead of opening the Analysis window. Including:
- Typing `popup("Hello")` into the Ghidra Python Interpreter
- File -> Open
- File -> Import File
- Edit -> Tool Options
- Edit -> Options for "name of current file"

**Expected behavior**
The help window should remain responsive at all times, so the user can have it open while working though other dialogs.

**Environment:**
- OS: Ubuntu 20.04.2 LTS
- Java Version: 11.0.11
- Ghidra Version: 10.0.1 PUBLIC 2021-Jul-8 1512 EDT
- Ghidra Origin: Github releases page

**Additional context**
I think this is a bug, not a feature request, since the Help window seems to work fine for some popup-like options.
For example
File -> Parse C Source
Allows the Help menu to keep working.

At the time the Help menu is frozen, so is the Ghidra Project Window and any active project windows. However, I wasn't sure if this was intentional, or a further issue.

**Comment by dragonmacher** [comment]
Thanks for the detailed info.

To work around this you can again press F1 with an open popup/modal dialog.   This will effectively reparent the help window over the new popup so that you can interact with the help window.   The downside of this is that the help window will be closed when you close the popup.

The desired behavior, as you mentioned, is to prevent the help window from being blocked at all times.   In the past, this was not possible in Java.   We will need to explore if we can change this with Java's new/updated modal dialog support.

**Comment by dragonmacher** [comment]
I looked into this.  We would have to change how our current system of showing modal dialogs works to make this happen.   This is a non-trivial change, with unforeseen potential fallout.    In the past, we had code that would re-open the help window if it had been closed by a modal dialog, as mentioned above.  We chose to remove this code due to the odd edge cases it produced.

For these reasons, we will not be implementing a fix for this ticket.

Another workaround is to run a second instance of Ghidra.  You can have a basic Ghidra running with no project open.   This will allow you to show the help window without it being blocked by the first running instance of Ghidra.    Using the help this way will prevent the help window from being blocked, allowing you to preserve your help content location.  However, you will not have any context-sensitive help by doing this, since the 2 running Ghidras do not communicate with each other.
