### ISSUE TITLE
Could connecting to ghidra server get a pop-up until sync/refresh is finished

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#3305]
**Is your feature request related to a problem? Please describe.**
When connecting to a Ghidra server the client will sync/refresh it's state with the server.  There is no graphical feedback that this is occurring except the GUI is locked until this finishes.

**Describe the solution you'd like**
Not really suggesting something stateful/progress bar/etc... but maybe just a pop-up with the dragon chomping on bits until the sync is finished

**Describe alternatives you've considered**
Typically when I'm disconnected I'll receive more than 1 pop-up related the ghidra server, so can click close which will be delayed and the click processed once the sync/refresh has finished.  When that window disappears I know I can use the tool again.

**Comment by dragonmacher** [comment]
Ideally the UI would never lockup.   We need to ensure that long running operations are run in the background, with a dialog where  needed, as you are suggesting.

**Comment by dragonmacher** [comment]
Will you please provide a jvm thread dump the next time the UI is frozen?  (Multiple separate dumps would be even better.) 

```
jstack
jps <pid>
```

**Comment by ghidra1** [comment]
How many files are in your project?

**Comment by mumbel** [comment]
Was hoping to get around to looking at jstack but didn't have time, hopefully tomorrow.

Probably around 375-400 @ghidra1

**Comment by mumbel** [comment]
[ghidraserver.txt](https://github.com/NationalSecurityAgency/ghidra/files/6957361/ghidraserver.txt)

@dragonmacher , sorry for the delay.  I did try this with 10.0.2 though now.   `jstack 30412` should split the multiple dumps.  one with password prompt open, a few during the whole sync/refresh process, and I had double clicked a firmware and it eventually triggered and you should come to the PPC:BE:32 task where the UI responds again.

**Comment by dragonmacher** [comment]
These are the 2 competing threads, as you may have seen:
```
"AWT-EventQueue-0" #30 prio=6 os_prio=0 cpu=4875.00ms elapsed=263.67s tid=0x000001defb51b000 nid=0x7f34 waiting for monitor entry  [0x000000cd1dbfd000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at ghidra.framework.data.GhidraFolderData.getFolderData(GhidraFolderData.java:744)
        - waiting to lock <0x00000005c84b5e28> (a ghidra.framework.store.local.IndexedV1LocalFileSystem)
        at ghidra.framework.data.GhidraFolder.getFolderData(GhidraFolder.java:102)
        at ghidra.framework.data.GhidraFolder.getFileData(GhidraFolder.java:79)
		...

"File System Listener" #51 daemon prio=6 os_prio=0 cpu=31.25ms elapsed=223.63s tid=0x000001de851f6000 nid=0x7e6c runnable  [0x000000cd1c7fd000]
		...
        at ghidra.framework.client.RepositoryAdapter.getItem(RepositoryAdapter.java:571)
        - locked <0x00000005c84c7a20> (a ghidra.framework.client.RepositoryServerAdapter)
        at ghidra.framework.store.remote.RemoteFileSystem.getItem(RemoteFileSystem.java:113)
        - locked <0x00000005c6558270> (a ghidra.framework.store.remote.RemoteFileSystem)
        at ghidra.framework.data.GhidraFileData.refresh(GhidraFileData.java:105)
        at ghidra.framework.data.GhidraFileData.<init>(GhidraFileData.java:91)
        at ghidra.framework.data.GhidraFolderData.addFileData(GhidraFolderData.java:790)
        at ghidra.framework.data.GhidraFolderData.refreshFiles(GhidraFolderData.java:618)
        at ghidra.framework.data.GhidraFolderData.refresh(GhidraFolderData.java:683)
        - locked <0x00000005c84b5e28> (a ghidra.framework.store.local.IndexedV1LocalFileSystem)
		...
```

The Swing thread is attempting to update the actions available in the Front End.   It ends up blocking on a folder while trying to get the folder's data, which is synchronized on the Ghidra file system.   Meanwhile, the file system listener is talking to the server while holding the file system lock.

We have faced the issue a few times in the past and have fixed them as we've found them.

Curious is this snippet:
```
	@Override
	public boolean isEnabledForContext(DomainFileContext context) {
		List<DomainFile> domainFiles = context.getSelectedFiles();
		for (DomainFile domainFile : domainFiles) {
			if (domainFile.canAddToRepository()) {
				return true; // Has at least one domain file that can be added to the repository.
			}
		}
		return false;
	}
```

This implies that you have a large number of files selected in the Front End, either in the tree or table.   Or, it could be that your project has a large number of files and updating them in the background thread takes long enough that even having just one selected file can block the UI long-term.

We should be able to come up with a couple different solutions to prevent this from happening without rewriting our locking mechanism.   The only tricky part for us is being able to reproduce the issue so that we can test our fixes.
