### ISSUE TITLE
support load into program for Elf-files

### ISSUE THREAD

**Issue by Buttje** [NationalSecurityAgency/ghidra#3307]
**Is your feature request related to a problem? Please describe.**
Embedded projects may consist of multiple binaries that share one memory space. Those binaries may be given as raw-binaries (supported), hex-files (supported) but also as Executable Load files. Executable Load files do have the nice advantage, compared to raw or hex, to contain symbol information.
Currently the ElfLoader class in ghidra.app.util.opinion does not support the 'LoadIntoProgram' feature.

**Describe the solution you'd like**
Please support the LoadIntoProgram feature in the ElfLoader class such as:
The Dialog 'File->Add To Program ...' offers Elf-Files  as input format (Combo Drop-Down box 'Format:')
Memory segments from the elf, that do not exist yet in the program, are created and added to the program.
Code and constants are loaded into the respective memory segments
Symbols are loaded from the elf-file 
Optionally re-trigger an analysis to resolve the new symbols

**Describe alternatives you've considered**
Create raw-images from the elf and import those.
Custom script to add symbols from the elf-file.

Thanks for your consideration,
Lutz

**Comment by c0d3z3r0** [comment]
+1

**Comment by ghidra1** [comment]
Sorry, this capability is not supported due to the various memory sections and load processing associated with a single image.  Mixing multiple loaded images together into Ghidra would require some form of isloation between memory  regions for each image and a big change to the ELF loader to handle such an organizational change.   Use of other loaded images in place of the EXTERNAL block would also be complicated due to the order of operation and relocation processing.  For this to work properly, all image dependencies would need to be loaded before any relocation processing is performed which would be a big change to the import process and loader implementation.

**Comment by c0d3z3r0** [comment]
Well, if that way is too complicated, what about providing a way of merging two projects? That's basically what I did by hand. See https://github.com/NationalSecurityAgency/ghidra/discussions/6814

**Comment by ghidra1** [comment]
That may not work well due to memory block conflicts, relocation processing and the placement of the fake EXTERNAL block.   This may have worked for your case #6814 becuase I suspect you did not have relocations or dynamic library linkages via a GOT, PLT and EXTERNAL block.  I assume your external function/data linkages were all fixed at compile time via predefined locations.  It is possible for simple fixed addressing cases such as yours you may be able to export each project program to Ghidra XML the report all of them with add-to-program using XML import.  If you do this I recommend it be done before any analysis or disassembly with all memeory blocks at the correct placement.

**Comment by c0d3z3r0** [comment]
> That will not work for the general ELF case due to memory block conflicts, relocation processing and the placement of the fake EXTERNAL block. This may have worked for your case #6814 because I suspect you did not have relocations or dynamic library linkages via a GOT, PLT and EXTERNAL block. I assume your external function/data linkages were all fixed at compile time via predefined locations.

Agreed, this only works well without dynamic linkage. @Buttje's and my case is about bare metal firmware images. There is no dynamic linking AFAICT.

> It is possible for simple fixed addressing cases such as yours you may be able to export each project program to Ghidra XML then re-import all of them with XML import add-to-program into a combined program file. If you do this I recommend it be done before any analysis or disassembly with all memeory blocks at the correct placement.

Ah great, I just tried this and this is *way* more convenient than doing it manually. Thank you!
