### ISSUE TITLE
Low-level Error: Trying to alter definition of type: Alignment

### ISSUE THREAD

**Issue by aboood40091** [NationalSecurityAgency/ghidra#3399]
I tried to upgrade to release 10.0.2 to stay up-to-date from a project I was working on in release 9.1 and now I get the error `Low-level Error: Trying to alter definition of type: Alignment` in the decompiler in any function which uses a structure that was set to use the `Alignment` type back in 9.1.

Example:
Function in 10.0.2:
![image](https://user-images.githubusercontent.com/10743814/132101460-c3b4a83a-492b-48e9-b276-8ffc9cdb7038.png)
Function in 9.1:
![image](https://user-images.githubusercontent.com/10743814/132101476-1d310239-2f68-4f35-b484-2568e0908d2f.png)

However, I noticed something I initially believed to be related (and did in the end turn out to be related), which is that whenever I use a built-in type, Ghidra creates a copy of it in my program, as follows:
![image](https://user-images.githubusercontent.com/10743814/132101130-1a87b0c2-64f7-4864-a8df-2c00614f8036.png)

Deleting the `Alignment` type copy "fixes" the error, but now every instance `Alignment` was used in is changed to `undefined` fields and I would like to avoid that since I used the type excessively and Ghidra does not provide any (easy) method to swap data types. The issue does not happen again if I use the `Alignment` type after deleting the 9.1 type copy.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: 11.0.2
 - Ghidra Version: 10.0.2
 - Ghidra Origin: GitHub Releases

**Comment by quietust** [comment]
Have you tried dragging the "original" Alignment type onto the copy (or vice-versa)?

**Comment by aboood40091** [comment]
> Have you tried dragging the "original" Alignment type onto the copy (or vice-versa)?

Now I get `Low-level Error: Bad structure definition` in decompiler.
I also get the following exception when I try editing the structure I showed before in the original message:
![image](https://user-images.githubusercontent.com/10743814/132106595-b7090e46-0db5-4a70-a564-2c7546f85fae.png)

**Comment by ghidra1** [comment]
In your structure images it would appear that your structure definition if unchanged.  I suspect the structure definition had upgraded fine and that the issue is related to possible decompiler changes that have impacted how this "black-box" dynamic datatype was treated by decompiler.  Deleting the Alignment type from the program will modify all uses of it within the program.  I don't think that is the answer, although avoiding its use within Structures should be considered.  If you know a full Structure definition you should consider enabling packing which will perform the alignment for you.

It is unclear what the decompiler error is really indicating.   May need @caheckman to way-in on this.

Are you able to attach your original 9.1 program before upgrade as a Ghidra Zip (*gzf) file?  May not be able resolve this without debugging it.

**Comment by ghidra1** [comment]
I think @caheckman and I have identified the issue in the current code which could cause the symptoms you are seeing.  If the decompiler, for a single function, encounters multiple uses of the Alignment datatype with different size (e.g., 1, 3) it will result in this error.  The issue is not with your datatype definition other than using the Alignment datatype which is generally not done within Structures - but it should have worked.  We will move forward with a fix but you may want to avoid using the Alignment datatype to avoid the issue for the time being.

**Comment by aboood40091** [comment]
Oh, I forgot to reply to this. Thank you for checking out the issue.
Do you still need the file from 9.1?

**Comment by ghidra1** [comment]
We do not need the file if you can verify that all is well in the latest 10.0.4 release.
