### ISSUE TITLE
RecoverClassesFromRTTIScript: Deduce base class function types/names from inheriting ones

### ISSUE THREAD

**Issue by jrmuizel** [NationalSecurityAgency/ghidra#3417]
```c++
struct Bar {
        virtual int a(int x) = 0;
        virtual int b(double x, double y) = 0;
        virtual int get() = 0;
};

struct Foo : public Bar {
        int a(int ax) override {
                x = ax;
                return x;
        }
        int b(double ax, double ay) override {
                x = ax;
                y = ay;
                return y;
        }
        virtual int get() {
                return y;
        }
        int x;
        int y;
};

int main() {
        Bar* b = new Foo;
        b->a(4);
        b->b(6, 7);
        return b->get();
}
```
Compiled with `cl.exe /Z7 /MD` is currently decompiled as something like:
```c
int main(int _Argc,char **_Argv,char **_Env)
{
  undefined uVar1;
  Foo *this;
  undefined7 extraout_var;
  undefined8 extraout_XMM0_Qa;
  Foo *local_18;
  
  this = (Foo *)operator_new(0x10);
  if (this == (Foo *)0x0) {
    local_18 = (Foo *)0x0;
  }
  else {
    local_18 = (Foo *)Foo::Foo(this);
  }
  (*((local_18->Bar).vftablePtr)->vfunction1)(local_18,4);
  (*((local_18->Bar).vftablePtr)->vfunction2)
            (extraout_XMM0_Qa,0x4018000000000000,0x401c000000000000,local_18);
  uVar1 = (*((local_18->Bar).vftablePtr)->vfunction3)(local_18);
  return (int)CONCAT71(extraout_var,uVar1);
}
```

It should be possible to improve the info in the Bar vtable struct by using the types and names from the Foo vtable struct.

@ghidra007

**Comment by ghidra007** [comment]
Thanks for the suggestion. The script currently only figures out which class the functions in the vftable originated in if they are inherited. I'll look into whether it would be feasible to know which signature to copy since one may have better info than the other but it may not be obvious which and I wouldn't want to propagate worse info if the parent signature were not as flushed out as the child. I suppose if either has types that are not undefined or names that are not default they could be propagated. There are two scripts that do what you want if a user changes the function signatures or function definitions after running the recover classes script. They are called ApplyClassFunctionSignatureUpdatesScript and ApplyClassFunctionDefinitionUpdatesScript.

**Comment by ghidra007** [comment]
In the above case, can you show me what the definition of the Foo vftable struct is?

**Comment by jrmuizel** [comment]
Foo and Bar look like this when run with debug info:
```
Foo
0    8    int a(Foo * this, int param_1) *    a *    a    Foo virtual function #1
8    8    int b(Foo * this, double param_1, double param_2) *    b *    b    Foo virtual function #2
16    8    int get(Foo * this) *    get *    get    Foo virtual function #3


Bar
0    8    undefined _purecall(void) *    _purecall *    vfunction1    VCRUNTIME140.DLL Bar pure virtual function #1
8    8    undefined _purecall(void) *    _purecall *    vfunction2    VCRUNTIME140.DLL Bar pure virtual function #2
16    8    undefined _purecall(void) *    _purecall *    vfunction3    VCRUNTIME140.DLL Bar pure virtual function #3
```

I've attached test.exe along with test.pdb which I applied before running analysis.
[class-analyzer.zip](https://github.com/NationalSecurityAgency/ghidra/files/7187586/class-analyzer.zip)

**Comment by ghidra007** [comment]
Ok. Thanks!

**Comment by ghidra007** [comment]
10.1 should address the issues you were seeing above.
