### ISSUE TITLE
Defined calling conventions missing in function definition.

### ISSUE THREAD

**Issue by Marisa-Chan** [NationalSecurityAgency/ghidra#3456]
**Describe the bug**
Defined calling conventions not in function definition list.

**To Reproduce**
1. Import or use not standard calling convention(from .cspec)
2. Create function definition with it (it's not listed)

Also try to "override signature" in calling place, but seems it's not work(because if it work then it will be informed that ECX not touched) and on next try of "override signature" it's still "__cdecl"

![Снимок экрана_2021-09-27_15-58-48](https://user-images.githubusercontent.com/431509/134879719-460b0040-f81a-4d5d-bf67-b3375e86664c.png)
![Снимок экрана_2021-09-27_16-04-45](https://user-images.githubusercontent.com/431509/134879735-96904aa5-3091-472d-89c6-f5c3c8883f2f.png)

**Environment (please complete the following information):**
 - OS: Archlinux
 - Java Version: 16.0.2
 - Ghidra Version: 10.0.3

**Comment by ghidra1** [comment]
Function Definition datatypes are currently limited to the enumerated set defined by the GenericCallingConvention enum.  Call overrides are unfortunately limited by this as well since that mechanism relies on such a datatype definition.  We recognize the limitations of this and is our intention to improve this in the future.  As this a design limitation and already on our radar I am going to close this ticket.  Unfortunately, a specific release for such a change has not yet been identified.
