### ISSUE TITLE
unable to run ghidra in mac os 

### ISSUE THREAD

**Issue by brahmashwiniregonda** [NationalSecurityAgency/ghidra#3477]
<img width="235" alt="Screenshot 2021-10-05 at 17 50 09" src="https://user-images.githubusercontent.com/79544357/136057889-002c5896-9f09-4a5d-b9df-d184be342cf0.png">

**Comment by ryanmkurtz** [comment]
If you go into your "Security & Privacy" settings, can you allow the Ghidra files to run as shown here?

https://github.com/NationalSecurityAgency/ghidra/issues/1559#issuecomment-895972722

**Comment by microlaser** [comment]
I got it to run in three steps.

1) Install JDK
2) ctl click and open ghidraRun
3) Navigate to ./Ghidra/Features/Decompiler/os/osx64 and ctl click Decompiler

These three steps will allow you to decompile on MacOS.  There are other features of Ghidra that may have to be enabled individually, like this because of the structure of MacOS security features.  In my humble opinion, this is not a bug in the Ghidra code, this is a result of the built-in security features of MacOS.  We don't need to change any code in my opinion, but rather expand the documentation of MacOS.  I would be willing to prepare documentation for Ghidra for OSX if the community would find it helpful.  I am new to GitHub and have mostly just written bash scripts, if someone would like me to do this please provide gentle guidance and I will document the steps for the communtity.  It would be valuable because MacOS is an ideal sandbox for analyzing potential bad Windows executables.

**Comment by ryanmkurtz** [comment]
I'm going to go ahead and close this since there isn't anything in Ghidra we need to fix.  Also be aware that when 10.1 releases you'll be able to run `support/buildNatives` to produce your own trusted native binaries that won't trigger Gatekeeper (assuming you have the necessary build tools installed).

**Comment by Darkcast** [comment]
not the best option but it works 
sudo spctl --master-disable
