### ISSUE TITLE
CodeBlockIterator does not extend iterator/iterable

### ISSUE THREAD

**Issue by wconlon** [NationalSecurityAgency/ghidra#3478]
**Describe the bug**
CodeBlockIterator cannot be used in for each loops as it does not properly implement Iterable

**Comment by astrelsky** [comment]
This is because it throws `CancelledException`. That being said it would be great to be able to use things that throw said exception in such cases as well as in streams.

**Comment by wconlon** [comment]
Why does this throw that exception but not the more commonly used iterators such as `InstructionIterator`? Apologies if this is a stupid question, I am new to using this API.

**Comment by astrelsky** [comment]
> > Why does this throw that exception but not the more commonly used iterators such as `InstructionIterator`? Apologies if this is a stupid question, I am new to using this API.
> 
> It is a good question.   Someone years ago thought it was more convenient to add the `CancelledException` to this interface.  The issue is that is presupposes the user of a `TaskMonitor`, which is not used in the interface.  This is a bit odd.   My personal feeling is that it was a mistake to add this exception to this interface.    However, it does not seem worth removing it at this point.
> 
> I have an addition coming to the interface that will allow it to implement the `Iterable` interface and thus be used in `foreach` loops.

Oh, you're going to take advantage of `Iterator<T> iterator()` and return one that doesn't throw aren't you? If so that's a pretty clever solution.

**Comment by ghidra1** [comment]
> Why does this throw that exception but not the more commonly used iterators such as `InstructionIterator`? Apologies if this is a stupid question, I am new to using this API.

The reason for `CancelledException` is the potential for long running computations for each step of the iterator.   The block determinations are not done up-front and are done as needed.  A `TaskMonitor` is supplied during the instantiation of the iterator from a block model providing a means of cancellation should a call to `hasNext()` run on for too long.  The exception allows for a distinction to be made between a successful completion of the iteration versus one that has failed to complete because it was cancelled.
