### ISSUE TITLE
aarch64: Wrong decompilation for 128bit load

### ISSUE THREAD

**Issue by rfalke** [NationalSecurityAgency/ghidra#3492]
**Describe the bug**
Wrong decompilation for 128bit load

**To Reproduce**
1. Decompile `_full_write_with_str ()` from https://github.com/rfalke/decompiler-subjects/blob/master/from_holdec/arm64_stX/arm64_macho/subject.exe

**Expected behavior**

Expected output is:
```
...
  param_1[1] = 0x1f1e1d1c1b1a1918;
  *param_1 = 0x1716151413121110;
...
```

Actual output:
```
...
  param_1[1] = 0x1f1e1d1c1b1a1918;
  *param_1 = 0x1f1e1d1c13121110;
...
```

Objdump:
```
0000000100002eb0 <_full_write_with_str>:
100002eb0: 00 8c 20 6e  cmeq.16b        v0, v0, v0
100002eb4: 21 8c 21 6e  cmeq.16b        v1, v1, v1
100002eb8: 42 8c 22 6e  cmeq.16b        v2, v2, v2
100002ebc: 63 8c 23 6e  cmeq.16b        v3, v3, v3
100002ec0: 03 22 82 d2  mov     x3, #4368
100002ec4: 43 62 a2 f2  movk    x3, #4882, lsl #16
100002ec8: 83 a2 c2 f2  movk    x3, #5396, lsl #32
100002ecc: c3 e2 e2 f2  movk    x3, #5910, lsl #48
100002ed0: 60 00 67 9e  fmov    d0, x3
100002ed4: 03 23 83 d2  mov     x3, #6424
100002ed8: 43 63 a3 f2  movk    x3, #6938, lsl #16
100002edc: 83 a3 c3 f2  movk    x3, #7452, lsl #32
100002ee0: c3 e3 e3 f2  movk    x3, #7966, lsl #48
100002ee4: 60 00 af 9e  fmov.d  v0[1], x3
100002ee8: 04 e6 00 4f  movi.16b        v4, #16
100002eec: 01 84 24 4e  add.16b v1, v0, v4
100002ef0: 22 84 24 4e  add.16b v2, v1, v4
100002ef4: 43 84 24 4e  add.16b v3, v2, v4
100002ef8: 00 00 80 3d  str     q0, [x0]
100002efc: e0 03 1f 2a  mov     w0, wzr
100002f00: c0 03 5f d6  ret
```

**Environment (please complete the following information):**
 - OS: Linux
 - Java Version: 11.0
 - Ghidra Version: 10.0.4
 - Ghidra Origin: GitHub zip

**Comment by CmP-lt** [comment]
This has something to do with `q0`/`v0` register being output varnode of `CALLOTHER` operation (which is how `cmeq` is currently implemented in pcode), because replacing `cmeq.16b v0, v0, v0` instruction with `cmeq.16b v1, v0, v0` (or any that doesn't affect contents of `v0` register) results in correct decompilation of the code fragment of interest.

**Comment by GhidorahRex** [comment]
@CmP-lt I think you're correct here, although I'm not sure why.

I have a temporary fix by replacing the pcodeop in the cmeq instruction at AARCH64neon.sinc, line 1337 with an actual implementation here that will deal with this specific issue, but it won't fix the more systemic issue:

```
:cmeq Rd_VPR128.16B, Rn_VPR128.16B, Rm_VPR128.16B
is b_31=0 & b_30=1 & b_2429=0b101110 & b_2223=0b00 & b_21=1 & b_1015=0b100011 & Rd_VPR128.16B & Rn_VPR128.16B & Rm_VPR128.16B & Rd_VPR128 & Rn_VPR128 & Rm_VPR128 & Zd
{
    local result:1 = ~0;

	Rd_VPR128[0,8]   = result * (Rn_VPR128[0,8] == Rm_VPR128[0,8]);
	Rd_VPR128[8,8]   = result * (Rn_VPR128[8,8] == Rm_VPR128[1,8]);
	Rd_VPR128[16,8]  = result * (Rn_VPR128[16,8] == Rm_VPR128[16,8]);
	Rd_VPR128[24,8]  = result * (Rn_VPR128[24,8] == Rm_VPR128[24,8]);
	Rd_VPR128[32,8]  = result * (Rn_VPR128[32,8] == Rm_VPR128[32,8]);
	Rd_VPR128[40,8]  = result * (Rn_VPR128[40,8] == Rm_VPR128[40,8]);
	Rd_VPR128[48,8]  = result * (Rn_VPR128[48,8] == Rm_VPR128[48,8]);
	Rd_VPR128[56,8]  = result * (Rn_VPR128[56,8] == Rm_VPR128[56,8]);
	Rd_VPR128[64,8]  = result * (Rn_VPR128[64,8] == Rm_VPR128[64,8]);
	Rd_VPR128[72,8]  = result * (Rn_VPR128[72,8] == Rm_VPR128[72,8]);
	Rd_VPR128[80,8]  = result * (Rn_VPR128[80,8] == Rm_VPR128[80,8]);
	Rd_VPR128[88,8]  = result * (Rn_VPR128[88,8] == Rm_VPR128[88,8]);
	Rd_VPR128[96,8]  = result * (Rn_VPR128[96,8] == Rm_VPR128[96,8]);
	Rd_VPR128[104,8] = result * (Rn_VPR128[104,8] == Rm_VPR128[104,8]);
	Rd_VPR128[112,8] = result * (Rn_VPR128[112,8] == Rm_VPR128[112,8]);
	Rd_VPR128[120,8] = result * (Rn_VPR128[120,8] == Rm_VPR128[120,8]);

	#Rd_VPR128.16B = NEON_cmeq(Rn_VPR128.16B, Rm_VPR128.16B, 1:1);
}
```

**Comment by CmP-lt** [comment]
Another observation is that replacing first `cmeq` instruction with any currently unimplemented instruction that has `d0` or `s0` or `h0` as it's output varnode also results in correct decompilation of code fragment of interest. This may, but not necessarily does, indicate that the issue in decompiler is caused by output varnode of `CALLOTHER` operation (or not only) having size of more than 8 bytes.

@GhidorahRex adding actual implementation for `cmeq` instruction is undoubtedly useful, but I think that it shouldn't be considered a proper fix for this issue, because the root cause of it is somewhere in decompiler's code (meaning that the issue might be reproducible on different architectures).
