### ISSUE TITLE
The NSA cannot license Ghidra outside of the public domain

### ISSUE THREAD

**Issue by ryazo** [NationalSecurityAgency/ghidra#351]
https://www.usa.gov/government-works#item-206099

Under US law, federal government works cannot be copyrighted. It may be that Ghidra contains code licensed under the Apache license, but it would be misleading to suggest that it would be the US government to deal with it.

**Comment by mumbel** [comment]
Dup #3 looks like

**Comment by d-millar** [comment]
> Dup #3 looks like

Yes and @ctubbsii's comment directly addresses this issue.  If it helps clarify the issue, however, keep in mind that licensing requirements are different for works produced exclusively by government employees, works produced under contract to the government, and works produced by mixed teams (government/contractor).  The latter is particularly complicated when specific code cannot be clearly identified by its origin.   That said, will close this out unless there are objections.

**Comment by ryazo** [comment]
There is no real objection, but the licensing of the project is unclear to contributors.


The contributing.md: 

> Furthermore, your contributing to this project does not create an employer-employee relationship between the United States ("U.S.") Government and the contributor.

Which contradicts your statement @d-millar :

>If it helps clarify the issue, however, keep in mind that licensing requirements are different for works produced exclusively by government employees, works produced under contract to the government, and works produced by mixed teams (government/contractor).

I doubt the NSA is in the business of employing trial lawyers, but instead attorneys for their legal interpretations, but at the very least this project doesn’t really represent the NSA well if no one is familiar with copyright law and it is under shaky legal ground.

Several parts seem to contradict the concept that the NSA can actually enforce it (by rejecting code) beyond saying something along the lines of “you may not sue others for reusing this code or enforcing patent claims on others using code you contributed.”

If the NSA does reject code, it would indicate some employer-employee relationship.

I suggest hiring new attorneys.

**Comment by d-millar** [comment]
@ryazo: Correct me if I am wrong, but I think you misunderstood my point - the original code base, prior to its release, was written by a mixture of direct government employees and government contractors.  The firms employing those contractors have IP in the project.  Because the IP is mixed, the Apache license may be legitimately applied.  I am making no comment whatsoever regarding contributors going forward post-release and/or their status relative to the government.

**Comment by ryazo** [comment]
Neither am I, but in that case, the government would be violating copyright law if it doesn’t credit the owners of the IP. 

Which is why contribution agreements exist.

**Comment by ctubbsii** [comment]
@ryazo I think there is a misunderstanding, but I can't tell where it is occurring. Please allow me an attempt to clarify (apologies for the length; I simply wish to thoroughly clear up any possible confusion):

### Re: *"The NSA cannot license Ghidra outside of the public domain"*

According to https://www.usa.gov/government-works#item-206099 , which you linked:

> Works prepared for the U.S. government by independent contractors may be protected by copyright, which may be owned by the independent contractor or by the U.S. government.

As I understand it, this applies to Ghidra and would make *"The NSA cannot license Ghidra outside of the public domain"* an untrue statement.

According to the above, those portions of Ghidra developed by such contractors may be "owned" (in the copyright sense) by either the respective contractor or the U.S. government. In either case, those portions are made available under the terms of the Apache License, Version 2, according to the project's LICENSE.

### Re: mixed copyright / public domain

While Ghidra as a whole is licensed under the terms of the Apache License, it is possible (although I don't know if this is the case) that isolated portions of Ghidra are "public domain" within the U.S. (but not necessarily in all worldwide jurisdictions where this project's code is now available), because they represent intellectual property wholly created by the U.S. government and do not represent the creative works of any contractor. However, I doubt it would be easy to identify and separate those portions from the rest of the code.

Even if it were the case that such portions exist, and are possible to identify and separate, I'm not sure what the benefit of doing so would be, because:

1. it's not likely that those portions would be very useful without the rest of Ghidra, and
2. the Apache License has *extremely* permissive terms and there are very few things you could do under "public domain" that you can't already do under the Apache License

### Re: contributing back and employer-employee relationships

Furthermore, as with other open source projects, you are free, and welcome, to offer contributions back to the maintainers (see section 5 of the Apache License), which they are free to accept or reject at their discretion. There is no obligation by the maintainers to accept a contribution, and the act of offering one, whether it is accepted or not, does not create an employer-employee relationship, as indicated in the contributor guide.

You are also free to fork the project and apply your own modifications, without explicitly offering them back to this project's maintainers, and to use the project's source code in other ways permissible under the Apache License. You do not need to have your modifications accepted by this project's maintainers in order for you to exercise your right to modify and redistribute the software under the terms of the Apache License.

### IANAL Disclaimer

Of course, I'm not a lawyer, and certainly not *your* lawyer, so you should seek your own legal counsel if you need legal advice working with open source projects such as Ghidra.

### Conclusion

I hope that clarifies things a bit, but if you still have confusion about whether the government can, or should, release code under any particular license terms, I would urge you to have that conversation in a more appropriate venue. This is an issue tracker for the Ghidra project, and while there is some room for discussion and answering questions about licenses, and even for suggesting changes to the README, CONTRIBUTING guide, or other documentation, this is **not** a legal forum or a place to debate legal issues, especially when those issues are well outside the scope of the Ghidra project.

**Comment by ctubbsii** [comment]
> Neither am I, but in that case, the government would be violating copyright law if it doesn’t credit the owners of the IP.
> 
> Which is why contribution agreements exist.

If your main concern is the preservation of copyright notices that a contributor includes, the Apache License for this project already specifies that your contributions (unless otherwise stated) fall under the terms of that license (section 5), and that license's terms include the obligation (in section 4) to preserve attributions and copyright notices that the author of the contribution had included.
