### ISSUE TITLE
Auto analysis hangs after ghidra.util.exception.UnableToSwingException, unable to interact with anything after.

### ISSUE THREAD

**Issue by snnaakee** [NationalSecurityAgency/ghidra#3525]
**Describe the bug**
Near 48 hours of auto analyze with DWARF option only, Ghidra failed at 87% of DWARF - Creating funcs & symbols, prompted few error logs, then left the auto analyze resuming, been unable to stop it, I was unable to save the progress up to those 48 hours.
The binary is an ELF executable, 365 MB, PowerPC 64-bit big-endian w/Altivec, G2 and contains 10M debug symbols which is why I'm trying to extract the DWARF information.

**To Reproduce**
1. Import 365 MB, PowerPC 64-bit big-endian w/Altivec, G2 with 10M symbols.
2. Click auto analyze
3. Near the end of the DWARF analysis, an error dialog pops up saying an unexpected error has occurred, the progress bar at the bottom right of the GUI is gone at this point.
4. Auto analysis is running stateless now, the auto analysis window is left open, you can't close/stop it and looking at error(s) is the only task you'll be able to do from now.

**Expected behavior**
The auto analysis closes and we should be able to resume our session without loosing progresses.

**Attachments**
Error logs: [ghidra_errorlogs.txt](https://github.com/NationalSecurityAgency/ghidra/files/7379229/ghidra_errorlogs.txt)

**Environment**
 - OS: Windows 10 64-bit
 - Java Version: OpenJDK version "11.0.12"
 - Ghidra Version: Ghidra 10.0.2 PUBLIC
 - Ghidra Origin: ghidra-sre.org

**Comment by astrelsky** [comment]
JDK 11 is a requirement for Ghidra. It shouldn't be able to run on java 8.

**Comment by dev747368** [comment]
When the DWARF analyzer is doing operations that generate a lot of Ghidra UI events, they can cause updates in slow UI components.  The DWARF analyzer will try to pace itself by scheduling an empty dummy method to run on the Swing thread, which is what I'm seeing on your stack trace.

If your slow down is caused by UI components repainting / accessing data due to events generated by the DWARF import, a good hack to make things run faster is to close just about all UI components in your CodeBrowser tool.... the Symbol Tree, the DataType manager, whatever else you may have configured in the tool.  When they are open (even if not displayed) they have to respond to Ghidra update events as they happen, which can cause contention for the cpu and database.

**Comment by snnaakee** [comment]
> > JDK 11 is a requirement for Ghidra. It shouldn't be able to run on java 8.
> 
> Thank you for pointing it out. I'm not proud of it.
> 
> I'm running a new analysis with OpenJDK version 11.0.2, I also set the timeout in launch.properties by adding: VMARGS=-Dghidra.util.Swing.timeout.seconds=3600 and hoping Ghidra will get further this time.

As I said I started a second attempt. This time with the headless analyzer and it finished minutes ago.
I'm dropping the logs, even though I'm not sure if they'd be relevant for this issue.
[ghidra_headlessAnalysis_logs.txt](https://github.com/NationalSecurityAgency/ghidra/files/7387659/ghidra_headlessAnalysis_logs.txt)


DWARF has been skipped, probably because of the default debug item count limit. I'm now running the DWARF analysis only from the CodeBrowser, extended the item count limit, removed all non-essential windows and with the line added in the launch.properties.

I'll be back with the result in less than 48 hours, the time it'll take to reach the state where the errors occurred.
