### ISSUE TITLE
ghidra.app.cmd.function.CreateFunctionCmd#applyTo (and thus FlatAPI.createFunction()) fail silently when ran outside a DB Transaction

### ISSUE THREAD

**Issue by fmagin** [NationalSecurityAgency/ghidra#3610]
**Describe the bug**

`FlatAPI.createFunction()` fails silently when ran outside a DB Transaction and simply returns `null` instead of the typical `NoTransactionException: Transaction has not been started`

**To Reproduce**

This is arguably kinda tricky to reproduce because all the contexts in which it is easy to simply run that command like the Jython Shell or a GhidraScript implicitly get wrapped in a DB transaction. I ran into this while using my [plugin for Jupyter Kotlin](https://github.com/GhidraJupyter/ghidra-jupyter-kotlin) integration, which does not wrap every executed snippet in a transaction. 

**Expected behavior**
`ghidra.app.cmd.function.CreateFunctionCmd#applyTo` should not catch the `NoTransactionException` in the generic `catch (Exception e) {}` block and instead reraise it to make sure the caller has clear feedback what went wrong in this case.

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
 - OS: Linux
 - Java Version: 11
 - Ghidra Version: Ghidra 10.1 DEV, but the code is the same for Ghidra 10.0.4 and probably all prior versions
 - Ghidra Origin: 10.1 DEV was locally built, Ghidra 10.0.4 is the GitHub release

**Additional context**
I am aware that calling the FlatAPI from some code that doesn't implicitly wrap it in a DB transaction is probably rare, but it could be more common to use the `CreateFunctionCmd` in such a context. This overall isn't a major bug, and if changing this would have consequences I am not aware of it might not be worth it anymore (might break existing code relying on that behavior?)

**Comment by dragonmacher** [comment]
A cursory glance suggests we should improve error handling here.   The `createFunction()` call does not make any effort to report error messages if the command fails.  At the very least, the error message should be logged.   Whether or not to propagate exceptions would require a more careful analysis.  I personally prefer code that fails fast and directly.

**Comment by dragonmacher** [comment]
>  This overall isn't a major bug, and if changing this would have consequences I am not aware of it might not be worth it anymore (might break existing code relying on that behavior?)

I took another look at this.  The way Ghidra uses command objects had dictated how we approach error handling.  The command objects are written assuming that the external world has already started transactions.  Commands are usually run inside of a Tool, the script engine or in tests.  Thus, the exception handling in the commands was implemented to not propagate exceptions.  Rather, the status of the command is updated with the text of any exceptions that have happened.  This allows clients to check the status and report information as needed.  In this light, it does not seem worth the effort to revisit command exception handling, as it would require to review all command classes in Ghidra.

The outlier in this conversation is the `FlatProgramAPI`.   That class assumes that the client has handled transactions, but it does not explicitly state this in the documentation.   The obvious problem with that class is the the client does not have access to the command that was used and thus cannot check the status of the command.   It seems to me, at the very least, that class should have reported/logged errors so that information was not lost.   As you can imagine, changing a public-facing class such as that should not be undertaken lightly.

You can certainly continue to use the `FlatProgramAPI`, along with this obvious limitation.  A better solution may be for you to start using the command classes directly, essentially bypassing the `FlatProgramAPI`.   If you do that, then you can manage transactions and command results/status directly.

**Comment by fmagin** [comment]
@dragonmacher  Thanks for the detailed response!
This definitely sounds like "might not be worth it anymore" to me. I was not aware that the Commands are assumed to be run in a context with a transaction, I am curious if and where that is made explicit in the doc?

My scenario is very specific anyway, and doesn't only concern me personally. The plugin I wrote implements an additional REPL and I made the choice that transactions should be made explicitly. This is partly opinionated preference, but also somewhat of a technical limitation of the design.

What I didn't account for is that Commands and `FlatProgramAPI` silently fail, so it is non obvious for someone else using the REPL that the lack of a transaction is the fault. My REPL allows running a transaction by basically marking a code block as code that should be run as a transaction:
```kotlin
currentProgram.runTransaction {
     // Everything in this block is part of the transaction
     createFunction(currentAddress, null)
}
```
The problem is that running `createFunction(currentAddress, null)` outside of a transaction fails so silently, and someone just playing around with the REPL will not realize why this failed.

But if the `FlatAPI` and any Commands are explicitly intended to be used only in transaction anyway, then I'll find some way to work around this for my plugin. Either make it clear in my documentation that this is needed, or find out how I can wrap each executed snippet in a transaction by default, like the Jython shell does it.
