### ISSUE TITLE
Disassembly of kernel modules

### ISSUE THREAD

**Issue by RamenN00dlez** [NationalSecurityAgency/ghidra#3638]
**Describe the bug**
When decompiling/disassembling a kernel module binary, there will be 0x40 bytes of metadata at the start rather than the actual base of the ELF.

**To reproduce**
To reproduce, just decompile some *.ko kernel module and observe all addresses in the binary are offset by +0x40 within the disassembly field.

**Expected behavior**
It seems the first function should be at the base rather than the metadata.

**Environment:**
 - OS: Windows 10
 - Java Version: 1.8
 - Ghidra Version: 10.0.2
 - Ghidra Origin: ghidra-sre.org

**Comment by ryanmkurtz** [comment]
I'm having trouble seeing what you are describing in the kernel modules I'm looking at.  When you say "there will be 0x40 bytes of metadata at the start"...at the start of what?

**Comment by RamenN00dlez** [comment]
At the start of the disassembly window.
I say there is an unwanted 0x40 bytes because when forming exploit payloads based on the addresses listed in ghidra, they will always be 0x40 bytes off the desired target.
I also call it metadata (i'm not sure if that's exactly what it is but it seems to fit my definition of it at least) because it will have some amount of data at the base address that is not addressable in the actual active module:
![image](https://user-images.githubusercontent.com/42827767/142493074-6949b2e7-90a1-422a-9eb6-0d6b2f88ce91.png)

**Comment by ryanmkurtz** [comment]
Thanks, we are looking into it.

**Comment by ghidra1** [comment]
@RamenN00dlez , what you are referring to as metadata corresponds to a .note section which has the SHF_ALLOC flag bit set which indicates that it should be loaded.  The header indicates an offset of 0x40 for this section, however since Ghidra uses the minimum section load address as the base, this section is loaded at the specified image base.  If you would like this section to be placed at 0x40 or 0x100040 you can specify this as your image base address during import.

**Comment by ghidra1** [comment]
Closing ticket since appears to be a non-issue.  Please re-open if needed.
