### ISSUE TITLE
AutoAnalysis vs Decompilation

### ISSUE THREAD

**Issue by aa-software2112** [NationalSecurityAgency/ghidra#3672]
Hello!

Quick question your for; If I run AutoAnalysis (with all default options) in GUI mode, I am able to quickly jump from function-to-function and view their decompiled results immediately. Something tells me that AutoAnalysis generates the decompiled functions in GUI mode which allows us to quickly navigate between decompiled functions. (Please correct me if I'm wrong).

With this logic, everytime we re-open an imported file, we don't need to re-run AutoAnalysis to get the decompiled functions - they are simply saved within the project from our first running of AutoAnalysis.

Now once AutoAnalysis is run in _headless mode_, as opposed to GUI mode, is there a way to fetch these decompiled results without re-decompiling the function? It seems a possibility in GUI mode, thus I am making the assumption that it would be possible to do this in headless mode as well. Any guidance/advice/suggestions on the matter? I get the feeling I am re-decompiling functions for no good reason!

Thanks so much

**Comment by astrelsky** [comment]
They are re decompiled repeatedly and are not saved in the project. What you are really seeing in the gui is that a small number of recently visited functions are cached (usually around 10). This is done so that you don't have to wait when navigating back and forth to the same functions to see what arguments are passed for example.

With that said it shouldn't take a long time for functions to be decompiled with the exception of some grossly large functions and other edge cases.

**Comment by aa-software2112** [comment]
Thanks so much!
