### ISSUE TITLE
Better graph view UX/UI.

### ISSUE THREAD

**Issue by 0xShad3** [NationalSecurityAgency/ghidra#3674]
**Is your feature request related to a problem? Please describe.**
The graph view of Ghidra is a solid limiting factor on why **not** to use it. Even though it is a personal preference it seems that most people prefer UIs similar to Binary Ninja or IDA.

**Describe the solution you'd like**
I would prefer a better UI in terms of readability and usability. With that I mean : mouse binding , option to use dark theme, higher contrast, modern color palette ( You may use something like https://imagecolorpicker.com/en to chose a set of colors. And definitely change the way arrows are shown ): 
![image](https://user-images.githubusercontent.com/44684802/143434402-c92d0648-196c-4f60-905f-1841ff6cfb8b.png)
I cannot explain this better, since im not a UI/UX engineer but for me and most of the people that are used in every other reverse engineering tool but want to move to Ghidra, the arrow following the black path is much easier to understand than the red one.

**Describe alternatives you've considered**

**Additional context**
A design similar to Cutter's  graph view or Binary Ninja's graph view would be ideal.

**Comment by dragonmacher** [comment]
Many of the issues you mention here are valid and should be addressed.  There are already tickets open for most/all of your concerns.    Based on your input, I see the following major needs:

- Themability (colors, fonts, contrast)
- Graph Layouts 
- Accessibility (mouseless interaction, screen reader support)

Perhaps the most requested feature of Ghidra overall is to support themability, so that users can apply a dark theme, high contrast theme, a community theme, or any custom theme.   This is something we regularly discuss when planning new work.

We have recently added new graph layouts that provide more options that allow users to better see related code flow paths.  These layouts are available from the toolbar of the graph.  I still think there are better layouts to be created in the future.

Accessibility is another area that we regularly discuss when planning future work.   As with the theme support, I see this as something that will eventually be updated.

> A design similar to Cutter's graph view or Binary Ninja's graph view would be ideal.

I have seen Cutter's graph and I am a fan of its beauty.  We can certainly use it as inspiration for future graph layouts and settings.

> the arrow following the black path is much easier to understand than the red one.

There are various tool options for the graph, which include color settings, edge settings and layout settings that may address some of your concerns.  For example, the edge transparency you show in the image above is something you can disable.  Further, you can set the colors used for the edges--you can use black edges if you like.

As it stands now, this ticket does not fit our bug or feature request format well, since it is too broad.   Please submit a new ticket for any specific bug of enhancement that you would like.   For example, you mentioned "mouse binding" / keyboard bindings.   We have support for many mouse and keyboard settings.  If there is something we do not support, then you can make a specific request for that feature.
