### ISSUE TITLE
Add to watch from context menu in the Dynamic listing of the debugger

### ISSUE THREAD

**Issue by Smileynator** [NationalSecurityAgency/ghidra#3680]
**Is your feature request related to a problem? Please describe.**
Currently, adding a watch is terrible workflow wise. You add the watch, remember that (to me) weird syntax of.. from memory:
*:64 0x004002aa:4 , this means to add a watch of 64 size to address 0x004002aa, and the rest i don't even know. And then manually typing it, etc.

**Describe the solution you'd like**
When i right click in the dynamic area, and the cursor address is typed, allow me a button that says "Add to watch" much like visual studio does. This automatically adds the address to watch, with the size, and type of the selected struct. (And if no struct, bring up a dialog that defaults to 4 bytes at that address and ask what you want it to do from there?)
Bonus points: Allow it in Static listing too (static listing is usually typed already, saving time)
Bonus Bonus points: Add breakpoint from watches, matching size, defaulting to SW_WRITE so i can start run until this struct changes.

**Describe alternatives you've considered**
Doing it manually as described above, usually halfassing the type or size for sake of quickness.

**Additional context**
I am a spoiled brat with fancy dev environments. But i feel as a programmer, assuming the context that is available in ghidra, this should be easy to make an MVP of, and is a massive time saver for anyone working with the debugger tool to do runtime inspection, because now i often forgo the use of a watch, because it is such a pain to add one manually.

**Comment by nsadeveloper789** [comment]
This would be a nice feature. Even the "Bonus points" request is pretty reasonable. The "Bonus Bonus", however, I hesitate to implement. Instead, if you double-click the "Address" column of the Watch, it'll take you there in the listing, and you can easily set the breakpoint from there using the K key. I you're worried about size, then use the "Select Addresses" button in the Watches toolbar before setting the breakpoint.

I hesitate to implement "Setting breakpoints on watches," since that would imply breaking whenever the watch's value changes, which is subtly different than the bytes at the address changing. Granted, for watches of the form you describe, they are the same, but consider `*:4 EAX`. The watch's value could change if EAX changes, or the bytes pointed to by EAX change, or both. Putting a 4-byte breakpoint where EAX points only covers the latter.

**Comment by Smileynator** [comment]
@nsadeveloper789 I suppose that the breakpoints setting would probably be a whole other 2nd feature request.
To the problems you pose, I imagine "add breakpoint on address" and "add breakpoint on value" to differentiate between the two would be an option. But it already sounds way more complicated than my original feature request.

I suggest you forgo the whole "add breakpoint" stuff and indeed stick to the workflow of "you have a shorthand, you can easily navigate there and do it yourself" in favor of making the feature request a lot less painful to develop.

**Comment by ghidra1** [comment]
Issue addressed by commit adeefc58c88de8b5b078665f1c04e031a0ce4881
