### ISSUE TITLE
getParam function seems to return an incorrect type

### ISSUE THREAD

**Issue by niconaus** [NationalSecurityAgency/ghidra#3702]
I'm trying to run a PCodeDump script [found here](https://github.com/d-millar/ghidra_pcode_scripts/blob/master/PCodeDumpMF.java).

I'm getting a type error indicating the following:

`PCodeDump.java:551: error: incompatible types: ghidra.program.model.pcode.HighSymbol cannot be converted to ghidra.program.model.pcode.HighParam`
			`HighParam param = proto.getParam(i);`

Looking at the Ghidra documentation, the function [getParam()](https://ghidra.re/ghidra_docs/api/ghidra/program/model/pcode/FunctionPrototype.html#getParam(int)) should return something of type HighParam, and not of type HighSymbol.

Is there a bug in the ghidra.program.model.pcode.FunctionPrototype library, or am I doing something wrong here?

**Comment by astrelsky** [comment]
This script seems to have been last updated in May 2019. The API has since changed. The change can be seen here https://github.com/NationalSecurityAgency/ghidra/commit/76d0f12bd3f1d3f87025f8e56424c02ded4c5ef2#diff-ca4121a3a0c68800e1a27b2262700fcf19fc7fec19ec0bbb8bfeb2b2560a37ad

Even though the script was written by @d-millar I still wouldn't expect it to be up-to-date. I wouldn't even expect the scripts provided with the Ghidra distribution to always be up-to-date. This particular one seems to be a minor change and the changed necessary to make it work *should* be trivial.

**Comment by chrisage** [comment]
The change to make the script work:
```
---
		for (int i = 0; i < proto.getNumParams(); i++) {
			HighParam param = proto.getParam(i);
+++
		for (int i = 0; i < hfn.getLocalSymbolMap().getNumParams(); i++) {
			HighParam param = hfn.getLocalSymbolMap().getParam(i);
```
