### ISSUE TITLE
Graph Fullscreen code ?

### ISSUE THREAD

**Issue by ALLERRORr** [NationalSecurityAgency/ghidra#3766]
![1](https://user-images.githubusercontent.com/43153257/146280323-e41d2d8a-f52d-4ef8-99d6-c0f7f7e71d3e.jpg)

... not showing the full command have any solution ... and address ... thanks

**Comment by dragonmacher** [comment]
The clipping on the right should not happen.  This may be a bug.  The clipping on the left is intentional, as the end of the address is usually the useful portion.   

For the right clipping, You can change the formatter used for the nodes to add a space block after the text by using the 'Edit Code Block Fields' icon at the top of the toolbar of the graph (the icon looks like a keyboard).

For the left address clipping, you can use the same edit feature.  When editing the format, click the item of interest in the dialog, the address in this case.  Then the header you can edit becomes highlighted.  You can drag the highlighted header to resize it.   To add a spacer, right-click the header to add a spacer field and resize as needed.
