### ISSUE TITLE
Function signature is "shifted" when using syscall overrides

### ISSUE THREAD

**Issue by Tim---** [NationalSecurityAgency/ghidra#3936]
**Describe the bug**
When overriding a system call similar to the [Advanced Course](https://github.com/NationalSecurityAgency/ghidra/blob/master/GhidraDocs/GhidraClass/Advanced/improvingDisassemblyAndDecompilation.pdf) on an ARM architecture, functions signatures are messed up.

To be more precise:
* In the course, the override is done on the x86 `syscall` instruction which yield the `syscall()` pcodeop (no parameters)
* In my case, I wanted to use it on the ARM `svc` instruction, which yields the `software_interrupt(tmp)` pcodeop (1 parameter).

When using `CALLOTHER_OVERRIDE_CALL` to call a function, the pcodeop parameters are treated as function parameters. This messes up the function calls (see below).

**To Reproduce**
1. Create a binary with two instructions: `svc 01` and `bx lr`:
 `echo 01df7047 | xxd -r -p > my_binary`
2. Open the binary as a raw file in Ghidra with language `ARM:LE:32:v8T:default`
3. Auto-analyze or decompile the binary. You should see the two instructions.
4. Basically follow the exercise on System Calls in the course:
   1. Create a memory region `syscall_block` at address `OTHER:0`, length 10 with the overlay property.
   2. Create a function "write" at address `syscall_block::1`
   3. Add a reference on the svc instruction to `syscall_block::1` of type `CALLOTHER_OVERRIDE_CALL`.

The decompiled functions should now be:

```
void Reset(void)
{
  write(1);
  return;
}
```

Now assume our syscall takes a `char *` as the first and only parameter. We can override the signature of `write` to `void write(char *)`, but this gives us an incorrect result:

```
void Reset(undefined4 param_1)
{
  write((char *)0x1, param_1);
  return;
}
```

Ok, the decompiler really wants to put the syscall number as the first parameter. Why not ? We can change the signature to `void write(int, char *)` to take this into account. Now we get:

```
void Reset(char *param_1, undefined4 param_2)
{
  write(0x1, param_1, param_2);
  return;
}
```

What we see is that we always get one more parameter, and the signature is "shifted". 

**Expected behavior**

The pcodeop parameters should not "steal" the first function parameters when using
 CALLOTHER_OVERRIDE_CALL.

In fact, I would argue that the pcodeop parameters should probably be removed from the decompiler output when using call overrides. In ARM, this parameter indicates the syscall number, and I use a script to map each SVC call to the corresponding function in the overlay. Having the syscall number in the decompiler is redundant.
I think it is the same on other architectures, but maybe there are corner cases that I didn't think about.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Java Version: openjdk version "11.0.13"
 - Ghidra Version: 10.1.2
 - Ghidra Origin: official ghidra-sre.org distro

**Comment by ghidracadabra** [comment]
Thanks for reporting this and for the minimal example!

As it turns out, we are working on a fix for this but I can't promise that it will make the 10.2 release.

Long story short, when we added the overriding references to handle syscalls we didn't go through and change all of our language definitions accordingly because we wanted some time to experiment and determine the best way to proceed.  Syscall instructions are a bit weird in that oftentimes the semantics we want to use are more properly thought of as a property of the toolchain that created a binary and the operating system running it rather than just the processor.  That is, different programs running on the same processor might handle system calls in different ways, which we need to handle sensibly.

For your particular example, you could fix this locally by changing the definition of the `svc` instruction in `ARMTHUMBinstructions.sinc` (starting on line 4610) to
`:svc^ItCond     immed8                  is TMode=1 & ItCond & op8=0xdf & immed8
{
  build ItCond;
  software_interrupt();
}`

You'd probably also want to replace the `swi` instruction in `ARMinstructions.sinc` (line 5644) with
`:swi^COND immed24               is $(AMODE) &  COND & c2427=15 & immed24 
{ 
  build COND;
  software_interrupt();
}`

You'll have to restart Ghidra for these changes to take effect.

There are some caveats to this approach, however:

- This will prevent the interrupt number from appearing in the code for all instances of these instructions (in all ARM programs), not just ones corresponding to syscalls.
- This won't work in a shared project unless everyone makes this change.
- Until we add the fix you'd have to do this manually every time you update Ghidra.

Given that, it may or may not be worth it for you to make these changes.

**Comment by Tim---** [comment]
Thanks for your answer.

I should have mentioned that I already use the workaround you proposed but I forgot while writing the issue. Oops. As you mentioned, the main drawback is that it must be done after each update.

> Syscall instructions are a bit weird in that oftentimes the semantics we want to use are more properly thought of as a property of the toolchain that created a binary and the operating system running it rather than just the processor. That is, different programs running on the same processor might handle system calls in different ways, which we need to handle sensibly.

If I understand correctly, the plan would be to determine this behavior in the pspec/cspec files ?

**Comment by ghidracadabra** [comment]
Sorry for the delay in responding.  Behavior will probably be determined in the pspec/cspec files; small possibility of adding a new spec type.

**Comment by deliciouslytyped** [comment]
Getting this would be nice because currently this conflicts with using function signatures acquired from external sources such as via "Parse C Source...", beyond the aesthetic reasons. I could try to automatically mangle the function signatures after the fact as well but that's not very nice.

**Comment by deliciouslytyped** [comment]
@ghidracadabra I'm having some trouble with the workaround:
I'm on 10.1.4, I've made the following edits:
```
:svc^ItCond     immed8                  is TMode=1 & ItCond & op8=0xdf & immed8
{
   build ItCond;
#  tmp:4 = immed8;
#  software_interrupt(tmp);
  software_interrupt();
}
```

```
:swi^COND immed24               is $(AMODE) &  COND & c2427=15 & immed24
{
  build COND;   
#  tmp:4 = immed24;
#  software_interrupt(tmp);
  software_interrupt();   
}
```

However the decompiler output is still like the following:
![image](https://user-images.githubusercontent.com/47436522/171993029-b86438d7-617a-49bb-addb-e7b9c9f2f2d9.png)

The first argument should not be the 0x8c immediate of the svc instruction?


I've restarted ghidra.

**Comment by deliciouslytyped** [comment]
I haven't figured out the cause of the discrepancy, but I was able to use the workaround on another machine.
