### ISSUE TITLE
memory map export to csv boolean values bug

### ISSUE THREAD

**Issue by legale** [NationalSecurityAgency/ghidra#3947]
**Describe the bug**
While exporting memory blocks to csv from "Memory map" window all boolean columns ("R", "W", "X" "Volatile") are empty.

**To Reproduce**
1. Go to 'Window -> Memory map'
2. Right button click on any block(s) and select export to csv
3. In generated csv file all boolean columns are empty.

**Expected behavior**
 Expected True/False or 1/0 values.

**Screenshots**
![image](https://user-images.githubusercontent.com/32621719/151718755-1472e770-1225-4d72-9fcb-034eb54a29b5.png)

**Attachments**
None

**Environment (please complete the following information):**
 - OS: Windows 10 x64 LTSC
 - Java Version: jdk-15.0.1
 - Ghidra Version: 10.1.1 PUBLIC
 - Ghidra Origin: official ghidra-sre.org distro 

**Additional context**
None

**Comment by ryanmkurtz** [comment]
It looks like the value that ends up in the CSV is the label text, but since we render a checkbox for the boolean values, the label text is `""`.

https://github.com/NationalSecurityAgency/ghidra/blob/7b38e60298b3ffabdf628887ba4ed2fc3e0bd936/Ghidra/Framework/Docking/src/main/java/docking/widgets/table/GTableToCSV.java#L168-L180

https://github.com/NationalSecurityAgency/ghidra/blob/7b38e60298b3ffabdf628887ba4ed2fc3e0bd936/Ghidra/Framework/Docking/src/main/java/docking/widgets/table/GTableToCSV.java#L190-L194

https://github.com/NationalSecurityAgency/ghidra/blob/7b38e60298b3ffabdf628887ba4ed2fc3e0bd936/Ghidra/Framework/Docking/src/main/java/docking/widgets/table/GBooleanCellRenderer.java#L79-L89

**Comment by dragonmacher** [comment]
This seems like something we should be able to fix.

**Comment by tati1454** [comment]
Hello is someone still working on this bug?
