### ISSUE TITLE
Encountered Errors Copying/Moving

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#3960]
**Describe the bug**
Attempting to replace the wrong datatype created by demangling with the correct one by dragging and dropping it onto the other produces an error pop up stating "Encountered Errors Copying/Moving".

**To Reproduce**
1. Attempt a drag n drop datatype replacement in the datatype manager window.

**Expected behavior**
The prompt to replace the type should appear like it had in the past.

**Environment (please complete the following information):**
 - Ghidra Version: 10.2_DEV c2510e5ab03b9aa8b88e34af65e5694701f799f7

**Comment by dragonmacher** [comment]
This code has been changed so that replacing a data type is now done by right-clicking on that type and choosing `Replace Data Type...`, which will show a data type chooser dialog.  Drag/drop should now result in a copy operation with optional conflict handling taking place.   


I was unable reproduce this particular message.   I would like to investigate the the condition.  Can you give a more specific setup that triggers the action?

**Comment by astrelsky** [comment]
Ah, I was unaware of the right click option. When I initially dragged it over it did add the conflict suffix. I initially thought I missed so I tried again while it had the suffix and this is when it appeared. So I think it might be trying to do the conflict suffix again which then clashes with the type attempting to be copied.

**Comment by astrelsky** [comment]
The right click option is definitely easier than drag n drop. I did notice that the type you are replacing shows up in the options when choosing the replacement type. I'm not sure what happens if you choose it but it would be cool to filter it out.

**Comment by astrelsky** [comment]
I'm going to close this since I've been using the right click option without issues since I've opened this.
