### ISSUE TITLE
DWARF Compile Unit Full Paths

### ISSUE THREAD

**Issue by bdemick** [NationalSecurityAgency/ghidra#3976]
When parsing DWARF info, the Data Type Manager only displays the basename of the compile unit path. It's often very useful to know the full path of the compile unit (e.g., `/usr/home/dev/toolchain/middleware/helper.c` vs. `DWARF/helper.c`). It totally makes sense to only display the basename from a UI perspective, but I'd love to get at the full path if possible.

Is this information (or the parsed Compile Units) saved anywhere when importing DWARF info? I have yet to locate it. I thought maybe it would be in the `ghidra.program.model.CategoryPath` object, but I was wrong. It looks like `DWARFCompileUnit.getFullFileByIndex()` is possibly the correct API for this, but it looks to be unused.

**Comment by dev747368** [comment]
Currently the path to the compiled file isn't saved anywhere, mostly because there isn't anywhere convenient to attach it to.

The sub-division of the data types into /DWARF/sourceFile.h/blah is done using the decl_file info that is attached to each type, not the filename name attached to the overall compile unit.   You can see this info if you turn on the option in the DWARF analyzer to output source info before analyzing.

I agree that the compile unit info (also the producer string, which typically includes the compiler invocation cmd line) would be handy to expose, the main problem being where to attach that info in ghidra.

**Comment by bdemick** [comment]
Heh, producer string was going to be my next question! At any rate, thanks for the quick response. Would love to see this as an enhancement within Ghidra for sure, tons of ideas for how to put this to good use.

**Comment by dev747368** [comment]
Added in f17ebb78ab96602c61682496ff8850df49b369ef
