### ISSUE TITLE
Simply constructed C-Enum cannot be imported (Better sharing of information with the user when duplicates exist)

### ISSUE THREAD

**Issue by 0xBEEEF** [NationalSecurityAgency/ghidra#3996]
**Describe the bug**
I cannot import the following file using the "Parse C Source" function. It always comes to an error, although the enum is correct in itself and also corresponds to the standard syntax.

**To Reproduce**
1. Call the "Parse C Source" function.
2. Create a new profile.
3. Add the header file.
4. Execute the "Parse To Program" function.
5. The following error message appears.

C Parser: Problem Parsing in sample.h near line 1
Last Valid Datatype: - none - 
Check around CParserPlugin.out around line: 1043

**Expected behavior**
It should be possible to import the enumeration without errors and smoothly.

**Screenshots**

**Attachments**
[Sample Header File](https://gist.github.com/0xBEEEF/ccf22d2d858ab2dfcbf8da89f16414b4)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version 11.0.9.1
 - Ghidra Version: 10.1.2
 - Ghidra Origin:  official ghidra-sre.org distro

**Additional context**

**Comment by Wall-AF** [comment]
Try removing `typedef enum` and replace it with `enum WindowsStdMessages` and also remove the enum name at the end.  At least it'll import then.

**Comment by 0xBEEEF** [comment]
OK, I made the adjustments as you suggested. Unfortunately, it still does not work for me. The same error still appears. [Here](https://gist.github.com/0xBEEEF/ccf22d2d858ab2dfcbf8da89f16414b4/revisions) are my changes.

**Comment by 0xBEEEF** [comment]
OK, that is indeed a good point. I didn't make the enum myself, but only took it over, and of course I didn't check all values (compiling with Visual Studio was possible without any problems).

It would be already somehow desirable that if it is because of the duplicates that one gets at least a tangible error message. I got no answer at all, except the above mentioned message back.

**Comment by emteere** [comment]
Normally a nice error message is put out, and the ENUM continues to parse even though there is a duplicate.

duplicate enum value: WindowsStdMessages : EM_CONVPOSITION : 1132
    In file third/line.h
    Near check_assert
duplicate enum value: WindowsStdMessages : EM_SETSCROLLPOS : 1246
    In file third/line.h
    Near check_assert

However, since you only had one data type in the file and there was no last defined data type, the error message printed to err had a null pointer exception.  This would only occur if there was only one data type defined in a file and there was a parse error in it.  Good find, but not exactly what I expected, since it worked when I tried it in the test .h file after other data types, but yours did indeed fail.

**Comment by emteere** [comment]
The duplicate will be ignored, but noted in the parse output.
Will be fixed in an upcoming set of changes.
