### ISSUE TITLE
Disassembly output h...

### ISSUE THREAD

**Issue by AnFunctionArray** [NationalSecurityAgency/ghidra#4013]
It seems th...

**To Reproduce**
Go to verylongna..
**Expected behavior**
Go to verylongnameGHIDRAIBEGYOU

The same issue IDA had - I tried to take it calmly but there was simply no option to CHANGE this IN THE OPTIONS (that I was able to find).

**Comment by Pokechu22** [comment]
You haven't been particularly clear about what your issue is, but if you want to change the number of characters before something in the disassembly gets truncated, you can resize them (and add additional fields) by clicking on the edit listing fields button (![image](https://user-images.githubusercontent.com/8334194/155276365-968cc684-baa9-4fc1-be48-f3da842de8dd.png)).  Look for "Browser Field Formatter" in the documentation for more info.
