### ISSUE TITLE
MIPS: Don't apply default base address for ELF

### ISSUE THREAD

**Issue by lab313ru** [NationalSecurityAgency/ghidra#405]
Binary is: [crack.zip](https://github.com/NationalSecurityAgency/ghidra/files/3068674/crack.zip)

Ghidra elf loader uses default image base `0x100000`, and when I'm loading this binary and decompiling function `checkPass()` it cannot find strings in `.rodata` section, because their references are not relative to ImageBase and hardcoded.

**Comment by emteere** [comment]
You can change the image base on import to a correct image base for your binary, unless the image base is specified in the binary.  A default image base for binaries that do not specify an image base is set in order to keep the image away from 0x0, which can cause erroneous references to be created in certain cases.

If you change the image base on the import of the crack to line up with .rodata, does that help?
Is the image base somehow specified in the binary and it is being incorrectly interpreted?

**Comment by lab313ru** [comment]
ELF binary contains virtual addresses in headers, so base addresses for every section are already specified, and it's don't require to apply other image base.

And, yes, changing imagebase at importing binary stage helps.

**Comment by nihilus** [comment]
Another crackle that is cracked up... try to rebuild the ELF file first before filing any bug. How to do this and why you get issues is not in the scope of ghidra. Personally I'd suggest elfsh/libbfd.

**Comment by nihilus** [comment]
Actually as I've stated before I am so perverse I am considering adding Java-bindings for libbfd to be able to import all kinds of files, that's why I added libbfd-support to 'snowman'-decompiler (and yes I did add MIPS-support to snowman as well).
