### ISSUE TITLE
Android ARM argument wrong

### ISSUE THREAD

**Issue by zchrissirhcz** [NationalSecurityAgency/ghidra#4143]
**Describe the bug**
I have a C function `mcReluCInplace`, compiled with android ndk for arm platform, and Ghidra disassembly gives different result with the original code(argument order wrong, and if condition wrong).
```c++
void mcReluCInplace(int width,int height, float slope, float* data)
{
  float *input = data;
  float *output;
  
  if (slope == 0.0) {
    output = input;
    for(int i = 0; i < width * height; i++)
    {
      input = output + 1;
      if (*output < 0.0) {
         *output = 0.0;
      }
    }
    return;
  }
  output = input;
  for (int i = 0; i < width * height; i++)
  {
    input = output + 1;
    if (*output < 0.0) {
      *output *= slope;
    }
  }
  return;
}
```

**To Reproduce**
I prepared the minimal reproduce example project in
https://github.com/zchrissirhcz/min-repros/tree/master/ghidra-android-arm-argument

**Expected behavior**

**Screenshots**

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
 - OS: ubuntu 20.04
 - Java Version: 11.0.14
 - Ghidra Version: 10.1.2
 - Ghidra Origin:  official ghidra-sre.org distro

**Additional context**

**Comment by nneonneo** [comment]
It seems like the expected result is

`void mcReluCInplace(int width,int height, float slope, float* data)`

whereas you're getting

`void mcReluCInplace(float param_1,int param_2,int param_3,float *param_4)`

According to the ARM Procedure Call Standard, VFP variant, the `float` is passed in a separate VFP register (probably `s0`), meaning that these two function signatures are actually identical at the machine code level. Here's how the registers are allocated:

```
reg     name1      name2
s0      slope      param_1
r0      width      param_2
r1      height     param_3
r2      data       param_4
```

As you can see, since the floating-point argument `s0` sits apart from the remaining arguments `r0-r2`, it is not possible to recover its argument position relative to the rest.
