### ISSUE TITLE
Update DevGuide.md to match the change in fetchDependencies.gradle

### ISSUE THREAD

**Issue by xiaoyinl** [NationalSecurityAgency/ghidra#4146]
Commit a71706569d64dfa84bc184107790494c3b3bc32f changes the fidb download URLs from https://github.com/NationalSecurityAgency/ghidra-data/raw/master/FunctionID/*.fidb to https://github.com/NationalSecurityAgency/ghidra-data/raw/Ghidra_${RELEASE_VERSION}/FunctionID/*.fidb in gradle/support/fetchDependencies.gradle, but the manual download instructions in [DevGuide.md](https://github.com/NationalSecurityAgency/ghidra/blob/master/DevGuide.md#get-ghidra-function-id-datasets) was not updated.

**Comment by ryanmkurtz** [comment]
Bah, I seem incapable of remembering  to update that. As a user, do you find that document useful now that the README.md has been improved?

**Comment by xiaoyinl** [comment]
@ryanmkurtz Yes, I find DevGuide.md still useful. I followed the manual download instructions to build Ghidra on an offline system.

**Comment by ryanmkurtz** [comment]
Might I ask why you followed those instructions rather than just running the `fetchDependencies.gradle` script and moving over the `dependencies` directory?  I've been playing with passing an `offline` flag to the script that just outputs a series of linux commands like we have in the instructions.  It works nicely, but I'm wondering what the real value is since that directory can just be moved around.

**Comment by xiaoyinl** [comment]
Because long time ago, the dependencies were not saved in one single directory, so at that time, I downloaded them individually and copied them to the corresponding directories. It was just a personal preference. I agree nowadays it's simpler to just run the script and move the `dependencies` directory, so I don't object removing the manual download instructions.
