### ISSUE TITLE
Directly jump to main function on opening the binary

### ISSUE THREAD

**Issue by acid-flux** [NationalSecurityAgency/ghidra#4267]
**Is your feature request related to a problem? Please describe.**
Most of the time it is kind of repetitive to navigate to the symbol tree -> function and pick the main function

**Describe the solution you'd like**
Directly jump to the main function on opening the binary, in case the binary is stripped jump to __libc_start_main directly on opening

**Comment by astrelsky** [comment]
Press g, type main, hit enter, profit.

**Comment by acid-flux** [comment]
for a stripped binary that wouldnt be a direct case i believe it should drop into  _start function first from there libc_start_main's first parameter would be the main function, still something like what IDA does like on opening the binary drops directly into main function or __libc_start_main, would have been a really powerful tool

**Comment by emteere** [comment]
Ghidra also labels the entry point "entry".  So you can "g entry", that isn't always what you want, so it could be changed to go to main or entry if main isn't defined.
Code would just need to be added to know that this is the first time the binary has been opened, otherwise Ghidra should go to your last location when the binary was last open in your tool.

**Comment by astrelsky** [comment]
> Code would just need to be added to know that this is the first time the binary has been opened, otherwise Ghidra should go to your last location when the binary was last open in your tool.

It only does this if you don't close the tool before closing Ghidra. So it therefore never does this.

**Comment by emteere** [comment]
Yes the last location is saved with the tool on the open programs, so that when Ghidra restarts all tools are open with the same programs at the same location.
I usually exit Ghidra with programs open rather than closing each tool then exiting Ghidra, so when I return to Ghidra the same tool and programs are open.
There has been thought about saving the last location opened for a given program.  It can't really be saved with the program.
A possible compromise solution: if you close a program, the tool would still remember the last location for the program even though the program was closed.  It could lead to a bit of garbage in the tools save state until you close the tool.

**Comment by astrelsky** [comment]
> Yes the last location is saved with the tool on the open programs, so that when Ghidra restarts all tools are open with the same programs at the same location.
> I usually exit Ghidra with programs open rather than closing each tool then exiting Ghidra, so when I return to Ghidra the same tool and programs are open.
> There has been thought about saving the last location opened for a given program.  It can't really be saved with the program.
> A possible compromise solution: if you close a program, the tool would still remember the last location for the program even though the program was closed.  It could lead to a bit of garbage in the tools save state until you close the tool.

I see where saving that information in the tool could be troublesome. I personally don't like having the tool automatically opened on me, especially when I'm doing dev work and then it crashes and the tool layout gets obliterated. Its super rare but does happen. 

If I want to save my spot I'll usually do a quick goto to the current address so I can jump back next time. I don't get to keep all my previous (back button) locations though.

It's probably just me though. People tell me I'm weird for logging off and shutting down everyday so idk.
