### ISSUE TITLE
Double clicking relative pointer goes to wrong address

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#4269]
**Describe the bug**
Double clicking on a pointer with offset settings changed will not take you to the correct address.

**To Reproduce**
1. Create a typedef to void*
2. Change the settings to add a component offset of 4 and the type to image base relative.
3. Find a small integer, create the type and double click it.
4. You will be taken to the image base + integer value

**Expected behavior**
Should be taken to image base + integer value + offset

**Environment (please complete the following information):**
 - Java Version: 11
 - Ghidra Version: 10.2_DEV

**Comment by ghidra1** [comment]
The navigation is based purely on the reference which may exist on the pointer.  This may vary depending upon when the reference was created relative to any settings changes.  The reference is created at the time the data is created and does not update with settings changes (known limitation with no current intention to address).  Please use the reference editor verify what reference exists at the location.

In addition, an offset setting may result in an offset-reference being created where (base+offset)=(stored pointer).  The navigation on this reference will always go to the (stored pointer) location with the exception of the EXTERNAL block where we attempt to navigate to the base address since the stored pointer address is not valid.

**Comment by astrelsky** [comment]
> The navigation is based purely on the reference which may exist on the pointer. This may vary depending upon when the reference was created relative to any settings changes. The reference is created at the time the data is created and does not update with settings changes (known limitation with no current intention to address). Please use the reference editor verify what reference exists at the location.
> 
> In addition, an offset setting may result in an offset-reference being created where (base+offset)=(stored pointer). The navigation on this reference will always go to the (stored pointer) location with the exception of the EXTERNAL block where we attempt to navigate to the base address since the stored pointer address is not valid.
> 
> This is working as intended and is not a bug.

That makes sense. I was trying to get similar behavior to the `ImageBaseOffset32` but section relative instead of image base. There are other ways I could accomplish it so it's not important. I just wasn't sure if it was an oversight or not.
