### ISSUE TITLE
Able to switch to using AT&T syntax?

### ISSUE THREAD

**Issue by andyhhp** [NationalSecurityAgency/ghidra#429]
Hello,

I'm having a play with v9.0.2 with some microkernels I've built.

First and foremost, is there any way to switch from Intel(ish) syntax to AT&T syntax?  I can't find anything obvious in the help or the settings.  If there isn't, can I request this as a feature?

A second issue I've noticed is that the disassembler doesn't recognise the Long-NOP instructions which are used for basic block padding.

Finally, the analysis has found:

`/* WARNING: Control flow encountered bad instruction data */`

which is referring to:

``00103c34 ea 00 00 00 00 48 00        JMPF       0x48:0x0=>zeroptr``

which it has decoded properly and correctly.  The trick here is that it is using x86's hardware task switching mechanism, where the offset is discarded by the processor and most often encoded with 0.

**Comment by emteere** [comment]
1) There currently isn't a way to switch to AT&T syntax.  The display of the disassembly is set in each sleigh processor module.  In general the syntax of the processor manual is followed, vice a particular disassembler.

One possiblility is to write an Intel to AT&T field for the code-browser that would extend the normal operand/mnemonic fields to display the operands.    Then you could use it instead of the normal operand field.  It could get dicey since there the ordering of the displayed operands would be different than the indexes, however the translation to the correct operand index could in theory also be done in the field.

2) Thought we had gotten all the NOP variants.  Ghidra does not normally disassemble if the code cannot be reached.  If you hit 'D' at the instruction does it disassemble?  If not, can you post the bytes for the missing instruction?

3) The decompiler is attempting to jump to address zero.  This case could be replaced with different Pcode that would show the indirection or task switch.  Something like:
     PC = TaskLookup(0x48, 0x0);
     goto [PC];
This probably is not the correct Pseudo-op, since this could be a different type of instruction depending on the mode of the processor.  Maybe something more along the lines of JmpDest().

**Comment by andyhhp** [comment]
1. Ultimately, Intel vs AT&T syntax is purely a function of how to display the underlying information.

2. Hitting 'd' did work.  The instructions are now listed as

`00100044 8d b6 00 00 00 00    LEA        ESI,[ESI]`
`0010004a 8d bf 00 00 00 00    LEA        EDI,[EDI]`

which is the literal decode of the instruction, but it would probably help to identify these as nops, even if only in the EOL comment.  It would also be nice if, in the middle of functions, the nops were disassembled and recognised, rather than having a load of single bytes identified with ?? in the padding.

3. I experimented with overriding the control flow to be CALL.  With this, the decompiler now has `func_0x00000000();` in the middle (which I suppose is the best it can do, seeing as it hasn't spotted the task state segment).  The decompilation then continues on to the end of the function (correctly), which is great.

I can also shift focus to later instructions (in the Decompile window) and the Listing window moves accordingly.  However, when shifting focus (in the Listings window) to any later instruction in the function, the decompiler starts afresh from elsewhere and misses the front half of the function.

If you'd like to have a play with the test case manually, it is http://xenbits.xen.org/docs/xtf/xsa-192_2main_8c_source.html This is actually a test case for a past security vulnerability which manifests differently between Intel and AMD hardware.  I also thought it would be a very interesting first try to reverse engineer.

**Comment by nickdesaulniers** [comment]
This would be nice to have.

**Comment by lhmouse** [comment]
Why do you want AT&T syntax, which is nothing but non-standard, unofficial, amateur nonsense?

**Comment by Martmists-GH** [comment]
> Why do you want AT&T syntax, which is nothing but non-standard, unofficial, amateur nonsense?

Many universities still teach AT&T syntax over Intel syntax. Adding support for this only makes Ghidra more accessible, and it's not something that really needs active maintenance since it's only sleigh definitions.

**Comment by lhmouse** [comment]
> Many universities still teach AT&T syntax over Intel syntax. Adding support for this only makes Ghidra more accessible, and it's not something that really needs active maintenance since it's only sleigh definitions.

Look, I don't want to look like a moron, so I'd just put my point here:

I have been coding in x86 assembly for more than 15 years. For people who wish to learn x86 assembly (especially undergraduates which I'm glad to see), they need to know how to read official docs. The fact is that there's only Intel syntax in both Intel and AMD docs. So one can't really study x86 assembly by just learning at&t syntax - sooner or later they will have to learn both; no doubt in that.

It's not strange that searching for `cwtl` or `rep movsl` on Google gives much much fewer results than `cwde` or `rep movsd`.

> Adding support for this only makes Ghidra more accessible, and it's not something that really needs active maintenance since it's only sleigh definitions.

As for this.. you know, new instructions are likely to be introduced every couple of years. Seriously, what would `vmulps zmm0, zmm1, DWORD BCST [rdx]` look like in at&t syntax? It's certainly not just a 'sleigh definition'.
