### ISSUE TITLE
Persistent hex mode in structure editor (or keyboard shortcut)

### ISSUE THREAD

**Issue by Swyter** [NationalSecurityAgency/ghidra#4326]
From what I gather, every time one opens the structure/enum editor the values appear in base ten and the user needs to manually open the configuration menu and click to switch to hexadecimal mode.

Given than in the decompiler the autogenerated members appear as some hex offset this adds some friction while filling out big structures.

It would be lovely to persistently save the current hex mode toggle globally across structure editor instances, maybe even adding a key-binding to quickly toggle it without using the mouse.

--

Maybe some of these features already exist and I'm just very bad at finding them, please let me know.

Thanks for the great program.

**Comment by dragonmacher** [comment]
I believe this is a bug.  (Although maybe it was intentional, since it could allow the user to have a global setting that they can change for an individual editor, without affecting all editors.)

You can turn on the hex option via the Tool Options under Edit -> Tool Options... Then Options -> Editors -> Structure Editor -> Show Numbers in Hex.    Setting the value here will apply to all editors and will get persisted, assuming you shutdown Ghidra normally.

**Comment by dragonmacher** [comment]
You should be able to set a keybinding on that menu action by hovering the mouse over it and pressing F4.

**Comment by Swyter** [comment]
Oh, boy. I think I need to take another good look at the manual. Thanks for the heads up.

**Comment by dragonmacher** [comment]
I'll close this for now, as I think it is working as we originally intended.

**Comment by Swyter** [comment]
Fair, hopefully other people searching for this will arrive here.
