### ISSUE TITLE
AVR: Support for Atxmega256

### ISSUE THREAD

**Issue by vogelfreiheit** [NationalSecurityAgency/ghidra#4333]
At the moment, I have been reverse engineering a firmware hex file that targets the Atxmega256.

Ghidra performs quite well for the most part, but the lack of specific support for the ATXMEGA256 vs. the 128 counterparts results in incomplete processing of the code section. There is also a not insignificant amount of data that remains unlabeled and not identified. While unrelated, lowering the string length profile to 3 characters can also be of interest in some cases.

Proper support for the 256 variants of Atxmega would actually make Ghidra a prime tool for revers engineering those platforms, as currently no other product supports them (wink), and Ghidra actually fares significantly better at the task, in my humble opinion.

Thank you in advance, and I can test any proposed changes before merging, if desired.

**Comment by emteere** [comment]
I've worked with the AVR8 chips to some extent.  In general Ghidra tries to support the base processor versus all the specific variants for a particular processor, memory mapped registers, memory sizes, etc...

Can you give us a good run down on the main issues with using the current implementation that is giving you the most trouble?

In my general order of importance:
-Are any instructions that we don't support?
-Are there memory addressing modes in the atxmega256 that either aren't correct, or are enhanced beyond the other avr chips? Possibly a new page register?
-Does the atxmega256 move around the basic registers for the chip?
-Are there conventions that the current analysis isn't handling to recover references to code?

Do have a sample binary that exhibits things you'd like to see better supported that is legally available to the public?  I've used printer firmware in the past.

I can go digging into the manual and differences, but it would help to get a summary from you since your head is currently in the issues.  The problems you mention above could be caused by many things, not necessarily the variant of the chip.

**Comment by emteere** [comment]
Initial possibility is the RAMPX,RAMPY registers are not current implemented correctly for addressing.  That would affect memory access above 64K.  These existed in prior variants and really should be implemented.  However your memory map shouldn't suffer from this issue.

The code above looks correct.  The code should not disassemble after the rjmp, as it jumps to itself, and there is a read of the bytes after it, unless it is a bad read.

There are many reasons a reference might not be made to a string, but I think the most likely is something that is being added to the next version.  The issue is CODE memory is addressed as 2 bytes words, however when the ELPM command access it the value is a byte offset into CODE memory.  So if the value is passed as a constant to a function, the value is byte oriented and must be shifted by 1 to get the actual address in CODE memory.  Neither the constant reference analysis or the decompiler knows about this.

The good news is there is a new PointerTypdef that can do shifting on the value when the actual ELPM byte access isn't explict in pcode for the function.  Unfortunately it will get the reference to the correct word, but the real access may be one byte off.  What needs to be done in this case, is encode in the data type, that the offset is byte/word addressed.  This hasn't been implemented yet.  Also there is a little more work in progress for the automated constant referencing.

There is also currently an issue with the hex format importer for binaries that have and address space above 0xffff.  So it is possible that when you loaded your .hex file things were over-written.  You can try patching the IntelHexMemImage.java to see if there are bytes getting overwritten.  It will put the bytes into an overlay space, and you can move them to the correct location.  I discovered this with a .hex image I had.

diff --git a/Ghidra/Features/Base/src/main/java/ghidra/app/util/opinion/IntelHexMemImage.java b/Ghidra/Features/Base/src/main/java/ghidra/app/util/opinion/IntelHexMemImage.java
index 36459b6..c4f5d3c 100644
--- a/Ghidra/Features/Base/src/main/java/ghidra/app/util/opinion/IntelHexMemImage.java
+++ b/Ghidra/Features/Base/src/main/java/ghidra/app/util/opinion/IntelHexMemImage.java
@@ -96,6 +96,10 @@
 					}
 					break;
 				case IntelHexRecord.END_OF_FILE_RECORD_TYPE:
+					// if hit EOF record, everything after goes into an OTHER space
+					// TODO maybe this should go into the data space?
+					space = AddressSpace.OTHER_SPACE;
+					base = space.getAddress(0);
 					// nothing to do, we're at the end (or should we ensure further parses fail?)
 //                log(line, "end of file");
 					break;
@@ -210,7 +214,8 @@
 				myRangeMap.remove(range);
 			}
 
-			String name = blockName == null ? base.getAddressSpace().getName() : blockName;
+			String name = blockName == null ? blockRange.getMinAddress().getAddressSpace().getName()
+					: blockName;
 			MemoryBlockUtils.createInitializedBlock(program, isOverlay, name,
 				blockRange.getMinAddress(), new ByteArrayInputStream(data), data.length,
 				"Generated by " + creator, progFile, true, !isOverlay, !isOverlay, log, monitor);


This shouldn't be a general issue with the ATXMEGA, and affects other avr version, like the xmega.
- RAMPX/RAMPZ addressing implementation
- PointerTypedef enhancements almost complete
- HEX importer change

**Comment by emteere** [comment]
I'm seeing some of what you are seeing, but not all.  Your main routine looks different, and possibly corrupt somehow?
I'm not seeing the same addresses you are.  The read reference above I believe is a bad reference from something, I don't get that, but I've futz with my code/procssor, so I'll have to isolate that.  Both loaded binaries look OK for me.  I'll isolate any changes to things that will work without code changes.

I have a modified AVR8.sinc/ldefs/pspec/cspec files which I'll post so you can try them out for me.  And it will help me with the decompilation.  Actually lucky you asked about this, it helps me out as I had been working on the AVR8 as a test binary for some of the new code.

There isn't any magic loader.  The code in the sample you sent just has a loop loading from code memory into data, for some number of bytes.  It looked pretty small, and you can just copy the bytes into the right place after making memory initialized.

If the references to code memory are passed as a parameter, then it will need to wait until I can get the change into the main branch.  Plus to use the new stuff, you'll have to build ghidra from source code, which isn't as bad as it sounds.

**Comment by emteere** [comment]
Here is what I get from above GccApplication1_hex:
This is with modification to the processor files
```
                             **************************************************************
                             *                          FUNCTION                          *
                             **************************************************************
                             undefined FUN_code_00041a()
             undefined         Wlo:1          <RETURN>
                             FUN_code_00041a                                                                                      XREF[1]:      InitMemory:000111(c)  
     code:00041a 40 e2                         ldi      R20,0x20
     code:00041b 50 e2                         ldi      R21,0x20
     code:00041c 60 e7                         ldi      R22,0x70
     code:00041d 70 e2                         ldi      R23,0x20
     code:00041e 88 e3                         ldi      Wlo,0x38
     code:00041f 90 e2                         ldi      Whi,0x20
     code:000420 0e 94 17 01                   call     DES_3DES_Encrypt                                                                                                                                                                                                                                undefined4 DES_3DES_Encrypt(unde
     code:000422 40 e2                         ldi      R20,0x20
     code:000423 50 e2                         ldi      R21,0x20
     code:000424 60 e7                         ldi      R22,0x70
     code:000425 70 e2                         ldi      R23,0x20
     code:000426 cb 01                         movw     W,R23R22
     code:000427 0e 94 6c 01                   call     DES_3DES_Decrypt                                                                                                                                                                                                                                undefined DES_3DES_Decrypt()
     code:000429 c8 e3                         ldi      Ylo,0x38
     code:00042a d0 e2                         ldi      Yhi,0x20
     code:00042b 00 e7                         ldi      R16,0x70
     code:00042c 10 e2                         ldi      R17,0x20
     code:00042d d8 01                         movw     X,R17R16
     code:00042e fe 01                         movw     Z,Y
                             LAB_code_00042f                                                                                      XREF[1]:      code:000436(j)  
     code:00042f 91 91                         ld       Whi,Z+=>data                                                                                                                                                                                                                                    = ??
     code:000430 8d 91                         ld       Wlo,X+=>single_ans                                                                                                                                                                                                                              = ??
     code:000431 98 13                         cpse     Whi,Wlo
     code:000432 43 c0                         rjmp     LAB_code_000476
     code:000433 80 e2                         ldi      Wlo,0x20
     code:000434 e0 34                         cpi      Zlo,0x40
     code:000435 f8 07                         cpc      Zhi,Wlo
```
And decompilation with some RE markup up of functions:
```
void FUN_code_00041a(undefined2 R19R18,char *R17R16)

{
  char *pcVar1;
  char *pcVar2;
  
  R21R20 = &Keys;
  R23R22 = &single_ans;
  W = &data;
  DES_3DES_Encrypt(&data,&single_ans,&Keys);
  R21R20 = &Keys;
  DES_3DES_Decrypt(&single_ans);
  Y = &data;
  R17R16 = &single_ans;
  X = &single_ans;
  Z = &data;
  do {
    pcVar2 = Z;
    pcVar1 = X;
    Z = Z + 1;
    W._1_1_ = *pcVar2;
    X = X + 1;
    W._0_1_ = *pcVar1;
    if (W._1_1_ != (char)W) goto code_c0x000477;
  } while ((byte)Z != 0x40 || Z._1_1_ != (char)(((byte)Z < 0x40) + ' '));
  R21R20 = &Keys;
  FUN_code_0001c1();
  R21R20 = &Keys;
  FUN_code_00024a(&single_ans);
  ```

**Comment by emteere** [comment]
You will need to create the overlay segments in the memoryMap by hand.  We're adding the capability to the .pspec files.  Currently we can only create the bitmapped overlay blocks, not bytemapped.

**Comment by emteere** [comment]
RE: processing DWARF/ELF. Funny you should mention that.  Almost.  I've been working on elf relocations for .o files for just this purpose.  It should go in soon.  I was just processing some ELF libraries and checking out the code.
You would need to process them into FID database files.  As long as the binary was compiled to use the same .a/.o as in the libraries you generate the FID files from it should probably work. YMMV.

**Comment by emteere** [comment]
There are some updates in patch and master for the larger than 16-bit avr8 memory.

I did try building a test FID file from the AVR8 GCC libraries.  I was able to match routines into a 3d printer firmware image.

There will be bigger changes in the main development branch to handle the various memories and different pointer parameters to each type of memory.  So for example if 0x1234 is passed to a function the decompiler and constant propagation does not know if that is a constant, sram, code byte, code word, or IO memory pointer.

**Comment by ryanmkurtz** [comment]
Closed by 1df11c6cb0e2cce67a14e6892a935e3544d80f1e

**Comment by emteere** [comment]
You can try using this script to automatically initialize the AVR8 RAM memory.

The code is very brittle if the reset vector code or do_copy_data code changes.
Its not the cleanest code, nor does it handle all error cases.  There are probably other ways of doing the same thing, but it should work.

[Avr8LoadMemScript.java.txt](https://github.com/NationalSecurityAgency/ghidra/files/9089464/Avr8LoadMemScript.java.txt)

**Comment by rbray89** [comment]
I'm seeing some similar behavior on an ATXMega256 as well... The strings in PROGMem aren't showing up as having any x-references. Any tips?
