### ISSUE TITLE
Help with RTTI problem

### ISSUE THREAD

**Issue by Guusggg** [NationalSecurityAgency/ghidra#4414]
Hi,

I don't think this is a bug in Ghidra but I must be making a mistake somewhere. I have a lot of strings like `11NisePVectorIN6ns_lib11NormalLayerEE`, `12BattleVersus` and `N6ns_lib12SmartPointerI16CellAnimLiveDataEE` in my program. This is a decompiled Nintendo DS ROM. These strings lead me to believe that there's Runtime Type Information in my binary. I'm almost convinced it was compiled with GCC, since they're RTTI strings are similar. 

The problem is that none of the scripts that are in Ghidra will help me reconstruct these strings into types and it seems I have to do it all by hand. When I run a script like `GccRttiAnalysisScript`, it tells me it doesn't think it's a GCC binary. I also tried the _Ghidra C++ Class and Run Time Type Information Analyzer_ plugin, which also does not run. 

Is there any way to reconstruct this, without doing it by hand? I'm sure I'm making a mistake in my understanding of all this, can you point it out to me? Why does it not recognize it as GCC RTTI? 

I was thinking I had to write my own script for this, but before I have to dive into the Ghidra Script API, I want to make sure I'm not making a simple mistake.

Some program info:
```
Language ID:	ARM:LE:32:v5t (1.103)
Compiler ID:	default
Processor:	ARM
Endian:	Little
Address Size:	32
Analyzed:	true
Created With Ghidra Version:	10.1.4
Executable Format:	Raw Binary
Executable Location:	unknown
```

Thank you for your input.

**Comment by astrelsky** [comment]
Are any of the following strings present in the ROM? I'm already almost certain they will be considering the presence of those strings there.

"St9type_info", "N10__cxxabiv120__si_class_type_infoE", "N10__cxxabiv121__vmi_class_type_infoE"

**Comment by Guusggg** [comment]
`St9type_info` is matching exactly, `N3abi17__class_type_infoE` is a little different than yours along with `N3abi20__si_class_type_infoE` and `N3abi21__vmi_class_type_infoE`. They seem to differ by the string `__cxx`.

**Comment by astrelsky** [comment]
> `St9type_info` is matching exactly, `N3abi17__class_type_infoE` is a little different than yours along with `N3abi20__si_class_type_infoE` and `N3abi21__vmi_class_type_infoE`. They seem to differ by the string `__cxx`.

That would be why then. It is possible that the abi isn't *exactly* the itanium abi (what gcc uses). If the data layout is the same then you could force it to work but I wouldn't know for sure without seeing the data. You can try patching those strings (quickest way) and you might get lucky. Alternatively you may be able to do it if you manually find the corresponding vtables for the base RTTI classes and define the correct symbols but that is more work and you'd need to manually backtrack.

**Comment by Guusggg** [comment]
Thank you so much for the response!

I'll try patching them first. I already found the corresponding vtables but I don't know how to make the scripts or your plugin understand them. Do you think those strings are the only one I should patch?

I'll close this for now since I have some new suggestions to work with.

**Comment by ghidra007** [comment]
> Are any of the following strings present in the ROM? I'm already almost certain they will be considering the presence of those strings there.
> 
> "St9type_info", "N10__cxxabiv117__class_type_infoE", "N10__cxxabiv120__si_class_type_infoE", "N10__cxxabiv121__vmi_class_type_infoE"
> 
> If the above strings are in the ROM then it does indeed have RTTI and I'd be more than happy to help diagnose my plugin with you. As for the RTTI scripts provided with Ghidra it doesn't look like they search for the strings and only look for symbols which means it will only work if the program is not stripped.
> 
> @ghidra007 do the scripts attempt to backtrack from those strings?

The script uses the symbols at those locations and looks for ones in namespace  "__cxxabiv1" with symbol names the special ones indicating the special vtables.  If it doesn't find them that way then it looks for the mangled symbols. The strings he is looking at are mangled but don't seem to be symbols so that is one reason the script may not be finding them. It also sounds like various analyzers are not kicking off so there also may be an issue with Ghidra recognizing the compiler or other important info about the program which is why the demangler didn't work, for example. This is similar to what I was seeing with the mingw programs you shared. They are a mixed bag of Windows and gcc items so Ghidra doesn't know what to do with them. I would be curious to know what happens once symbols are created for the special vtables with the RecoverClassesFromRTTI script. I'm guessing it won't get far if it isn't recognizing gcc.  You  might have to set the compiler type ahead of time then run analysis then run the script.  If that still doesn't work then please paste the script output here so I know what it got hung up on.  I definitely know the script wasn't tested on Nintendo DS ROMS. LOL.

**Comment by Guusggg** [comment]
Thank you a lot for taking the time to write this out! Very much appreciated. I realize that Nintendo DS ROMS are definitely not a first target for tests, which is why I'm not too surprised it didn't work out... Thanks again!

**Comment by ghidra007** [comment]
> 

I'd like to look into the static stripped gcc case even if this other case was different which I'm not sure now if it was. Is one of your examples static and stripped gcc? If so, which one?

**Comment by Guusggg** [comment]
Hi @ghidra007, I'm extremely sorry as I want to provide more information but I have no clue which compiler was used. I do know that in my specific case, the Nintendo DS has a devkit which provides the compiler so I think it would be easy to find out. I'm looking into it as we speak, to try to provide information about which compiler was used. (I imagine the chance of the compiler being GCC very high, as it's not likely they created their own compiler)

**Comment by astrelsky** [comment]
> > 
> 
> I'd like to look into the static stripped gcc case even if this other case was different which I'm not sure now if it was. Is one of your examples static and stripped gcc? If so, which one?

I did fix the samples in my tests. https://github.com/astrelsky/InheritanceTests/releases/download/4/InheritanceTests.tar.xz

`x86_64/static` has `main` and `main_stripped`. `main` is not stripped and has full dwarf debug information (`-g3`). I don't know what is going on here with Ghidra but I see a lot of error bookmarks due to calls to `NULL` that I do not recall ever seeing before. I did just confirm that the programs are valid and run correctly so I'm not sure what is going on there. You should be able to use these to test with though since my analysis still seems to work.
