### ISSUE TITLE
Module addresses all set to 00000000 when debugging remote target

### ISSUE THREAD

**Issue by dlmarrero** [NationalSecurityAgency/ghidra#4456]
**Describe the bug**
When debugging a remote target, module Base Address and Max Address values are all set to zero. In some cases, the modules list does not populate at all. This causes module mapping to be incorrect which affects breakpoint addresses, cursor sync, etc.

**To Reproduce**
1. Open a .so in the debugger
2. Start an IN-VM gdb-multiarch session
3. Issue the target remote command to connect
4. Open the Modules tab and see that the binaries libraries either have not populated or all have 0 for a base address

**Expected behavior**
Module base address should reflect the address it is currently loaded to in memory.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Java Version: 11.0.13
 - Ghidra Version: 10.1.3
 - Ghidra Origin: Official GitHub distro 

**Additional context**
Remote target is correctly identified as an ARMv7 binary.

**Comment by dlmarrero** [comment]
On the host Ghidra is running on is gdb-multiarch 9.2. On the remote I'm running gdbserver 8.0.1. The addresses in the Objects tree are non-zero and correctly match the running program. 

info proc mappings sample line:
```
        0xb6a47000 0xb6a65000    0x1e000        0x0 /lib/libz.so.1.2.11
```

maintenance info:
```
Exec file:
    `/path/to/executable', file type elf32littlearm.
```

I'll give 10.1.4 a try and get back to you about whether it solves the problem.

**Comment by dlmarrero** [comment]
In 10.1.4, after disconnecting from the running target and reconnecting (no restart of the target process) with sysroot properly set, the modules seem to load at the correct addresses. If I set a breakpoint to a symbol in the gdb interpreter, the dynamic and static listings are synced when the breakpoint is hit. However, if I try to set a breakpoint in the static listing or decompiler, the breakpoint address is the static listing address, not the correctly mapped address where the module is loaded in memory.

**Comment by d-millar** [comment]
OK - progress (I think).  Appreciate your slogging through all this and providing us with feedback.  Let us know if you hit further problems.

**Comment by saruman9** [comment]
@d-millar,
I'm sorry to write in this issue, but I think it would be better this way, since the problem is similar to mine.

As I said, I have the same problems. But I have a different context: modules that are loaded from the very beginning of execution are determined without problems, but modules that are loaded using the `dlopen` function have a zero Base/Max addresses. I tried to solve it using [the proposed method](https://github.com/NationalSecurityAgency/ghidra/issues/4456#issuecomment-1191872145) - it didn't work.

- OS: ArchLinux
- Java Version: 20.0.1
- Ghidra Version: ce5f6b44
- Guest OS: Android x86_64

- `gdb` Version: 13.1
- `gdbserver` Version: 8.3 x86_64-linux-android

`info proc mappings`:

```
      0x555555554000     0x555555555000     0x1000        0x0  r--p   /data/local/tmp/harness
      0x555555555000     0x555555557000     0x2000        0x0  r-xp   /data/local/tmp/harness
      0x555555557000     0x555555558000     0x1000     0x1000  r--p   /data/local/tmp/harness
      0x555555558000     0x555555559000     0x1000     0x1000  rw-p   /data/local/tmp/harness
      0x7ffd67553000     0x7ffd6765a000   0x107000        0x0  r-xp   /data/local/tmp/liblinkparser.so
      0x7ffd6765a000     0x7ffd6765e000     0x4000   0x106000  r--p   /data/local/tmp/liblinkparser.so
      0x7ffd6765e000     0x7ffd6765f000     0x1000   0x10a000  rw-p   /data/local/tmp/liblinkparser.so
```
Objects:
![objects](https://github.com/NationalSecurityAgency/ghidra/assets/4244396/d1de90ed-d3d5-4f15-a428-2cc9c58da779)

Modules:
![modules](https://github.com/NationalSecurityAgency/ghidra/assets/4244396/638257ff-f9dc-40c1-b44a-e77d15a0d538)

**Comment by nsadeveloper789** [comment]
Try expanding/refreshing the Sections node within the affected module(s).

**Comment by saruman9** [comment]
> Try expanding/refreshing the Sections node within the affected module(s).

It didn't work.

I found a solution, or rather understood what I was doing wrong. When I manually set the module address, I forgot to trim the `0x` at the beginning of the address. That is, if you manually set the address of the module, then everything works. However, the problem remains: newly loaded modules have zero addresses.

![image](https://github.com/NationalSecurityAgency/ghidra/assets/4244396/6497945d-04a2-4b68-8c87-ac935bf42756)

BTW the regions are working properly.

![image](https://github.com/NationalSecurityAgency/ghidra/assets/4244396/a9c30c56-1ca5-48f9-b59c-d9ecbd79b0d7)

**Comment by d-millar** [comment]
OK, we're able to reproduce the problem (and found another, which is sucking up memory) and are working on a solution.  Will let you know if and when we have a fix.

**Comment by nsadeveloper789** [comment]
You will need to refresh the Modules node in the Objects window. We disabled doing this automatically on module load events for efficiency reasons some time ago. There may be a smarter way to go about it, but we haven't tried it out, yet. Something like setting a flag on LOAD/UNLOAD, and then re-syncing modules at the next STOPPED event if that flag is set.

**Comment by saruman9** [comment]
My mistake: when I updated the node, I had the cursor at the position of one of the modules, and not on Modules in general. Thank you!

**Comment by saruman9** [comment]
> Something like setting a flag on LOAD/UNLOAD, and then re-syncing modules at the next STOPPED event if that flag is set.

That would be great! Because now I need to set several breakpoints to catch the moment when libraries are loaded, update Modules, and only then the breakpoint that I need will work.
In IDA, everything happens automatically: every time a new module is loaded, breakpoints are checked, if there are any in the module space, then the breakpoint is translated to new addresses. In addition, it is possible to set a flag to automatically stop execution every time a new module is loaded.

**Comment by saruman9** [comment]
Thank you for such a detailed description of the solutions to my problems.

I'm using `gdb` and `gdbserver` (see [above](https://github.com/NationalSecurityAgency/ghidra/issues/4456#issuecomment-1552972447)) and I can't find the nodes *Processes->[x]->Debug->Events->Load module* in the Objects Tree in any way. I think it is because I am using GDB IN-VM (I need remote debugging).

![image](https://github.com/NationalSecurityAgency/ghidra/assets/4244396/7eeea01b-431f-4223-a751-d331c8ed5c3c)

> Obviously, you can do this from the Interpreter using the normal windbg commands

I tried to do it this way, but I regularly got a `NullPointerException` every time the debugger stopped. I used `set stop-on-solib-events 1` as I usually do.

```
java.lang.NullPointerException: Cannot invoke "ghidra.app.services.DebuggerModelService.getTarget(ghidra.trace.model.Trace)" because "this.modelService" is null
	at ghidra.app.plugin.core.debug.gui.objects.DebuggerObjectsProvider.setTrace(DebuggerObjectsProvider.java:413)
	at ghidra.app.plugin.core.debug.gui.objects.DebuggerObjectsProvider.traceActivated(DebuggerObjectsProvider.java:408)
	at ghidra.app.plugin.core.debug.gui.objects.DebuggerObjectsPlugin.processEvent(DebuggerObjectsPlugin.java:118)
	at ghidra.framework.plugintool.Plugin.eventSent(Plugin.java:293)
	at ghidra.framework.plugintool.mgr.EventManager.sendEvents(EventManager.java:286)
	at ghidra.framework.plugintool.mgr.EventManager.lambda$new$3(EventManager.java:49)
	at ghidra.util.Swing.doRun(Swing.java:292)
	at ghidra.util.Swing.runNow(Swing.java:208)
	at ghidra.util.Swing.runNow(Swing.java:163)
	at ghidra.framework.plugintool.mgr.EventManager.fireEvent(EventManager.java:216)
	at ghidra.framework.plugintool.PluginTool.firePluginEvent(PluginTool.java:536)
	at ghidra.framework.plugintool.Plugin.firePluginEvent(Plugin.java:456)
	at ghidra.app.plugin.core.debug.service.tracemgr.DebuggerTraceManagerServicePlugin.fireLocationEvent(DebuggerTraceManagerServicePlugin.java:824)
	at ghidra.app.plugin.core.debug.service.tracemgr.DebuggerTraceManagerServicePlugin.lambda$prepareViewAndFireEvent$12(DebuggerTraceManagerServicePlugin.java:817)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

> If you'd like, I can put a ticket in for that (probably not a lot of work)

I would be very grateful to you, because I think this function is useful for debugging. At least in my practice, I often have to deal with this and so far I can't fully use the Ghidra Debugger, because every time I restart the target (I do this very often), I need to do a lot of operations in order to get to the right destination (my goal is not an executable file, but a shared library).

**Comment by d-millar** [comment]
@saruman9 Big apologies, I apparently have confused issues!  I somehow thought you were using the dbgeng agent, not the gdb agent!

We haven't implemented the Events/Exceptions nodes on gdb - will put in a ticket for that - which means for now you're stuck with what you can do with the command line.  I believe @nsadeveloper789 has already put in a ticket for some form of auto-refresh for the modules.

Again, apologies.
