### ISSUE TITLE
Assume contiguous functions by default

### ISSUE THREAD

**Issue by Tim---** [NationalSecurityAgency/ghidra#4573]
**Is your feature request related to a problem? Please describe.**
When decompiling binaries, I often stumble upon functions using [tail-call optimization](https://stackoverflow.com/questions/310974/what-is-tail-call-optimization).

By default, Ghidra will not recognize the tail call, and will assume that the called function is part of the caller function. This creates functions bigger than necessary, and can mess with the stack analysis.
The problem is that detecting this situation can be tricky. The dumb way to do this is to select the function, and navigate in the selected ranges to see if some ranges are far away from each other.

I found that the Shared Return Calls analyzer can fix this problem (#1658), but it is not enabled by default.

**Describe the solution you'd like**
I think it would make sense to enable the options for the "Shared Return Calls" analyzer by default. I guess most people deal with compiled code rather than handmade assembly, and most compilers make only contiguous functions.

**Describe alternatives you've considered**
An alternative would be to warn clearly in the decompiled view that "this functions spans over other functions", similar to the inline or dead branch warnings. It would make it easier to detect and fix undetected tail calls.

**Comment by emteere** [comment]
Turning the "Assume Contiguous Functions Only" option on by default has been considered for a while.

It can cause trouble if the control flow is not clean or there is alot of shared code.

For example ARM code can use BL normally a call as a long jump.
It would make even more of a mess if it was on by default.

Malware might be another bad case, or when many functions share epilog code.

One way to fix this issue if there is a function that many routines share as an epilog, would be to turn it into an inlined function so the decompiler would drag in the code after the Shared Return Analyzer turned it into a function.

I'm leaning towards turning it on by default because as you say it does work well on clean code.
I think it should be off by default for ARM/Thumb code, unless we can detect that the code doesn't use BL as a long-jump.

**Comment by emteere** [comment]
In the interim, you can set your own defaults for this option, and save it to a named Analysis Option Configuration in the Analysis Options dialog.

Ghidra will continue to use the named set of options if you set it as default.

**Comment by Tim---** [comment]
> One way to fix this issue if there is a function that many routines share as an epilog, would be to turn it into an inlined function so the decompiler would drag in the code after the Shared Return Analyzer turned it into a function.

I did not have the pleasure to stumble upon code that uses shared returns yet, but don't you take the risk of inlining the `__stack_chk_fail` function for example, and add a lot of bloat to most functions ?

> It can cause trouble if the control flow is not clean or there is alot of shared code.
> 
> For example ARM code can use BL normally a call as a long jump.
> It would make even more of a mess if it was on by default.

I'm bugged by your example on ARM. Do you mean cases where the compiler would use an absolute jump instead of a PC-relative jump inside a function because the target branch is "too far" ?
I can see that happening on some archs, but given that the relative jumps in Thumb can go to ±16MB, I think it's unlikely for ARM. 

If it's a shared epilog, does it hurt to consider it as another (noreturn) function ?

> I'm leaning towards turning it on by default because as you say it does work well on clean code. I think it should be off by default for ARM/Thumb code, unless we can detect that the code doesn't use BL as a long-jump.

Setting it "on" for only a subset of processors probably makes sense. I also remember decompiling on some exotic archs where the switch analysis was having some trouble. Having it on would probably consider every `case` to be a different function and be a pain to fix.

> In the interim, you can set your own defaults for this option, and save it to a named Analysis Option Configuration in the Analysis Options dialog.
>
> Ghidra will continue to use the named set of options if you set it as default.

I made a custom named set of options, but I didn't see how to set it as the default. Did I miss something ?

**Comment by emteere** [comment]
We've decided to turn the Contiguous Functions Only option on by default for all processors, but the ARM processor.  It will be in the main branch, and a 10.2 release soon.

For default analysis options on/off it really is an issue of knowing that it should be on for most programs and doesn't cause alot of harm on the other programs.  The code has been tightened up a bit to fix some bad cases like jumping to the top of an existing function, or bad jumps into the middle of good code.

It can also cause extra problems if there is some badly disassembled code, say because of an undetected non-returning function that causes a bad single call to a bogus location.  The shared return with contiguous on could see that as a reall function and start adding to the mess.  It was chosen to leave it off originally because the default options were meant to be an initial do no harm, until you know you code has clean flow and can handle things that will trip it up.

Side Note: I would definitely turn this option off, at least at first with malware.  But there are others I would turn off as well.  So you could make a custom named options setting to use while looking at malware.

In the case of ARM Thumb code where a BL can be used as a long jump within a function, it would do more harm than good if that is occurring.  We'll try to get that better detected in the future.  There are currently scripts to solve the issue.  One automatically, and one by selection of the function.  IT almost could be turned on by default for ARM in most cases.  There just needs to be better detection of the BL case.

> I did not have the pleasure to stumble upon code that uses shared returns yet, but don't you take the risk of inlining the __stack_chk_fail function for example, and add a lot of bloat to most functions ?

You are right having the option off can cause functions to include more code than they should or was in the original source code.

__stack_chk_fail is really a different issue.  That is a non-returning function, not a shared return, although they can get added into the code in the same way with a jump depending on the compiler.  They would be solved in the same way with the shared return analyzer if it is done with a jump.  In a large number of binaries, __stack_chk_fail will be a call that doesn't return, so that is detected/handled a different way.

> I'm bugged by your example on ARM. Do you mean cases where the compiler would use an absolute jump instead of a PC-relative jump inside a function because the target branch is "too far" ?
I can see that happening on some archs, but given that the relative jumps in Thumb can go to ±16MB, I think it's unlikely for ARM.

In ARM Thumb code only, the compiler might use a BL which is normally a call as a long-jump within a particularly large function.  There isn't enough bits in the smaller relative branch.  The setting of the LR is lost/ignored.  This is mostly an issue with older ARM binaries/compilers however I've seen plenty of binaries that use it, even modern day compilers.  Not sure when they added the Thumb branch instructions that have a longer reach than -2048 to 2046, but old habits or code dies hard.

> If it's a shared epilog, does it hurt to consider it as another (noreturn) function ?

Normally jumping to a shared epilog adds extra compiler generated artifacts into the decompilation.  In most cases it doesn't hurt.  The shared epilog can have code that is needed to restore the function back to a normal state.  So if something is checking for that, say that the LR is in its original state, that won't be included in flow analysis.

> I made a custom named set of options, but I didn't see how to set it as the default. Did I miss something ?
The defaults will be tool specific, and it will use the last set you chose.  They are also saved into the program each time you analyze.
You just choose the named set of options you want, and it will remember the last chosen name for the next program.
When you exit, you would need to save your tool state, or else the options will revert to the default.
If you are doing headless analysis, you can set the option in the script / pre-script.  I'm not sure if you can use a named set of analysis options, but you can set them explicitly.  For example you could always turn off stack analysis.

**Comment by Tim---** [comment]
Thanks for your detailed answer ! It clears up the points that confused me. 
It is sad for ARM, but I am getting used to customizing the analyzers now, which can be pretty useful.

Also, good luck baking 10.2 ; I'll be waiting by the oven :).

**Comment by AntonKukoba1** [comment]
So is there a way to turn this option on/off anywhere in UI? I don't see it anywhere 
![image](https://user-images.githubusercontent.com/35240638/212723344-6e31aabe-a375-4bd6-8808-c43358d366cf.png)
