### ISSUE TITLE
How to access a compiler spec's `returnaddress` from the API?

### ISSUE THREAD

**Issue by frabert** [NationalSecurityAgency/ghidra#4611]
Running the following script on an x86 GCC binary results in all empty lists being reported:

```py
for func in currentProgram.getFunctionManager().getFunctions(True):
  cc = func.getCallingConvention()
  if cc is not None:
    print(cc.getReturnAddress().tolist())
```

i.e. no function has apparently a `returnaddress` specified, even though it is present in the compiler spec.

How can I access this property from the API?

**Comment by ghidracadabra** [comment]
In the python console, assuming you want the place where integer values are returned:

``` 
f = getFunctionAt(currentAddress)
dt = ghidra.program.model.data.IntegerDataType.dataType
f.getCallingConvention().getStorageLocations(currentProgram,[dt],False)
```

**Comment by frabert** [comment]
I'm actually interested in obtaining the place where a function call's return address is stored, not where its return values are stored. In the case of x86, that would be the `ESP` register, as is written in e.g. `x86gcc.cspec`

**Comment by ghidracadabra** [comment]
Ah, sorry, misread your question.  

The `returnaddress` in `x86gcc.cspec` is set for the compiler spec.  This sets a default `returnaddress` for all prototypes contained in `x86gcc.cspec.`  A prototype can set its own `returnaddress` to use instead of the default (although all prototypes in `x86gcc.cspec` just use the default).

The `getReturnAddress()` method you are calling only returns a non-empty list if the prototype has overridden the default.  The return address actually being used in this case is in the program's `BasicCompilerSpec`, but it is not publicly accessible.  Its should be a simple fix to make `PrototypeModel.getReturnAddress()` return the default if that's what it's using.  I'll take a look.

**Comment by frabert** [comment]
Either exposing the default value as `PrototypeModel.getReturnAddress()` in absence of an override, or providing access to the raw compiler spec values and keeping the behavior as it is would be greatly appreciated and much better than the current solution I use, which is to parse the XML once again to extract the value :D
