### ISSUE TITLE
6809 (6x09.sinc) : Inaccurate JSR and JMP implementations

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#4630]
**Describe the bug**

![image](https://user-images.githubusercontent.com/55233728/193223639-e8c7fa4e-92db-4067-80d5-240bc32f61c7.png)
![image](https://user-images.githubusercontent.com/55233728/193224109-d73d838f-d708-435e-a91c-6668b60ff2e6.png)

is incorrect, according to https://www.maddes.net/m6809pm/appendix_a.htm

![image](https://user-images.githubusercontent.com/55233728/193224175-62171e0c-5c6b-430e-bbdc-dccfde42d4ca.png)

This results in inaccurate decompilation/disassembly e.g.

![image](https://user-images.githubusercontent.com/55233728/193224323-52fbaaa5-45a8-4b0d-9031-19fe97b23978.png)

![image](https://user-images.githubusercontent.com/55233728/193224372-3958e925-067e-4975-ac7a-11eb60effe39.png)

**Comment by GhidorahRex** [comment]
This looks like a duplicate of https://github.com/NationalSecurityAgency/ghidra/issues/4600 at first, but that one has a disassembly error vs this one disassembling incorrectly.

**Comment by GhidorahRex** [comment]
This doesn't seem wrong, unless I'm misunderstanding your issue.
![6809_jmp_screenshot](https://user-images.githubusercontent.com/49028988/193307441-7de97588-84ef-42cb-a8f9-f65a1870fb13.png)

I have `7e f0 00` which, according to the instruction manual should branch to address `0xf000`. The instruction does branch to `f000` in my test binary. What address is your `JMP` instruction branching to?

**Comment by sad-dev** [comment]
Mine reads a pointer from f000 and tries to branch there.

![image](https://user-images.githubusercontent.com/55233728/193375118-77b7f721-0f3d-4725-ac50-c202a84c75bc.png)

I was following this writeup at https://mahaloz.re/2022/09/23/0ctf22-rev.html

a.) Get game.bin from https://github.com/shellphish/writeups/blob/main/challenges/rev/m68k/0CTF22-Vintage/game.bin
b.) Load as 6809, say no to autoanalysis and add an RWX memory block at 0x8000 of size 0x8000, initialize with 0x33
c.) Creating functions at 001e, 0974, 0A5F, etc. causes errors like these

**Comment by sad-dev** [comment]
A second thing that I'm not as sure about is the implementation of push and pull in SLEIGH:

![image](https://user-images.githubusercontent.com/55233728/193375689-67d6f5d4-0f1d-4e1f-80a2-9ec7d2078d35.png)

It doesn't appear that pull1 and push1 are symmetric? Contrast with ia.sinc (x86)

![image](https://user-images.githubusercontent.com/55233728/193375940-8893aa23-872e-4f2c-a338-e9ac01e7a6c2.png)

**Comment by GhidorahRex** [comment]
The pull1 macro is definitely off. It should be decremented then stored. I'll have to investigate the pull2 macro because it definitely feels wrong, but it might be an endianness issue.

I see the JMP issue now, as well (line 379 reads the data at the address of the immediate instead of just exporting the immediate). I think it is a straightforward fix, but I want to make sure it won't break any other instructions.

If you want to test that fix out, replace 379 with:
`tmp:2 = imm16;`
`export tmp;`

In the meantime I'll analyze the rest of the sleigh file and make sure that doesn't cause other issues.

**Comment by GhidorahRex** [comment]
After having an opportunity to read through some of the documentation on the 6809, I found a programming reference that mentioned this issue:

>Unlike most other instructions which use the Direct, Indexed and Extended addressing
modes, the operand value used by the JMP instruction is the Effective Address itself,
rather than the memory contents stored at that address (unless Indirect Indexing is used).

The same comment is included in the `JSR` instruction. Clearly, we're interpreting the indexing modes incorrectly.
