### ISSUE TITLE
Register variable references markup is often misleading

### ISSUE THREAD

**Issue by ubitux** [NationalSecurityAgency/ghidra#4672]
**Describe the bug**
The "Markup Register Variable References" toggle option in `Listing Fields` → `Operands Fields` is enabled by default but confusing more than often.

**To Reproduce**
1. `gunzip` and load the attached `test` binary into Ghidra and run analysis
2. Retype the `main` function with its appropriate prototype: `int main(int ac, char **av)`
3. Scroll down to the `puts()` calls 
4. See in Listing the `RDI` register being incorrectly inferred as `main` function argument `ac`

**Expected behavior**
Either keep `RDI` as-is or maybe name it as the argument of the function call it is going to be associated with.

**Screenshots**
![2022-10-18-014910-hai5Ai9m](https://user-images.githubusercontent.com/34467/196304587-733fe543-0039-4212-9601-79c7dd2f784f.png)

**Attachments**
- binary: [test.gz](https://github.com/NationalSecurityAgency/ghidra/files/9805273/test.gz)
- original source code:
```c
#include <stdio.h>

int main(int ac, char **av)
{
    for (int i = 0; i < ac; i++)
        printf("%d:%s\n", ac, av[i]);
    printf("end\n");
    printf("of\n");
    printf("main\n");
    return 0;
}
```

**Environment (please complete the following information):**
- OS: Archlinux
- Java Version: 11.0.16.1
- Ghidra Version: 10.1.5
- Ghidra Origin: Archlinux official packages

**Comment by ghidra1** [comment]
All register markup can be disabled via the Listing Tool Options if you prefer not to see it.
`Edit->Tool Options...->Listing Fields->Operands Field->`
- Markup Inferred Variable References
- Markup Register Variable References
- Markup Stack Variable References
  
We acknowlege that our operand markup can at times be misleading and confusing.  The inferred markup can be a particular issue since it relies on the first-use offset on register variables to identify the scope range.  Frequently, not all uses of a register for other variable is identified causing the scope to continue until taken over by another variable for the same register.  In your case, the other writes to EDI shoud be assigned to a new register variable.  Within the assembly listing this is most easily accomplished by creating an new register write reference where the register is reassiged.
