### ISSUE TITLE
Data structure loss when using archive

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#4691]
**Describe the bug**
Not really sure what's going on.  After creating a struct in an archive, cast to a variable and create fields, if I cast another field as this struct the struct reverts.  I am creating the struct first in an archive and have not committed before 2nd use, is it possibly pulling from the archive and overwriting the local copy of the struct.

This is at least the last struct I lost, but it has happened multiple times now.  Creating in the data archive first is a change in my workflow, vs linking to the archive after its created/filled out some.

```C
struct foo {
    uint16_t a;
    uint16_t b;
    undefined field_0x2;
    undefined field_0x3;
    undefined field_0x4;
    undefined field_0x5;
    undefined field_0x6;
    undefined field_0x7;
    undefined field_0x8;
    undefined field_0x9;
    undefined field_0xa;
    undefined field_0xb;
    uint16_t c;
    uint16_t d;
};
```

**To Reproduce**
1. Have program open with program archive and data type archive
2. Create named and sized structure in data type archive
3. Have one function assign this type (stack variable, unsure if this matters... probably?)
4. Create typed/named fields (this should only be applied to local type copy)
5. data type archive should be named and sized, but all undefined.  local should have named/typed fields.   I think I had struct editor closed.
6. Go-to another function and cast this type to another variable (again stack variable, unsure if this matters)
7. local copy gets reverted to named/sized but all undefined

**Environment (please complete the following information):**
 - OS: win10
 - Java Version: 11.0.10
 - Ghidra Version: 10.1.5
 - Ghidra Origin: official

**Comment by ghidra1** [comment]
I believe this may be occuring because you are resolving the type from the archive a second time.  Both the local modified one and the second resolve-from-archive have the same UniversalID.  Since it considers the types to be the same by their sourced UniversalID, but not equivalent, it defers to the specified conflict handler to decide.  The default conflict handler gives preference to type being resolved in this case and replaces the old one which you had modified.  A few of the conflict handlers would have kept your modified struct if used: `KEEP_HANDLER` (Use Existing Data Type) or `REPLACE_EMPTY_STRUCTS_OR_RENAME_AND_ADD_HANDLER` (Replace Empty Structures else Rename).  The behavior of the later one is unclear from its name but has the desired affect when the sourced UniversalID is the same.

**Comment by ghidra1** [comment]
The behavior is as intended and is not a bug.

**Comment by mumbel** [comment]
Thanks for the explanation
