### ISSUE TITLE
The difference is unclear to me between Ghidra direct and indirect references

### ISSUE THREAD

**Issue by gtackett** [NationalSecurityAgency/ghidra#4726]
### Discussed in https://github.com/NationalSecurityAgency/ghidra/discussions/4642
(I thought I had submitted a "question" issue last week on this topic (how to understand what an indirect reference type means in Ghidra). But searching open and closed issues that I submitted doesn't turn anything up, so perhaps I was wrong. Is there some chance that I _did_ create an issue but that it is somehow invisible?)
<div type='discussions-op-text'>

<sup>Originally posted by **gtackett** October  6, 2022</sup>
Ghidra has a number of indirect reference types, but I'm not sure I know how to interpret "indirect" in the context of a Ghidra reference. The built-in help doesn't clarify this.

In the context of an instruction set architecture, I understand indirect reads and writes as using the value in a register or a memory location, as a pointer to the memory location to be read or written. The destination address of an indirect call is determined similarly.

But is this also how a Ghidra indirect reference is to be used?

I ask, because Ghidra's analyzers, for the several ISAs I'm familiar with, appear always to create simple read or write references (_READ_ or _WRITE_) where one might expect indirect references with the __INDIRECT_ suffix on the reference type. Also, I believe that indirect references don't show up in the XREF column in the disassembly--that was true, anyway, several major versions back.</div>

**Comment by ghidra1** [comment]
The INDIRECT reference type is an odd duck but is used in certain situations to reflect an indirect flow of a computed call or jump through a pointer.  The INDIRECT reference implies a READ of a pointer in memory which will be used as an instruction's flow destination.  The from instruction's FlowType must be queried to clarrify the relavent instruction flow type (`Listing.getInstructionAt(ref.getFromAddress()).getFlowType()`).  In some analysis situations INDIRECT references can simply be treated like a READ since they do not refer to a destination instruction.  Other analysis may lay down computed jump/call flow references on the same instruction which do refer to the destination instruction(s).

**Comment by gtackett** [comment]
Thanks, @ghidra1 . Your response makes it clear how the reference type `INDIRECTION` specifically is intended for use where flow destination is based on dereferencing a pointer.

But it's not so clear how (or if)  that applies to the indirect data reference types that I'm most puzzled about:  (`DATA_`|`READ_`|`WRITE_`|`READ_WRITE_`)`IND`.

**Comment by ghidra1** [comment]
There is no reference type that reflects an indirect memory read/write since such a reference would in most cases be via a register value and would simply be considered a simple memory read or write.   Data flow analysis would be required to determine the origin of a memory read/write pointer.  In some cases it would be an encoded constant from an instruction (aboslute or relative) and in other cases the pointer may be computed or read from another memory location.  We do not attempt to produce different data reference types that reflect these distinctions.

**Comment by gtackett** [comment]
@ghidra1 do you have any information about the indirect data reference types I asked about in my last comment?

**Comment by gtackett** [comment]
Where the built-in help names the indirect data reference types, it does not mention that Ghidra itself makes no use of  them. That's partly why I've been scratching my head over their meaning.

You (Ghidra team) probably have many issues you want to address regarding the built-in help. Perhaps this lack of information is one that you might add to the list?
