### ISSUE TITLE
Types not applied to function signature from demangled name

### ISSUE THREAD

**Issue by jrmuizel** [NationalSecurityAgency/ghidra#4735]
**To Reproduce**
1. Download winhttp.dll from https://vsblobprodscussu5shard14.blob.core.windows.net/b-4712e0edc5a240eabf23330d7df68e77/EC6B7D3B2217F755D56B65E398D152F636CDCCFFE421E0A1C1656A0586EE4D4D00.blob?sv=2019-07-07&sr=b&si=1&sig=wUS1zcTZaoEviFvIyPbwcGP9uVebx8rhV0LzkGqkzFY%3D&spr=https&se=2022-11-12T18%3A55%3A22Z&rscl=x-e2eid-3177a19f-3d764fe3-af101058-150c75b6-session-7d06dcc5-85bc4ad9-a16859cb-2f698dbc
2. Load into Ghidra
3. Don't run auto-analysis
4. Download and apply the symbols from Microsoft symbol server
5. Run auto-analysis
6. Goto "CallWinHttpGetProxyForUrlEx" which gives us signature of `uint CallWinHttpGetProxyForUrlEx
               (longlong param_1,longlong *param_2,uint param_3,int param_4,int param_5,int param_6,
               int param_7,int param_8,int param_9,longlong param_10,longlong param_11,
               undefined8 param_12,longlong param_13)`

**Expected results**
`?CallWinHttpGetProxyForUrlEx@@YAJPEAXPEBUtagProxyResolveUrl@@KHHHHHHPEBGPEAUIGetProxyForUrlParameters@@P6AKJPEBU_PROXY_RESULT@@PEAVRefCountContext@@@Z5@Z` demangles to something more like `long __cdecl CallWinHttpGetProxyForUrlEx(void *,struct tagProxyResolveUrl const *,unsigned long,int,int,int,int,int,int,unsigned short const *,struct IGetProxyForUrlParameters *,unsigned long (__cdecl*)(long,struct _PROXY_RESULT const *,class RefCountContext *),class RefCountContext *)` which comes from demangler.com. I'd expect the function signature to be closer to that.

**Environment (please complete the following information):**
 - OS: macOS
 - Ghidra Version: 10.2
 - Ghidra Origin: Official

**Comment by ghizard** [comment]
I was hoping there would be a way to rerun the PDB Analyzer to do what you need, but the inherent issue is that it is not going to change mangled symbol to become the primary symbol, which is what the Demangler keys off of.

One option you have is to write a script to do work.  The DemangleAllScript does not want to work here, as is, because it uses the DemanglerCmd, which checks for signature mismatches and when found, prevents the new signature from being applied (return type seems to be culprit, and the I question the logic of the code).  A script you could write, would probably need to first find all functions you want to fix, clear the function and also change the mangled symbol to be the primary symbol, then run the DemanglerCmd at that address (or use the DemangleAllScript on all processed functions).

Another solution might be to re-import the program with 10.2.2 and do auto-analysis.  Then use the Version Tracking tool copy all analysis you want between your from one imported program to the other (analyzed with the older Ghidra).  Which to copy from/to would probably be up to you.  There is is also the option of using Program Diff.  I'm not sure which would be better in your situation.  One of them might allow more automated copying (maybe Version Tracking).

**Comment by ghizard** [comment]
Note that I introduced a regression in this last fix.  It has been addressed by @ghidra1 for 10.2.3.

I hope to do some fixing for 10.3 to simplify the logic before the more complicated work to address the situation where there are many symbols and function signatures at the same address.

**Comment by jrmuizel** [comment]
What was the regression?

**Comment by ghidra1** [comment]
@ghizard misstated fix version.  The fix was provided in 10.2.2 release.  This fix addressed a regression in 10.2.
