### ISSUE TITLE
Support for Sun Solaris "WorkShop" SPARCompiler C++ Demangler

### ISSUE THREAD

**Issue by cztian** [NationalSecurityAgency/ghidra#4773]
Either IDA Pro or Ghidra cannot demangle Sun Solaris C++ names (generated by WorkShop Compiler?), nor GNU binutils c++filt. I have build an executable out of Solaris source tree for "c++filt". Ghidra is the only full-featured decompiler for SPARC available today, since Hex-Rays does not include decompiler for SPARC (only disassembler).
Example: For mangled C++ name `__0Ftv2a_resolved_conditional_stmt_post_processingP6SV2A_ADN_LIST_BLOCKP6KV2A_MODULE`, demangled `v2a_resolved_conditional_stmt_post_processing(V2A_ADN_LIST_BLOCK*, V2A_MODULE*)` should be displayed.
![image](https://user-images.githubusercontent.com/14105716/204089266-ad4054fb-149d-49cf-afa2-8c59ecde3395.png)
![image](https://user-images.githubusercontent.com/14105716/204089292-db6b993e-4b24-4e4f-b93a-3b5e4553c223.png)
![image](https://user-images.githubusercontent.com/14105716/204089525-3df7d06c-7d32-499c-9a7d-94bcc3c5046b.png)
https://docs.oracle.com/cd/E19957-01/802-3043/802-3043.pdf

**Comment by ghizard** [comment]
> https://docs.oracle.com/cd/E19957-01/802-3043/802-3043.pdf

This document does not appear to have the name-mangling pages that provided the image for.
Do you have a link to the document that can be found on the Oracle site?

**Comment by ghizard** [comment]
@cztian I've never looked at the Solaris source.  Is it easy to find? On Mercurial or other?  What steps did you use to build their c++filt? I'm not sure that we would include a build of their c++filt or not, but it would be helpful for creating tests if we work this issue.

Could you tell us some of the "About Program" attributes for the binary you are analyzing, including "Executable Format", "Compile ID", and "Compiler"? Currently, we use some of this information to help select which demanglers should be available for a binary under analysis (note: this area needs improvement in Ghidra; issues with Cygwin, etc.)

On another note, in the short term, there's a chance that you could replace the current c++filt in ghidra (rename the delivered version) with one that you have built and it might work (I think it would consider a non-windows PE to be an ELF).  There's are lots of places it could fail, such as with needed command line options and parsing of its output.

**Comment by cztian** [comment]
![image](https://user-images.githubusercontent.com/14105716/204454660-ec0a5268-7c6e-4715-b811-d5b55b24873e.png)
![image](https://user-images.githubusercontent.com/14105716/204454699-8781de7f-6f41-40c7-bacd-4446e1db04a4.png)
`maxplus2.80.sol.patched: ELF 32-bit MSB executable, SPARC, version 1 (SYSV), dynamically linked, interpreter /usr/lib/ld.so.1, not stripped`

**Comment by cztian** [comment]
> @cztian I've never looked at the Solaris source. Is it easy to find? On Mercurial or other? What steps did you use to build their c++filt? I'm not sure that we would include a build of their c++filt or not, but it would be helpful for creating tests if we work this issue.
https://github.com/Arquivotheca/Solaris-8/blob/2.8/osnet_volume/usr/src/cmd/sgs/sgsdemangler/common/dem.c

**Comment by cztian** [comment]
> This document does not appear to have the name-mangling pages that provided the image for. Do you have a link to the document that can be found on the Oracle site?

[mangling.pdf](https://github.com/NationalSecurityAgency/ghidra/files/10110652/mangling.pdf)

**Comment by ghizard** [comment]
We considered several options of how we might address this issue ranging from not feasible due to licensing to a likely candidate of writing an ANTLR parser and testing against test symbols generated with a compiled c++filt.
However, given the amount work and its lower priority compared to that of other work we have to do, it is unlikely that it would get addressed any time soon.

The fourth route would be for you to try the c++filt, as suggested earlier to see if/where it fails, and then to follow-up with your writing a script to do the various pieces required to place the labels on the program.  I'm not sure if this is a route that you would like to try.  You could study source we have in a variety of our scripts and analyzers to put your own script together.  You could copy code to put into your script.  You might want to look at GnuDemangler, GnuDemanglerOptions, and GnuDemanglerParser for how they play in demangling and applying GNU symbols.  Note that if you tried to use DemanglerCmd, it might prevent you from using your demangler.  That is why I'm not suggesting you use it, but it might work.  Also note that our native c++filt programs are: demangler_gnu, demangler_gnu_v2_24, demangler_gnu_v2_33_1 in the GPL section.

**Comment by cztian** [comment]
![image](https://user-images.githubusercontent.com/14105716/206338788-75b865ed-7526-4190-b746-95494582fdc6.png)
![image](https://user-images.githubusercontent.com/14105716/206338948-902bdc7e-656e-4c62-a49f-6e5fd4b64015.png)

Updated: Deprecated GNU Demangler in format "ARM" works for WorkShop Compilers 4.2!

**Comment by ghizard** [comment]
I'm glad that works for you!
