### ISSUE TITLE
getFunctionsNoStubs() and isExternal() do not work as expected

### ISSUE THREAD

**Issue by fzuo** [NationalSecurityAgency/ghidra#4809]
-----------------------------------------------------------
#sample code
		funcs_All = fm.getFunctions(True)
		funcs_Real= fm.getFunctionsNoStubs(True)
		funcs_Ext = fm.getExternalFunctions()

		print("---------External_functions---------")
		for func in funcs_Ext : 
		     print("Function: {} @ 0x{}".format(func.getName(), func.getEntryPoint()))
    
		print("---------Real_functions---------")
		for func in funcs_Real: 
		     print("Function: {} @ 0x{}".format(func.getName(), func.getEntryPoint()))

-----------------------------------------------------------
#Question
I found when I use getFunctionsNoStubs(), I will the same list of functions as obtained from getFunctions() including glibc functions which should be external functions.
If I use isExternal(), I also found all functions return False. 
I don't know whether this is a bug that should be fixed, or did I do anything wrong?

Thanks for your help in advance and I look for anyone's response.

----------------------------------------------------------
#comments
getFunctionsNoStubs() should return an iterator over all REAL functions in address (entry point) order (real functions  have instructions, and aren't stubs). But, it does not work as expected. In fact, it almost has the same implementation as getFunctions(boolean forward). 

		public FunctionIterator getFunctions(boolean forward) {
				return new FunctionIteratorDB(false, forward);
		}

		public FunctionIterator getFunctionsNoStubs(boolean forward) {
				return new FunctionFilteredIterator(new FunctionIteratorDB(false, forward));
		}

Both return all functions considering:

		/**
		 * Construct a function iterator over all functions.
		 * @param external if true only external functions, else
		 * functions within program memory regions
		 */

		FunctionIteratorDB(boolean external, boolean forward) {
			if (external) {
				it = program.getSymbolTable()
						.getSymbols(
							new AddressSet(AddressSpace.EXTERNAL_SPACE.getMinAddress(),
								AddressSpace.EXTERNAL_SPACE.getMaxAddress()),
							SymbolType.FUNCTION, forward);
			}
			else {
				it = program.getSymbolTable()
						.getSymbols(program.getMemory(), SymbolType.FUNCTION, forward);
			}
		}
Is this a bug?

**Comment by ghidra1** [comment]
The `getFunctionsNoStubs` is a legacy method which is no longer relavent and has the same behavior as `getFunctions`.  Bother of these methods iterate over non-external functions.   At one point in time we had created fake functions on Import Address Table pointers which has long since been eliminated.  These fake function were referred to as stub functions which were filtered out by this method.  

The `getFunctions` method will include thunk functions which may thunk an external function.  You can test for thunk functions and ignore them and/or get the function be thunked and check to see if it is external.

`
function.isThunk() && function.getThunkedFunction(true).isExternal()
` 

The `getFunctionNoStubs` methods should be eliminated and will be depricated in the next release.

**Comment by ghidra1** [comment]
This is working as intended.
