### ISSUE TITLE
How to stop structure editor from going to last item

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#4820]
How do you prevent the highlight from going to bottom of structure after a change.

I am filling in the structure from decompiler and have the editor open to verify other surrounding data and everytime I name something the cursor moves to the bottom.  I can't find anything obvious in settings.

Why the bottom, why not the line after the line changed.. but really why move at all as a default?

**Comment by dragonmacher** [comment]
That API is quite complicated.   The last item as as default makes sense when the editor first is shown.  But, I would expect the editor to preserve the last selected row, perhaps with some assumptions about how to update the selection after a selected row(s) is deleted.

If you add a set of specific steps that show the annoying behavior, then we can try to figure out if that case is intentional or just an oversight.

**Comment by mumbel** [comment]
1. open code browser with a program
2. create a large structure `foo` of sufficient size that scrolling would be needed in the structure editor
3. create a `int bar` as the first field
4. keep structure editor window open with cursor on `bar`
5. open python window
6. `getDataTypes("foo")[0].getDataTypeAt(0).setFieldName("baz")`
7.  cursor will now be on row after last element

**Comment by dragonmacher** [comment]
Thanks for the info.

In this case, I can see that the editor is reloading the newly changed data type completely, which is clearing any existing selection (unintentionally, I believe).   We can look into preserving the selection in this case, as I cannot see any reason why we should not.
