### ISSUE TITLE
Can't import from SystemKernelExtensions.kc on ARM64 macOS 13.0.1 

### ISSUE THREAD

**Issue by jrmuizel** [NationalSecurityAgency/ghidra#4827]
**To Reproduce**
1. Go to Import file and choose /System/Library/KernelCollections/SystemKernelExtensions.kc
2. In the Container File Detected dialog choose "File System"
3. Try to import "System/Library/Extensions/acfs.kext"
4. Get "Unable to import file acfs.kext". Cause: invalid start position: 0

**Environment (please complete the following information):**
 - OS: macOS 10.13
 - Java: 17
 - Ghidra Version: 10.2.2
 - Ghidra Origin: official

**Comment by ryanmkurtz** [comment]
I'm reproducing this.  I think i just need to add support for `LC_FILESET_ENTRY` to `MachoPrelinkFileSystem`.

**Comment by ryanmkurtz** [comment]
> I'm reproducing this. I think i just need to add support for `LC_FILESET_ENTRY` to `MachoPrelinkFileSystem`.

For my own future notes: the issue is actually that XML integer values are being read as hex instead of decimal.  Fixing that though reveals more problems, such as the  chained fixups not working because the file offsets are not being adjusted when the extracted Mach-O is put into its own provider which starts at 0.
