### ISSUE TITLE
Function's Stack Depth Change and Fallthrough Override doesn't work?

### ISSUE THREAD

**Issue by lab313ru** [NationalSecurityAgency/ghidra#484]
I have a function that uses data exactly placed after its call (function calculates data size based on data content) and then jumps over the data. I've tried to specify that size using StackDepthChange feature, but it doesn't work.

![изображение](https://user-images.githubusercontent.com/7189309/56470750-88661c80-6452-11e9-9d92-4884858bb717.png)

Decompiler should show two lines of `print_text` calls.

**Comment by lab313ru** [comment]
Fallthrough override doesn't work too:

![изображение](https://user-images.githubusercontent.com/7189309/56470925-c5331300-6454-11e9-8d6d-b9ae2fc2f83e.png)

**Comment by emteere** [comment]
These setting generally only work in the assembly listing.  Stackdepth would definitely not work since the decompiler would need to calculate the target location.  Fallthrough override is an easy potential if the decompiler paid attention to it.  This is a possiblity in the future as a simple pcode override.

One possiblity is to inline the called function, which should cause flow to the correct location.  However it will drag in the functions code to your function.

The alternative is to create a general call-fixup that is added to the .cspec file to describe the implicit side-effects that happen for the particular call.  This isn't necessarily the best method, since you would need to share the .cspec with others working on the same binary.  We have/are discussing the ability to inject pcode for this type of situation, since your situation is similar to other situations, but the details are unique.

**Comment by carlreinke** [comment]
I'm in a similar situation, with a software interrupt that consumes 3 bytes from the instruction stream.

![image](https://user-images.githubusercontent.com/11667451/63652306-26793480-c71c-11e9-8e33-b6a6e851628b.png)
![image](https://user-images.githubusercontent.com/11667451/63652410-23327880-c71d-11e9-8f6f-abfcd2d34a64.png)

**Comment by lab313ru** [comment]
Still doesn't work.

If some function gets a data from the code that follows after a call, it's impossible to specify that it will skip these bytes.

**Comment by lab313ru** [comment]
They've fixed it in ca44ae9a5970dfe6fa39d43f562c124ddeca6bd4.

**Comment by beketata** [comment]
1. I'm sorry, but it doesn't work in this (latest?) build: ghidra_9.1-BETA_DEV_20190923

![1](https://user-images.githubusercontent.com/7413903/67555278-ca8a5680-f732-11e9-8043-d7ba2adc8b59.jpg)

![2](https://user-images.githubusercontent.com/7413903/67555304-d413be80-f732-11e9-9e95-493f47b10c7c.jpg)

2. > emteere: One possiblity is to inline the called function, which should cause flow to the correct location. 

Unfortunately it's also doesn't help.

3. > emteere: The alternative is to create a general call-fixup that is added to the .cspec file to describe the implicit side-effects that happen for the particular call.

Could you kindly provide an example of this call-fixup ?
