### ISSUE TITLE
Pcode disassemble error (caused by unsupported ELF relocation)

### ISSUE THREAD

**Issue by Muqi-Zou** [NationalSecurityAgency/ghidra#4859]
**Describe the bug**
For the function "decode_syncpoint",  pcode is not disassembled correctly, which causes the decompilation being suspended:
![Screenshot from 2022-12-29 21-55-25](https://user-images.githubusercontent.com/54459497/210029843-8fde6b42-4ae3-44a0-b85a-5a1d00311679.png)

The binary is attached, use latest version of ghidra with default setting can reproduce it.
[nutdec.zip](https://github.com/NationalSecurityAgency/ghidra/files/10322917/nutdec.zip)

And the source code can be found:
https://github.com/FFmpeg/FFmpeg/blob/54b29e1656979a6879221c0d2d0b50cc91e43bdc/libavformat/nutdec.c#L626

**Comment by astrelsky** [comment]
> The issue is that the `ff_crc04C11DB7_update` function is being incorrectly marked as non-returning.  As a workaround, you can import and analyze the binary again with the `Non-Returning Functions - Discovered` analyzer deselected.
> 

This is a problem 99% of the time in my experience.

**Comment by emteere** [comment]
The real issue is the unhandled relocation type 42(0x2a) on the MOV instruction @0x1012b after the call's to that function that makes the non-returning analysis detection think that the function is non-returning. This occurs after many instructions triggering the function to get set to non-returning.

Many times it appears to be an issue with the non-returning analysis, but usually is just a symptom of another problem.  To diagnose this type of issue in general, the analyzer should be disabled, analysis run, and then using the FixupNoReturnFunctionsScript analyzer to see the indications why something is set to non-returning.

We'll take a look at doing something for the unhandled relocation.

**Comment by ryanmkurtz** [comment]
Closed by c2440f906231fc75a7f8f6940ec964af6c27af1e
