### ISSUE TITLE
Can no longer merge single data types via drag and drop

### ISSUE THREAD

**Issue by MichaelEbert** [NationalSecurityAgency/ghidra#4882]
**Describe the bug**
You can no longer drag a data type over another one in the same category to overwrite it.

**To Reproduce**
Go to the data type manager
Create 2 data types, a and b, in the same category .
Drag B on top of A.
You get a message saying "Move failed. DataType is already in this category."
**Expected behavior**
A dialog pops up saying "Replace A with B?"

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: 17
 - Ghidra Version:  commit a8cdc43bd4c885f5714f6267e6a4b29f05572bf9 (master from 2023-01-04)
 - Ghidra Origin: locally built

**Additional context**
Change seems to have occurred in commit d9af59df1a. We no longer replace datatype if we drag on to a datatype.

This feature is useful to remove duplicate data types, as it is faster than right click->Replace...->[type in name of other data type]->OK

**Comment by dragonmacher** [comment]
This was an intentional decision done to make the natural copy/move actions work as users expected.  As you mentioned, for occasionally replacing data types, the `Replace...` action is the suggested way to perform a replace operation.  For any sort of bulk operations, a script is usually used.

I'd like to better understand your workflow.   You mention that dragging is faster than using the `Replace...` action.  Does your workflow require you to frequently replace data types?

**Comment by MichaelEbert** [comment]
I had a lot of conflict types from before  #4634 was fixed. Now that it is working, the number of conflict types has gone down to basically zero so this is no longer a big issue, other than the one-time cleanup of all the old types.

**Comment by dragonmacher** [comment]
Thanks for the feedback.  We are going to close this for now, as this is not a high priority item.   We can revisit as needed.
