### ISSUE TITLE
HDPI Font Support

### ISSUE THREAD

**Issue by cmatthewbrooks** [NationalSecurityAgency/ghidra#489]
I'm on Ubuntu 18.10, specifically Xubuntu, using Ghidra 9.0.2. My laptop is a Thinkpad X1 Carbon 6th Generation with a screen resolution of 2560x1440. I set a custom DPI value in the OS so that application font sizes are bigger. It doesn't seem like Ghidra recognizes that? Is there a way to increase the font size overall for the entire application, and not just things like disassembly, etc? Right now, everything is tiny.

![ghidra_small_font](https://user-images.githubusercontent.com/3974104/56498454-bfc6de80-64cf-11e9-9be7-1a966874f4c1.png)

I noticed issue #212 but I think this is different as the font is clear if I squint...just far too small.

**Comment by ryanmkurtz** [comment]
In support/launch.properties you can try setting font.size.override to a specific font size.

**Comment by cmatthewbrooks** [comment]
Ah sweet. Yea, that seems to help with 90% of the issue and def makes it usable in my environment. Thanks!

**Comment by ryanmkurtz** [comment]
Sure thing!

**Comment by mahchiahui** [comment]
If anyone is still looking for a solution, it is possible to just increase all the icons and font size by increasing the property Dsun.java2d.uiScale in support/launch.properties. I feel it works better than just changing the fonts as the icon size also increases.

**Comment by Divan009** [comment]
@mahchiahui where would I find this property, very new to Ghidra

**Comment by ryanmkurtz** [comment]
`support/launch.properties`

**Comment by throwaway-a** [comment]
This thread needs clarification that "support" is a folder in the Ghidra root level folder structure, and "launch.properties" is a file within that folder

**Comment by sunset124** [comment]
Hello everyone, I want to change the font Ghidra. How to change? Thank you very much. Sorry about my English.

**Comment by MPINTERNATIONAL** [comment]
Duck duck better luck luck look out for the huntor

**Comment by Crazor** [comment]
> If anyone is still looking for a solution, it is possible to just increase all the icons and font size by increasing the property Dsun.java2d.uiScale in support/launch.properties. I feel it works better than just changing the fonts as the icon size also increases.

This does not work for me on macOS 11.5.2 with current Ghidra running under Temurin-17.0.1, even after changing the line from `VMARGS_LINUX` to `VMARGS_MACOS` or `VMARGS`. `sun.java2d.uiScale.enabled` is true and if I change it to false, the text will get blurry in Ghidra, because now macOS scales it up by itself.

**Comment by eventhorizon02** [comment]
"works good, lasts long time". Thanks

**Comment by omegahacker** [comment]
I'm finding that the uiScale can only be set to integer values, with 2 making it *too* big.  I'm going to experiment with setting it to 2 and then *reducing* the font size to see if that works, but if that property is supposed to enable HiDPI it kinda has to support arbitrary scaling.

This is on XUbuntu 22.04 [in a VM].  I can't install Ghidra on the native Windows host due to company policy....

**Comment by mumbel** [comment]
```
        public static final String FONT_SIZE_OVERRIDE_PROPERTY_NAME = "font.size.override";
        private static final Integer FONT_SIZE_OVERRIDE_VALUE =
                Integer.getInteger(SystemUtilities.FONT_SIZE_OVERRIDE_PROPERTY_NAME);
```
```
        public static Font adjustForFontSizeOverride(Font font) {
                if (FONT_SIZE_OVERRIDE_VALUE == null) {
                        return font;
                }

                return font.deriveFont((float) FONT_SIZE_OVERRIDE_VALUE.intValue());
        }
```
@ryanmkurtz   could that just read a float and not lose the precision?

**Comment by omegahacker** [comment]
@mumbel said:
> @ryanmkurtz could that just read a float and not lose the precision?

Just to clarify, it's the uiScale that doesn't handle fractional values.  I doubt the font size needs fractional since it's nominally in points anyway.

FWIW I'm also finding that when I set the uiScale to 2 and then *reduce* the font size, there are a random collection of menu strings and other stuff that don't respond to the font size and end up being doublesized because of the uiScale.

**Comment by dev747368** [comment]
@omegahacker you are correct about the uiScale being limited to an integer.  Kinda sucks.

The font size override was always just a quick hack, I believe it was added to make showing/demo'ing ghidra on a projector more visible.

**Comment by mpdairy** [comment]
I finally found a decent solution to this. Inside the `xpra` package there's a program called `run_scaled` that basically loads up an X11 program in a scaled Xvfb frame buffer, then connects to it. It lets you run at 1.5x scale and it somehow still lets your native window manager manage the individual ghidra windows.

https://github.com/Xpra-org/xpra

For some reason I can't run ghidra directly with `run_scaled`, but I can do:

```
run_scaled --scaled=1.5 xterm -ls
```

then run ghidra from the xterm.

This also fixes a bug I was having with using Ghidra in Xmonad, where any graph views would just rapidly flash back and forth with the main Ghidra window.
