### ISSUE TITLE
Is there a way to change Ghidra's native addressing of files?

### ISSUE THREAD

**Issue by ZPaul2Fresh8** [NationalSecurityAgency/ghidra#4930]
I'm working with a new processor module I've been writing which expects data to start at an address of 0xFF800000 which can easily be done with an offset, but the problem I'm having with this processor is that it each byte is addressed by 8 and not just 1 as Ghidra lists.

This processor is word aligned and each opcode is 2 bytes for example. So if we use NOP (x03x00) Ghidra will  list the next instruction to be at 0xFF800002 instead of the processors expected 0xFF800010. So in a nutshell Ghidra is going 1 by 1, but this processor goes 8 by 8.

Is there a way to change this in the processor module I'm writing? TIA.

TMS34010 Module I'm writing https://github.com/ZPaul2Fresh8/Ghidra_TMS34010

**Comment by astrelsky** [comment]
https://github.com/ZPaul2Fresh8/Ghidra_TMS34010/blob/fdd1372fec05850c1acf4181cd8e082f179ee763/tms34010.slaspec#L10

Try adding `wordsize=8`. The docs for the wordsize attribute state:

```
The wordsize attribute can be used to specify the size of the memory location referred to with a single address.
If a space has wordsize two, then each address of the space refers to 16 bits of data, rather than 8 bits.
If the space has size two, then there are still 216 different addresses, but since each address accesses two bytes, there are twice as many bytes, 217, in the space.
If the wordsize attribute is not specified, the size of a memory location defaults to one byte (8 bits).
```

**Comment by ZPaul2Fresh8** [comment]
I've tried that previously, it really just breaks down the byte into subsections. So now we have...

`0xff800000.0: AA
0xff800000.1: BB`

When I'd like to see...

`0xff800000: FF
0xff800008: FF`

**Comment by astrelsky** [comment]
> I've tried that previously, it really just breaks down the byte into subsections. So now we have...
> 
> `0xff800000.0: AA`
> `0xff800000.1: BB`
> 
> When I'd like to see...
> 
> `0xff800000: FF`
> `0xff800008: FF`

Oh, that's unfortunate. I guess I misunderstood the description or the word size attribute.

**Comment by ZPaul2Fresh8** [comment]
> > I've tried that previously, it really just breaks down the byte into subsections. So now we have...
> > `0xff800000.0: AA`
> > `0xff800000.1: BB`
> > When I'd like to see...
> > `0xff800000: FF`
> > `0xff800008: FF`
> 
> Oh, that's unfortunate. I guess I misunderstood the description or the word size attribute.

No worries, thanks for chiming in though.

**Comment by emteere** [comment]
What is happening with bytes 0xff800002-0xff800007?

If they are consumed as part of the NOP, then you would change your token size to  64.

```
define token ops (64)
     byte1 = (0, 7)
     byte2 = (8,15)
     ....
  ;
  ```

**Comment by emteere** [comment]
There is bit-mapped memory as is done in the 8051.  I don't think you want to use that for the code.
So if you really want to see the full 8-bit accesses, I would make bit mapped memory over the base memory that is a wordsize of 2.

This isn't a panacea, as you would need to code the access to the bit mapped memory for all data read/writes, so the bytes would occur in two places and the references would occur in one space or the other.

You mention the Data section starts at 0xF800 0000 0.  But you would use an offset.  You could use 0x0.
That would be your bit mapped memory, over 0xF8000 0000.  But the addressing of the bits would be 0x0.

It all depends on if you want to see the individual bits addressed, and the numbers the processor is using to access those bits.

Another possibility:

Sleigh is just a model.  You could see the memory however you want.  When the processor is accessing the bit memory, you can just shift the address down by 3 for wordsize 1, or 4 if you use a wordsize of 2.

**Comment by emteere** [comment]
I'd try first using raw as a wordsize of 2.  Then either just shift the bit accesses down and grab the right bit.
This would provide combined referenced space.

Or create another ram space that it bitmapped over the first byte indexed memory if all data accesses are to the bitmapped space.

**Comment by ZPaul2Fresh8** [comment]
Thanks for the suggestions @emteere, from initial interpretation I feel like that's just a work around. One problem I see with changing the byte size is disassembling, it will throw things off completely. As or now this particular problem affects ptrs and offsets pointed inside the file disassembled. I have written scripts to correct this, but I had to ask if there was a better way.

If not then I can live with running a script over the file or in certain areas when needed. I've heard about loaders possibly being a solution but at this moment that's foreign territory.

**Comment by emteere** [comment]
Having multiple ways to access the same address space can be troublesome.

For disassembly you need to keep with the byte orientation.  Sleigh is not meant for bit.  I was not suggesting it for that.
Any access can be calculated in sleigh, including accessing the correct address space.  From what I see, I'd stick with a 1-byte wordsize or 2-byte word-size for anything with code in it.  You really have to.

Interesting they actually have the low 4-bits of the bit addressing in the PC, and addresses have the low 4-bits of the bit address.  So I see your pain.

The real issue is going to be raw numbers that are passed as parameters or in memory.  There would be no pcode manipulations to tell you how the number is used.  You can possibly use PointerTypedefs for that.  We still have a little more work to do with it, but it will work for the decompiler and pointers in memory.

You may also be able to just set the global settings on pointer to shift all pointers by 4 bits.

For data offsets in memory that don't have instruction use to tell you how to interpret the number, I would use the PointerTypedef which you can configure to be in a given space, CODE/DATA, or shifted to get rid of the low 4 bits.

```
                             //
                             // dummy 
                             // ram:01234567-ram:0123558a
                             //
               01234567 12 34 57 00                   addr                 DAT_12345700
               0123456b 12 34 57 00                   TMS34010Ptr __(())   DAT_01234570
               0123456f 00                            ??                   00h
                             DAT_01234570                                                                           XREF[1]:      0123456b(*)  
               01234570 00                            ??                   00h
```
The first pointer is bad since it isn't shifted.  The second points to the right place.
This can work on bytes in memory, but also defining pointer parameters passed to functions.
Currently you have to make a typedef on a pointer to another datatype, then you get these settings.

You may be able to fix the references with a script, but the decompiler will most likely have alot of trouble interpreting them as raw numbers unless there is pcode manipulation of the number to use the number correctly.

Good luck.  You may have to play with a variety of ways, as nothing is a panacea.

**Comment by ZPaul2Fresh8** [comment]
Can I ask what this particular setting in PSPEC is used for? Does it not seem to be what I'm looking for?
https://github.com/NationalSecurityAgency/ghidra/blob/57656b567b23d31cbdc559af4766c1ec8d6a2671/Ghidra/Framework/SoftwareModeling/data/languages/processor_spec.rxg#L163****

**Comment by emteere** [comment]
The bit_mapped_address and byte_mapped_address in the default memory block section allocate memory blocks possibly mapped from one addressSpace on top of another when a program is loaded.

The bit_mapped_address tag will allocate a block that use the bytes of another block of memory in another addressSpace. Each address in that memory block will be 1-bit for each bit in the bytes in the underlying space.  It is useful if memory needs to be seen in two different ways, addressed as individual bits and as bytes.

The tag you are asking about is only for allocating, it would need to be used along with sleigh and a bit addressed addressSpace.  The 8051 uses this for a section of registers that are addressed as bits in instructions, but also as bytes.  So two addressSpaces are created in sleigh with the sleigh instructions using the right addressSpace to access the memory.
