### ISSUE TITLE
Version tracking implied match not picking up size or struct def

### ISSUE THREAD

**Issue by rollsch** [NationalSecurityAgency/ghidra#4936]
I have file 1 elf with full debug
File 2 hex with nothing

When using version tracking I often get implied matches (which are 100% correct) however the source file will be size 24 and a struct and the destination file size 1 with a length delta of 23. How can I get apply markup to copy the data type and struct size? Or better yet determine it is the same type of struct?

Same goes for the above but the implied match is in ram but with no ram dump available.

**Comment by ghidra007** [comment]
Implied matches are created when function matches are applied from other correlators and two items referenced by those functions also appear to be matches based on their locations/usage in the two matching functions. It is up to the user to corroborate whether the implied matches are good matches or not, either by inspection by eye  or by running other correlators (in your case if the structures are defined in program memory you could try running the exact or similar data correlators to see if they match).  If you determine they are matches, you can choose to accept and apply the implied match which should apply the data type to the other program. Make sure you are using the "Apply Markup" (big green checkmark) action instead of only the "Apply Match" action. The first will apply the match and the markup, the second will only apply the match and (assuming the default settings are used) will apply a matching label only. If this isn't happening, it could be there is conflicting data in the other program and it won't overwrite it by default. You can change the apply data options using the "Adjust Apply Markup Settings for Applying Matches" icon (smaller green checkmark in black box.)
