### ISSUE TITLE
Multiple processors in single program

### ISSUE THREAD

**Issue by dvsaf** [NationalSecurityAgency/ghidra#494]
Is it possible somehow to analyze different parts of a program using different processors?
For example, x86 BIOS code may contain 16-bit real mode, 32-bit protected mode and 64-bit long mode instructions in one binary image. Can I markup different kinds of "segments"?
The same for CLI mixed mode assemblies, which contains x86 code and CLI code

**Comment by emteere** [comment]
Mixed x86 modes are possible.  The artificial context registers addrsize and opsize can be used to set an area in one mode or another.

```
addrsize=(0,1)        # =0  16-bit addressing  =1  32-bit addressing   =2 64-bit addressing
opsize=(2,3)          # =0  16-bit operands    =1  32-bit operands     =2 64-bit operands
```

Using a 32-bit processor spec you would only be able to get 16/32 mode.  As long as there is really only one segment in 16-bit mode, then you will most likely get the behavior you need.

It had been discussed to add actions for setting each of these modes, similar to the ARM/Thumb disassembly.  However there can be ramifications to mixing what should be segmented memory into 32/64-bit memory, so it wasn't added so as not to encourage this mixing leading to potentially unknown odd behavior.

CLI and x86 mixed is an issue, since they are implemented with two different processor definitions.
This has also been discussed, but there are assumptions in many places that there is only one language, compiler spec, and other specifications.

One possibility, once the CLI has matured, is to include the CLI spec into the x86 processor module.

One way to handle mixed mode, for the mentioned cases, is to create multiple programs with external references to another portion of the program using a different processor when necessary.

**Comment by ryanmkurtz** [comment]
A similar enhancement request has been created for this (#510), so I'll close out this question.

**Comment by dvsaf** [comment]
Thanks for your reply!

**Comment by hanetzer** [comment]
@emteere sorry for the necrobump, but you mention it can be done. Do you think you could elaborate on exactly how this is supposed to be done, or point to some resources on the matter?

My use case is the 'BIOS Binary' entry in amd/ryzen's PSP firmware table; its the first bit of x86 code ran on such a system, and is comprised of a zlib-compressed UEFI filesystem trailed by some 'real' (whether or not real mode or what is still a mystery to me, trying to piece it together when all the docs are behind NDA) x86 code, with the last 0x10 bytes containing a jmp instruction backwards (encoded as `0xe9 0x63 0xe8`)

**Comment by emteere** [comment]
To flip modes you need to set the following context registers across the area of memory that you want to disassemble in a different mode, say 16-bit in a 32-bit program.  There can be issues as mentioned above, due to the underlying memory model.

addrsize=(0,1)        # =0  16-bit addressing  =1  32-bit addressing   =2 64-bit addressing
opsize=(2,3)          # =0  16-bit operands    =1  32-bit operands     =2 64-bit operands

16-bit set - addrsize=0, opsize=0
32-bit set - addrsize=1, opsize=1
64-bit, set - addrsize=2, opsize=2

To set them across an area of memory, select the area of memory, and use SetRegisterValues... from the listing popup menu.

As long as there isn't real 16-bit segment addressing going on with multiple segments, you can probably get away with a 32-bit program and set the 16-bit addrsize/opsize across the area that is 16-bit.

**Comment by hanetzer** [comment]
hrm. Won't let me set addr/op size to 0
