### ISSUE TITLE
High P-Code's CBRANCH is often incorrect 

### ISSUE THREAD

**Issue by niconaus** [NationalSecurityAgency/ghidra#4947]
### Discussed in https://github.com/NationalSecurityAgency/ghidra/discussions/4944

**Describe the bug**
As stated in [an earlier issue](https://github.com/NationalSecurityAgency/ghidra/issues/2736), the CBRANCH instruction often has incorrect arguments. The problem is also described in more detail in [Section 3 of this article](https://link.springer.com/chapter/10.1007/978-3-031-25803-9_7#Sec3).

**To Reproduce**
Please refer to [this issue](https://github.com/NationalSecurityAgency/ghidra/issues/2736)

**Expected behavior**
From a conversation with the Ghidra team and the earlier issue, it seems like this is intended behavior. I myself find it puzzling that this choice has been made. I think it would be good to further discuss this issue. At the very least, the documentation should be updated with a warning that the CBRANCH instruction's arguments are unreliable.

**Comment by homes410** [comment]
ActionNormalizeBranches of action name "normalizebranches" does pcode transformation in-place in a way the reporter of above issues suspect that the transformed pcode is a bit odd and need to be addressed.

But that's not true. and the referenced article doesn't even address which *extra information* of high pcode handled in decompiler even the author mentioned it. Kinda weird in some perspective like `Who benefits from omitting such non-trivial breakthrough?'

I want to name extra information added in high pcode as `clever trick` and I think those tricks found in the source code is reasonable trade-off for addressing complexity of tasks in a tolerable range.

In this point, I think the title of this issue is better to renamed as "Rework decompiler to get rid of extra information of high pcode thoroughly to match the definition of referenced paper"

**Comment by niconaus** [comment]
I'm not sure I understand your comment @homes410 . Perhaps a code example further clarifies the issues with CBRANCH I've run into.

````
100000f10
(unique, 0xd300, 1) INT_SLESS (const, 0x2, 4) , (register, 0x38, 4)
(unique, 0x10000052, 4) COPY (register, 0x38, 4)
 ---  CBRANCH (ram, 0x100000f37, 1) , (unique, 0xd300, 1)
100000f37
(stack, 0xffffffffffffffec, 4) COPY (const, 0x0, 4)
...
````

In the high P-Code above, the CBRANCH will always jump to block 100000f37, if the condition holds, or due to fall though. Looking at Ghidra's control flow information, for this example it is actually the case that if the condition does not hold, we should jump to block 100000f99. As described in the paper, I've also seen cases where the true branch is incorrect.

I'm in no way trying to get rid of information, or requesting that Ghidra adheres to any definition that I made. I think it is important that users are aware of the fact that the CBRANCH might display unexpected addresses.

**Comment by ghidracadabra** [comment]
This should certainly be clarified in our documentation.

Just to verify:  the issue is only with the inputs to the `CBRANCH` op?  The  corresponding branch in the C code produced by the decompiler is correct?

**Comment by ghidracadabra** [comment]
I'm going to close this ticket and treat the issue as a special case of #4945
