### ISSUE TITLE
Disassemble and Decompile function contains both ARM and THUMB

### ISSUE THREAD

**Issue by hax0r31337** [NationalSecurityAgency/ghidra#4959]
**Describe the bug**
These functions won't be disassembled correctly, the THUMB part will not be identified in auto analyze and i need select and disassemble manually. The decompiler won't work expected even after the manual disassemble, the thumb part will be identified as another function.    

**To Reproduce**
1. Import and analyze the file
2. Search for function have both ARM and THUMB format, `_ZN9easy_util18encryptHttpContentERKSs` in my sample
3. Select the function assembly and unidentified area, and disassemble
4. See error in assembly and decompiler doesn't work as expected

**Expected behavior**
The THUMB assembly detect and disassemble automatically and identified as one function in decompiler like [IDA does](https://paste.gg/p/anonymous/c61c8c29ec0d4df49078fcf8ff9ff677)

**Screenshots**
![image](https://user-images.githubusercontent.com/65506006/216809430-3316b501-972d-4701-ba8f-20b2c5850dde.png)

**Attachments**
The file in my case: https://drive.google.com/file/d/1mJDC5lKtmd-Yf0tcsq5kT0YENMduSYqL/view?usp=share_link

**Environment (please complete the following information):**
 - OS: Manjaro Linux with kernel `6.2.0-1-MANJARO`
 - Java Version: 17.0.6
 - Ghidra Version: 10.2.2
 - Ghidra Origin: official GitHub distro

**Comment by emteere** [comment]
I see some flow-override issues on the functions, some are getting detected as non-returning.  That could be a symptom of something else going on.  The code above looks like it is all Thumb code and seems to be disassembled correctly other than the bad flow issues.

I took a look and it appears something is wrong with the instruction:
ldr.w    r1,[pc,#-0x44]

The real value of the PC is not being used, so a relative reference is created incorrectly.
The real value of the PC is being used in instructions like "add r1,pc".

This then causes the no-return analyzer to think there is a non-returning functions from all these references after the call.

We'll fix the instruction pcode issue.  Good find as this may have been causing many other people frustration.

**Comment by sad-dev** [comment]
To clarify, does this mean functions like ``operator new`` are getting marked as no-returns due to problems with patterns like the following?

```
     04e28bf2 df f8 ac 04       ldr.w              r0,[LAB_04e290a0]
                                                                         r0 = COPY *[ram]0x4e290a0:4
...
     04e28bfe 78 44             add                r0,pc
                                                                         $U8b180:4 = INT_ADD 0x4e28bfe:4, 4:4
                                                                         r0 = INT_ADD r0, $U8b180:4
```

**Comment by emteere** [comment]
10.2.3 is out, so you'll need to use that.

There is still an issue with no-return having the evidence set too low for this binary.  After the fix there was still three things that indicated the "operator new" might be non-returning.  There was bad code after several calls to "operator new" were caused by other bad flow in the code, possibly from other non-returning functions.

So I'd push the evidence up to 10, then use the FixupNoReturnFunctionsScript to find the straggler no-return functions.

**Comment by emteere** [comment]
Your understanding is correct.  The no-return analyzer does use evidence of non-returning issues.

In this case because of a bug in the arm decode which involved instructions using the value of pc, the value was then used as an offset constant in the load later on.  This instruction was actually using the add and modify addressing mode form of the ldr.  The form is actually illegal when using the PC.

ldr.w     r1, [pc,#-0x44]!

which in pcode would have been something like:
    $u1 = sub PC, 40:4
    pc = copy $u1
    r1 = load ($u1)
    
Then set the value of the pc to something, which would then be used later on in conjunction with other instructions.  And the right set, which the program used alot, would then end up with read references right below the function.

The PC register isn't kept to a constant value and shouldn't be used this way in any calculation.  When the PC is involved Sleigh would know the value based on the current instructions address and use a constant value for the PC.

The issue would affect the decompiler too, unless it had logic to never trust any value in the PC.  Which could be problematic because you could set the PC in a sleigh instruction and use it in the sleigh instruction, say for a return.  It doesn't really hurt anything until there are assumptions that the PC will always have a good value, which is not the case.

So there are several things that I think need to be changed.
- check that the PC register is never read to get a value if it wasn't set in the instruction.  Or make sure that all instructions don't use the PC even in calculations in all sleigh languages, or this might occur in other ways.
- Have the evidence of no-return required be tied in some way to the number of calls to the function.  The more calls, the more evidence required.  With something like "operator new" if you make a mistake, it causes havoc.  However if you don't mark a function non-returning that is non-returning, the more bad flow you will have in your binary, so it is very important to identify them as early as possible to prevent collateral damage.  It is a balance.  Possibly first pass get rid of obvious no-return with alot of calls and alot of evidence.  Then go back and pick off the others candidates possibly requiring less evidence.

**Comment by emteere** [comment]
There are still a few issues with the binary after using 10.2.3, and upping the evidence.  Possibly a bad instruction, pop in the it instruction block,  some Arm/Thumb flow issues, an errant function start pattern, and not cleaning up all bad flow bookmarks.  I've been looking to see some of the root causes.
