### ISSUE TITLE
Filtering and Sorting of Symbols is slow with large numbers of symbols.

### ISSUE THREAD

**Issue by jonwilson030981** [NationalSecurityAgency/ghidra#500]
With a large number of symbols (approx 500,000), the Symbol Tree and Symbol Table panes become slow to the point of unusable when sorting and filtering symbols.

Open a large monolithic binary and load its associated symbols (e.g. using ImportSymbolsScript.py). Attempt to use Symbol Tree or Symbol Table to search symbols. Issue also occurs when using "Starts With" as "Text Filter Strategy" as well as enabling case sensitivity (e.g. attempting to simplify the filtering behaviour).

Ubuntu 18.04, OpenJDK 11.0.2, Ghidra 9.0.2

**Comment by ddbb2017** [comment]
Dude, this is not a bug it's a feature. OK, seriously, this is the downside of using Java. I've been dealing with the same issue since day one. All Ghidra tutorials that you see online deal with small Hello-world type projects. Once you open a normal size binary with its symbols, that Symbol Tree pane becomes unusable.

Solution: Don't use it. Instead, as soon as you create the project delete all existing bookmarks (lower pane) and start adding your own (thru the right-click menu.) That way it's faster to navigate through your code. (Simply double click on your bookmark in the lower pane to go there.) 

Then also use back and forward buttons. They work much faster.

Suggestion 2: Close that Symbol Tree pane as well as the one above it (Program Trees) -- this will greatly speed everything up. (If you need to study the structure of the PE/ELF file use some other tool. There's a plenty of them online.)

That's the only option that I've found so far (that doesn't involve waiting for 10 seconds or even longer for the function search to finish.)

**Comment by jonwilson030981** [comment]
I am not sure this performance issue is inherent to Java, although obviously native code is inherently faster at cpu bound tasks, this comes at the cost of portability. After all projects like Elasticsearch (also written in Java) allow very fast indexed string searching on much larger data-sets.

Rather I suspect that before its public release, it hasn't much been used on large monoliths, but on smaller applications and perhaps stripped closed source ones (lacking symbols) at that. Therefore I just don't think the implementation has had such requirements for scalability until wider use by the community has introduced more esoteric use-cases. I expect this issue along with many others will appear as the community use the tool to tackle different tasks and I hope they are able to be fixed in due course.

Thanks for the tips though on how to work around the issue in the interim though.

**Comment by dragonmacher** [comment]
Obviously, there is a natural limit to the size of data that can be reasonably processed withing given time and space constraints.

- Ghdra trees and tables will perform reasonably well with relatively large data (hundreds of thousands of symbols)
- As mentioned above, closing any Component Provider window will increase Ghidra's performance with regard to memory consumption and performing updates with visible UI elements.

As the size of binaries become larger, we update our components to handle newly discovered deficiencies.   For example, when symbol counts reach into the millions, we could ostensibly provide the ability to further restrict the data that appears in any given Component Provider.   Thus, after the initial load of the provider, the applied data set could be a much smaller subset of the universe of data, allowing for reasonable user interactions.

**So, with that being said, the best way to help us improve the user experience is to provide metrics (e.g., number of symbols in the binary) and Use Cases, with steps that expose the impaired behavior.**

Finally, Java's slowness is relative and is in most cases masked by Ghidra being a desktop application, with the UI being considerably slower than the observable performance of the language.  The only time I have ever seen Java visibly underperform compared to other languages it is when the Garbage Collector thrashing, when the JVM has consumed most of its allowed memory.  Even in this case, it is usually the programmer that allowed the JVM to get into this state in the first place.

**Comment by jonwilson030981** [comment]
@dragonmacher Thanks for the fast response, very impressed with Ghidra so far by the way (especially the de-compiler). Completely understand that as you need to process more data, you will need more memory and processing power to do so and so you will reach practical limits. 

In my case I am not processing a public domain binary and so it will not be possible for you to re-produce the exact issue. The binary in question is approx 100Mb with approx 500k symbols. It sounds like your experience shows that Ghidra would be expected to handle such a binary?

After importing the image and setting the base address (without running any analysis), typing a 4 letter filter string (without wildcards) into the Symbol Tree window takes over 5 minutes to return results. The steps to reproduce are therefore very minimal.

This makes me think it could be something environmental (I am running Ghidra in a relatively powerful VM, rather than on real hardware) if you have experienced much better performance in similar circumstances. However, performing a similar task in IDA 7 (for comparison) with the same test data returns results in a few seconds (although its search capabilities are much more limited). I have tried configuring Ghidra to search using "Starts With" and exclude wildcards to try to get a more equivalent test, but performance is similarly slow.

Do you have a any test data which you use for performance testing, or can you suggest a similar size public domain binary with a similar number of symbols which I could use to benchmark and determine whether the issue is likely related to my environment? I tried using a flat ARM binary of Linux kernel (approx 10Mb), but this had only around 50k symbols (an order of magnitude less) and the performance of filtering was approx 5s quite usable.

Thanks for your assistance.

Jon

**Comment by dragonmacher** [comment]
> Do you have a any test data which you use for performance testing, or can you suggest a similar size public domain binary with a similar number of symbols which I could use to benchmark and determine whether the issue is likely related to my environment?

We do not have any such deliverable test data.

> The binary in question is approx 100Mb with approx 500k symbols. It sounds like your experience shows that Ghidra would be expected to handle such a binary?

At 500k symbols, you may start to see appreciable slowdown, depending upon your environment.  That being said, 5 mins does border on ridiculous and is certainly unusable.  As mentioned earlier, closing unused UI components (especially tables) may help free-up memory.   When binaries approach 100M, the overall JVM will slowdown due to memory consumption, which in turn will cause Ghidra overall to feel sluggish.

Our trees are a bit slower in general than our tables.   Also, the Symbol Table does have a secondary filter (configurable via the toolbar by clicking the gear icon) that allows you to reduce the table's input set of symbols.   This may allow you to use the Symbol Table in place of the symbol tree when searching/filtering is required.

**Comment by ddbb2017** [comment]
@jonwilson030981 wow, 100 MB binary! Is it all code? Or is it mostly resources? (You can tell by the section sizes in the PE header.) Without seeing how Ghidra loads PE files, if it's a bunch of bitmaps, icons and other resources, my guess would be to try to strip those out first before doing the static analysis.

@dragonmacher I would somewhat disagree with your assessment. I ran my tests that I describe below and mostly the bottleneck was the CPU. (Specs also below.) Pretty much every action in Ghidra would peg CPU to about 50% and then to 100% for a few seconds.  As for RAM it stayed consistent and way below 50% usage level for the OS. (I was monitoring it along using a notification tray CPU, RAM and Drive [meters](https://dennisbabkin.com/ctm/).) Things got better though when I upped the specs for the virtual machine. (See at the bottom.)

First, to answer your point. If you need a large test binary with symbols, that shows a slow-down with a stock installation of Ghidra, you can use one of the Windows 10 DLL binaries. My colleague and I have been playing with 32-bit version of the `comctrl32.dll` and Ghidra is definitely showing a visible slow-down with it. Or, pick the NT kernel binary. It's way larger: `C:\Windows\System32\ntoskrnl.exe`

Here's how to repro:

**VM stats:**
VMWare Workstation 15
CPU: Intel(R) Core(TM) i9-7940X CPU @ 3.10GHz
Cores: 2
RAM: 4.00 GB
Disk (on host): Samsung SSD 850 EVO, 99.51 GB total, 29.69 GB Free

**Binary & How to Open in Ghidra:**
File: C:\Windows\SysWOW64\comctl32.dll
Size: 561 KB
OS: Windows 10 (any version)
Symbols: Download using Microsoft public symbol server at:
https://msdl.microsoft.com/download/symbols

**Ghidra:**
RAM usage: 1.5 GB (average) per all Java processes
CPU: 50%-100% when in use

Open `comctl32.dll` in Ghidra (with symbols mentioned above) and analyze with default settings. Keep all windows in Ghidra at the default layout. First off, the analysis itself takes minutes (don't know how long exactly, I had to leave it and go do something else.) Then doing pretty much anything in Ghidra would involve a noticeable slow-down. For instance, while renaming a function, even a text box will be very slow to display typed up letters.

---------------------------

Before posting this I decided to up the specs in the VM to the following:

**New VM stats:**
VMWare Workstation 15
CPU: Intel(R) Core(TM) i9-7940X CPU @ 3.10GHz
Cores: 6
RAM: 16.00 GB
Disk (on host): Samsung SSD 850 EVO, 99.51 GB total, 29.69 GB Free

**Ghidra:**
RAM usage: 0.5 GB (so far) -- I can't really explain such a sharp drop. I've opened the same project. Maybe a memory leak, since I had previous instance of Ghidra open for about a week long?
CPU: <10% when in use, altho search still pegs CPU at about 100% for a few seconds (which is normal)

As you see above, with these new (but almost unrealistic for most people) stats, Ghidra started running like a pro. I don't see hardly any slow-downs, things are still a little bit slow, but quite manageable. 

Additionally @jonwilson030981, FYI, I've found a new pane that may be handy and is not slow at all. If you go to Window -> Functions it will open a window with a list of all functions. It will originally open over the decompiler window. But you can drag it in place of the Symbol Tree window (which I would definitely close, since it's a reason of quite a measurable slow-down.) Well, that function window is also sortable and has a search box that works way fasters.

**Comment by jonwilson030981** [comment]
@ddbb2017 Unfortunately, it's just a large binary full of code and data, no resources or anything like that. I found the Functions Window much quicker also, but still borderline unusable (about 30 seconds to search with the most basic search settings enabled). I'm hoping to trial performance on physical hardware to rule out anything related to VM resource contention.

**Comment by dragonmacher** [comment]
@ddbb2017 Thank you for the data.

As I'm sure you can imagine, it is quite difficult to compare performance across different hardware and OS versions, even more so when VMs are used.   The easier it is for us to reproduce the behavior, the higher the likelihood of the problem being addressed.   The data you provided should help us get close to the issue.

In my mind, the questions to be addressed for this ticket can be distilled to these primary concerns:

1. Can we improve the functionality of the Symbol Tree specifically in order to have it be more responsive for reasonably sized data?
2. Can we improve generally all Trees and Tables to be more responsive for reasonably sized data?
3. What improvements can be made for Trees and Tables to remain functional for unreasonably large data?

**Comment by jonwilson030981** [comment]
@ddbb2017 Thanks for the data, unfortunately I don't have anything I can share my end.

@dragonmacher That sounds like a good approach. Perhaps it's worth clarifying what is a "reasonable" size for data, what a reasonable hardware specification might be and what sort of response time should be expected within these limits? Then perhaps rely on best efforts outside these paramters?

**Comment by dragonmacher** [comment]
@jonwilson030981 Ha.  Yes, I was intentionally vague on this point.   Once we have done some testing, then we will have a better idea of reasonableness.

**Comment by ddbb2017** [comment]
@jonwilson030981 it sounds like you need a beefier hardware to run it on. It sure improved performance in my case.

On the side note, it just dawned on me. A general recommendation for native (Windows) developers is to break up code into smaller (more manageable) DLLs. But now I see that bunching it all up into one monolithic code chunk might be the way to protect against static analysis. Hmm...

**Comment by jonwilson030981** [comment]
I have done a little more investigation.  I have worked around the problem by creating my own plugin. 

Using the API **_"Program".getSymbolTable().getSymbolIterator(String searchStr, boolean caseSensitive)_** on the other hand took several minutes. I didn't do any detailed analysis, but a quick look at the code seemed to show that perhaps each symbol was being loaded in turn from the backing store and then filtered?

Using the API **_"Program".getSymbolTable().getAllSymbols(boolean includeDynamicSymbols)_** (passing false) gives me all of the symbols in a handful of seconds. 

My plugin caches all of the symbols in a TreeMap<String,Address> and uses **_UserSearchUtils.createContainsPattern(String input, boolean allowGlobbing, int options)_** to build a Pattern object. This is used to filter the symbol data which is displayed in a simple JTable. 

It's not very pretty, but it works pretty well for my needs. Hope this is useful in narrowing down the potential bottle-neck.

**Comment by dragonmacher** [comment]
Thanks for the info. 

Does your table have roughly the same number of rows after it is loaded?

I am trying to determine whether the slowness you are seeing is due to the size of the table or something specifically related to the filtering.

**Comment by jonwilson030981** [comment]
The SymbolTable window has about 650k symbols. If I pass true to **_getAllSymbols_** (e.g. include dynamic symbols). I see about 2.4M (taking about 2 seconds to search), with the flag set false it has around 470k and searching is instantaneous. Not sure why I am seeing a different number in each case.

Hope that helps.

**Comment by shuffle2** [comment]
This is slightly off topic but also in the "ghidra is slow" realm: as someone who's worked with multi-gigabyte files in IDA, I feel like trying to do the same in ghidra would be impossible. Performing initial tasks (auto-analysis, version diffing) on a 30MB x64 kernel ELF is already quite slower than IDA.

I assume the ghidra team already has a good idea of the performance-critical code paths(?). I haven't used Java for ~10 years; are there any pointers for the community to profile performance and start improving the situation in a general sense? Just observing core usage during ghidra processing, it's easy to see work is not affinitized in a good way and overall utilization is low.

To veer further off-topic, is there a way for end-users to just throw compute at ghidra until it becomes more performant? Can the UI be connected remotely to the actual tools in some way?

**Comment by ddbb2017** [comment]
I'm just curios, ppl, everyone keeps mentioning multi-GB binaries. Can someone give me an example of one? Where does it even come from?

If it's some vendor product, wouldn't they break it up into DLLs? I mean they need to sell that sucker somehow, don't they? And if so, how would it even run on customers machines with, say, 3GB of RAM? It will grind their system to a halt.

And if it's malware, how would it even spread with such huge binary? Email is out of the question, and having a downloader for such monster would be a total fail on the malware part.

**Comment by shuffle2** [comment]
@ddbb2017 at least in my case, large input files are typical memory dumps of some sort or another (from debug tool, or just a flat physical memory dump for examples). However, I'm aware of projects which do use multi-GB PE files in production. These are typically large web apps that get compiled into a single file for "reasons". Another nice stress test would just be to load chrome with full pdb (which are made publicly available by google's build system) into ghidra, or any other Very Large C++ App With Scary Symbols.

**Comment by jonwilson030981** [comment]
Thanks for the fix. Looking forward to 9.2 to try it out.

**Comment by dragonmacher** [comment]
We have rewritten the structure of GTree nodes for 9.2.    Large tree performance has gone from unusable in the degenerate case to being relatively fast.

We have also made a handful of changes to tables in general and specifically to the Symbol Table and Functions Table.    These changes have addressed some degenerate cases that caused these two tables to become unusable.

Some notes for getting the best performance from tables:

- When filtering, most columns are checked for a match against the filter text.  Thus, to improve filtering performance, remove any unused columns.
- You can disable sorting if you do not need it by Control-clicking the sorted header.   This will remove one of the 2 default steps when loading a table.
- Sorting a filtered table is fast.   This is because we only sort the filtered data set.
- Some columns are now ignored for filtering.   As an example, the 'Reference Count' and 'Offcut Ref Count' columns no longer get filtered.  Often for numeric columns it does not make sense to filter for an exact value.  
- All columns can be filtered using the Column Constraints filtering mechanism.  This is independent from the filter text field below the table.  You can access this feature by pressing the second button to the right of the filter text field.
- The Symbol Table now defaults to only filtering on the 'Name' column.  To change this, de-select the 'Name Only' checkbox to the right of the filter text field.  This increases filter time by not examining any other column values.
- The initial filter (or sort of the 'Name' column) will be slow.  Any follow-up sorts and filters will used the cached name values, greatly increasing performance.

**Comment by jonwilson030981** [comment]
Great stuff. I see 9.1 is in beta. Did you have any timescales for 9.2 yet?

**Comment by dragonmacher** [comment]
> Great stuff. I see 9.1 is in beta. Did you have any timescales for 9.2 yet?

The short answer is no.  The hope is that 9.2 will be out sooner than later, with a focus on performance improvements.  Keep in mind that you can use the master branch by creating a build or running in a development environment.

https://github.com/NationalSecurityAgency/ghidra/blob/master/DevGuide.md
