### ISSUE TITLE
GhidraScript askInt accepts invalid input

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#5028]
**Describe the bug**
The GhidraScript method `askInt` will accept an invalid integer value. If you specify a value that is to large for an int it will be silently ~~truncated~~.

**To Reproduce**
1. Use `askInt`
2. Enter `0x123456789`
3. Printing the entered value yields `0x23456789`

**Expected behavior**
Same behavior as `askLong`

**Environment (please complete the following information):**
 - Ghidra Version: 10.3_DEV

**Comment by foralost** [comment]
Working on it.
Commit should appear today.

**Comment by foralost** [comment]
Well, there might be I think another bug with that:
![image](https://user-images.githubusercontent.com/28221162/221994920-e75d4630-3e03-409c-8ef9-b6799e034a14.png)
Because we check if the overflow would happen with 0x, but we are not doing it with decimal system. It happens both with askInt and askLong.

I think the solution would be to change respectively `return bi.intValue() * sign;` and `return bi.longValue() * sign;` (both can be found at Framework Generic /src/main/java/ghidra/util/NumericUtilites.java; lines 172, 126; in my PR) to `return bi.intValueExact() * sign` and 'return bi.longValueExact() * sign', to enforce no truncating regardless of the number system.

**Comment by foralost** [comment]
Well, the issue I think is solved in the PR#3057.
My previous preposition could be in another issue, because there are multiple occurrences of this problem in NumerUtilities.java, and kinda goes out of scope of this issue.
