### ISSUE TITLE
i386: Relocation incorrectly applied to GOT entry

### ISSUE THREAD

**Issue by yifanlu** [NationalSecurityAgency/ghidra#52]
**Describe the bug**
In an i386 ELF binary, an GOT entry is incorrect which leads it to display the wrong symbol information.

**To Reproduce**
1. Download the ELF here: http://pwnable.kr/bin/hash
2. Load into ghidra with all the default options
3. Go to `0x0804b008`
4. See `0804b008 04 c0 04 08     addr       srand                                            = ??`

**Expected behavior**
The GOT entry should point to `getchr`

Tested with Hopper, IDA Pro, and Cutter, and all produce the expected result. It appears that Ghidra is performing the relocation on that GOT entry but it's doing so incorrectly.

```
           080486f0 08 b0 04 08 07  Elf32_Rel                         [2]
                    03 00 00
              080486f0 08 b0 04 08     ddw       804B008h                r_offset      location to apply 
              080486f4 07 03 00 00     ddw       307h                    r_info        the symbol table i
```
```
           08048208 1e 01 00 00 00  Elf32_Sym                         [3]
                    00 00 00 00 00 
                    00 00 12 00 00
              08048208 1e 01 00 00     ddw       11Eh                    st_name       getchar
              0804820c 00 00 00 00     ddw       0h                      st_value
              08048210 00 00 00 00     ddw       0h                      st_size
              08048214 12              db        12h                     st_info
              08048215 00              db        0h                      st_other
              08048216 00 00           dw        0h                      st_shndx
```

**Comment by gibbed** [comment]
If I'm reading the code correctly, this type of relocation isn't supported currently.

`ghidra\app\util\bin\format\elf\relocation\X86_32_ElfRelocationHandler.java` (found in `Ghidra\Processors\x86\lib\x86-src.zip`):

```java
			// TODO: Cases not yet examined
			// case ElfRelocationConstants.R_386_32PLT
			// case ElfRelocationConstants.R_386_TLS_IE:
			// case ElfRelocationConstants.R_386_TLS_GOTIE:
			// case ElfRelocationConstants.R_386_TLS_LE:
			// case ElfRelocationConstants.R_386_TLS_GD:
			// case ElfRelocationConstants.R_386_TLS_LDM:
			// case ElfRelocationConstants.R_386_TLS_GD_32:
			// case ElfRelocationConstants.R_386_TLS_GD_PUSH:
			// case ElfRelocationConstants.R_386_TLS_GD_CALL:
			// case ElfRelocationConstants.R_386_TLS_GD_POP:
			// case ElfRelocationConstants.R_386_TLS_LDM_32:
			// case ElfRelocationConstants.R_386_TLS_LDM_PUSH:
			// case ElfRelocationConstants.R_386_TLS_LDO_32:
			// case ElfRelocationConstants.R_386_TLS_IE_32:
			// case ElfRelocationConstants.R_386_TLS_LE_32:
			// case ElfRelocationConstants.R_386_TLS_GOTDESC:
			// case ElfRelocationConstants.R_386_TLS_GOTDESC:
			// case ElfRelocationConstants.R_386_TLS_DESC_CALL:
			// case ElfRelocationConstants.R_386_TLS_DESC:

			default:
				appliedSymbol = false;
				markAsUnhandled(program, relocationAddress, type, symbolIndex, symbolName,
					elfRelocationContext.getLog());
				break;
```

**Comment by rvolgers** [comment]
Nah, relocation type is `(r_info & 0xff) == 0x7 ==  ElfRelocationConstants.R_386_JMP_SLOT`, which is handled.

**Comment by gibbed** [comment]
@rvolgers Oh, I was going by the output pasted which showed r_info as 0x12.

**Comment by ryanmkurtz** [comment]
This is caused by a bug in the ELFSymbol equals() and hashcode() methods.   This bug surfaces when multiple symbol tables are present in the ELF binary and can impact the processing of the GOT, PLT, and relocation processing for any processor.  A fix for this will be included in our next release.

**Comment by coverclock** [comment]
I installed the 9.0.1 on my x86_64 Ubuntu desktop, created a new project from scratch, and imported a shared object compiled for an ARM7L target and am still seeing Ghidra get confused about what symbols are where due to the incorrect 0x10000 offset. When I compare the output of objdump for the same file and run the ARM7L target itself, I can see that Ghidra has the disassembly for the function diminuto_cue_debounce correct, but because of the incorrect offset, it places it in the middle of an entirely different object module (diminuto_controller) and proceeds to interpret the variables as if they were in that module (e.g. "numerator" etc.), not in diminuto_cue. Remarkably, the decompile for diminuto_due_debounce seems reasonable. Maybe this is a different bug... but it sure seems like this bug. Here are links to my screen snapshots.

[Ghidra version](https://flic.kr/p/2foP1RZ)

[nm run on the target](https://flic.kr/p/2foP1Uz)

[objdump run on target](https://flic.kr/p/2foP21r)

[Ghidra run on host](https://flic.kr/p/2foP27D)
