### ISSUE TITLE
buildNatives fails for linux_arm_64

### ISSUE THREAD

**Issue by haai** [NationalSecurityAgency/ghidra#5204]
**Describe the bug**
I want to execute the `support/buildNatives` script on `linux arm64/aarch64` in a vm on macos apple silicon but the scripts returns with an error. Do I miss something?

**To Reproduce**
`$ support/buildNatives`

**Expected behavior**
script runs sucessfully

**Screenshots**
```
 support/buildNatives   
Building natives in Ghidra...
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment (build 17.0.6+10-Debian-1)
OpenJDK 64-Bit Server VM (build 17.0.6+10-Debian-1, mixed mode, sharing)
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true

> Configure project :Debugger-swig-lldb 
OS: Linux
Arch: aarch64
Using platform: linux_arm_64
Debugger-swig-lldb:buildNatives skipped - LLVM_HOME not defined

> Configure project :Decompiler 
OS: Linux
Arch: aarch64
Using platform: linux_arm_64

> Configure project :PDB 
OS: Linux
Arch: aarch64
Using platform: linux_arm_64


FAILURE: Build failed with an exception.

* Where:
Script '/home/parallels/dev/ghidra/ghidra_10.2.3_PUBLIC/GPL/nativeBuildProperties.gradle' line: 87

* What went wrong:
Could not find method get() for arguments [] on platform 'linux_arm_64' of type org.gradle.nativeplatform.platform.internal.DefaultNativePlatform.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
```

**Environment (please complete the following information):**
 - OS: `Linux kali-linux-2022-2 5.18.0-kali5-arm64 #1 SMP Debian 5.18.5-1kali5 (2022-07-04) aarch64 GNU/Linux`
 - Java Version: `openjdk-17-jre/jdk`
 - Ghidra Version: 10.2.3
 - Ghidra Origin: Github

**Comment by ryanmkurtz** [comment]
It used to work, but I haven't tested it in a while.  What version of gradle are you using?

**Comment by ryanmkurtz** [comment]
I just tried it on an Ubuntu 22.04 VM running on an M1 host and it worked without an issue.  I used openjdk 17 and gradle 8.0.2. I also had make, gcc, and g++ installed which are requirements of the build.

**Comment by haai** [comment]
First of all, thanks @ryanmkurtz .. the response time was phonomenal. But could not test it anymore yesterday.
And you gave me a clue about gradle. Somehow I missed to check that point and it was really old `Gradle 4.4.1` installed.
So update to `Gradle 8.0.2` and it works fine. Thanks you :)

**Comment by lhtzei6** [comment]
> I just tried it on an Ubuntu 22.04 VM running on an M1 host and it worked without an issue. I used openjdk 17 and gradle 8.0.2. I also had make, gcc, and g++ installed which are requirements of the build.

what's gcc version?

**Comment by lhtzei6** [comment]
> I just tried it on an Ubuntu 22.04 VM running on an M1 host and it worked without an issue. I used openjdk 17 and gradle 8.0.2. I also had make, gcc, and g++ installed which are requirements of the build.

./buildNatives --info
Building natives in Ghidra...
Initialized native services in: /root/.gradle/native
The client will now receive all logging from the daemon (pid: 430883). The daemon log file: /root/.gradle/daemon/6.8.3/daemon-430883.out.log
Starting 4th build in daemon [uptime: 12 mins 16.733 secs, performance: 99%, non-heap usage: 18% of 256 MiB]
Using 64 worker leases.
Watching the file system is disabled
Starting Build
Settings evaluated using settings file '/home/lht/ghidra_test/ghidra_10.1.2_PUBLIC/Ghidra/settings.gradle'.
Projects loaded. Root project using build file '/home/lht/ghidra_test/ghidra_10.1.2_PUBLIC/Ghidra/build.gradle'.
Included projects: [root project 'Ghidra', project ':Debugger-swig-lldb', project ':decompile', project ':Decompiler', project ':PDB']

> Configure project :
Evaluating root project 'Ghidra' using build file '/home/lht/ghidra_test/ghidra_10.1.2_PUBLIC/Ghidra/build.gradle'.

> Configure project :Debugger-swig-lldb
Evaluating project ':Debugger-swig-lldb' using build file '/home/lht/ghidra_test/ghidra_10.1.2_PUBLIC/Ghidra/Debug/Debugger-swig-lldb/build.gradle'.
OS: Linux
Arch: aarch64
Using platform: linux_arm_64
Debugger-swig-lldb:buildNatives skipped - LLVM_HOME not defined

> Configure project :decompile
Evaluating project ':decompile' using build file '/home/lht/ghidra_test/ghidra_10.1.2_PUBLIC/Ghidra/Features/Decompiler/src/decompile/build.gradle'.

> Configure project :Decompiler
Evaluating project ':Decompiler' using build file '/home/lht/ghidra_test/ghidra_10.1.2_PUBLIC/Ghidra/Features/Decompiler/build.gradle'.
OS: Linux
Arch: aarch64
Using platform: linux_arm_64

> Configure project :PDB
Evaluating project ':PDB' using build file '/home/lht/ghidra_test/ghidra_10.1.2_PUBLIC/Ghidra/Features/PDB/build.gradle'.
OS: Linux
Arch: aarch64
Using platform: linux_arm_64
All projects evaluated.
Starting process 'command '/usr/local/gcc-11.4.0/bin/gcc''. Working directory: /usr/local/gcc-11.4.0/bin Command: /usr/local/gcc-11.4.0/bin/gcc -dM -E -v -
Successfully started process 'command '/usr/local/gcc-11.4.0/bin/gcc''
Starting process 'command '/usr/local/gcc-11.4.0/bin/gcc''. Working directory: /usr/local/gcc-11.4.0/bin Command: /usr/local/gcc-11.4.0/bin/gcc -m64 -dM -E -v -
Successfully started process 'command '/usr/local/gcc-11.4.0/bin/gcc''
file or directory '/home/lht/ghidra_test/ghidra_10.1.2_PUBLIC/Ghidra/Features/Decompiler/src/decompile/c', not found
file or directory '/home/lht/ghidra_test/ghidra_10.1.2_PUBLIC/Ghidra/Features/Decompiler/src/decompile/c', not found
file or directory '/home/lht/ghidra_test/ghidra_10.1.2_PUBLIC/Ghidra/Features/Decompiler/src/decompile/c', not found
file or directory '/home/lht/ghidra_test/ghidra_10.1.2_PUBLIC/Ghidra/Features/Decompiler/src/decompile/c', not found
file or directory '/home/lht/ghidra_test/ghidra_10.1.2_PUBLIC/Ghidra/Features/Decompiler/src/decompile/c', not found
file or directory '/home/lht/ghidra_test/ghidra_10.1.2_PUBLIC/Ghidra/Features/Decompiler/src/sleigh/c', not found
file or directory '/home/lht/ghidra_test/ghidra_10.1.2_PUBLIC/Ghidra/Features/Decompiler/src/sleigh/c', not found
file or directory '/home/lht/ghidra_test/ghidra_10.1.2_PUBLIC/Ghidra/Features/Decompiler/src/sleigh/c', not found
file or directory '/home/lht/ghidra_test/ghidra_10.1.2_PUBLIC/Ghidra/Features/Decompiler/src/sleigh/c', not found
file or directory '/home/lht/ghidra_test/ghidra_10.1.2_PUBLIC/Ghidra/Features/Decompiler/src/sleigh/c', not found
Selected primary task 'buildNatives' from project :
Tasks to be executed: [task ':Debugger-swig-lldb:buildNatives', task ':Decompiler:CheckToolChain', task ':Decompiler:compileDecompileLinux_arm_64ExecutableDecompileCpp', task ':Decompiler:linkDecompileLinux_arm_64Executable', task ':Decompiler:compileSleighLinux_arm_64ExecutableSleighCpp', task ':Decompiler:linkSleighLinux_arm_64Executable', task ':Decompiler:buildNatives', task ':PDB:buildNatives']
Tasks that were excluded: []
:Debugger-swig-lldb:buildNatives (Thread[Execution worker for ':',5,main]) started.

> Task :Debugger-swig-lldb:buildNatives UP-TO-DATE
Skipping task ':Debugger-swig-lldb:buildNatives' as it has no actions.
:Debugger-swig-lldb:buildNatives (Thread[Execution worker for ':',5,main]) completed. Took 0.006 secs.
:Decompiler:CheckToolChain (Thread[Execution worker for ':',5,main]) started.

> Task :Decompiler:CheckToolChain
Caching disabled for task ':Decompiler:CheckToolChain' because:
  Build cache is disabled
Task ':Decompiler:CheckToolChain' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
:Decompiler:CheckToolChain (Thread[Execution worker for ':',5,main]) completed. Took 0.004 secs.
:Decompiler:compileDecompileLinux_arm_64ExecutableDecompileCpp (Thread[Execution worker for ':',5,main]) started.

> Task :Decompiler:compileDecompileLinux_arm_64ExecutableDecompileCpp FAILED
:Decompiler:compileDecompileLinux_arm_64ExecutableDecompileCpp (Thread[Execution worker for ':',5,main]) completed. Took 0.007 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':Decompiler:compileDecompileLinux_arm_64ExecutableDecompileCpp'.
> No tool chain is available to build for platform 'linux_arm_64':
    - Tool chain 'gcc' (GNU GCC):
        - Could not determine GCC metadata: could not find vendor in output of /usr/local/gcc-11.4.0/bin/gcc.

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
2 actionable tasks: 2 executed

**Comment by lhtzei6** [comment]
> > I just tried it on an Ubuntu 22.04 VM running on an M1 host and it worked without an issue. I used openjdk 17 and gradle 8.0.2. I also had make, gcc, and g++ installed which are requirements of the build.
> 
> ./buildNatives --info Building natives in Ghidra... Initialized native services in: /root/.gradle/native The client will now receive all logging from the daemon (pid: 430883). The daemon log file: /root/.gradle/daemon/6.8.3/daemon-430883.out.log Starting 4th build in daemon [uptime: 12 mins 16.733 secs, performance: 99%, non-heap usage: 18% of 256 MiB] Using 64 worker leases. Watching the file system is disabled Starting Build Settings evaluated using settings file '/home/lht/ghidra_test/ghidra_10.1.2_PUBLIC/Ghidra/settings.gradle'. Projects loaded. Root project using build file '/home/lht/ghidra_test/ghidra_10.1.2_PUBLIC/Ghidra/build.gradle'. Included projects: [root project 'Ghidra', project ':Debugger-swig-lldb', project ':decompile', project ':Decompiler', project ':PDB']
> 
> > Configure project :
> > Evaluating root project 'Ghidra' using build file '/home/lht/ghidra_test/ghidra_10.1.2_PUBLIC/Ghidra/build.gradle'.
> 
> > Configure project :Debugger-swig-lldb
> > Evaluating project ':Debugger-swig-lldb' using build file '/home/lht/ghidra_test/ghidra_10.1.2_PUBLIC/Ghidra/Debug/Debugger-swig-lldb/build.gradle'.
> > OS: Linux
> > Arch: aarch64
> > Using platform: linux_arm_64
> > Debugger-swig-lldb:buildNatives skipped - LLVM_HOME not defined
> 
> > Configure project :decompile
> > Evaluating project ':decompile' using build file '/home/lht/ghidra_test/ghidra_10.1.2_PUBLIC/Ghidra/Features/Decompiler/src/decompile/build.gradle'.
> 
> > Configure project :Decompiler
> > Evaluating project ':Decompiler' using build file '/home/lht/ghidra_test/ghidra_10.1.2_PUBLIC/Ghidra/Features/Decompiler/build.gradle'.
> > OS: Linux
> > Arch: aarch64
> > Using platform: linux_arm_64
> 
> > Configure project :PDB
> > Evaluating project ':PDB' using build file '/home/lht/ghidra_test/ghidra_10.1.2_PUBLIC/Ghidra/Features/PDB/build.gradle'.
> > OS: Linux
> > Arch: aarch64
> > Using platform: linux_arm_64
> > All projects evaluated.
> > Starting process 'command '/usr/local/gcc-11.4.0/bin/gcc''. Working directory: /usr/local/gcc-11.4.0/bin Command: /usr/local/gcc-11.4.0/bin/gcc -dM -E -v -
> > Successfully started process 'command '/usr/local/gcc-11.4.0/bin/gcc''
> > Starting process 'command '/usr/local/gcc-11.4.0/bin/gcc''. Working directory: /usr/local/gcc-11.4.0/bin Command: /usr/local/gcc-11.4.0/bin/gcc -m64 -dM -E -v -
> > Successfully started process 'command '/usr/local/gcc-11.4.0/bin/gcc''
> > file or directory '/home/lht/ghidra_test/ghidra_10.1.2_PUBLIC/Ghidra/Features/Decompiler/src/decompile/c', not found
> > file or directory '/home/lht/ghidra_test/ghidra_10.1.2_PUBLIC/Ghidra/Features/Decompiler/src/decompile/c', not found
> > file or directory '/home/lht/ghidra_test/ghidra_10.1.2_PUBLIC/Ghidra/Features/Decompiler/src/decompile/c', not found
> > file or directory '/home/lht/ghidra_test/ghidra_10.1.2_PUBLIC/Ghidra/Features/Decompiler/src/decompile/c', not found
> > file or directory '/home/lht/ghidra_test/ghidra_10.1.2_PUBLIC/Ghidra/Features/Decompiler/src/decompile/c', not found
> > file or directory '/home/lht/ghidra_test/ghidra_10.1.2_PUBLIC/Ghidra/Features/Decompiler/src/sleigh/c', not found
> > file or directory '/home/lht/ghidra_test/ghidra_10.1.2_PUBLIC/Ghidra/Features/Decompiler/src/sleigh/c', not found
> > file or directory '/home/lht/ghidra_test/ghidra_10.1.2_PUBLIC/Ghidra/Features/Decompiler/src/sleigh/c', not found
> > file or directory '/home/lht/ghidra_test/ghidra_10.1.2_PUBLIC/Ghidra/Features/Decompiler/src/sleigh/c', not found
> > file or directory '/home/lht/ghidra_test/ghidra_10.1.2_PUBLIC/Ghidra/Features/Decompiler/src/sleigh/c', not found
> > Selected primary task 'buildNatives' from project :
> > Tasks to be executed: [task ':Debugger-swig-lldb:buildNatives', task ':Decompiler:CheckToolChain', task ':Decompiler:compileDecompileLinux_arm_64ExecutableDecompileCpp', task ':Decompiler:linkDecompileLinux_arm_64Executable', task ':Decompiler:compileSleighLinux_arm_64ExecutableSleighCpp', task ':Decompiler:linkSleighLinux_arm_64Executable', task ':Decompiler:buildNatives', task ':PDB:buildNatives']
> > Tasks that were excluded: []
> > :Debugger-swig-lldb:buildNatives (Thread[Execution worker for ':',5,main]) started.
> 
> > Task :Debugger-swig-lldb:buildNatives UP-TO-DATE
> > Skipping task ':Debugger-swig-lldb:buildNatives' as it has no actions.
> > :Debugger-swig-lldb:buildNatives (Thread[Execution worker for ':',5,main]) completed. Took 0.006 secs.
> > :Decompiler:CheckToolChain (Thread[Execution worker for ':',5,main]) started.
> 
> > Task :Decompiler:CheckToolChain
> > Caching disabled for task ':Decompiler:CheckToolChain' because:
> > Build cache is disabled
> > Task ':Decompiler:CheckToolChain' is not up-to-date because:
> > Task has not declared any outputs despite executing actions.
> > :Decompiler:CheckToolChain (Thread[Execution worker for ':',5,main]) completed. Took 0.004 secs.
> > :Decompiler:compileDecompileLinux_arm_64ExecutableDecompileCpp (Thread[Execution worker for ':',5,main]) started.
> 
> > Task :Decompiler:compileDecompileLinux_arm_64ExecutableDecompileCpp FAILED
> > :Decompiler:compileDecompileLinux_arm_64ExecutableDecompileCpp (Thread[Execution worker for ':',5,main]) completed. Took 0.007 secs.
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':Decompiler:compileDecompileLinux_arm_64ExecutableDecompileCpp'.
> 
> > No tool chain is available to build for platform 'linux_arm_64':
> > - Tool chain 'gcc' (GNU GCC):
> > - Could not determine GCC metadata: could not find vendor in output of /usr/local/gcc-11.4.0/bin/gcc.
> 
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 1s 2 actionable tasks: 2 executed

I environment is arm64, gradle6.8.3, java11.0.27,gcc 11.4.0
