### ISSUE TITLE
Correct GDB Base Address

### ISSUE THREAD

**Issue by Guusggg** [NationalSecurityAgency/ghidra#5284]
Hi,

Lately I've been trying out the debugger in Ghidra. I'm debugging a wine application, and to my surprise it works very, very well. Except for one thing; the base address gdb reports seems off. Or at least I don't understand how it got to that address.

In Ghidra, all the addresses I'm interested in start at `0x140000000`. When I launch the application through the debugger and add a Watch or a Breakpoint, it is never hit. In the Modules panel I can see that apparantly gdb thinks the module is at `0x140000c00`. This offsets my addresses by `0xc00` and nothing really works. 

Example:
Take the address at `0x140660754` (in my Listen window). When I right click on the address and click on Watch, the address and Symbol is added to the Watch window, but at `0x140661354`. (Which is exactly `0xc00` off). When I set a Watch myself, with the address `0x140660754`, the value I expect is shown. So Ghidra is translating something for me, but it's wrong.

Is there any way to tell Ghidra that the binary is really at `0x140000000`, and not at `0x140000c00`?

Thank you very much for reading this, and of course for making this awesome tool. It's truly fantastic!

Kind regards,

**Comment by nsadeveloper789** [comment]
This is actually a known issue, but I've been having quite the time trying to reproduce it. Wine might be a decent clue for me, so thanks for that. In the meantime, there are two known workarounds.

1. As you've asked, you can manually define the mappings. In the Modules window, there is a "Map Manually" button in the toolbar. Alternatively, in the Debugger menu, choose Static Mappings. Either way, you'll get the "Static Mappings" window, and you can remove and replace the incorrect mapping with one of your choosing.
2. You can configure the Mapper to use section information instead of module information. Without knowing your particulars, I'm not sure this will work for you, but it may. From the Ghidra **Project** window (not the Debugger window), select Edit &rarr; Tool Options in the menus. Then find Debugger / Workflow in the left panel. You should see an option to map sections. You'll need to re-launch your target for it to take effect.

**Comment by Guusggg** [comment]
Alright, not a problem at all! Thank you for pointing me into the direction of fixing it statically. I'm in luck because it seems the same program is almost always loaded exactly in memory as it is in the binary. 

I'll try to give you some more details on my set-up, for completeness:
I'm using Wine 8.0 (Proton) as my runtime, I use `winedbg --gdb $PROCESS_ID` to connect, and it seems everything is fine. Ghidra is not complaining and I can pause and continue as I please. It is known that `winedbg` is not as fullfletched as `gdb`, but it does provide a `gdb` frontend. So I would assume the problem happens maybe because `winedbg` has a bit different output before it enters `gdb` as the frontend...

Thank you very much, at least I can continue by fixing it by hand for now!

**Comment by zb3** [comment]
Would anyone be able to briefly describe what causes this? I've run into the same problem, but it's hard for me to know where does this value come from just by looking at the source code.

**Comment by zb3** [comment]
I don't even understand why file offset is not taken into account here, I tried to follow but I got lost:
https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Debug/Debugger-agent-gdb/src/main/java/agent/gdb/model/impl/GdbModelTargetSection.java#L77

**Comment by d-millar** [comment]
@zb3 are you unable to solve the problem using @nsadeveloper789‘a suggestions above, or is it a question of convenience or of just wanting to understand what’s going on?  As you’ve noted, we don’t support null ranges, so that could have something to do with it, or could be we’re driving the base from the section list vs. the modules list.

**Comment by zb3** [comment]
@d-millar, changing debugging options solves this exact problem, yet as always I'm a little curious what's going on here :)

I see that the discrepancy is introduced here:
https://github.com/NationalSecurityAgency/ghidra/blob/d932173a25bdcb36171f5c0fbaf454ba24f0435d/Ghidra/Debug/Debugger-agent-gdb/src/main/java/agent/gdb/manager/impl/GdbModuleImpl.java#L169-L173

But if `0x140001000` is the `vmaStart` and `0x400` is the `offset`, then it doesn't automatically mean the base is `0x140000c00` so again I got lost... but yeah, the workaround helps

**Comment by d-millar** [comment]
@zb3  Just following up:  I think you're correct - if I'm not mistaken, the logic in lines 169-173, while a useful heuristic, is not guaranteed to be true.  Need to discuss this with @nsadeveloper789, but wanted you to know we're looking into this.

**Comment by nsadeveloper789** [comment]
Yes, I had identified the same block of code in my own investigations. If I may generalize, this issue really comes down to collecting a good variety of test cases. The heuristic I applied there worked well for the Linux user-mode programs I observed on my machine :) (and it's presumably working for others'). But, it has apparently failed for some qemu system targets and now also failed for Windows user-mode targets on Wine for Linux. I assume you're also debugging with Wine? If not, I'd like to know, since it could be another useful test case.

I'm looking at two solutions, though it may turn out it's really two pieces to one solution:

1. Incorporate the output of `info proc mappings`. Potential issue here is that command is not always available, and it's not clear to me there will *always* be a mapping to the module's offset 0x0. I suspect I'll wind up applying a similar heuristic, but it may be more accurate.
2. When figuring out the mapping of the Dynamic listing to Ghidra's Static listing, incorporate the file offset information in the imported image. Since Ghidra's importer should agrees with the target in terms of memory layout, this should work. Potential issue here is that not all importers record file offset information.

If you're able to devise a patch that fixes `GdbModuleImpl` for your case, even if it breaks every other case, that may be useful. I realize this is a bit of an ask, but if you like to tinker....
