### ISSUE TITLE
Code Browser - Tool Options > Listing Display changes are not being saved to tool settings XML

### ISSUE THREAD

**Issue by oldmanludd** [NationalSecurityAgency/ghidra#5377]
**Describe the bug**
Changes to Tool Options > Listing Display are not being saved to tool settings XML.

Things like font face, font size, text color for various elements of the disassembly listing. The changes are applied during the existing Ghidra session but are lost after closign & reopening, even after first doing File > Save Tool (or Save Tool As)

Settings for changes to sub-categories of Listing Fields are confirmed to be saving correctly so it's not a generalized settings save issue.

**To Reproduce**
1. Edit > Tool Options
2. Listing Display 
3. Change font size
4. Press OK
5. File > Save Tool
6. Close Ghidra
7. Reopen Ghidra
8. Changes were not retained
9. Locate XML files containing tool settings (on Linux they are at HOMEDIR/.ghidra/.[GHIDRA VERSION]/tools/
10. Examine XML in file `_code_browser.tcd`. There is an empty XML tag for `CATEGORY NAME="Listing Display" />` with no saved customizations
11. Repeat process with other changes to Listing Display (font face, text colors, etc...)

**Expected behavior**
Changes to Listing Display should be saved

**Environment (please complete the following information):**
 - OS: Pop OS 22.04  (Ubuntu based distro)
 - Java Version:  OpenJDK 17
 - Ghidra Version: 10.3 PUBLIC
 - Ghidra Origin: GitHub Releases ZIP download links

**Comment by dragonmacher** [comment]
> Superceded by the new theme functionality in 10.3 maybe?

I haven't tested this specific use case yet, but yes, the theme now controls those features.   Any changes to the options should be passed through to the theme.  Changing the theme should prompt you to save the theme when closing the tool.

**Comment by ghidragon** [comment]
There appears to be a bug with how you exit Ghidra. If you exit Ghidra using the menu, you don't get prompted to save your theme changes. If you hit the "x" button in the main Ghidra project window to exit Ghidra, you get promped to save your changes to the theme. I almost didn't see this bug because when I followed your instruction, I exited Ghidra the way I always do, which is to hit the "x" button. Anyway, can you verify if you exit using the "X" button, that you can save your font and color changes and see them when you start back up?  I will be putting in an internal ticket for fixing the exiting from Ghidra menu problem.
