### ISSUE TITLE
Debugging "decompiled" code

### ISSUE THREAD

**Issue by ThorvaldAagaard** [NationalSecurityAgency/ghidra#5386]
When I debug an executable it would be nice if it was possible to debug at the "decompiled" level.

If possible please explain how

**Comment by d-millar** [comment]
@ThorvaldAagaard Assuming you’ve loaded the relevant executables into the debugger, the static and dynamic listing should be synchronized and the decompile view should be available.  is this not the case for you?

**Comment by ThorvaldAagaard** [comment]
I looks like it should be as you wrote, and it might just be a user error, but I can try to describe how far i got

I am using Ghidra 10.3.3 and this is what I see
![image](https://github.com/NationalSecurityAgency/ghidra/assets/10560652/c10ff61d-91df-411e-b623-da1f7c8412fd)
Loading this in the codebrowser I get something like this
![image](https://github.com/NationalSecurityAgency/ghidra/assets/10560652/1b912c14-2199-4fd4-9aa4-6139af2dab99)
So the code is decompiled

So now I open the same in the debugger and get this
![image](https://github.com/NationalSecurityAgency/ghidra/assets/10560652/79383d76-dbe4-48de-a343-49b9b0005ca6)
Notice I have added a breakpoint at the while statement

Now selecting the debugger
![image](https://github.com/NationalSecurityAgency/ghidra/assets/10560652/8eb03b38-32ea-41a4-84ec-96772e2c1cdb)

and starting to debug I get this popup:
![image](https://github.com/NationalSecurityAgency/ghidra/assets/10560652/a7dc4884-b6fc-4b71-904b-4b5500c3e289)
and after accepting that I get this screen

![image](https://github.com/NationalSecurityAgency/ghidra/assets/10560652/e60e9a04-1dfe-46e1-af81-2a71376b5772)

This looks like a break before the execution will start so I press the green arrow, and get this screen, and the debugging is terminated

![image](https://github.com/NationalSecurityAgency/ghidra/assets/10560652/d8a50f00-b82a-4bb3-a924-5bbf83becbd2)

**Comment by d-millar** [comment]
@ThorvaldAagaard OK, so you were very close to having it working.  The key is knowing what to do with that pop-up.  What it's essentially telling you is there's nothing in the Module List that matches the program loaded in the Static Listing.  There can be a couple of reasons for this.  In your case, I am guessing there's an entry in the Module List that corresponds to "application.exe", but that the name is somehow different.  As a result, the debugger has no way to map the memory from the program (static) to the memory in the debugger (dynamic), so the Dynamic and Static listings will be out of sync, the decompiler will not show the current location, and breakpoints in the decompiler will be unresolved and therefore ineffective.

Assuming you can identify which item in the Module list should be mapped to "application.exe," you can right-click on the item and map it to the current program.  Then the two listings should track and any new breakpoints in the Decompiler should show up in blue indicating they are enabled.  (You should also be able to click on greyed-out breakpoints to re-enable them.)  You're probably wondering why the two names differ.  Again, could be several reasons.  Technically, you could compile a program with one name, rename the file image, load it into Ghidra under another name, and rename it again - basically there is no guarantee that the name of the executable as loaded in memory has anything to do with the name of your program in Ghidra. You could rename the prorgam in Ghidra to solve the problem, but re-mapping it is probably as easy.

The other possible cause of that pop-up is having no Module List at all.  This is more common on gdb variants, such as embedded targets, where there's a single image and hence no need to support the module list commands.  Shouldn't happen on Windows with the dbgeng unless something else has gone seriously wrong.

Let us know if this doesn't fix the problem, isn't clear, or just leads to new ones!

**Comment by ThorvaldAagaard** [comment]
This sound like a probable reason, but trying to make the mapping I had trouble finding the Module listing.

But after the debugging is started I get something that looks like a module listing in the Objects window. That looks like this
![image](https://github.com/NationalSecurityAgency/ghidra/assets/10560652/7966f11b-0db1-4e96-80f3-a0cb3f2e5792)

Right-clicking show no entry with mapping
![image](https://github.com/NationalSecurityAgency/ghidra/assets/10560652/732406ba-dd33-4f68-b7b0-8517ebe114ce)

but I tried then attach, and here application.exe was in the list, so I attached that, but got a "katastrofal fejl" (Danish for a very bad error)

![image](https://github.com/NationalSecurityAgency/ghidra/assets/10560652/a714aea3-3d7f-4a3f-93c3-2ca8940aa68e)

I then tried running Ghidra as Administrator, but that did not change anything.

From the above list I can also select execute, and that will execute the application, but as the debugger probably still has the mapping problem, the breakpoints are not hit.

**Comment by d-millar** [comment]
Ah, apologies - wasn’t clear enough.  “image_0…” is definitely the matching process.  (Not obvious why it shows up like that, but we’ve seen that before.)  That name will be in the Module Listing, in addition to the Objects Tree.  You’ll find this view on the right among the tabbed panes.  

In this view, right-click and look for something like “map to current program”.  (The “attach” command in the Objects Tree attempts to re-attach to a process you were previously executing - not helpful in this case.)

**Comment by d-millar** [comment]
Note: you should probably never run Ghidra as Admin as it can change the permissions on the dot files in your home directory, preventing you from running under your normal account afterwards.

**Comment by ThorvaldAagaard** [comment]
Funny how searching for a specific item is almost impossible until you get the right hint: "You’ll find this view on the right among the tabbed panes" - Thx a lot.

Now the mapping is correct, and the application starts fine when I select debug.

But the debugger is not handling the breakpoints, and as they are grey I am suspecting something is missing.

This should be my entry point
![image](https://github.com/NationalSecurityAgency/ghidra/assets/10560652/ee5b2148-db7b-4ad5-a92b-98f5ab7a233e)

Reading in the manual I expected the breakpoint to be blue, if module was loaded correctly

Looking at the Interpreter the error there could be the explanation
![image](https://github.com/NationalSecurityAgency/ghidra/assets/10560652/066e4b5b-3f8f-4257-aa30-0be7803bdb11)


Now I did play around a bit in the Symbol tree, just to check that the decompiler found the different functions, and suddenly the breakpoint in the listing got blue and I got this message in the Interpreter
![image](https://github.com/NationalSecurityAgency/ghidra/assets/10560652/0e3f1823-c73b-442e-8f74-1947da5b63d8)

Anyway I could suddenly debug, and I noticed that F8/F10 would single step at the assembler level and I was hoping for stepping at the decompiled level. 

So with a bit patience and clicking on some functions in the symbol tree it looks like I can get the debugger to respect the breakpoints :-) - Later I realized that functions lower in the symbol tree was not loaded so my breakpoints there stayed grey.

And after some more testing I found that a previously marked breakpoint would be grey and I had to disable and enable it before it turned blue. After some more testing I realized I could do that from the Breakpoint window.


Now this is my decompiled code
![image](https://github.com/NationalSecurityAgency/ghidra/assets/10560652/12b29d2c-8f77-4f86-bc12-2c380ce87797)
and the debugger stopped right after filling local_cc with information about the platform the application is running on

Now using mouseover on the variable I get an error message
![image](https://github.com/NationalSecurityAgency/ghidra/assets/10560652/533564c4-a312-43f7-b4a2-aeca25f42905)

This is the type for local_cc
![image](https://github.com/NationalSecurityAgency/ghidra/assets/10560652/ae83176d-cc42-4539-9890-84743d5fbbd6)
but adding a Watch for this will only show the first DWord
![image](https://github.com/NationalSecurityAgency/ghidra/assets/10560652/56fdd756-c42e-4e6d-8bf1-cffa42443436)



I am also a bit confused about the different Breakpoint types
![image](https://github.com/NationalSecurityAgency/ghidra/assets/10560652/1049ac28-4114-45fe-a363-1a435b974aa7)
but I just used the default SW_EXECUTE


Another issue is that when the application terminates it looks like Ghidra is keeping the process alive, so I have to reboot my computer before I can debug the application again. 

When the application is terminated, there is still this left in the job list
![image](https://github.com/NationalSecurityAgency/ghidra/assets/10560652/dcd2e328-c568-49c8-9982-fe8afb43625e)
Midlertidigt stopper = temporarely stopped
and trying to terminate it from the joblist won't work

Update - Only restarting Ghidra is needed - all Ghidra, not just the debugging tool

**Comment by d-millar** [comment]
@ThorvaldAagaard There are basically three conditions that need to be true for a breakpoint to be enabled.  The first, which you've already encountered, is that, if the breakpoint was inserted on the static listing, i.e. in the Ghidra program, the debugger needs to know how to map it to the dynamic memory, either by virtue of the module list or manual intervention.  Second, the debugger has to be stopped.  For Windows debuggers, generally, commands cannot be executed against a running target.  (This isn't strictly true, but ignoring it leads to complicated behavior.)  Finally, the module has to have been loaded.

Any breakpoints set before all three things are true show in grey, possible with annotations in the Breakpoint Viewer indicating their state.  Once the three conditions are true, you can enable them from either listing or the Breakpoint Viewer or the command line, but you have to do that manually.  We don't automatically enable breakpoints because they may be disabled by choice, not just because they haven't met the initial conditions.  The exception to this is "bu" breakpoints.  Breakpoints set from the command line using "bu" are understood to be pending.  They will be enabled by the underlying engine on module load and will fire without intervention.  That said, you probably will have to refresh the Breakpoints node in the Objects tree to see them in Ghidra.

Regarding stepping by source instruction, I can't remember whether that's actually supported for Windows debuggers.  If it is, I definitely don't know which API call enables this off the top of my head.  I will investigate this, though.  Would certainly be a nice feature.  If it exists, however, the mapping between true source and decompilation will almost certainly not be one-to-one, so am guessing the behavior might be slightly confusing.

With respect to Watch values, possibly a question for @nsadeveloper789, but I believe, if you set the type in the Watch Listing, you can influence the display.  DWORD is, in essence, the default for "no type".  I believe this is described in the Help and also in the new course documents released with 10.3.  It's not a feature I've used much.  It also is not currently possible to display things like structures or unions, although that idea was raised recently in another post and is under discussion.

As far as not disconnecting and leaving "ghost" processes, am guessing this happens when the process terminates while the debugger is still attached.  You probably cannot "Detach" once the process is greyed out (although I might try that).  I would have guessed, however, that disconnecting from the session in the Targets window pull-down would allow the system to clean-up and remove the ghost.  Let me know if I'm wrong about this.

Hope this helps a bit.  Appreciate you feedback and bearing with us as we smooth out some of the rought edges!

**Comment by ThorvaldAagaard** [comment]
You have been to great help, and I really appreciate your responses.

When my application is terminated it is still shown in debugger targets:
![image](https://github.com/NationalSecurityAgency/ghidra/assets/10560652/39328777-9815-40fb-a615-e12a03f3112c)
So right clicking and select Terminate release the process, and the debugging can start again.

I am not sure if it is related, but the next time I start the application and try to active a breakpoint I get this message:
![image](https://github.com/NationalSecurityAgency/ghidra/assets/10560652/7c8afb3b-3bef-471f-a982-8b1787998c80)

so I had to close the debugger and start it again
But I can decompile and debug my program :-)

About watching it is more interesting how to inspect 

Look at this code
![image](https://github.com/NationalSecurityAgency/ghidra/assets/10560652/7d963554-a7c1-43a1-a257-e6c1be63c44e)
where _OSVERSIONINFOA is a struct defined in windows

So executing with a breakpoint just after the call
![image](https://github.com/NationalSecurityAgency/ghidra/assets/10560652/d55b6641-0443-41c5-af56-d812e6db1bb9)

Now It would be nice if I can see the value of local_cc but currently it looks like I have to add a watch for each atttribute, but I will start by reading the documentation about Watch. Using mouseover over a field sometimes give me a value, but most of the time I just get an exception like
![image](https://github.com/NationalSecurityAgency/ghidra/assets/10560652/5a197e18-90f5-4ebf-95a6-76d27c155aea)

And finally: Is there a description in the documentation of the 5 different Breakpoint types?

**Comment by d-millar** [comment]
Oops, I knew I forgot to answer (at least) one of your questions.  The five flavors of breakpoints correspond to the five modes avaliable for triggering a break on Intel/AMD processors.  Basically, there are software and hardware breakpoints.  Software breakpoints are created when you overwrite an existing machine instruction with a special opcode or opcodes that trigger an interrupt on the processor. On Intel/AMD machines, this is usually INT_3, triggered using 0xCC.  The debugger overwrites the desired address with 0xCC, gets control after the interrupt, resets the instruction pointer back one, and re-writes the original byte.  On resume, it steps past the instruction, replaces the 0xCC, and continues.  You can have an unlimited number of these breakpoints, designated SW_EXECUTE.  

Hardware breakpoints are implemented by writing values in specific registers, which cause the processor to break when something happens at the address matching that value.  "Something" can be (1) code at that address is executed, (2) the contents of memory at that address are read, (3) the contents are written two, or (4) the contents are either read or written, i.e. the memory is accessed in some way.   As you have probably guessed by now, the hardware breakpoint modes correspond to HW_EXECUTE, READ, WRITE, and READ/WRITE. The hardware breakpoints are more powerful, in some sense, than their software counterparts because they allow for more complex operations.  However, on Intel/AMD processors, there are only four of these registers, DR1-DR4 (plus DR5 and DR6, which control their function).

We currently have several tickets in place regarding the hover and errors that result from it, so you probably don't need to open a new ticket for that.  At a minimum, we would like to fix the stack traces that have been resulting, but we're also thinking about the right way to implement the feature for complex data objects, such as unions and structures.  Sort of along the same lines as the Watch issue. A little complicated, so that fix will likely take some time.

Not sure what exactly is causing the RejectedExecutionException - interesting.  I will check into that this week, see if I can reproduce it, and with luck understand what's happening there.  Will let you know if  I figure it out!

**Comment by d-millar** [comment]
@ThorvaldAagaard Having trouble re-creating the RejectedExecutionException - any chance your application is erroring out during shutdown?

**Comment by ThorvaldAagaard** [comment]
I will try to recreate it, and see if there is anything in the logs, that might be of any help.

So I start the debugger and let the application execute until some user-input. Then I terminates the application.

Now I remove the debugger target, so I can execute a new try.

I start the debugger again and all looks OK, and I can select the breakpoints I want to activate from the breakpoint window.

Now terminate the application again and remove the target, but notice that the breakpoints are not being greyd out (Not everytime for me), so clicking on it results in
![image](https://github.com/NationalSecurityAgency/ghidra/assets/10560652/8a0f48ca-fe66-40bc-876b-9c3904ed0508)

Now forget to remove the application from the debug target, and try to start the application again, and it will probably hang. Now in some situations it looks like when trying to start all over I can get the RejectedExecutionException but I haven't found a way of making it fail every time.

I think it is related to the previous operations, so I would not care a lot about it
