### ISSUE TITLE
Patch Instruction: Snap Cursor to subsequent byte after instruction

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#5397]
**Is your feature request related to a problem? Please describe.**
I often input multiple instructions using the Patch Instruction action in the listing. The autocomplete and preview is amazing, but it is a mild annoyance having to press down and then Ctrl-Shift-G repeatedly

**Describe the solution you'd like**
A setting for this action where the cursor immediately moves to the next byte and waits for further input e.g. after assembling the following:

  ```31 c0         ff00000500    XOR                 EAX, EAX```

My cursor should be at ``ff00000502   [blank box]   [blank box]``

**Comment by nsadeveloper789** [comment]
Unfortunately, we're not inclined to implement this. There's a bit of complexity from handling all the follow-on events that change the display from the first patch that we'd have to account for before invoking the follow-on patch action. Otherwise, the action could be cancelled, or GUI elements may be displayed at the wrong location, etc. In the end, it spares a few keystrokes. I get it, but I don't think it's worth the effort. In the end, patching is a useful action for fixing up a couple of instructions, but Ghidra is not a forward-engineering tool.
