### ISSUE TITLE
Struct drag-n-drop from two code browsers locked up

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#5402]
**Describe the bug**
Opened two images in their own code browser, one is new and I'm copying structs over.  When I attempted to drag-n-drop ghidra locked up as a pop-up came up for the drag-n-drop (title appeared, no painting).  Had to kill -9

**Attachments**
[dragndrop.txt](https://github.com/NationalSecurityAgency/ghidra/files/11608532/dragndrop.txt)

**Environment (please complete the following information):**
 - OS: 22.04
 - Java Version: 17.0.7
 - Ghidra Version: 10.3
 - Ghidra Origin: official

**Additional context**

**Comment by dragonmacher** [comment]
Looking at the traces, it appears to be a live lock scenario.   Two threads are competing for the same lock.  It seems like they are both acquiring and releasing the lock repeatedly.   One thread is the Swing thread, which is painting the Data Types tree; the other thread is the Task thread that is performing the drop operation.

In the past when performing bulk manipulations of a Data Type Manager, we have had to add special code to deal with this type of situation.  Specifically, we will close the tree/node of the manager being manipulated so that the task thread is not fighting the tree's rebuilding and repainting as these bulk background operations are happening.

For your case, this doesn't quite seem like the same thing, unless the structure you were dropping is very large and required numerous other new types to be pulled in while completing the drop.   Does this sound like what was happening for this particular structure drop?

**Comment by mumbel** [comment]
@dragonmacher   Ahhh, I thought I was moving a tiny struct with some `void *` ... I forgot I had updated to a function definition pointer, and yes one of those arguments is a massive struct.... it just threw me off when i thought it was 0x10 with two pointers.  That would have likely been trying to copy the entire type database, so the lockup makes sense now.    Please close unless if you need this to track anything on your end.
