### ISSUE TITLE
Error importing .exe: java.io.IOException: Invalid index: 67400821

### ISSUE THREAD

**Issue by KoalafiedDev** [NationalSecurityAgency/ghidra#5483]
**Describe the bug**
When I try to import a .exe file, I get the error: "Error importing file: MSIPackageBuilder. exe". Invalid index: 67400821
java.io.IOException: Invalid index: 67400821

**To Reproduce**

1. Create a project
2. Click on File > Import File
3. Select the .exe and click on Select to Import
4. Click on OK
5. See error

**Expected behavior**
Being able to import the .exe and decompile it.

**Screenshots**
![image](https://github.com/NationalSecurityAgency/ghidra/assets/110347745/6bf0af22-b36d-4958-a235-39a362641653)

![image](https://github.com/NationalSecurityAgency/ghidra/assets/110347745/1dada7d4-3e31-4281-8bc3-2ed94423b495)

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
 - OS: WIndows 11 Enterprise 22H2 22621.1848
 - Java Version: jdk-20
 - Ghidra Version: 10.3.1
 - Ghidra Origin: official GitHub distro

**Additional context**
I think this error is related to: [Issue #4605](https://github.com/NationalSecurityAgency/ghidra/issues/4605), But I don't know for sure.

**Comment by ryanmkurtz** [comment]
Can you share the binary?  Are you sure the binary is not corrupt?  Does it run correctly?

**Comment by KoalatyC0de** [comment]
Thank you for the quick response! I have uploaded both the program and the setup files to [WeTransfer](https://we.tl/t-AJUd4rqI1L). Upon further investigation, I discovered that I am able to import the setup executable, but not the application .exe that is generated after the installation process.

The .exe file that cannot be imported is named MSIPackageBuilder.exe. However, I can successfully import the MSIPackageBuilderSetup.exe file, which is the setup executable.

I am confident that the binary files are not corrupt since I am able to execute the program and use it without any issues. The application itself runs smoothly.

**Comment by ryanmkurtz** [comment]
Ok, i'll take a look next week.

**Comment by ryanmkurtz** [comment]
I have reproduced the problem and will work on a fix.

**Comment by ryanmkurtz** [comment]
I've allowed the import to proceed past the bad parsing of the `ExceptionDataDirectory`.  This binary is possibly packed in some way, so you might run into more warnings, but the import will complete.

**Comment by KoalafiedDev** [comment]
Great work! But do I need to replace ExceptionDataDirectory.java and recompile Ghidra myself, or do I need to wait for another release?

**Comment by ryanmkurtz** [comment]
You an either wait for release 10.3.2, build the `master` branch, or in theory simply zero-out the ExceptionDataDirectory VirtualAddress field in your binary, and your current version of Ghidra will think there is nothing there to parse.

**Comment by KoalafiedDev** [comment]
Thank you!
