### ISSUE TITLE
Ability to ignore / take ownership of project when opening.

### ISSUE THREAD

**Issue by fenugrec** [NationalSecurityAgency/ghidra#5507]
**Is your feature request related to a problem? Please describe.**

This problem comes up often : #172 ,  #2229 , #4364 .
There is definitely use cases for sharing projects without a full-blown ghidra server, accross machines with different user names. Export + Import as an archive is not always an option, and just about as tedious as manually editing the .prp file

**Describe the solution you'd like**
A global option to ignore ownership, or an extra button in the dialog that informs me of the username mismatch, allowing me to take ownership of the project. It should also mention obvious caveats (don't open project simultaneously on multiple machines (( I think the lock files already prevent this ?)), other user may be unable to open project etc etc.)

**Describe alternatives you've considered**
Editing the .prp file by hand is tedious. I often jump from one machine to another.

**Additional context**
UI design could be  trivial : simple dlg box, 2 buttons, "Force open / take ownership", "Cancel".

**Comment by ghidra1** [comment]
Due to the high-probability that bad File permissions exist, this is not an "Easy button" type of situation.  The owner concept was created for this very reason.  While we could probably examine all project files and folders to check for such permission issues, we would have no recourse other than to fail if such a situation exists.  It would seem having an Admin alter file ownership/permissions at the file-system level is much more involved then the edit of the property file once permissions have been corrected.   For these reasons we are unlikely to incorporate such a mechanism.

**Comment by ghidra1** [comment]
In addition to the above, any project file checkouts from a Ghidra Server could pose a problem when taking possesion of another user's project.

**Comment by ghidra1** [comment]
Are you accessing a shared Ghidra Server project where others have checked-in revisions and you have not?  Could you look at your  Program information properties and tell me what you have for "Created with Ghidra Version".  You can find this from the `Help->About <your-program-name>`.

What version of Ghidra are you currently using?

There are no provisions in the `DomainFile.getChangesByOthersSinceCheckout` method to cope with a `VersionException`, however you should not have run into this under normal conditions.

The Module DB Adapter schema version has not been changed since Ghidra was released so I can only assumed there may be some other issue.  Are you able to share your Ghidra project file with us?  If so, I would need to it to be produced from the project file on your server and not the one you may have checked-out.  If your answer is yes, I will provide further instructions on how best to do this.

**Comment by fenugrec** [comment]
@ghidra1 did you post this in the correct ticket ? I'm not sure I follow; I'm not using Ghidra Server at all and this was a feature request, not really a bug report

**Comment by fenugrec** [comment]
Got annoyed at this once too many, and made a bash script to save a few seconds : 
https://gist.github.com/fenugrec/49091f26ae3ee944087c47777b67023e

If I use this script a few thousand times I might recover my development time  : )

**Comment by gynt** [comment]
Nice, I switched PC's and this is a lifesaver, although I did it just manually.
