### ISSUE TITLE
6809 decompiler: overlapping input varnodes with LSLA/B output for indexed JMP

### ISSUE THREAD

**Issue by hjanetzek** [NationalSecurityAgency/ghidra#5523]
**Describe the bug**
Decompiling the function shown in the screenshot results in `Low-level Error: Overlapping input varnodes`. Changing the LSLA instruction to INCA fixes decompilation, as well as changing 6x09.sinc to
```
macro logicalShiftLeft(op)
{
        $(C) = op >> 7;
---      op = op << 1;
+++      op = op + 1;
        $(Z) = (op == 0);
        $(N) = (op >> 7);
}
```

![shot-2023-07-03_23-31-42](https://github.com/NationalSecurityAgency/ghidra/assets/1747/dc5a31c4-6252-4e2a-95d6-5f5367a0225d)
![shot-2023-07-03_23-56-20](https://github.com/NationalSecurityAgency/ghidra/assets/1747/7ae1f672-01e2-4fd2-b639-839f3c05fd8d)

**Comment by hjanetzek** [comment]
Shouldn't `$(V)` also be set? 
![shot-2023-07-04_00-00-20](https://github.com/NationalSecurityAgency/ghidra/assets/1747/b8433c7f-bde0-4064-b69c-162010a03cd3)

**Comment by Pinoerkel** [comment]
Not sure what causes the original issue, but as I see it, $(V) should definitely be set to the exclusive or of the original bits 6 and 7 of the operand. This is also wrong in the `rotateLeftWithCarry` macro which affects `ROLA`, `ROLB` and `ROL`. The correct versions might look like this (if `^` is the correct XOR operator):
```
macro rotateLeftWithCarry(op)
{
        local carryIn = $(C);
        local tmp = (op >> 7);
        $(C) = tmp;
        op = (op << 1) | carryIn;
        $(V) = tmp ^ (op >> 7);
        $(Z) = (op == 0);
        $(N) = (op >> 7);
}

macro logicalShiftLeft(op)
{
        local tmp = (op >> 7);
        $(C) = tmp;
        op = op << 1;
        $(V) = tmp ^ (op >> 7);
        $(Z) = (op == 0);
        $(N) = (op >> 7);
}
```

**Comment by mumbel** [comment]
Isn't N also implemented incorrectly there too?  It's setting N to the high bit (1->1 0->0) but should be setting if clear (0->1 1->0)

`$(N) = (op >> 7) == 0`

**Comment by Danil6969** [comment]
This is generally a bug in decompiler because it doesn't check and reject input varnodes which cause error. It doesn't have to do with instructions or something, it just makes unsafe assumptions or like.

**Comment by Pinoerkel** [comment]
> Isn't N also implemented incorrectly there too? It's setting N to the high bit (1->1 0->0) but should be setting if clear (0->1 1->0)
> 
> `$(N) = (op >> 7) == 0`

That sounds correct. Seems like there is an error in the programming reference manual I used (see [here](https://colorcomputerarchive.com/repo/Documents/Books/Motorola%206809%20and%20Hitachi%206309%20Programming%20Reference%20%28Darren%20Atkinson%29.pdf) on page 96) vs. the original reference [here](http://www.bitsavers.org/components/motorola/6809/M6809PM.rev0_May83.pdf) on page  A-46.

**Comment by Pinoerkel** [comment]
@Danil6969 : Thank you for the analysis starting point. Since the error message itself is not very informative at all, I tried to hack `setInputVarnode` to sneak some more info in there. For most of the occurrences, I got something like this (in the first line the varnode and input varnode are extended with the address and the size, the lines below are the output of the `printInfo` method of the varnodes):

````
  Low-level Error: Overlapping input varnodes vn: 0x00, 1 invn: 0x00, 2
  vn:
   undefined = A(free) (consumed=0xffffffffffffffff) (internal=000000000066B8F0) (create=0x454)
  invn:
   undefined2 = D(i) (consumed=0xffff) (internal=0000000000697760) (create=0x2ad)

  
  Low-level Error: Overlapping input varnodes vn: 0x00, 1 invn: 0x00, 2
  vn:
   undefined = A(free) (consumed=0xffffffffffffffff) (internal=000000000066CDC0) (create=0x2cb)
  invn:
   undefined2 = D(i) (consumed=0xff00) (internal=000000000066BCE0) (create=0x262)

  
  Low-level Error: Overlapping input varnodes vn: 0x00, 1 invn: 0x00, 2
  vn:
   undefined = A(free) (consumed=0xffffffffffffffff) (internal=00000000005EE020) (create=0x154a)
  invn:
   short = D(i) (consumed=0xffff) (internal=0000000000699B60) (create=0xef5)
````
So far as I understand it, it is trying to create a varnode of size 1 at an address, where a varnode with size 2 already exists. If the identifiers `A` and `D` stand for the respective 6809 registers, the overlap would at least sound plausible, though the reason remains unclear. It the moment, I can not make much sense of the remaining information.

**Comment by mumbel** [comment]
are you testing this with the fix for Push2/Pull2?

**Comment by Pinoerkel** [comment]
Yes, and with my recent fixes to `rotateLeftWithCarry`, `logicalShiftLeft`, `subtraction`, `compare`, `LEAX`, `LEAY` and `ADDB`.

**Comment by pjanetzek** [comment]
Hey @Pinoerkel could you share a branch with printInfo debug logs? I've build Ghidra master now and would like to investigate this issue further.

**Comment by hjanetzek** [comment]
Hey @Pinoerkel could you share a branch with printInfo debug logs? I've build Ghidra master now and would like to investigate this issue further.

**Comment by Pinoerkel** [comment]
> Hey @Pinoerkel could you share a branch with printInfo debug logs? I've build Ghidra master now and would like to investigate this issue further.

I am not completely sure what you want me to do, but I think the key to understanding the issue is having several as small as possible code examples that produce the error and then squeezing as much information out of ghidra at the position where the error is detectable. Then one should probably determine what Ghidra should do in several specific error situations and see if there is a rule or heuristic that can be derived from that to resolve the issue.

To produce the output I posted above, i patched `Ghidra\Features\Decompiler\src\decompile\cpp\funcdata_varnode.cc` at line 358, where the overlapping input varnodes error is produced, replacing 
```
		throw LowlevelError("Overlapping input varnodes");
```
with
```
		ostringstream s;
		s << "Overlapping input varnodes";
		s << " vn: ";
		vn->getAddr().printRaw(s);
		s << ", " << vn->getSize();
		s << " invn: ";
		invn->getAddr().printRaw(s);
		s << ", " << invn->getSize();
		s << "\nvn:\n ";
		vn->printInfo(s);
		s << "\ninvn:\n ";
		invn->printInfo(s);
		throw LowlevelError(s.str());
```
to produce an error string with more information about the respective varnodes.

Unfortunately I was not able to find someone who could explain the general varnode issue to me by means of a specific minimal example. At the moment, I have the theory(but I may be completely wrong with this) that it might be something like:
- A function with parameters gets called from multiple other pieces of code.
- Using each piece of code and looking at what stack data is used inside the function, the Ghidra decompiler tries to estimate, which parameters the function has.
- Now, if on one function call this estimation leads to differently sized parameters or a different amount of parameters(e.g. because one parameters is not used inside the function during one call) than on another function call to the same function, the Ghidra decompiler does not know how to handle differently sized input parameters estimated to be at the same location.
- Theoretically, it should be possible to reconstruct the original set function parameters by looking at the code and find a solution that works for all instances the function is called.
Unfortunately, I am quite new to Ghidra and thus, the theory outlined above may be completely wrong.

**Comment by hjanetzek** [comment]
Thanks a lot for your answer and ideas!  I'll try to dig into it more next weekend.
As a first try I've just commented out the exception and the decompilation result looks reasonable on first sight :)

**Comment by hjanetzek** [comment]
ok the issue when turning off the exception is that things that should be stored in D are stored in B

**Comment by Pinoerkel** [comment]
In my case, it seemed to be mostly conflicts between A and D. The architecture of the 6809 with the overlapping A, B and D registers could make it especially hard or even impossible for the compiler to decide how some stack variables should be handled. E.g. the ROM code could compute the upper and lower byte separately in A and B, push them onto the stack and use them via the D register in the function. In another call of the same function the data for the D register in the function could have been explicitly computed in the D register, confusing the decompiler. Maybe there is a heuristic that can handle all those cases. Until now, I even failed to clearly understand these conflicts in my ROM code and see if I would be able to determine the "correct" solution manually. If I could, then the solution for errors like this, might be as easy as looking at the code, understanding what the function parameters should look like and manually editing the stack frame of the function accordingly.
