### ISSUE TITLE
Ghidra build toolchain assumes Visual Studio Installer is located on C drive

### ISSUE THREAD

**Issue by Aurumaker72** [NationalSecurityAgency/ghidra#5549]
**Describe the bug**
The Ghidra build toolchain assumes Visual Studio Installer is located on C drive, which causes a build failure when the Visual Studio Installer is located on another drive.

**To Reproduce**
1. Copy the Visual Studio Installer to an external hard drive, which has a drive letter other than C
2. Run `gradle buildGhidra`
3. `> Supported Windows native toolchain not found!`

**Expected behavior**
The Ghidra toolchain

**Environment (please complete the following information):**
 - OS: Windows 11
 - Java Version: 18
 - Ghidra Version: Commit 069c943d30907ebc5ea805a90cf22040e24761b8
 - Ghidra Origin: locally built

**Additional context**
The offending code is located in `/GPL/vsconfig.gradle` at line 30

**Comment by ryanmkurtz** [comment]
Do you have an environment variable that points to your studio installation?

**Comment by ryanmkurtz** [comment]
We could potentially change it to look for `%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe`.  Would that help your case?

**Comment by ryanmkurtz** [comment]
We should and will do `%ProgramFiles(x86)%`, but I think the best we can do for your specific case is to accept a gradle property specifying the PATH to `vswhere.exe`.  Thoughts?

**Comment by Aurumaker72** [comment]
Yep, definitely sounds the most ideal.

**Comment by ryanmkurtz** [comment]
In `master`, you can now specify a `-PvswherePath=<vswhere.exe path>` Gradle command line argument.  Hopefully `vswhere.exe` is able to find your Visual Studio installation...we are still relying on that.

**Comment by lmstearn** [comment]
Related:  Ghidra is not on the C drive but Visual Studio is.
Would a link to _devenv.exe_ suffice in the Visual Studio Code Integration box? There's a nonexistent `C:\...\bin\code.cmd` in the suggest field already, so pasted in the path to devenv above, it didn't show, likely due to permissions. Ran Ghidra as Admin (created shortcut to .bat, Shortcut>Advanced) and the correct devenv path immediately showed in the Visual Studio Code Executable Path field. Wonderful. 😄
