### ISSUE TITLE
IllegalStateException on trying to print help page

### ISSUE THREAD

**Issue by danra** [NationalSecurityAgency/ghidra#563]
**Describe the bug**
Getting an error message after clicking the "Print" icon in help.

> Uncaught Exception! 
> IllegalStateException - This function should be called while holding treeLock

The print dialog does open up alongside the error message, and printing does work properly.

Detailed log attached below.

**To Reproduce**
1. Go to Help->Contents
2. Click on the Print icon
3. Get error message alongside the print dialog (happens consistently and on any help page)

**Attachments**
[ghidra print exception.txt](https://github.com/NationalSecurityAgency/ghidra/files/3144287/ghidra.print.exception.txt)

**Environment (please complete the following information):**
See attached log

**Comment by dragonmacher** [comment]
It seems that the print functionality still works after getting this exception.

The exception is coming from code that is not ours, but is from the Oracle help package.   I will investigate a 'workaround' that we can add to prevent the exception from being shown to the user.

**Comment by dragonmacher** [comment]
As an aside, I noticed that this does not happen when using the 'Metal' Look and Feel (as settable via the Front End tool options).   

As mentioned, the feature still works, despite the exception.  Considering the code is from a third-party and that the severity of the issue is low, we are not planning to create work around at this time.
