### ISSUE TITLE
GraphASTScript maybe should not use normalize

### ISSUE THREAD

**Issue by edmcman** [NationalSecurityAgency/ghidra#5657]
**Describe the bug**
The built-in GraphASTScript is missing edges in the data-flow graph that I think should be there.  I think it is because of the "normalize" decompiler option.

**To Reproduce**
1. Open https://github.com/cmu-sei/pharos/blob/master/tests/ooex_vs2010/Debug/oo.exe
2. Decompile 0x411830
3. Possibly modify function to return undefined4 *
4. Run GraphASTScript
5. Find this in the graph

![image](https://github.com/NationalSecurityAgency/ghidra/assets/1017189/f0de6d5b-27af-4c2f-9a9c-00f80518e825)

Here is my decompilation for reference:
``` C
undefined * __fastcall FUN_00411830(undefined4 *thisptr)

{
  int iVar1;
  undefined4 extraout_ECX;
  undefined4 extraout_EDX;
  undefined4 *puVar2;
  undefined4 local_d0 [49];
  undefined4 *local_c;
  undefined4 uStack_8;
  
  puVar2 = local_d0;
  for (iVar1 = 0x33; iVar1 != 0; iVar1 = iVar1 + -1) {
    *puVar2 = 0xcccccccc;
    puVar2 = puVar2 + 1;
  }
  local_c = thisptr;
  thunk_FUN_00411a40(thisptr);
  thunk_FUN_00411b10(local_c + 3);
  *local_c = Cls3::vftable;
  local_c[3] = Cls3::vftable;
  local_c[0x14] = 0x2a;
  uStack_8 = 0x411896;
  __RTC_CheckEsp(extraout_ECX,extraout_EDX);
  return (undefined *)local_c;
}
```

**Expected behavior**

Well, since we return `local_c`, I expected an edge from the RETURN pcode op to something representing `local_c`.

**Screenshots**
See above.

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04.3
 - Java Version: 17.0.6
 - Ghidra Version: git master, 10.3.2
 - Ghidra Origin: official Github, locally built + 10.3.2 release

**Additional context**
The problem seems related to the use of "normalize" in the GraphASTScript.  Commenting that line out results in more reasonable results IMHO.

![image](https://github.com/NationalSecurityAgency/ghidra/assets/1017189/b38a739f-fe0a-4793-bdcf-a7a76183a645)

**Comment by edmcman** [comment]
https://ghidra.re/ghidra_docs/api/ghidra/app/decompiler/DecompInterface.html#:~:text=%22decompile%22%20%2D%20this%20is%20the,syntax%20trees%20of%20the%20dataflow. says about "normalize":

> It is suitable for creating normalized pcode syntax trees of the dataflow.

I'm not sure that I agree.

**Comment by ghidracadabra** [comment]
Thank you for reporting this.  I wasn't able to reproduce the issue in the function you mentioned, but I could get it to occur in other functions in the binary.  

In general the "normalize" style should result in a graph with the edges you expect.  However, in the decompilation you provided, the line 
- `uStack_8 = 0x411896;` (an assignment of a local variable to a value which happens to be an address in the body of the function)

is an indication that something might be amiss with the decompiler's stack analysis.  The  `__RTC_CheckEsp` function might need a call fixup - I'll need to dig into this a little bit.  There are a number of calls to `__RTC_CheckEsp` in this binary; once the fix is in place the analysis should improve.  You can try editing the signature of `__RTC_CheckEsp` and marking it as "In Line".  This should fix many of the callsites, but for some you will probably get a message that inlining was not possible.

The "decompile" simplification style treats INDIRECT ops differently than "normalize" in some cases, which may be why you see the edges you expect if you comment that line out.  Note that the `Graph Data Flow` action in the decompiler windows (upper right corner) uses the "decompile" style to draw the graph, so that should also have the edges you expect.

**Comment by edmcman** [comment]
Interesting, thank you for the explanation of what is going on!  The situation was very confusing because I was trying to use the DDG to gain a better understanding of the High Pcode in general.

> The "decompile" simplification style treats INDIRECT ops differently than "normalize" in some cases, which may be why you see the edges you expect if you comment that line out.

Can you elaborate or point to an area of the code that explains this?  Not important, just for my own understanding of the Ghidra decompiler (which needs a lot of improvement).

> Edit: we should also probably have the script and the action use the same decompiler setting...

Agreed!  Though it also begs the question of why both exist in the first place instead of just one of them...

**Comment by edmcman** [comment]
Also, making the `__RTC_CheckEsp` call inlined as you suggested did fix the problem with the GraphASTScript.

**Comment by d-millar** [comment]
@edmcman Re "why both exist" - largely historical.  The script pre-dates the pull-down but was found to have more utility.
