### ISSUE TITLE
Does NSA really use this ?

### ISSUE THREAD

**Issue by alom4hdi** [NationalSecurityAgency/ghidra#5765]
Its not a better choice to use IDA pro for NSA purposes ? Cause its better than Ghidra ?

**Comment by NeedsMoar** [comment]
You're assuming the NSA still uses this internally, or that their internal version isn't 10 years ahead of the open source release in features...  or for that matter that they'd bother with _software_ diassembly when they probably have in-circuit emulators for every processor architecture anybody cares about.  Most Epyc motherboards have the header for ICE connection waiting for a soldered connector and somebody with the hardware that will perform handshaking correctly.

Or it's a big misdirection and they want people thinking they use this and they really just use IDA Pro internally.  Assuming that what a spy agency appears to be doing and what they are doing are related in any way is probably a bad idea.  

IDA Pro is written by someone outside of the US which is probably a big issue for a US government agency if nothing else, and  verifying the safety of running updates on their internal machines is probably a huge amount of work and would probably need to be done to meet their internal standards, although I don't work there so I don't know.

**Comment by alom4hdi** [comment]
@NeedsMoar thanks

**Comment by NeedsMoar** [comment]
I should also add that the last larger red team I did years ago before I got out of software engineering / security (involved an AACS vs. an implementor suspected of leaking keys, because the AACS apparently wasn't willing to effectively yell at themselves in the form of Sony, one of the main companies involved in Bluray creation and their ongoing PS3 exploit at the time), work bought us a 1-node IDA Pro floating license and bought me a named license of standard.  Our company was involved because if we proved that their implementor's protection had been inadequate (AACS required horrifying things like an obfuscated ring 0 driver for playback on PC), in addition to the $$$ they were getting from the red team they were likely going to be able to sell our hideously expensive protection product to the third party.  

Because of the number of ways this software was required to fail and the system access it had, it was more actively hostile / dangerous than any file infecting virus that didn't have some kind of script kiddie payload like drive corruption, and had the potential for a 1/100 type deal of being worse than cryptoware (which you can at least pay somebody to fix).  Getting any kind of debugger within 1000 feet of any of the memory this driver was watching or running one at all during the key exchange where the most likely exposure of the desired key would occur caused an instant trashing of a huge memory range that included most of the windows kernel and a bluescreen, so static analysis was "easier" (work wouldn't buy me a $15k x86 ICE despite my line about for-profit movie pirates easily affording one because of the cost, may have had something to do with the fact that it probably would have needed the entire time allocated for the project to learn to use correctly as well) but there were also tons of ways looked into to access the memory without the ring 0 driver noticing.  Any and all debuggers and software possible were tried, intentional crashes that didn't involve triggering their intentional crash, various PE and crypto constant scanners dating from modern to not updated in 10 years, and old windows 95 era disassembler that didn't try to be as smart about control flow, various types of debuggers, and I even modified a hypervisor-based debugger project that had been abandoned so that it could support more than one core (as another part of the AACS agreement was that programs couldn't run on single-core systems so just disabling 5/6 cores in the bios wasn't an option) although that turned out to be a dead end as well because it couldn't be signed within the time frame most likely (if MS would even do it) and there was only a slight chance of the ring 0 driver not noticing a hypervisor running since there were ways to check.  I considered trying to write a debugger that hijacked SMM but there was no way that was happening in the time frame either.  I even used plenty of Scotch or Bourbon when I was stuck and it was getting towards the end of the work day, which helped me come up with lots of new ideas.  Not necessarily good ones, but they were new at least.

I never did find any leaking of keys, although I learned that I should rip any blurays I purchased and play them with some other player and uninstall the software that came with my drive which wasn't the same but they're all required to do the same thing.   Luckily this was accepted by the AACS because I didn't want to be called as an expert witness in a tribunal

My point here is that when you're attacking some piece of code the best bet is generally throwing everything you've got at it.  IDA will help find simple constructs that aren't well-hidden right away if you know what you're looking for...  heck, a lot of times just listing the imports of something is enough to classify it as suspicious.  If it's not very obvious most of the time you're better jumping tools first before going nuts in IDA or you might pass up an easy "win".   I rarely disassemble anything any more, but I still have my old named license because I paid the support fees for the next 3 years and work didn't feel like they had any claim on it any more...  it's 32-bit only but thankfully IDA has the free version now which is sufficient for lots of simpler stuff.  Lack of scripting and some of the other features are kinda ugly but hey, it's free.  I haven't even tried Ghidra since it came out after I wasn't doing this for a living but was preparing to download / try it on a whim when I saw your question browsing issues for anything painful that might come up right off the bat.    Then I remembered that it was written in Java, which ranks somewhere just above python on my "dear god, why was it written in that, was not performing well a design goal?" list and figured I'd think it over a bit longer.  :D

**Comment by nightlark** [comment]
> Then I remembered that it was written in Java, which ranks somewhere just above python on my "dear god, why was it written in that, was not performing well a design goal?" list and figured I'd think it over a bit longer. :D

Aside from using C++ for the decompiler: https://github.com/NationalSecurityAgency/ghidra/tree/master/Ghidra/Features/Decompiler/src/decompile/cpp

Maybe due to performance :smile:
