### ISSUE TITLE
Expression logic error in decompiled code, may be memory layout error

### ISSUE THREAD

**Issue by zijiancogito** [NationalSecurityAgency/ghidra#5797]
**Describe the bug**
I have carefully analyzed the decompilation results of the binary file in the attachment and found a logic error. This error appears to be a bug in the mapping of the content stored on the stack. The second operand of the instruction at 0x001013ad, 'local_c', should correspond to the return value of the function f_rand_2() at 0x00101160. However, the decompilation results seem to incorrectly identify it as the constant 0x2a6 at local_2c.
What's more, 'iVar1' should not be redifined in line 33.

**To Reproduce**
decompile the attached files

**Expected behavior**
code in line 38 should be local_28 = (local_28 % local_14) - iVar1, iVar1 is the return value of f_rand_2.

**Screenshots**
<img width="1582" alt="1695051639942" src="https://github.com/NationalSecurityAgency/ghidra/assets/11942934/ee017089-af40-464e-90f7-afe20e15cec9">
<img width="713" alt="1695051704186" src="https://github.com/NationalSecurityAgency/ghidra/assets/11942934/0b98cabd-23d9-4915-ad39-6dd2870eecaf">

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.
[Ghidra-43.zip](https://github.com/NationalSecurityAgency/ghidra/files/12650076/Ghidra-43.zip)

**Environment (please complete the following information):**
 - OS: WIN 11
 - Java Version: 20.0.1
 - Ghidra Version: 10.3
 - Ghidra Origin: official GitHub distro

**Additional context**
Clang 14.0 -O0 -fno-inline-functions

**Comment by LukeSerne** [comment]
> [...] the decompilation results seem to incorrectly identify it as the constant 0x2a6 at local_2c.

You are seeing the results of constant propagation. The decompiler realises that the second operand to the subtraction, `local_c` can only have the value `0x2a6`. This is because `local_c` is the return value of `rand_2()`, and if it had a different value, execution would go inside the `if` body and get stuck in an infinite loop at lines 24 to 26 of the decompiled code in your screenshot. In other words, if the execution ever reaches line 28, `local_c` must not have been "not `0x2a6`", so it must have been `0x2a6`. The decompiler realises this, and replaces all further uses of `local_c` by the constant `0x2a6`.

In conclusion, I think the behaviour you have observed is not a "logic error".

> 'iVar1' should not be redifined [sic] in line 33

The decompiler creates variables in the decompiled code for expressions it deems too complex. These variables do not (necessarily) correspond to the variables that were used in the original source code. That information typically gets lost during compilation. It is impossible to perfectly reconstruct this information. In this specific case, I think there's nothing incorrect about `iVar1` being used to store the result of the sub-expression `local_28 % local_14`.

---

However, maybe pivoting this issue a bit, I do agree the the way the decompiler uses variables in the final C code is not always great. While I don't mind it using a local variable to store the intermediate result of the modulo too much (like in your example), I find it especially annoying that it assigns the return value of a function to a local variable, even if the return value is only used once in evaluating a condition or returning a value.

Example output the decompiler might produce something like this:
```c++
int func(void)
{
    bool bVar1;
    int iVar1;

    if (bVar1 = getSomeBool(), bVar1) {
        otherFunc();
    }
    iVar1 = getSomeInt();
    return iVar1;
}
```
I would much prefer the intermediate variables to not be used at all, and instead the function calls being printed directly, like this:

```c++
int func(void)
{
    if (getSomeBool()) {
        otherFunc();
    }
    return getSomeInt();
}
```

In functions that are larger and more complex, not using local variables to store the return value of a function call can reduce the total number of local variables used, and it reduces the complexity of the code, by removing an assignment and a level of indirection. I realise this might be considered a separate issue, and if the Ghidra maintainers prefer, I can create a separate issue for the specific case of the decompiler assigning the return value of functions to local variables.

**Comment by zijiancogito** [comment]
Thank you so much for your analysis. I now realize that I overlooked the above 'if' condition. The logic of the decompiled result is indeed correct. 
Using of "iVar1" is likely to be confusing but correct. 
In this scenario, redeclaring a local variable as temporary storage may be more beneficial for code comprehension than utilizing an existing local variable. The number of local variables may not necessarily be the fewer, the better.

**Comment by LukeSerne** [comment]
If you feel this issue has been resolved, I think you can close this.

> In this scenario, redeclaring a local variable as temporary storage may be more beneficial for code comprehension than utilizing an existing local variable.

I agree. What I tried to say was that I think `local_28 = (local_28 % local_14) - 0x2a6` is easier to understand than the subexpression `local_28 % local_14` first being assigned to a local variable (`iVar1`, in this case) and then the subtraction being printed as `local_28 = iVar1 - 0x2a6`. This introduction of `iVar1` makes it ever so slightly more complex: It's harder to answer questions about the value of `local_28` such as "How does the value of `local_28` change throughout the iterations of the loop?" and, since `local_28` is involved in the guard of the `while` loop, "How many iterations does this loop have?" becomes "How many iterations until `local_28` exceeds 126?".

> The number of local variables may not necessarily be the fewer, the better.

True, though reducing the number of local variables might, in some cases, improve readability. Unfortunately, what readable code looks like is sometimes a matter of opinion, which makes it impossible to come up with general rules on how to generate / format code in a way that makes it readable. However, I think nearly everyone would agree that `if (bVar1 = getSomeBool(), bVar1) {` is less readable than `if (getSomeBool()) {`. As such, I think there is room for (somewhat) objective improvement in the way Ghidra currently represents the decompiled code. Though such suggestions should probably be submitted separately.
