### ISSUE TITLE
Search Program Text should show progress when Next/Previous takes a long time

### ISSUE THREAD

**Issue by comex** [NationalSecurityAgency/ghidra#585]
**Is your feature request related to a problem? Please describe.**
When using Search Program Text, clicking Search All opens a window that shows a progress bar, but clicking Next or Previous just shows an hourglass.

**Describe the solution you'd like**
There should be a progress bar and/or a display of where Ghidra is currently searching.

**Describe alternatives you've considered**
It would also be nice if Search Program Text was faster :)

**Additional context**
IDA shows an indicator for where it's currently searching in the file scrubber bar thingy.

**Comment by dev747368** [comment]
-5 internet points for trying to pressure us with what the other guys are doing.

**Comment by comex** [comment]
I apologize, as it wasn't my intent to pressure anyone.  My main reason for mentioning IDA in feature requests has been to demonstrate that the feature in question isn't just some random idea I had that I speculate might be useful, but something I *know* would be useful if implemented, given that it's useful in IDA.  I admit I also mentioned it because I saw IDA parity as one factor among many potentially worth considering when prioritizing work; again, not with the intent to pressure, but as something worth noting.  But this seems to have been received badly, so I will stop doing it.

**Comment by ryanmkurtz** [comment]
No need to apologize @comex.  I believe @dev747368 was just trying to make a joke.  We welcome all enhancement requests, so we'd love to hear about anything you think would make Ghidra better and more useful. Of course, we have a massive list of enhancement requests to consider and prioritize, so we cannot guarantee when or even if they will get implemented, even if we agree that it is a good idea.  Sorry for any confusion!

**Comment by dev747368** [comment]
yep, my comment could have used a smiley face.

**Comment by dragonmacher** [comment]
@comex The Search Program Text dialog shows not only a spinning hour glass, but also a progress bar.   If you are not seeing this, then can you describe the steps to reproduce the issue?

I'm not familiar with this **IDA** tool of which you speak, so I cannot speak to its functionality.   Our current progress bar shows something to the effect of "1% (26930 of 4493601)".   Are you asking for some other sort of message?

> It would also be nice if Search Program Text was faster :)

Haha, yes, it can be quite slow on large binaries.  You can somewhat mitigate this slow down by reducing the number of fields to be searched via the dialog's checkboxes.  Also, you can also restrict the search to a program selection in order to reduce the search scope.
