### ISSUE TITLE
VT Matches Table require an objective / more coarse Similarity Score

### ISSUE THREAD

**Issue by clearbluejar** [NationalSecurityAgency/ghidra#5859]
**Is your feature request related to a problem? Please describe.**

VT Matches Table require an objective / more coarse Similarity Score.

After running Automatic Version Tracking, or manually running correlators, the matches table contains a similarity score that is not useful in for identifying how similar the matched functions are. 

The Symbols name correlator will score a match 1.0 if two function have the same name, even if the functions are different.
https://github.com/NationalSecurityAgency/ghidra/blob/c24d25f3abc766f48f3f837e4fd1f942c7650071/Ghidra/Features/VersionTracking/src/main/java/ghidra/feature/vt/api/correlator/program/SymbolNameProgramCorrelator.java#L145

The combined function and date reference match seem to provide a score that recognize differences: 
https://github.com/NationalSecurityAgency/ghidra/blob/c24d25f3abc766f48f3f837e4fd1f942c7650071/Ghidra/Features/VersionTracking/src/main/java/ghidra/feature/vt/api/correlator/program/VTAbstractReferenceProgramCorrelator.java#L198-L201

But the similarity scoring seems to be affected by address offsets and is a bit too sensitive. 
![image](https://github.com/NationalSecurityAgency/ghidra/assets/3752074/b713f618-8328-4a57-85c2-a724269d8b1f)

Taking a look at scoring from various correlators for a single function, you can see the variety of scores.
![image](https://github.com/NationalSecurityAgency/ghidra/assets/3752074/fd537f96-b07f-4d2e-ab0e-6f29cc54abfd)

You might even notice that there are some other correlators in that list. 
![image](https://github.com/NationalSecurityAgency/ghidra/assets/3752074/9d077bc8-cd2f-43d6-8d2d-bdbf88064a48)

They are from https://github.com/threatrack/ghidra-patchdiff-correlator.

I use that plugin as a means to overcome this very issue. After I finish matching functions, I run either the Bulk Mnemonics Match or Bulk Basic Block Mnemonics Match to obtain an accurate score for function similarity. 

After running, I can focus on the matches that identify modified functions. 

To demonstrate:
1. Match functions
2. Filter on function that have a similarity score < 1.0
3. Results in 151 matches from the combined function and data reference match. This would also miss any symbol name matches with modified functions (as they are all marked 1.0)
![image](https://github.com/NationalSecurityAgency/ghidra/assets/3752074/44554e18-bab4-49e5-8b7d-71a6df1a64b2)

Using the more coarse similarity score from patchdiffcorrelator ([code](https://github.com/threatrack/ghidra-patchdiff-correlator/blob/master/PatchDiffCorrelator/src/main/java/patchdiffcorrelator/BulkProgramCorrelator.java#L206)), the picture is much clearer.  

![image](https://github.com/NationalSecurityAgency/ghidra/assets/3752074/3e2c8db4-ec12-4d47-9911-36a50a6aaf22)

**Describe the solution you'd like**
I'd like either each correlator to provide a similar score, or if you want to preserve the right for each correlator to create its own score, the best solution then would be to add an objective  "coarse similarity score" column that can be sorted. Likely modelled on the on the scoring used in patchdiffcorrelator. It could just be added as a hook when a match is created, or perhaps when the table is rendered.  

Happy to discuss this more, I have implemented this in my own tooling.

**Comment by ghidra007** [comment]
The similarity score for each correlator was designed to reflect the similarity of the item being correlated. Scores should only be compared to those run by same correlator not between correlators. The symbol is the item being correlated in the symbol correlator so the score is 1.0 if the symbol names are identical. This is to identify functions with the same purpose not necessarily identical code. It helps in the case where binaries are compiled with same language/widely different compiler options or with different language.  Users can start by matching identical symbols and data then running the various reference correlators to find more matches from the known symbol/data matches. Running several different correlators and using the match tables within the Source and Destination Codebrowsers to get a list of correlators/matches for a particular function, can help determine code similarity in your case. Also the side by side view helps visually identify how similar the code is.  I see your point, though, that it is confusing. Maybe there should be a correlator score and function/data similarity score. But that would require each correlator to do more work than was originally intended which could drastically slow down the correlators.

**Comment by clearbluejar** [comment]
> It helps in the case where binaries are compiled with same language/widely different compiler options or with different language. 

Ah, fair point. I didn't consider that. 

> Maybe there should be a correlator score and **function/data similarity score**.

This!  

>  But that would require each correlator to do more work than was originally intended which could drastically slow down the correlators.

Currently, there is a hook for implied matches after each match (as I understand it). I'm not sure how much more overhead it would be to run a function/data similarity score on every match. After matching the functions, when I run `patchdiffcorrelator` Bulk Mnemonics Match on only accepted matches, it completes anywhere from instantly (smaller binaries) to < 30s for the Windows kernel.  Fixing this really increases the usability, especially for patch diffing.

**Comment by ghidra007** [comment]
@clearbluejar The team decided against adding another column to the VT match table because they thought adding another similarity column would be too confusing and in most cases redundant since most similarity scores do reflect the similarity of the function or data it is correlating. Also, you can often combine information from various correlators to get the information you need. If you run the various correlators and do not exclude known matches, you can see all correlator information for a given source or destination association if you look in the SOURCE or DESTINATION code browsers while a match is selected in the match table. Those browsers will navigate to the corresponding source/dest addresses and you will see a table added to each browser that contains all the known match information for each. I hope between this and the plugin you created you will be able to get the information you need to determine function similarity.

**Comment by clearbluejar** [comment]
Without the objective score it is still impossible to sort out which functions actually had code changes within VT. These two issues remain. 

> The Symbols name correlator will score a match 1.0 if two function have the same name, **even if the functions are different.**

> combined function and data reference match is too sensitive
It reports non significant changes. 

@ghidra007,  thank you for considering it.  I'm still a huge fan of VT.

**Comment by clearbluejar** [comment]
although... while I'm here I might as well ask! 

1. Would the new planned customizable VT auto script have the option to run a correlator added from a plugin?  Then I could at least auto run my custom correlator at the end so it would provide the score.
2. Would the team be more open to the column if I provided a PR?

**Comment by ghidra007** [comment]
I will ask the team again if they would reconsider. 

After reading more about the bulk correlator you referenced, I noticed that it says the correlators shipped with Ghidra cannot show similarity scores lower than 1.0. This is true for the exact match correlators but the others have adjustable similarity score limits. The auto VT forced it to only automatically apply ones with similarity .95 or higher and confidence of 1.0 in order to be extra cautious. The new changes allowing options to be set, will allow you to lower the thresholds. Hopefully that will help. 

As currently written it would not find the options to run another correlator but it certainly would be possible if it were written to discover all correlators and add them as options. you could always copy the script and add a run of your correlator afterwards. Or write a script that calls the autoVT script then calls your script. 

It has been on our list for awhile to have follow on actions that would identify various types of differences. There are many ways people would define "differences" though which makes this complicated to design properly. Some people are interested in differences (various types) in the assembly and others in differences in the functionality of the functions that would be more apparent in the decompiler.

**Comment by clearbluejar** [comment]
> but it certainly would be possible if it were written to discover all correlators

Shall I submit a new issue to track it? What release are the auto VT options feature slated for?

> differences in the functionality of the functions 

Yeah the semantic correlation (vs syntax or graph structure correlation) is a difficult problem.

Overall I feel like the object similarity score is still needed, but perhaps I can start with a plugin modification that will add it.
