### ISSUE TITLE
Ghidra Installation on Ubuntu 22.04.3 is totally confusing

### ISSUE THREAD

**Issue by vimleshkumarkanaujiya** [NationalSecurityAgency/ghidra#5868]
1. I downloaded the release edition from Github.
2. Unzipped the source.tar.gz.
3. ``` cd ghidra-Ghidra_10.4_build/Ghidra/RuntimeScripts/Linux ```
4. ```./ghidraRun```
5. But it isn't working and shows following.
6. ``` Cannot launch from repo because Ghidra has not been compiled with Eclipse or Gradle. ```

**Comment by d-millar** [comment]
Just to clarify, you downloaded the link labelled "Source code (tar.gz)" but not link labelled "ghidra_10.4_PUBLIC_20230928.zip"?   If so, you probably (?) should have used the other link:

[https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.4_build/ghidra_10.4_PUBLIC_20230928.zip]

The second two links in each are really archives of the source code, i.e. C and Java files, not executables, and cannot be launched without first using, well, gradle or Eclipse to compile them.

**Comment by ryanmkurtz** [comment]
Closing, as @d-millar has provided the correct explanation for your issue.

**Comment by vimleshkumarkanaujiya** [comment]
Thank you people 💯

**Comment by reikred** [comment]
It would be really helpful it it was made crystal clear in the installation instructions (both README.md and in the htmlversion 
 https://htmlpreview.github.io/?https://github.com/NationalSecurityAgency/ghidra/blob/stable/GhidraDocs/InstallationGuide.html
that when you say "Download a Ghidra [release file](https://github.com/NationalSecurityAgency/ghidra/releases)", you mean specifically the ghidra_10.4_PUBLIC_20230928.zip and NOT  any of the tar.gz files.

It gets confusing because we read the InstallationGuide.html, where it talks about native binaries, which makes us think "oh that zip file is the windows version" and then we download the tar.gz and end up wasting time.

**Summary**: Please be super clear everywhere that the ghidra_10.4_PUBLIC_20230928.zip file is the installation file **both** for linux and windows. Best if it can be noted also on the download page itself.

**Comment by vimleshkumarkanaujiya** [comment]
Yes, I was confused because tar file type predates zip file type. Mostly Unix based system use tar.* and Microsoft uses zip. tar deals with file ownership, permissions, links, special files and zip is a compressing archiver works very with windows but can not deal with file permissions.

**Comment by ryanmkurtz** [comment]
GitHub automatically sticks those tar'ed up source downloads there...I wish they would isolate them a little better.
