### ISSUE TITLE
Display non-local Namespace option on vtables don't work with armv7 thumb because the function is offset by 1

### ISSUE THREAD

**Issue by altalk23** [NationalSecurityAgency/ghidra#5886]
**Describe the bug**
The function pointers in an armv7 C++ binary vtables are missing their namespaces even though the Display non-local Namespace option is checked in Listing Fields/Operands Field.

**To Reproduce**
1. Analyze an armv7 C++ binary that has thumb function pointers in their vtables
2. Enable Display non-local Namespace option for Listing Fields/Operands Field 
3. Go to the vtable
4. The functions are missing their namespaces

**Expected behavior**
The function pointers should have their namespaces, but they are missing.

**Screenshots**
![スクリーンショット 2023-10-15 19 50 55](https://github.com/NationalSecurityAgency/ghidra/assets/45172705/43c7ffc0-691b-42de-a2ef-ca62314f4baa)

**Environment (please complete the following information):**
 - OS: macOS 11.6.8
 - Java Version: 20.0.2
 - Ghidra Version: 10.1.5, I can confirm the issue is there on 10.4 though
 - Ghidra Origin: official GitHub distro

**Comment by ghidra007** [comment]
Have you navigated to the functions to verify there are namespaces on the function symbols? I suspect it is a thumb issue since they are pointing to the function address offcut by 1. It's possible that whatever is showing the field symbol isn't picking up the namespace in that case. Will try to recreate your use case and verify.

FYI unrelated to your issue but related to your binary, there is a RecoverClassesFromRTTI script that is a little bit better in the current version at handling ELF binaries, assuming yours is an ELF and that it has RTTI. I'd be curious to know if the latest Ghidra works on it if you are willing to give it a try. If you do try it, run it on a newly analyzed binary. I'm pretty sure it deals with the offcut thumb issue.

**Comment by altalk23** [comment]
Yeah, all of the functions listed are inside the namespace, they are just missing the namespace in the label text. And I also agree it is most likely related with whatever adds the +1 since it works just fine when that offset is not there and it directly points to a symbol.

**Comment by ghidra007** [comment]
Was able to recreate the issue.
