### ISSUE TITLE
SuperH: trapa Incorrect Usage of pc

### ISSUE THREAD

**Issue by pjsoberoi** [NationalSecurityAgency/ghidra#5891]
Directly related to https://github.com/NationalSecurityAgency/ghidra/issues/5888. 

`*r15 = pc + 2.` should be `*r15 = inst_next`. 

The reason being the program counter register (in this case pc) is never set. See issue 5888 for more info.

**Comment by fenugrec** [comment]
haven't looked at sleigh or even superH in a while, but I have in mind #4396 that was fixed last year and is correctly analyzed. Do I understand correctly that your issue is related to emulation and not the disasm or analysis ?
I also have concerns on using "inst_next" vs delay slots; if I recall using `trapa` "wrong" should trigger some kind of fault; not sure if this is handled at all currently.

That is,
```
 trapa 0x3f
 bra XYZ   ; I think this is ok ?

 bra XYZ
 trapa 0x3F ; probably illegal ?
```

**Comment by pjsoberoi** [comment]
Good point regarding the delay slot. I'm not sure how to handle it then. Maybe inst_start + 2? Is that a thing?

Agree with you on the example. The first looks legal, the 2nd is definitely illegal.

![image](https://github.com/NationalSecurityAgency/ghidra/assets/60081609/6bf6d334-39ce-4cb8-8913-df951beb034b)
