### ISSUE TITLE
6502: Unable to Read Entire imm16

### ISSUE THREAD

**Issue by pjsoberoi** [NationalSecurityAgency/ghidra#5923]
I'm working on resolving a bug in the JMP instruction in 6502 processor module. I need to be able to read both bytes of imm16 but for some reason the first byte is valid but the second byte is always 0. I'm stumped. 

```
define token opbyte (8)
   op       = (0,7)
   
   aaa      = (5,7)
   bbb      = (2,4)
   cc       = (0,1)
;

define token data8 (8)
   imm8		= (0,7)
   rel		= (0,7) signed
;

define token data (16)
	imm16 = (0,15)
;

:JMP imm16     is (op=0x6c); imm16
{
    X = imm16 & 0xFF; // valid
    Y = imm16 >> 8; // always 0
}
```

Initial state (unit test):
```
	Registers:
		A: 25
		P: 239
		PC: 64399
		S: 123
		SH: 1
		X: 194
		Y: 3
	RAM:
		33302: 100
		49476: 22
		49477: 130
		64399: 108
		64400: 68
		64401: 193
```
Opcode is 108 (0x6c), X is 68, and Y is 0 instead of the expected 193. 

Any idea what I'm doing wrong? Thanks in advance.

**Comment by GhidorahRex** [comment]
try saving imm16 to a local variable like so:
```
local tmp:2 = imm16;
X = tmp(0);
Y = tmp(1);
```

**Comment by pjsoberoi** [comment]
Yes that works. Can you help me understand why? The previous syntax feels like it should work and feels more consistent. Thanks again.

**Comment by GhidorahRex** [comment]
When you have an immediate value, it doesn't have a default "size" associated with it. So it ends up conforming to the size it needs to be for the operations to be correct. In your case, since you were assigning it to Y, it defaulted to 1 byte even though it's technically larger than 1 byte. By assigning it to a two-byte variable, it locks the size in at 2 bytes.

I'm going to go ahead and close this ticket since the issue is now resolved.
