### ISSUE TITLE
Can Ghidra be configured to exceed the 16k max null-terminated string size? 

### ISSUE THREAD

**Issue by as0ni** [NationalSecurityAgency/ghidra#594]
I recently looked at malware with a 16k+ size base64 encoded null-terminated string. Ghidra did not identify the string due to its large size. Is this configurable in the interface somewhere?  (FYI, the "Data" help page says "A null- terminated string will extend until a null character is found (with a sanity check max of 16k)...".

**Comment by dev747368** [comment]
No, the sanity check is hard-coded right now.  This is a interesting situation though.

**Comment by dev747368** [comment]
As a quick workaround, you can manually create a string instance at that location using a GhidraScript:

`currentProgram.getListing().createData( askAddress("String start", "starting addr"), StringDataType.dataType, askInt("String len", "number of bytes"));`

**Comment by emteere** [comment]
Maybe the string identification should identify the string up to the max, and then start another string.
If it is a string up to the max length, then it is still a string.
You may also be able to force a string with a selection and create a string.  The string data type doesn't always rely on there existing a terminating null, since a string buffer in memory could be uninitialized, or all zeros.

**Comment by ryanmkurtz** [comment]
Question was answered...closing.
