### ISSUE TITLE
ARM EPOC PE support

### ISSUE THREAD

**Issue by mupfdev** [NationalSecurityAgency/ghidra#5948]
**Is your feature request related to a problem? Please describe.**
I am a passionate Symbian S60v1 developer and I have already created a development environment for modern systems for myself and others to develop for the Nokia N-Gage: https://github.com/ngagesdk

Unfortunately, it is often unavoidable to de-compile native applications so that the tricks of the trade are not lost. Open source was not the norm in the Symbian universe.

Sadly, the only way to work with ARM EPOC PE is currently IDA Pro 7 which can't de-compile to C/C++.

**Describe the solution you'd like**
Please add support to open and analyze files in the ARM EPOC PE format.

**Useful resources**
https://web.archive.org/web/20141018215857/http://www.antonypranata.com/node/10

https://github.com/mrRosset/E32Explorer

**Describe alternatives you've considered**
IDA Pro 7

Best regards, Michael

**Comment by ryanmkurtz** [comment]
Because this is such a niche thing, we are likely never going to support it.  However, Ghidra was designed to be very extensible for this very reason.  I recommend you create a Ghidra extension that contains a `Loader` capable of handling this target.  There are many examples within Ghidra and on other people's GitHub pages on how to do this, and we'd be happy to answer any questions you may have about it.

**Comment by ryanmkurtz** [comment]
Closing the ticket, but please reach out if you need help developing a custom `Loader`.
