### ISSUE TITLE
Cannot view/edit function override

### ISSUE THREAD

**Issue by marcushall42** [NationalSecurityAgency/ghidra#6000]
**Describe the bug**
Just updated to ghidra 10.4 and a change between 10.1.5 and 10.4 disrupts a part of my workflow..

If a function call has a signature override, now it seems that the only option in the context menu is "Remove Signature Override".  Previously, the "Signature Override" menu entry would open to an existing override and I could edit that.  Now it seems that I cannot view the existing override at all.

Viewing/Editing an override was very useful:

-- If I needed to add an additional argument to the override, or if I have better refinement for one of the arguments (say change "void *" to "struct_XXX *").  If there are many arguments already there, it's difficult to remember what they were if I have to re-enter the entire signature whenever there are any changes.
 -- If I need to copy the signature to produce an override in another place, it was useful to open the override in one call site, copy the override and escape out, then create an override at another call site with the same (or slightly modified) override.

**To Reproduce**
Right click over a call site with an existing Override.  The only option is to Remove the existing Override.

**Expected behavior**
Some way to at least view what the override is so I can copy it, delete it, and re-enter it if I have to.  The old behavior would be preferable, though.

**Environment (please complete the following information):**
 - Ghidra Version: 10.4
 - Ghidra Origin: official GitHub distro

**Comment by emteere** [comment]
Is your use mostly with calls to vararg functions like printf?

There was a change made in 10.3 that I can see that would cause this behavior.

The way it was implemented previously, these overrides would accumulate and not get deleted.
The signatures can be re-used by other locations if they are exactly the same.
The signatures are essentially a hash of the signature stored in the data type manager in the folder auto_proto.

So if you were to edit it, you might change somewhere else.

It is cleaner now, and signatures don't build up.

I do agree that the "Signature Override" could be added back and done carefully so that if it exists you would essentially have what was there, and be able to edit it.  This would need to be done carefully so that other locations weren't affected.

**Comment by marcushall42** [comment]
Yes, commonly used for varargs functions.  Currently I'm finding it useful for virtual function calls, with the heavily used virtual methods getting function definitions so I can put that into the vtable.

In the past, I could just hit delete in the listing window to delete the override.  I did think that the override was unique for each call site, though.  I was not aware that they were accumulating, that could certainly be a problem..  I had thought that it was a property map unique to each address or something...
