### ISSUE TITLE
Cursor Text Highlighting Color in Decompile Window

### ISSUE THREAD

**Issue by EntropyEndeavor** [NationalSecurityAgency/ghidra#6001]
**Describe the bug**
The Cursor Text Highlighting feature allows you to highlight other instances of a variable etc. By default this is done with the middle button on the mouse, although this is customizable. If you change the button in the settings for the Listing Window then the button is also changed for the Decompile Window, which would indicate the settings are actually for both windows. However, a change in color is only applied to the Listing Window, not the Decompile Window. As best as I can tell there is no setting that will change the highlight color for Cursor Text Highlighting in the Decompile Window. I personally am trying to change the color since the nighttime blue light filter I use makes it near impossible to see the default color.

**To Reproduce**
1. Go to Edit->Tool Options.
2. Go to Listing Fields/Cursor Text Highlight
3. Change the highlight color
4. Use the chosen button (middle by default) to select something in the Listing window to observe the new color.
5. Use the chosen button to select something in the Decompile window to observe the original color.

**Expected behavior**
Either for the Decompile window to use the Cursor Text Highlighting color from the Listing Field options, or for there to be a separate settings window that controls both the color and mouse button for Cursor Text Highligting in the Decompile window.

**Screenshots**
The screenshot shows the DS register with the correct Cursor Text Color Highlighting color in the Listing window and the unaff_SS variable with the incorrect color in the Decompile window.
![image](https://github.com/NationalSecurityAgency/ghidra/assets/152674086/84c4d5d9-c917-4c08-8189-a48ec40340cb)

**Environment:**
 - OS: Windows 11 Pro 22H2
 - Java Version: 21.0.1
 - Ghidra Version: 10.4
 - Ghidra Origin: official GitHub distro

**Comment by dragonmacher** [comment]
The Decompiler does share the middle-mouse highlight color with the Listing.  However, the option for changing that is not the one you have shown.  Instead, it can be found in the options under `Listing` -> `Selection Colors` -> `Highlight Color`.   

The options screenshot above shows the values that are used specifically for the colors related to highlighting scoped register usage.  Granted, the fact that that shows `Highlight Color` is confusing, since it has the same name as the option I mentioned above.

This value can also be changed by editing the theme value for `color.bg.highlight.listing`.

**Comment by EntropyEndeavor** [comment]
Thank you. I can confirm this option changes the color in the Decompile window as desired.
