### ISSUE TITLE
NPE GoRttiMapper

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#6006]
Forgive the crudeness of this report, I'm submitting from my phone.

Cannot invoke `ghidra.app.util.bin.format.golang.rtti.GoRttiMapper.init(ghidra.util.task.TaskMonitor)` because `supplier_result` is null.

GoRttiMapper.java:113
Transient program properties.java:106
GoRttiMapper.java:107
GolangSymbolAnalyzer.java:113
AnalysisScheduler.java:186
...

**Environment (please complete the following information):**
 - Ghidra Version: 10.5_DEV approx 6242fda

The GitHub app let me assign it to someone which silently failed when submitted :joy:

**Comment by dev747368** [comment]
thanks.

The quick fix is just a null check at GoRttiMapper line 113, but the bigger issue is that the binary isn't a go binary, or its an older version that isn't handled yet.

**Comment by astrelsky** [comment]
> thanks.
> 
> The quick fix is just a null check at GoRttiMapper line 113, but the bigger issue is that the binary isn't a go binary, or its an older version that isn't handled yet.
> 

It is a go binary, it's something I wrote myself. Go version 1.21.3

**Comment by dev747368** [comment]
Ah yeah.  Its been a few months since I looked at it.  The GoVer enum currently maxes out at 1.20, and would need a 1.21 .gdt.

**Comment by astrelsky** [comment]
> Ah yeah.  Its been a few months since I looked at it.  The GoVer enum currently maxes out at 1.20, and would need a 1.21 .gdt.
> 

That may not be the best way to handle it. Looking at the go release history, it looks like they put out a major release twice a year.

**Comment by dev747368** [comment]
For some reason the message with the failed golang struct name wasn't logged at all.  I'm sure my code was perfect, must have been something else.  😄 

The OutputParamCheck stuff is normally avoided when a supported golang version successfully parsed, but could happen in non-golang situations also.... its just that golang uses that dwarf feature on just about everything causing the spam.

I haven't poked into the 1.21 changes in much depth yet, but I suspect they changed enough things that just mapping an old structure name to a new structure name is not the main concern.  Some of the internals of golang seem to be pretty fluid even between minor point releases.  I think because they're open source and they have the entire toolchain in their repo its easier for them to make binary format changes that other toolchains would hesitate to make.

**Comment by ryanmkurtz** [comment]
Fixed by f6305f2cba5b4e5c43d69e0d3cedf476ffa1eeee
