### ISSUE TITLE
MIPS binaries with debug symbols incorrectly loaded

### ISSUE THREAD

**Issue by Nemoumbra** [NationalSecurityAgency/ghidra#6025]
I have noticed a very strange behavior of the MIPS loader that occurs when a binary with debug symbols is imported. As I was working with the Allegrex Ghidra plugin (it adds support for MIPS-Allegrex special instructions) at the moment, I reported it initially to the plugin's repo.

https://github.com/kotcrab/ghidra-allegrex/issues/36
There you can find the screenshots of this behavior and my discussion with Kotcrab that explores the issue in detail.
TL;DR - Ghidra makes a total mess from the binary: there's not a single "code" in `.text`, only gigantic chunks of "data", the labels are all over the place, the functions are created in the middle of the real function bodies and they're assigned incorrect names. That's disastrous.
I was worried the debug symbols are just wrong, but it looks like some other tools (such as PPSSPP or IDA) handle them correctly. I propose that this matter is looked into.

**Expected behavior**
The labels have to be applied accordingly, no data in text, etc.

**Screenshots**
You can check the screenshots in the original issue.

**Environment (please complete the following information):**
 - Windows 10
 - Java Version: jdk-19.0.2
 - Ghidra Version: 10.4
 - Ghidra Origin: official GitHub distro

**Comment by ghidra1** [comment]
There appear to be some symbols that claim large areas.  Ghidra ELF loader places undefined arrays on these regions but these can easily be cleared to reveal the symbols that have been placed within their boundaries.  Just hit the 'C' key with your cursor placed on the top of the array data.

You can remove all of these undefined arrays using the Windows->Defined Data display and filtering on all undefined[nn] arrays (there are quite a few sizes), generate selection from this, and use the 'C' clear action to clear the selected code units.  After this is done you can run auto-analysis.

The ELF importer should probably provide an option to disable the creation of undefined array data.

**Comment by Nemoumbra** [comment]
Well, that much was obvious already, like I said here: https://github.com/kotcrab/ghidra-allegrex/issues/36#issuecomment-1852943442

The labels pose a significantly harder problem.

**Comment by ghidra1** [comment]
I did identify the problem in the ELF Loader and will attempt to get a fix out in the next patch.

**Comment by ghidra1** [comment]
I am finding inconsistent behavior with other binaries when it comes to the area of the code in question.  Sorting this our may delay a patch since my original thought breaks other cases.

**Comment by ghidra1** [comment]
After digging into this more it appears that PSP MIPS binaries are rather non-conforming and have some characteristics that are unique to PSP such as: custom file type (e_type=0xffa0) as well as custom relocation sections (sh_type=0x700000a0) whose encoding of r_info is unique to the PSP.  Provided the image is loaded at its default offset it may be possible to ignore these relocation tables.  The effort to support this custom relocation table is much more extensive than we can justify for PSP images, although I may take the oppotunity to see if such an extension could be facilitated.

The processing of these relocation tables for PSP MIPS can be seen here: [PPSSPP ElfReader.cpp](https://github.com/hrydgard/ppsspp/blob/master/Core/ELF/ElfReader.cpp)

I have experimented in Ghidra with just correcting the PSP symbol placement for a default image base and the results look much better - at least for the binary I am experimenting with.

**Comment by Nemoumbra** [comment]
Then it's the plugin's fault after all?

**Comment by kotcrab** [comment]
Hopefully the relocations don't matter for this issue and it can be fixed in the common loader.

To add some insight: PSP relocations can't be ignored if the binary is relocatable, even when loaded at the "default" 0 address. If ignored it causes some instructions to have wrong data offsets. There is also separate type of relocations for kernel modules (`sh_type=0x700000A1`). PSP has a non standard calling conversion and the instruction set also deviates from the standard MIPS. This is all handled by the ghidra-allegrex plugin, having official support for PSP would be nice but it's a pretty big undertaking.

**Comment by ghidra1** [comment]
It may be possible to apply PSP relocations post-import as is done by the MingwRelocationAnalyzer.  

The ElfHeader can re-instantiated post-import to access header information which could help to facilitate this.  Example:
```
FileBytes fileBytes = program.getMemory().getAllFileBytes().get(0);
ByteProvider byteProvider = new FileBytesProvider(fileBytes);
ElfHeader elfHeader = new ElfHeader(byteProvider, msg -> Msg.error(this, msg));
```

**Comment by ghidra1** [comment]
@kotcrab I am working on the assumption that e_type==0xffa0 implies relocatable because I am triggering on this file type to correct the section-relative symbol offset issue which by default relied on e_type==ET_REL

**Comment by kotcrab** [comment]
`e_type==0xffa0` is used for most (maybe all) PSP binaries as far as I know. It doesn't always imply it's relocatable though, there are some games which are not relocatable. In Ghidra plugin it's processed at import time with [this logic](https://github.com/kotcrab/ghidra-allegrex/blob/519e9cf232172770bf811702dce84bd669c394ea/src/main/kotlin/allegrex/format/elf/relocation/AuxRelocationProcessor.kt#L17) checking for relocations presence in sections _and_ program headers.

The original issue was about debug symbol placements though and the discussion shifted to relocations. Do you think those debug symbols placements are affected by the relocations or did we somehow lose focus here. If it's affected by relocations perhaps the fix will need to be in the plugin? Hard to say without knowing what's causing the issue here.

**Comment by ghidra1** [comment]
> The original issue was about debug symbol placements though and the discussion shifted to relocations. Do you think those debug symbols placements are affected by the relocations

@kotcrab I have addressed the symbol address issue, although the logic which computes a symbol address relies on knowing if a binary is relocatable - I am assuming this `e_type` can be used to infer how the ElfSymbol value is treated.  At this point, we do not allow the image base to be specified since we are not handling the relocations.  When an ElfSymbol refers to a loaded section the symbol-value is treated as relative to the section start only when the binary is relocatable.  Otherwise, the symbol value provides an absolute address.  Can you inspect an `etype==0xffa0`binary which you believe is not relocatable and check the ElfSymbol values if they are relative or absolute.

**Comment by kotcrab** [comment]
Sorry for the late answer, that assumptions seems fine. On the games I've checked the non relocatable ones have `e_type=0x2`.
