### ISSUE TITLE
SLEIGH: How to Handle Intentional NOP?

### ISSUE THREAD

**Issue by VGKintsugi** [NationalSecurityAgency/ghidra#603]
How can I handle an intentional NOP instruction in my processor spec? The reason I don't want to leave it blank is because I get a warning ("WARN  4 NOP constructors found (SleighCompile)  
") when I compile my processor. Example:

    :nop  is opcode_00_15=0b0000000000001001 
    {
        # BUGBUG: intentional nop
    }

Obviously I can do something like "r0 = r0;" but is there a better way? Thanks in advance.

**Comment by mumbel** [comment]
`goto inst_next`

**Comment by emteere** [comment]
Not a bad fix for NOP warnings.  There is an "unimpl" that can be used for instructions that are not implemented and should not be assumed to have no effect. A "nop" tag could be added to note that the nop behavior was intentional which would get rid of the warnings.  It would generate no Pcode, but suppress the warning.

**Comment by VGKintsugi** [comment]
I think a "nop" tag would be a great idea. I think the defaults should be swapped. An empty SLEIGH definition ({}) should be treated as "unimpl" by default and an intentional "nop" should be labelled as such.

**Comment by emteere** [comment]
In further discussion, if you want to suppress the NOP warnings, I would encode a NOP as:
```
local NOP = 0;
```
Anything else will mess with the instruction op-objects and/or flowtype.

**Comment by mumbel** [comment]
Then I guess `NOP = NOP;` to avoid the `operations wrote to temporaries that were not read` if you're going for warning less
