### ISSUE TITLE
Ghidra on Mac (Apple SIlicon) fails to start while attempting to create cache directory in temp directory it doesn't has permission to

### ISSUE THREAD

**Issue by nuschpl** [NationalSecurityAgency/ghidra#6064]
**Describe the bug**
A clear and concise description of the bug.

**To Reproduce**
1. Compile Ghidra from source on Mac Apple Silicon M2m, Ventura 13.6.3
2. Unzip the only distributable named ghidra_11.1_DEV_20231229_mac_x86_64.zip despite compiled on Apple Silicon (aarch64)
3. Launch ghidraRun from it noticing silent failing
4. Launch support/launch.sh to find it has no permission to create /var/tmp/USER-ghidra while it has to create user temp directory
5. Manually create the cache directory, chown to local user, notice now Ghidra is correctly starting with below in log:
```
INFO  User temp directory: /var/folders/nd/j4bss2xxxxxx5k7dst3gw6r0000gp/T/USERCUT-ghidra  (GhidraRun.java:79)
INFO  User cache directory: /var/tmp/USERCUT-ghidra  (GhidraRun.java:80)
```

**Expected behavior**
Initialize cache same way as temp or request elevation of privileges if this would be really needed

**Environment (please complete the following information):**
 - OS: OSX  Ventura 13.6.3
 - Java Version: 17
 - Ghidra Version: 11.1_DEV, 20231229 head - Ghidra Origin: built from official GitHub distro

**Comment by ryanmkurtz** [comment]
Can you share your permissions on the `/var/tmp` directory?  On Sonoma mine is `drwxrwxrwt`.  This is a new default location for the cache directory so it might reveal some platform inconsistencies.

**Comment by ryanmkurtz** [comment]
I tried on 2 different Ventura machines and i'm also seeing `drwxrwxrwt` there too.

**Comment by nuschpl** [comment]
Mine are: `drwxrwxr-t root wheel` . I didn't change anything unless some endpoint protection/EMM software did. I'm not experiencing any issues with other software because of that. Can't you use  modern secure ways of creating unguesable temp files and directories like Java's
```java
import java.nio.file.Files
Path tempfile = Files.createTempDirectory(null, ".tmp")
```
or python's:
```python
import tempfile 
tempfile.TemporaryDirectory()
```
It seems it creates directory with long guessable path similar to the other one in the log.
Currently the cache in /var/tmp/USERCUT-ghidra/ is kept there unencrypted lot of days  after Ghidra was used. So having in mind sensitive nature of tasks performed it might be even considered a security threat - project GPR files might be encrypted at rest somewhere and this cache is left with read permission to all users of the machine. This could be leveraged by state level attacker to filter controlled machines towards selecting those where actual RE with Ghidra is happening not just the software installed.

**Comment by ryanmkurtz** [comment]
Ghidra uses 3 different types of user directories...a user settings directory, cache directory, and temp directory.  Each of these serves a different purpose, which are outlined here: 
https://github.com/NationalSecurityAgency/ghidra/blob/7765e8338bb9f866ce31ba98059243f0af2ca80d/Ghidra/RuntimeScripts/Common/support/launch.properties#L86-L127

As you can see, they are all able to be overridden.  The goal is to pick a set of reasonable and standardized defaults that satisfy the requirements of each directory type, and provide a means to override them if there are specific needs or concerns (like your state level attacker example).  

For macOS, it seems the standard location for program cache directories is `/Users/user/Library/Caches/`.  However, we have users that use network mounted home directories, and we can write large amounts of data to our cache directory (for GFileSystem stuff), so that location isn't ideal.  `/var/tmp` seemed like a great choice on Linux and macOS for the cache directory, but this permissions issue is a problem...especially the way Ghidra handles it (failure to launch).

It's still unclear how common your issue is, so I am thinking we fall back to putting the cache directory in the user temp directory if it's unable to write there.  This is where the cache directory used to live (in Ghidra <= 11.0).
