### ISSUE TITLE
GDB IN-VM: Use DOS line endings sends LF LF instead of CR LF on Linux

### ISSUE THREAD

**Issue by nm004** [NationalSecurityAgency/ghidra#6073]
**Describe the bug**
GDB/MI commands sent by Ghidra have two line feed characters (`LF LF`) instead of `CR LF` if you set "Use DOS line endings" checked.

**To Reproduce**
1. Open Debugger
2. Select "Debug <application> in GDB locally IN-VM"
3. Check "Use existing session via new-ui" and "Use DOS line endings (unchecked for UNIX and Cygwin))"
4. Click "Connect"

Then, I could confirm this issue by following these steps:

1. Open a terminal emulator, then issue `cat -v < /dev/pts/[ghidra's pty num]`
2. On another terminal, issue `echo '=thread-group-added,id="i1"' > /dev/pts/[ghidra's pty num]`
3. You can see the input from Ghidra on the terminal opened on Step. 2

```
-interpreter-exec console "show architecture"

```
It has two LF characters instead of one (a blank line after the first line).

**Expected behavior**
GDB/MI commands have `CR LF` line endings.

In the test case above, we should see the following output (`^M` is at the end of the first line and no blank line is followed):
```
-interpreter-exec console "show architecture"^M
```

I think this happens becase the pty that Ghidra opens has `icrnl` termios setting by default, which must be off. You can check it by `stty -F /dev/pts/[ghidra's pty num] -a`

**Environment (please complete the following information):**
 - OS: Fedora Linux 39 (Workstation Edition)
 - Java Version: 17.0
 - Ghidra Version: 11.0
 - Ghidra Origin: official GitHub distro

**Comment by nsadeveloper789** [comment]
Is this flaw preventing you from using this feature? If I may prod, what is your use case here? Or is this more about the software doing precisely what it says, in principle?

The text on the checkbox indicates you should not enable it on UNIX (Linux is a UNIX, despite the expansion of its acronym) nor on Cygwin. The behavior you demonstrate of the pty is part of Linux, so I do not believe this is truly a flaw in practice.

That said, it seems like a low-risk change, but we won't know until we test. We'd like to know how necessary this actually is in practice before we put in any work.

**Comment by nm004** [comment]
@nsadeveloper789 Thank you for your reply.

First thing is first, I found this feature is not required for my use case after some investigation. FWIW, let me tell you what I was working on.

I was trying to run GDB on Wine and control it directly through Ghidra. I first tried to use gdbserver as it was described on [this page](https://john-millikin.com/debugging-win32-binaries-in-ghidra-via-wine) and scripts bundled with Ghidra. Unfortunately, gdbserver did not work well especially with multi-threaded applications. There were problems such as GDB always does break whenever a thread terminates. On the other hand, running gdb directly on Wine worked well even with multi-threaded applications.

I tried `new-ui` command by passing Ghidra's pty, but GDB stopped responding when I launched the debbuged program (they implemented event loop with `select()`, it does not work well with Windows and Wine). Next, I tried to connect GDB on Wine to Ghidra with a shell script that mimicked GDB on Linux. To my surprise, they could talk each other even after launching an program. Some tweaks were still needed for features like manual interrupting (I also had to patch GDB to generate `info proc mappings` but that's another story). Manual interrupts need direct input from a tty (pty), but not from a pipe. Also, Wine pre-processes input when the standard input is a pty, so input filtering was necessary (this was also true for output).

Lastly, I have suceeded in connecting GDB on Wine and Ghidra. However, it still does not meet my requirements. For example, the communication between GDB and Ghidra freezes when GDB receives an interrupt. This is because GDB and Ghidra exchange a lot of data and Wine's pre/post-processing slows down their communication (espacially when there are many threads). In my case, the debugged program has ~80 threads, and their communication stops for around 2-3 mininutes.

That's the whole story. Thank you for taking your time. I'm very surprised the power of Ghidra.

P.S.
I am curious for use cases of this option. Programs on Windows opens [stdin in text mode by default](https://learn.microsoft.com/en-us/cpp/c-runtime-library/text-and-binary-mode-file-i-o?view=msvc-170), and so does GDB. According to [the Microsoft's `fopen` manual](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/fopen-wfopen?view=msvc-170) (and some investigation), both a single LF and CR LF sequenses are sent to an apllication as LF in text mode, so I think sending LF terminated lines to GDB has no problem even on Windows. Additionaly, It looks like Ghidra on Windows does not even have "Debug in GDB locally IN-VM" menu item. Is "Use existing session via new-ui" option obsolete?

**Comment by nsadeveloper789** [comment]
Interesting. Some of these configurations where I've seen people attempt to debug Windows apps on Linux/Wine have been rather convoluted. This is quite an example.... FWIW, I'm hoping that the upcoming Trace RMI stuff will greatly simplify this. Instead of stdio, it'll use TCP, and for gdb, it's a Python plugin, so this setup should be easier 🤞 . But, that's yet to come.

You might just try using Linux gdb on wine itself. You'll need to unwrap the wine scripts a bit to get at the command line for the actual wine binary, but I've had success doing it for Minesweeper :) . To gdb, wine is just a regular Linux app, so you don't need the wine32 helper scripts, and this simplifies the connection between gdb and Ghidra. However, Linux gdb is unable to parse the PE files that wine maps into memory, at least with the version I tried. It's not terrible unless you need to refer to symbols in the gdb CLI.... You may also need to map the PE-based modules in Ghidra manually.

It's a fair question why that checkbox would be presented at all for the plain gdb case. The checkbox was originally created for the SSH connector, where Ghidra can't know the remote system's line endings _a priori_. IIRC, for the plain gdb connector, we used to just used CR LF on Windows and LF on Linux. However, the Cygwin and MinGW versions of gdb each behave differently. Thus, we copied the checkbox over to the plain gdb connector and put the onus on the user to set it correctly. A user running Ghidra on Linux should always leave it unchecked. A user running Ghidra on Windows connecting to Cygwin gdb should also leave it unchecked. A user running Ghidra on Windows connecting to MinGW gdb would need to check it. In our experience, just sending LF (as we would on Linux) has not worked with MinGW gdb.

**Comment by nm004** [comment]
I'm glad to hear that news! That new GDB interface is going to solve our problems. I'm looking forward to that.

Also, thank you for the great tip! I've never thought of attaching wine process to the native GDB. It worked well for me. Thankfully, memory mapping of a wine process is relatively simple, so it was easy to find the target regions and map those to the image. Since my target program did not have that many exported symbols, how to refer to them in GDB was not my problem in the first place . Ghidra, by contrast, found me a lot of functions and classes, though :)

Lastly, thank you for answering my question. I hope the new Trace RMI will solve Cygwin and MinGW related issues as well.

I'm closing this issue now. As I mentioned above, the new Trace RMI will likely solve this issue.
