### ISSUE TITLE
Code Review: Sega Saturn (SuperH SH-1/SH-2) Processor Module

### ISSUE THREAD

**Issue by VGKintsugi** [NationalSecurityAgency/ghidra#608]
I've gotten my Sega Saturn (SuperH SH-1/SH-2) processor module to beta status. Disassembly looks correct, all instructions have SLEIGH definitions, and decompilation looks reasonable. Once polished I would like to contribute the module back to Ghidra.

 Would someone mind reviewing my processor module for issues? The code is available here: https://github.com/VGKintsugi/Ghidra-SegaSaturn-Processor. I used the instruction information here: http://www.shared-ptr.com/sh_insns.html. 

I struggled with issues related to sign extensions, flags, conditionals, and branches. I also struggled writing SLEIGH code for some of the longer instructions such as addv, div1, mac.l, and mac.w. Thanks in advance.

**Comment by mumbel** [comment]
You might consider an in-tree pull request, as-is there is no mechanism for code review. 

At first glance though, a significant issue is when you're quoting registers ("PC", "R0", "GBR" and a few others looks like).  These should really just be unquoted and match the registers used in the SLEIGH definitions.  Worst case the pcode is broken, best case the the disassembly is broken ("r0" != "R0").

If you're sticking with the `goto <END>` for the unpredictable/invalid instruction, you might consider just doing `goto inst_next` instead of adding the goto within the instruction.

There also seem like a few instances of semi-pointless local variables (notably n/m checks) that could probably be removed and just use the actual fields. not sure if this matters at all in pcode

From feedback from on my module, it also seems like the preference to adding goto for a few cases could be math based on the condition, notably ternary logic an be C = (a * cond) + (b * !cond).  A simple case for example `cmp"/hs"` could simply be ` $(T_FLAG) = zext(rn_08_11 >= rm_04_07)` removing the need for any goto logic looks like

**Comment by ryanmkurtz** [comment]
As @mumbel mentioned, the best way to get your code reviewed is to submit a pull-request into Ghidra, especially since you'd like to end up contributing it.  Thanks!

**Comment by VGKintsugi** [comment]
@mumbel, 

Thank you for the feedback, it will take some time to make the requested changes but I will implement them. 

@ryanmkurtz,

I was holding off on submitting a pull-request because I didn't think my codebase was ready yet. I'll make the changes mumbel referenced and submit a pull-request.

**Comment by bsturk** [comment]
Hi @VGKintsugi,

I'm using your processor to reverse SH-3 code and it is working quite well, thank you.  

There are a few instructions it is hiccuping on, but it might be due to them not being present for the IS for SH-1/SH-2.

**Comment by VGKintsugi** [comment]
@bsturk, 

I'm glad you found my processor module useful. I submitted a PR (https://github.com/NationalSecurityAgency/ghidra/pull/715) to contribute it back to Ghidra. Feel free to submit a PR for SH-3 support.
