### ISSUE TITLE
BSIM headless execution with H2 database

### ISSUE THREAD

**Issue by ThisIsLibra** [NationalSecurityAgency/ghidra#6098]
Hello,

Upon testing the newly released BSIM feature on Windows 10, I had the same issue as described in #6054. Given that it was already reported, I waited for an update on it, which has since been made, thank you for the swift response there. Upon cloning and locally building the patch branch, the feature now works as intended on my local Windows 10 environment.

There has been a change in the way it seems to work out, based on my initial understanding. Before the change, one could specify an output folder to write the newly created signatures in, which could later be imported by any supported database. As such, sharing the created signatures is easier with the raw signature files, since anyone can import them into their desired database of choice. Currently, one provides the Ghidra project and the BSIM database (a H2 one in my case). This works, but the vector limit of a H2 (medium_nosize) database is 10 million. 

My questions are: 

1. What happens if I have a number of Ghidra projects (or one really large project) that I want to create signatures for, but the 10 million limit is hit prior to processing all files?
2. How can I export the "raw" signatures of programs within a Ghidra project, which anyone can import into their preferred database?

Thank you for your time!

Cheers,
Max

**Comment by ghidracadabra** [comment]
Signatures can be generated with the `bsim generatesigs` command.  There are a few variants.  Two of them require an `<xmldirectory>` argument, which is the directory where the signature files will be written.  If you run the `bsim` command with no arguments you should see a detailed usage message.

One variant of the `bsim generatesigs` command takes a `config_template` argument instead of a URL for a BSim database.  You can use this to generate signature files without connecting to a BSim database.  

The database template contains several pieces of information.  Some are relevant to signature generation and some are relevant for database indexing.  

If you want add a signature file to an existing database, what's important is that the signature settings (the `settings` element of a config template) used when generating signatures agrees with the value used when creating the database.

It might be worth separating these values instead of combining indexing parameters and signature-generation parameters into one file.  We'll consider this.  It would help your situation, but it would not allow you to generate one signature file that could be ingested into any BSim database.

The 10 million figure you mention is not a hard limit.  Instead, it's a rough guideline used for determining specifics of the database index.  Furthermore, H2 databases are intended to be used with small collections and are not indexed, so the database index parameters don't matter for them.  

For indexed databases, if you exceed the limit query performance will (eventually) suffer.  H2-backed BSim databases will display the same behavior but at smaller sizes and there's no index you can adjust.

A few things to keep in mind:
- The performance of a database depends on the number of unique BSim signatures it contains.  A database with ten million functions almost certainly contains fewer unique BSim signatures because different functions can have the same BSim signature.  Only one copy of the signature is stored in the BSim database.
- Setting a higher confidence threshold for your query can greatly reduce the number of comparisons performed.  This is particularly useful for H2.

**Comment by ThisIsLibra** [comment]
Thank you for the swift response to my questions! The explanation has cleared up how to make the signatures without directly inserting them into a BSim database. I do have some other questions, related to my prior ones, I'll list them below, in no particular order. Thank you for your time in advance.

1. With regards to the limit for a H2 database, it sounds like 10 million would be the limit to actively search through at a decent speed, meaning that a much larger (i.e. 50 million) database would still perform decently when using a high(er) confidence threshold. Would that assumption be correct? Not trying to squeeze everything into a H2 database, but rather trying to understand the limits, to apply them as wisely as possible on future projects.
2. If I generate the signatures into a folder, would I be able to import them into any supported BSim database? I assumed it works like this, but based on the phrasing in your message, I'm not entirely sure. If not, could you elaborate on the differences?
3. If multiple H2 databases were to be used, is it possible to iterate over all of them with a single query? Based on my understanding of the documentation, the query is made against a single database. As such, having multiple smaller databases sounds more efficient, and would make it possible to maintain separate projects while maintaining usability. If it is possible, I'd like to ask if this is already part of supported behaviour, or if additional scripting would be required to iterate over multiple databases?

Cheers,
Max

**Comment by ghidracadabra** [comment]
1. To clarify, the 10 million value has nothing to do with H2.  It's only relevant for indexed databases.  When you create any BSim database you pass it a configuration template.  H2 ignores the information in the configuration template related to the index.  I'm not sure what the upper limit of an H2-backed BSim database is but 10 million likely exceeds it for many use cases.  It *might* be tolerable if you are querying for matches to a single function at a time, but querying for matches to many functions will be painfully slow.
2. If you generate the signatures into a folder, you will be able to import them into any BSim database whose signature settings (from `createdatabase`)  are compatible with the signature settings used when generating signatures (from `generatesigs`), provided that the versions of the BSim database layout and the signature generation algorithm are also compatible (which isn't an issue now but might be in the future).   Examine the first hit for "signature settings" in the Ghidra help and/or the first line of a signature file for more information. 
3. Queries are made against a single database.  You could write a script to perform the same query against multiple databases relatively easily, but you'd have to deal with the query results programmatically instead of through the BSim GUI. You might consider using a single postgres or elasticsearch BSim database rather than multiple H2 databases.  There are various ways of using BSim filters which would allow you to essentially have separate "projects" within a single BSim database (for example, executable categories).

**Comment by ThisIsLibra** [comment]
Thank you very much for the swift answers. No further questions from my side about this. Appreciate the help here, in the documentation, along with the active development. Locking this issue as it is finished, but feel free to re-open it if you want to.

Cheers,
Max
