### ISSUE TITLE
"Toggle Break Point K" Not Appearing in the Debugger's Context Menu

### ISSUE THREAD

**Issue by momexn** [NationalSecurityAgency/ghidra#6105]
Hello. I am Japanese and have been transitioning from OllyDbg to Ghidra for debugging. I am working on a C++ x86 application and attempting to debug using MS dbgeng.dll (WinDbg) via GADP. When I attach to the process, the Listing window shows the disassembled results.

However, when I tried to set a breakpoint to start my analysis, I couldn't find the "Toggle Break Point" option.

I thought this might be a debugger issue, so I followed the steps described in a blog using a sample program they provided, but still, the context menu was nowhere to be found. I haven't modified the context menu in any way, so I'm puzzled as to why this is happening.

In the following video, the option clearly appears, but I can't figure out why it's not showing up in my case: https://youtu.be/5huuiZu4fIY?t=78

My system is Windows 11, and I'm using Ghidra version 10.4. I also tried with a fresh install of version 11.0, but the issue persists.

I'm having a lot of trouble using this wonderful debugger since a key feature is not working. I would greatly appreciate any insights you can offer.

Installed extensions:
- GhidraEmu
- GnuDisassembler
- MachineLearning
- SleighDevTools

My environment (where the option does not appear):
![スクリーンショット 2024-01-10 184713](https://github.com/NationalSecurityAgency/ghidra/assets/117027909/0d10610c-97e9-41eb-a2ae-c55d34e06c64)

**Comment by nsadeveloper789** [comment]
@momexn I'm trying to make sense of the screenshot you've provided. I see you have entered a string into the filter for the Objects panel, and the only result is under "Available." It's possible you're not actually attached to your target?

Under the Objects panel, there's usually a "Processes" node, and under that, the actual process your attached to. Under that there's usually a Breakpoints node. If that node doesn't exist, you might not see the options in the menu to manage breakpoints.

Also, because of the placement of each panel in your screenshot, I'm thinking you added the Debugger plugins to the CodeBrowser instead of just using the default Debugger tool? If that's the case, you may have misconfigured something. Also, I don't see your Dynamic listing, just the Static one.

So a few things I think you might try to help diagnose this:
1. Search the objects panel tree for "breakpoints". If there's no, then perhaps there's a latent timing issue. Clear the filter and try manually expanding the nodes "Processes[0].Breakpoints". If it appears, then retry toggling the breakpoint.
2. Open the Dynamic listing and verify the address where you want the breakpoint is mapped. When you navigate in the Static listing, the Dynamic one should follow to the corresponding run-time address. If that's not happening where you want to place the breakpoint, then it's not mapped. Use the Modules panel to resolve that.
3. Check that the title bar says "Debugger: [whatever program]", not "CodeBrowser: [whatever program]". If you see CodeBrowser, I'd recommend closing it, then deleting and re-importing the default tools, then re-opening it with the Debugger tool.
4. Try launching using the dbgeng IN-VM connector (instead of GADP). Despite the stability warnings, we've generally seen better user experiences with IN-VM vs GADP.

My apologies if some of these recommendations seem elementary, but with such a strange screenshot, I'm not sure where to begin.
