### ISSUE TITLE
Can't Connect to GDB Terminal

### ISSUE THREAD

**Issue by tehomen** [NationalSecurityAgency/ghidra#6107]
Whenever I try to connect to GDB I get this exception:
ghidra.dbg.error.DebuggerModelTerminatingException: Error while starting GDB: Pty implementation does not support null 
sessions. Try C:\msys64\mingw64\bin\gdb.exe -i mi2

I've tried running it with -i mi2, I've also tried where I write the path like this:
C:\\\msys64\\\mingw64\\\bin\\\gdb.exe

Nothing works.

I am running this on Windows 10.

**Comment by d-millar** [comment]
If you could, we might need two pieces of information.  First, what version of gdb.exe?  And, second, if you run "gdb.exe -i mi2", what's the first line of output.  (We're expecting something like '=thread-group-added,id="i1"'.

**Comment by tehomen** [comment]
@d-millar The version is 14.1 and the first line of the output is:
`=thread-group-added,id="i1"`

**Comment by d-millar** [comment]
OK, thanks - am going to have to do some poking around.  At a guess, your gdb is more recent than what we've tested against, and the reply for one of the early commands is coming back with a format we're not expecting. Will have to consult with @nsadeveloper789.  (Separate note:  your version of the path with the double-backslashes should have been the one that worked.)

**Comment by nsadeveloper789** [comment]
I've personally tried gdb 14.1 on Linux, but had some hang-ups. I was able to get connected, though. That said, it'd be worth trying with an earlier version if you can. I'd recommend 13.2.

Because you're on Windows, you'll definitely need to add `-i mi2`. What is the error you get when you try that? Same message? Just hangs? Anything?

There is also a checkbox regarding line endings. Make sure yours indicates CRLF (DOS-style) line endings. (You might as well try it both ways, but in theory, MinGW requires CRLF.)

Also, to @d-millar's point. Please check for the *very first* line of output when you run `gdb.exe -i mi2`. Sometimes there's a version line or some warnings that precede the `=thread-group-added` event. Those matter.

If none of that works, we can enable some logging for better diagnostics:
1. Modify your `ghidraRun.bat` file and add the following VM argument:
   * `-Dagent.gdb.manager.log=true`
   * (You put this into the empty quotes on line 10, column 58).
2. Restart Ghidra and try connecting to gdb again.
3. Search your `C:\Users\<yourname>\.ghidra\` directory for `GDB.log`.
4. Scrub it, if you must, then paste or upload it here.

**Comment by nsadeveloper789** [comment]
So, I take it the log outputs you're showing are from the 14.1-1 and 13.2-3 packages?

The fact that the log believes it's CLI instead of MI2 indicates one of two things AFAIK.
1. The `-i mi2` argument is being ignored. Check for any quotations, and maybe try a few variations to see what happens. I would expect, e.g., `"C:\\msys64\\mingw64\\bin\\gdb.exe" -i mi2`, if there are quotes at all.
2. Despite being in MI mode, gdb is still printing a version line before the first event.

I apologize for asking a third time, but please confirm, when you run `gdb.exe -i mi2`, do you get:

```
GNU gdb (GDB) 13.2
=thread-group-added,id="i1"
```

or only:

```
=thread-group-added,id="i1"
```

or something else? It might help to paste a screenshot of this experiment. Also, if you don't mind, please run it from a vanilla Windows command prompt, not the MSYS2 terminal (no bash).

**Comment by tehomen** [comment]
@nsadeveloper789 I get this when I run `gdb.exe -i mi2` I get the following:

> ~"GNU gdb (GDB) 14.1\n"
> ~"Copyright (C) 2023 Free Software Foundation, Inc.\n"
> ~"License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law."
> ~"\nType \"show copying\" and \"show warranty\" for details.\n"
> ~"This GDB was configured as \"x86_64-w64-mingw32\".\n"
> ~"Type \"show configuration\" for configuration details.\n"
> ~"For bug reporting instructions, please see:\n"
> ~"<https://www.gnu.org/software/gdb/bugs/>.\n"
> ~"Find the GDB manual and other documentation resources online at:\n    <"
> ~"http://www.gnu.org/software/gdb/documentation/>.\n\n"
> ~"For help, type \"help\".\n"
> ~"Type \"apropos word\" to search for commands related to \"word\".\n"
> (gdb)

Also, I did try to do `"C:\\msys64\\mingw64\\bin\\gdb.exe" -i mi2` and it gives me the same error:
`ghidra.dbg.error.DebuggerModelTerminatingException: Error while starting GDB: Could not detect GDB's interpreter mode. `

**Comment by tehomen** [comment]
@d-millar Any progress figuring why this issue is or any temporary workaround?

**Comment by d-millar** [comment]
Am hoping @nsadeveloper789 has some ideas on this.  Unfortunately, am out of town for a week without a laptop.

**Comment by nsadeveloper789** [comment]
I'm scraping the bottom of the barrel here, unfortunately. I get the following when I run `gdb -i mi2` with gdb-13.1 on Linux, where this is known to work:

```
$ gdb -i mi2
=thread-group-added,id="i1"
~"GNU gdb (GDB) 13.1\n"
~"Copyright (C) 2023 Free Software Foundation, Inc.\n"
~"License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law."
~"\nType \"show copying\" and \"show warranty\" for details.\n"
~"This GDB was configured as \"x86_64-pc-linux-gnu\".\n"
~"Type \"show configuration\" for configuration details.\n"
~"For bug reporting instructions, please see:\n"
~"<https://www.gnu.org/software/gdb/bugs/>.\n"
~"Find the GDB manual and other documentation resources online at:\n    <"
~"http://www.gnu.org/software/gdb/documentation/>.\n\n"
~"For help, type \"help\".\n"
~"Type \"apropos word\" to search for commands related to \"word\".\n"
(gdb) 
```

Notice the *very first* line it outputs is the `=thread-group-added` event. Then, it prints the version info wrapped in all the MI output-stream stuff. Because your `GDB.log` file shows the version first, and without MI wrapping, I can only guess two possibilities:

1. You've mis-typed part of the command line, or
2. The `-i mi2` arguments are not getting passed through by Ghidra.

For item 1, just double-check your launcher config.

For item 2, you'd need to set up a dev environment and place a breakpoint at `GdbMangerImpl.java#start` (Line 651). Then, you'd inspect the `fullArgs` variable as you step through until line 665. You might also step into the `session()`  call and see it all the way down into the `CreateProcessW` call.

**Comment by tehomen** [comment]
@nsadeveloper789 I get this when I do gdb -i mi2:
I must have accidentally cut off the first line before.

> =thread-group-added,id="i1"
~"GNU gdb (GDB) 14.1\n"
~"Copyright (C) 2023 Free Software Foundation, Inc.\n"
~"License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law."
~"\nType \"show copying\" and \"show warranty\" for details.\n"
~"This GDB was configured as \"x86_64-w64-mingw32\".\n"
~"Type \"show configuration\" for configuration details.\n"
~"For bug reporting instructions, please see:\n"
~"<https://www.gnu.org/software/gdb/bugs/>.\n"
~"Find the GDB manual and other documentation resources online at:\n    <"
~"http://www.gnu.org/software/gdb/documentation/>.\n\n"
~"For help, type \"help\".\n"
~"Type \"apropos word\" to search for commands related to \"word\".\n"

**Comment by Nemoumbra** [comment]
This reminds me of https://github.com/NationalSecurityAgency/ghidra/discussions/5698#discussioncomment-6794755

**Comment by nsadeveloper789** [comment]
@Nemoumbra Yes, it is similar, which is why we're trying to get at the first line.

@tehomen I'm glad to see the first line is the event. Still, we're seeing something different in the log than we're seeing when you run gdb in isolation. My recommendations are still the same: 1) Please double-check the command line in your gdb launch config from Ghidra. (I don't suspect it's that simple, but I want to double check before going into the deep end.) If that doesn't fix it, you may need to 2) do some debugging of Ghidra itself on your end to see why those arguments aren't getting passed to gdb. Otherwise, you'll be waiting for us to try to replicate your environment to reproduce the issue, but it's not a priority for us. We're focused on getting Trace RMI going, which ought to overcome this issue....

**Comment by tan-wei** [comment]
Met the same issue with GDB via SSH (Linux), And in *GDB.log*, I could only see several lines like
> <CLI: GNU gdb (GDB) 13.2

**Comment by nsadeveloper789** [comment]
I've got a little extra time today. I may obtain a copy of gdb-14.1 and see if I can reproduce this. I'm surprised to see the same problem via SSH. It Works on My Machine (TM), but I'm still using 13.1.

**Comment by nsadeveloper789** [comment]
Here's what I've tried so far: I've built and install gdb-14.1 on Linux, then using our development branch of Ghidra, I connected to it in a variety of ways: With and without `-i mi2`; with UNIX and DOS line endings; local and via ssh. Of those, the only configurations that fail are those using DOS line endings, and they fail in a different way than you're seeing.

I'm now in the process of obtaining gdb-14.1 (mingw64) on Windows. I already had gdb-13.1 installed, and it worked fine with Ghidra 11.0 (with `-i mi2`, DOS line endings, local)

**Comment by nsadeveloper789** [comment]
Okay, It Works on My Machine (TM) for gdb-14.1 in Windows as well. I'll do my best to capture everything I did in case you want to try repeating it on your end: I'm using MSYS2 with mingw64. I'll refrain from screencapping my system's "About" dialog, but I'm on Windows Server 2019, which is closest to Windows 10 as far as consumer editions go.

First, I installed (upgraded) to mingw64/mingw-w64-x86_64-gdb version 14.1-1. I just did this using `pacman`.

![image](https://github.com/NationalSecurityAgency/ghidra/assets/46821332/349b1b31-354d-40d6-ab4f-a9cb3a2e74b6)

Then, I checked that I can invoke it from the vanilla command prompt with `-i mi2`:

![image](https://github.com/NationalSecurityAgency/ghidra/assets/46821332/c1cf5270-bc7e-4bc2-a6fb-de11e70dd2cf)

Then I launch Ghidra 11.0 and use the Targets window to create a connection to gdb and configure it accordingly:

![image](https://github.com/NationalSecurityAgency/ghidra/assets/46821332/f0d72c61-6b2b-4ce7-afcb-ade9365c4f7d)

Note the path has the doubled `\\`s, no quotes, and it ends with `-i mi2`. I've also checked the DOS line endings box. Then, I clicked Connect. Looks like it worked:

![image](https://github.com/NationalSecurityAgency/ghidra/assets/46821332/2e735ad1-c692-4fc4-b036-4eb209c244da)

Going back: I can get it to malfunction by unchecking the DOS line endings box. If I do, it'll hang in the Connect dialog with a "Connecting...." status message indefinitely. However, my GDB.log is still showing MI2 output, not CLI:

```
<MI2: =thread-group-added,id="i1"
<MI2: ~"GNU gdb (GDB) 14.1\n"
*CMD: class agent.gdb.manager.impl.cmd.GdbListInferiorsCommand
>MI2: -list-thread-groups
<MI2: ~"Copyright (C) 2023 Free Software Foundation, Inc.\n"
<MI2: ~"License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law."
<MI2: ~"\nType \"show copying\" and \"show warranty\" for details.\n"
<MI2: ~"This GDB was configured as \"x86_64-w64-mingw32\".\n"
<MI2: ~"Type \"show configuration\" for configuration details.\n"
<MI2: ~"For bug reporting instructions, please see:\n"
<MI2: ~"<https://www.gnu.org/software/gdb/bugs/>.\n"
<MI2: ~"Find the GDB manual and other documentation resources online at:\n    <"
<MI2: ~"http://www.gnu.org/software/gdb/documentation/>.\n\n"
<MI2: ~"For help, type \"help\".\n"
<MI2: ~"Type \"apropos word\" to search for commands related to \"word\".\n"
<MI2: (gdb)
```

So, this is not what you've observed. Alternatively, if I keep DOS line endings but remove the `-i mi2` part, then I get what you got in your original post. I hope this helps.

**Comment by tan-wei** [comment]
Now I use `new_ui` as a workaround.

Is that because I use Ghidra on Windows and connect to remote GDB via SSH (which is a Linux OS)?

**Comment by chetuna** [comment]
I too have this problem and report it. 
I get the same result with devkitpro's `aarch64-none-elf-gdb.exe` and mingw-w64-x86_64-gdb `gdb.exe`.

```
ghidra.dbg.error.DebuggerModelTerminatingException: Error while starting GDB: Could not detect GDB's interpreter mode. 
Try aarch64-none-elf-gdb -i mi2
---------------------------------------------------
Build Date: 2024-Jan-30 1212 EST
Ghidra Version: 11.0.1
Java Home: C:\Program Files\Eclipse Adoptium\jdk-17.0.8.101-hotspot
JVM Version: Eclipse Adoptium 17.0.8.1
OS: Windows 10 10.0 amd64
Workstation: PC-PC
```
I think this is as expected, since the second line of the command shows `=thread-group-added,id='i1"`.
This is the same when executed with the full path. `C:\\msys64\\mingw64\\bin\\gdb.exe -i mi2`
```
C:\Users\pc>aarch64-none-elf-gdb -i mi2
=thread-group-added,id="i1"
~"GNU gdb (GDB) 14.1\n"
~"Copyright (C) 2023 Free Software Foundation, Inc.\n"
~"License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law."
~"\nType \"show copying\" and \"show warranty\" for details.\n"
~"This GDB was configured as \"--host=x86_64-w64-mingw32 --target=aarch64-none-elf\".\n"
~"Type \"show configuration\" for configuration details.\n"
~"For bug reporting instructions, please see:\n"
~"<https://www.gnu.org/software/gdb/bugs/>.\n"
~"Find the GDB manual and other documentation resources online at:\n    <"
~"http://www.gnu.org/software/gdb/documentation/>.\n\n"
~"For help, type \"help\".\n"
~"Type \"apropos word\" to search for commands related to \"word\".\n"
(gdb)
```
![cmd](https://github.com/NationalSecurityAgency/ghidra/assets/80691120/036f3595-997e-4413-8a05-e1a6566a6d2f)

I also checked the logs by giving `-Dagent.gdb.manager.log=true` to ghidraRun.bat.
As a result, I got two patterns: either a line `<CLI: GNU gdb (GDB) 14.1` is printed or nothing at all is printed.

- C://msys64//opt//devkitpro//devkitA64//bin//aarch64-none-elf-gdb.exe -> <CLI: GNU gdb (GDB) 14.1
- C://msys64//opt//devkitpro//devkitA64//bin//aarch64-none-elf-gdb.exe -i mi2 -> empty
- "C://msys64//opt//devkitpro//devkitA64//bin//aarch64-none-elf-gdb.exe" -> <CLI: GNU gdb (GDB) 14.1
- "C://msys64//opt//devkitpro//devkitA64//bin//aarch64-none-elf-gdb.exe" -i mi2 -> empty
- aarch64-none-elf-gdb -> <CLI: GNU gdb (GDB) 14.1
- aarch64-none-elf-gdb -i mi2 -> empty
- aarch64-none-elf-gdb -i=mi2 -> empty
- aarch64-none-elf-gdb --i=mi2 -> empty
- aarch64-none-elf-gdb -i -> empty

And this is the log of ghidraDebug.bat "C://msys64//opt//devkitpro//devkitA64//bin//aarch64-none-elf-gdb.exe -i mi2"
```
Listening for transport dt_socket at address: 18001
INFO  Using log config file: file:/C:/ghidra_11.0.1_PUBLIC/support/debug.log4j.xml  (LoggingInitialization.java:50)
INFO  Using log file: C:\Users\pc\.ghidra\.ghidra_11.0.1_PUBLIC\application.log  (LoggingInitialization.java:51)
INFO  Loading user preferences: C:\Users\pc\.ghidra\.ghidra_11.0.1_PUBLIC\preferences  (Preferences.java:122)
INFO  Loading previous preferences: C:\Users\pc\.ghidra\.ghidra_10.3.3_PUBLIC\preferences  (Preferences.java:175)
INFO  Searching for classes...  (ClassSearcher.java:259)
INFO  Class search complete (1207 ms)  (ClassSearcher.java:278)
INFO  Initializing SSL Context  (SSLContextInitializer.java:76)
INFO  Initializing Random Number Generator...  (SecureRandomFactory.java:37)
INFO  Random Number Generator initialization complete: SHA1PRNG  (SecureRandomFactory.java:41)
INFO  Trust manager disabled, cacerts have not been set  (ApplicationTrustManagerFactory.java:95)
INFO  User pc started Ghidra.  (GhidraRun.java:77)
DEBUG Recovery snapshot timer set to 5 minute(s)  (RecoverySnapshotMgrPlugin.java:170)
INFO  Opening project: C:\Users\pc\mojipitan  (DefaultProject.java:114)
INFO  Packed database cache: C:\Users\pc\AppData\Local\Ghidra\packed-db-cache  (PackedDatabaseCache.java:64)
DEBUG Using cached packed database: C:\ghidra_11.0.1_PUBLIC\Ghidra\Features\Base\data\typeinfo\generic\generic_clib_64.gdt  (PackedDatabaseCache.java:364)
INFO  Starting gdb with: [C://msys64//opt//devkitpro//devkitA64//bin//aarch64-none-elf-gdb.exe, -i, mi2]  (GdbManagerImpl.java:663)
INFO  local Windows Pty session. PID = 18656  (LocalWindowsNativeProcessPtySession.java:42)
DEBUG Terminating agent.gdb.manager.impl.GdbManagerImpl@6394b4d  (GdbManagerImpl.java:809)
DEBUG STDOUT,null reader exiting because java.lang.NumberFormatException: For input string: "25l["  (GdbManagerImpl.java:168)
DEBUG Terminating agent.gdb.manager.impl.GdbManagerImpl@6394b4d  (GdbManagerImpl.java:809)
ERROR Could not connect: ghidra.dbg.error.DebuggerModelTerminatingException: Error while starting GDB: Could not detect GDB's interpreter mode.
Try C://msys64//opt//devkitpro//devkitA64//bin//aarch64-none-elf-gdb.exe -i mi2  (ConsoleErrorDisplay.java:59)
```
![dbg01](https://github.com/NationalSecurityAgency/ghidra/assets/80691120/f742cc6f-633a-40d9-9c45-06c8ca0e834f)

I don't know if this is the cause, but my machine is Win10 and ja-JP language.

**Comment by nsadeveloper789** [comment]
Wow. Thank you for the thorough write up! So, the bit that catches my eye (finally), is the log line for ghidraDebug.bat:
> ```
> DEBUG STDOUT,null reader exiting because java.lang.NumberFormatException: For input string: "25l�["  (GdbManagerImpl.java:168)
> ```
I'm guessing I'll need to implement the `l` and `h` CSI escape codes in `AnsiBufferedInputStream`. Luckily, for this use case, they need not do much....

FWIW, I don't think the ghidraDebug.bat thing is necessary. It just happens that you included the log for it, and it had the clue.

If you're able to spin up a development environment, could you make the following changes and try again?
```diff
diff --git a/Ghidra/Debug/Debugger-agent-gdb/src/main/java/agent/gdb/manager/impl/GdbManagerImpl.java b/Ghidra/Debug/Debugger-agent-gdb/src/main/java/
agent/gdb/manager/impl/GdbManagerImpl.java
index 413613b91b..a1d897325c 100644
--- a/Ghidra/Debug/Debugger-agent-gdb/src/main/java/agent/gdb/manager/impl/GdbManagerImpl.java
+++ b/Ghidra/Debug/Debugger-agent-gdb/src/main/java/agent/gdb/manager/impl/GdbManagerImpl.java
@@ -165,7 +165,7 @@ public class GdbManagerImpl implements GdbManager {
                        }
                        catch (Throwable e) {
                                terminate();
-                               Msg.debug(this, channel + "," + interpreter + " reader exiting because " + e);
+                               Msg.debug(this, channel + "," + interpreter + " reader exiting because ", e);
                                //throw new AssertionError(e);
                        }
                }
diff --git a/Ghidra/Framework/Pty/src/main/java/ghidra/pty/windows/AnsiBufferedInputStream.java b/Ghidra/Framework/Pty/src/main/java/ghidra/pty/windows/AnsiBufferedInputStream.java
index 047489a664..4c573815b9 100644
--- a/Ghidra/Framework/Pty/src/main/java/ghidra/pty/windows/AnsiBufferedInputStream.java
+++ b/Ghidra/Framework/Pty/src/main/java/ghidra/pty/windows/AnsiBufferedInputStream.java
@@ -270,6 +270,14 @@ public class AnsiBufferedInputStream extends InputStream {
                                execSetGraphicsRendition();
                                mode = Mode.CHARS;
                                break;
+                       case 'h':
+                               execPrivateSequence(true);
+                               mode = Mode.CHARS;
+                               break;
+                       case 'l':
+                               execPrivateSequence(false);
+                               mode = Mode.CHARS;
+                               break;
                }
        }
 
@@ -473,4 +481,9 @@ public class AnsiBufferedInputStream extends InputStream {
                // TODO: Maybe a callback. Otherwise, don't care
                titleBuf.clear();
        }
+
+       protected void execPrivateSequence(boolean enable) {
+               // These don't matter for input buffering.
+               escBuf.clear();
+       }
 }
```
The first change is only temporary and should give us better diagnostics if my guess turns out to be wrong, or if there are more issues. The remaining changes implement what I think are the missing ANSI codes. Thanks!

**Comment by nsadeveloper789** [comment]
I already think my guess is off. The private commands have a question mark in them, and I already have code that's supposed to handle that. So, either the exception is not about the command I think it is, or that code is broken. My next suggestion, again assuming you set up a dev environment, is to tell Eclipse to break on `NumberFormatException`. Then attempt the launch. When it breaks, inspect the contents of `escBuf`. You might also or instead, uncomment `AnsiBufferedInputStream.java:121` (the call to `printDebugChar`), in case the preceding characters are important.

**Comment by chetuna** [comment]
I added those codes and they connected to the target.
command used this: `C://msys64//opt//devkitpro//devkitA64//bin//aarch64-none-elf-gdb.exe -i mi2`
I'm not sure if this is working perfectly as I'm not used to dealing with gdb, but I appreciate your support.
