### ISSUE TITLE
Inability to load DLLs

### ISSUE THREAD

**Issue by RampantDespair** [NationalSecurityAgency/ghidra#6363]
**Describe the bug**
Ghidra is unable to load the needed DLLs when I attempt to debug an exe.

**To Reproduce**
1. Select Windows executable in the project, click "Open With" -> "Debugger"
2. Click "Debugger"->"Debug Executable.exe"-> "In dbgeng locally" (either option), then click "Connect"

**Expected behavior**
The target is launched and can be debugged.

**Screenshots**
![image](https://github.com/NationalSecurityAgency/ghidra/assets/63611551/cd73c194-1dc1-4bd4-8dce-954c8f5ee6bc)
![image](https://github.com/NationalSecurityAgency/ghidra/assets/63611551/27321ccc-e58c-4249-b1d2-3cdd07cb5295)

**Attachments**
N/A

**Environment (please complete the following information):**
 - OS: 
    Microsoft Windows 10 Pro
    Version 10.0.19045 Build 19045
 - Java Version: 
	java version "21.0.2" 2024-01-16 LTS
	Java(TM) SE Runtime Environment (build 21.0.2+13-LTS-58)
	Java HotSpot(TM) 64-Bit Server VM (build 21.0.2+13-LTS-58, mixed mode, sharing)
 - Ghidra Version: 11.0.2
 - Ghidra Origin: [official GitHub distro](https://github.com/NationalSecurityAgency/ghidra/releases)

**Additional context**
I've tried the solution provided #3090, however it fails all the same as shown above.
It's the same message with my JDK instead of System32.
I tried launching ghidra as administrator, however it did not change the error.

**Comment by d-millar** [comment]
Two quick questions for you just so I have a better sense of what’s going on.  (There are several possible problems here, all of which result in the same set of messages.)

First question:  when you say you tried the solution from #3090, would I be correct in assuming that means you copied the dbgXxxx libraries into the bin directory in your active JDK?

Second question: leaving aside the messages in the console, is the debugger actually failing? i.e. are you unable to continue and launch the target?

**Comment by RampantDespair** [comment]
To answer the first question, the files I copied are:
- dbgcore.dll
- DbgModel.dll
- dbgeng.dll
- dbghelp.dll
- Dbgv.sys
- ntdll.dll

And as for the second question:
I get this message
![image](https://github.com/NationalSecurityAgency/ghidra/assets/63611551/b598ba95-7c8d-40a9-a760-5968f85e8992)

However I am able to run it, I just noticed (lol, oops).
But I'm not sure I'll be able to make everything work accordingly considering the to image posted above?

**Comment by d-millar** [comment]
@RampantDespair OK, so I think you're actually in pretty good shape, despite the various error messages.  You're getting the pop-up because the name of the executable in the list of running modules differs from the name of the imported program.  Per @nsadeveloper789's advice (from a different issue):

> 'The Modules window is where to go to configure the mapping. If the mapping is identical, e.g., the address 80000024 in the dynamic listing is supposed to correspond to the same 80000024 in the static, then you can easily map by pressing the "Map Identically" button in the Modules window's toolbar. It's a little red-ish arrow.  If that's not the case, you can use the "Map Manually" button, which will bring up a table of mappings and allow you to edit it directly. If the mapping is complicated, you can script it using the FlatDebuggerAPI and getMappingService.'

The dbghelp error appears typically because one of the processes involved has already loaded dbghelp.dll - could be your target, but more likely it's the java process on your machine doing the debugger.  Worse, @nsadeveloper789 recently realized that in many cases that dll has actually been injected into the java process by the AV product on the machine where java is running, which means we have very little control about which version gets loaded.  In most cases, however, you can just ignore the message and move on.

**Comment by nsadeveloper789** [comment]
As @d-millar states, it looks like you're in pretty good shape. The only missing part is probably the module mapping. As for the mapping, go to the Modules window. Based on the screenshot above, it looks like the Windows debugger is just calling your EXE `image...` then some address. Right-click that entry and select "Map to BoardGame.exe".

**Comment by RampantDespair** [comment]
@nsadeveloper789 
I followed the procedure you mentioned, however after right-clicking the entry and clicking `Map Modules to BoardGame.exe` a window shows up and I can't really do anything with it...
![image](https://github.com/NationalSecurityAgency/ghidra/assets/63611551/ac062703-a68c-45f2-8bc8-3cbc86d369af)
My only option is to click ok, with no return message. I don't know if it's doing something or not.
But in any case, after doing it, the image remains unknown
![image](https://github.com/NationalSecurityAgency/ghidra/assets/63611551/4c07342b-490b-4595-8757-741c76eb8bb4)

**Comment by nsadeveloper789** [comment]
That is the expected behavior.

The dialog is to confirm the relevant addresses. It's saying "I'm about to map image00007f....", which was loaded at 7ff74c7.... to the program "BoardGame.exe" whose static address is 140000000, over a range of 0x64800 bytes. There are bulk mapping actions, so this is a chance to examine and/or correct any mapping changes it's about to make. In general, you just press OK.

The Name / Module Name columns are what dbgeng tells us it is, regardless of any additional knowledge Ghidra has. The Mapping column is what displays the mapped program from Ghidra. In your screenshot, that is displaying "BoardGame.exe" now, as expected.

The portion you've annotated with an arrow indicates where your cursor (usually the PC) is right now. It seems to me, you are in a region of memory outside the EXE file. You can use Window -> Debugger -> Regions, to see the full list of regions known to dbgeng.

**Comment by RampantDespair** [comment]
@nsadeveloper789 
Alright I understand.
Thank you for taking the time to answer my questions.
