### ISSUE TITLE
Binary raw manuall language set

### ISSUE THREAD

**Issue by ahmed22pm7** [NationalSecurityAgency/ghidra#6391]
I anlyzed the file with seer tool and there are sevral architectures which one i should choose when i anlyze the file on ghidra and will the code be not completed consedering it has a lot of architectures and i have to choose just one them?
![Screenshot_20240407_055043.jpg](https://github.com/NationalSecurityAgency/ghidra/assets/105469178/bb7fa884-7d35-46be-9980-9cbef89b8fb7)

![IMG_20240407_060627_377.jpg](https://github.com/NationalSecurityAgency/ghidra/assets/105469178/c2a5ab96-9923-49d6-b268-6cb9b38f5c74)

**Comment by 01ChenQing** [comment]
> I anlyzed the file with seer tool and there are sevral architectures which one i should choose when i anlyze the file on ghidra and will the code be not completed consedering it has a lot of architectures and i have to choose just one them? ![Screenshot_20240407_055043.jpg](https://private-user-images.githubusercontent.com/105469178/320320351-bb7fa884-7d35-46be-9980-9cbef89b8fb7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NDY4ODAsIm5iZiI6MTcxMjU0NjU4MCwicGF0aCI6Ii8xMDU0NjkxNzgvMzIwMzIwMzUxLWJiN2ZhODg0LTdkMzUtNDZiZS05OTgwLTljYmVmODliOGZiNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOFQwMzIzMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03M2RlNDhkZDA0MTQzNjJkZTEwZGVjMzgxODQyYjc1YzMzMmUzZWRkMGFiMGYxYmU5YzJmOTEzYjlkOWJjMDIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QiX3gkhzPnrNfqx5t0R7qUlui-qnW5uxAYWc__bps74)
> 
> ![IMG_20240407_060627_377.jpg](https://private-user-images.githubusercontent.com/105469178/320320352-c2a5ab96-9923-49d6-b268-6cb9b38f5c74.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NDY4ODAsIm5iZiI6MTcxMjU0NjU4MCwicGF0aCI6Ii8xMDU0NjkxNzgvMzIwMzIwMzUyLWMyYTVhYjk2LTk5MjMtNDlkNi1iMjY4LTZjYjliMzhmNWM3NC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOFQwMzIzMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNjkyYTU5OTcyZjIyODZiMDIyMTMxOTc0YWY5MWQwNzk2MWRiYjJkNDJkNjk5OTEwYmU2MjEyNmYwYzBhMzE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zvX3F_GR_ZAzoi7mXtoKH40X4seIGdCDN7KPGbK2WZA)

I think for this case, you should try to understand more about the background information of the program being analyzed, because it is rare that there are multiple different instruction sets in a program. If this is the case, I think every analysis starts from Manually extracting the instructions of the same instruction set from the file is a better option.

**Comment by 01ChenQing** [comment]
I think for this case, you should try to understand more about the background information of the program being analyzed, because it is rare that there are multiple different instruction sets in a program. If this is the case, I think every analysis starts from Manually extracting the instructions of the same instruction set from the file is a better option

**Comment by mumbel** [comment]
dont spam issues, you already have a discussion open

**Comment by ryanmkurtz** [comment]
Duplicate of #6382
