### ISSUE TITLE
Stack-based string initialization on a single line

### ISSUE THREAD

**Issue by Stefan-Radu** [NationalSecurityAgency/ghidra#6431]
![Screenshot_20240416_230904](https://github.com/NationalSecurityAgency/ghidra/assets/30214214/c76035ae-0741-4070-b7d4-b004c8240dd9)

I run into scenarios like the above quite often, which involves some kind of stack-based array. Is there a way to have Ghidra display such an initialization on a single line, as follows:

wchar16 buf[22] = L"69F2a+18d346b/SQ5c65e";

For me at least, having the option would make the decompilation a lot easier on the eyes. 

If this feature does not exist, how would one go about implementing it? Thanks!

**Comment by astrelsky** [comment]
It is not currently possible. It's even more painful when it's a pointer because you can't even get that output and are stuck doing mental gymnastics to figure out the value from different sized assignments and concat macros.

**Comment by EmosewaMC** [comment]
> It is not currently possible. It's even more painful when it's a pointer because you can't even get that output and are stuck doing mental gymnastics to figure out the value from different sized assignments and concat macros.
> 
> Also you're lucky that example is showing the assignments in order.

Why do those issues exist and what makes stack based strings so difficult to work with?

**Comment by shapaz** [comment]
The issue was supposedly fixed since 11.2, but I'm on 11.3 and still have it:

![Image](https://github.com/user-attachments/assets/1263f19d-a032-45a8-a148-3326215150ce)

**Comment by shapaz** [comment]
> The issue was supposedly fixed since 11.2, but I'm on 11.3 and still have it:
> 
> ![Image](https://github.com/user-attachments/assets/1263f19d-a032-45a8-a148-3326215150ce)

@ryanmkurtz please re-open this issue, as it isn't fixed yet.

**Comment by ryanmkurtz** [comment]
Can you please open a new issue for it?

**Comment by shapaz** [comment]
@ryanmkurtz 
> Can you please open a new issue for it?

I opened #8374 and mentioned how this issue is not fixed for AARCH64 in [this comment](https://github.com/NationalSecurityAgency/ghidra/issues/8374#issuecomment-3112982006).
You then closed #8374 as a duplicate of #4461.

If you believe this issue should be handled as part of resolving #4461, then this issue should be mentioned there.
If not, then this issue should remain open.

**Comment by ryanmkurtz** [comment]
I asked for a new issue because it would be better for our bookkeeping to track it as such, since something was done for this for 11.2 already, went in the the release notes, etc.  I'm not saying there still isn't a problem, but ideally, it would come in as a new issue so we can treat it as a fresh fix for a new version of Ghidra.

When i read #8374, it seemed like a straight up duplicate of #4461.  I see your additional comment now.  I can reopen it, but you might want to rename the title of the ticket and edit the first comment to highlight the problems you bring up in this ticket.

**Comment by shapaz** [comment]
@ryanmkurtz You're right to observe that #8374 seems to duplicate the issue of #4461 (detection of inline str functions), when considering the title and the main text, without my comments. It actually started as trying to build a concise example of how this issue (#6431, stack string initialisation) was not in-fact resolved, as per your request. I must have confused the two topics when creating the reproduction code. Seeing how I missed my original intent I added the comments.

I think the issues are tied closely together; notice the subtle diff in the code reproducing each of the issues:
```c
#include <string.h>
void md5(char *out, const char *in);

int foo()
{
    char buf[32];
    int r = 0;
    memset(buf, 0, 32);
    md5(buf, "some string");
    for (int i=0; i<100; i++)
        r += buf[r & 31] << (i & 31);
    return r;
}
```
for triggering the inline `memset` issue vs
```c
#include <string.h>
void md5(char *out, const char *in);

int foo()
{
    char buf[32] = "01234567890123456789012345678901";
    int r = 0;
    md5(buf, "some string");
    for (int i=0; i<100; i++)
        r += buf[r & 31] << (i & 31);
    return r;
}
```
for the stack-buffer initialisation issue.
The source code difference is only in the initialisation of `buf`, and the resulting de-compiled code is also similar. When initialising `buf` as an empty string, the resulting de-compiled code is actually identical.

It should also be noted that #4461 is a 3 years old issue, and seems to be forgotten. IMHO, this is too frequent of an issue to be ignored for so long.
