### ISSUE TITLE
Build failure for :Decompiler:ip

### ISSUE THREAD

**Issue by philpem** [NationalSecurityAgency/ghidra#661]
**Describe the bug**
Running "gradle buildGhidra" results in a build failure if the project has been built in Eclipse.

**To Reproduce**
1. Load the Ghidra repository into Eclipse and build it.
2. Run "gradle buildGhidra" from the command line
3. The build fails with a "No IP found for $HOME/git/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/xml.cc" error.

**Expected behavior**
Build succeeds

**Screenshots**
````
(...)

> Task :DebugUtils:compileJava
Note: /home/philpem/git/ghidra/Ghidra/Features/DebugUtils/src/main/java/db/DbViewer.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :Decompiler:ip FAILED

FAILURE: Build failed with an exception.

* Where:
Script '/home/philpem/git/ghidra/gradle/support/ip.gradle' line: 125

* What went wrong:
Execution failed for task ':Decompiler:ip'.
> No IP found for /home/philpem/git/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/xml.cc in module: /home/philpem/git/ghidra/Ghidra/Features/Decompiler. Expression: (ip != null). Values: ip = null

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.0/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 6m 1s
141 actionable tasks: 89 executed, 52 up-to-date
````

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04.2 LTS
 - Java Version: 11.0.3
 - Ghidra Version: Current master (25894ff9ae6b670811ce4e3ed1aea973069a5e21)

**Additional context**
Disabling the IP dependency in ghidra/gradle/support/ip.gradle allows the build to run to completion.

**Comment by pwmoore** [comment]
grammar.cc in the same directory also causes this issue due to lack of IP block.

**Comment by ryanmkurtz** [comment]
Is Eclipse CDT installed?

**Comment by ryanmkurtz** [comment]
I am trying to recreate this but I do not have xml.cc or grammar.cc files anywhere.

**Comment by mumbel** [comment]
They're generated in build process, I do remember at least seeing a ref to grammar.cc when manually compiling decompile

https://github.com/NationalSecurityAgency/ghidra/blob/eadf39e6e4f00aeb054f5bb961890e72c84df235/Ghidra/Features/Decompiler/src/decompile/cpp/.gitignore#L1

**Comment by ryanmkurtz** [comment]
I was able to reproduce it.  From Eclipse using the CDT I did `_Decompiler -> Build Targets -> decomp_opt -> Build Target`.

@philpem, did you go out of your way to build it this way (or a similar way) or did Eclipse build it automatically somehow?

**Comment by philpem** [comment]
Eclipse built it automatically, I think. I don't recall running that build target.

The only other possibility I can think of is that it was invoked as part of one of the Gradle build preparation or native build commands.

**Comment by ryanmkurtz** [comment]
The intent is that Gradle is used to build the native binaries, including the decompiler.  Our Gradle tasks (native or prepDev) will not produce these source files in a location that will fail the IP check.  I suppose the best answer for now is try to prevent Eclipse CDT from automatically building the decompiler.  In my setup, that did not happen.  I am going to close this for now since there is not an action we are going to take, but if you get more insight into why Eclipse automatically built it, feel free to comment here again and we can revisit the problem.

**Comment by hedgeberg** [comment]
FYI, this bug can be worked around by changing the `assert(ip != null)` at like 125 in `gradle\support\ip.gradle` to nesting the following lines in an if statement. Modified code looks like: 
```c++
tree.each { file ->
    String ip = getIp(p.projectDir, file)
    //assert ip != null : "No IP found for "+file.path+ " in module: "+p.projectDir
    if (ip != null) {
        String ipString = ip.replace(' ','_')
        assert allowedIP.contains(ipString) : "Found non-allowed IP: "+ip+" for file "+file.path+" in module: "+p.projectDir
        addToMap(map, ip, getRelativePath(p.projectDir, file))
    }
}
```

This appears to fix the build without causing any further errors, since the failure case just seemed to be when the getAllowedIP() function was hitting an empty directory.
