### ISSUE TITLE
Inconsistant treatment of enumerations between pointers and arrays

### ISSUE THREAD

**Issue by Wall-AF** [NationalSecurityAgency/ghidra#6696]
**Describe the bug**
Whilst dereferencing a pointer to an enumeration the value does get converted into the enum name, when dereferencing an array it doesn't.  (See the 2 lines below - from the included zip.)
`*pmap = _FREE_PARA;`
`preg->last_failed_alloc[page_index] = 0xf1;`
`0xf1` is defined as `_NO_FAILED_ALLOC`

**To Reproduce**
1. Load in the enclosed function (from the `Decompile:`Panels `Debug Function Decompilation` menu)
2. See error

**Expected behavior**
Array dereferencing should work the same as pointer dereferecing wrt enumeration usage.

**Screenshots**
N/A.

**Attachments**
[__sbh_free_block.zip](https://github.com/user-attachments/files/16119510/__sbh_free_block.zip)

**Environment (please complete the following information):**
 - OS: Windows 11
 - Java Version: Temurin-21.0.3
 - Ghidra Version: 11.2-DEV
 - Ghidra Origin: locally built from 0475071f5

**Additional context**
Fixing this may help with other array issues.

**Comment by kkots** [comment]
@Wall-AF 
In the XML file you sent the "last_failed_alloc" field is of type array[1024] with elements of type __map_t which is defined as uchar, hence this is why it doesn't recognize the enum. The "pmap", on the other hand, is defined as __map_t*, and that __map_t is a different one, although named the same, and is defined as, I think, a typedef (?) to enum__map_t, which is your enum, so it recognizes enum there.
So the issue here is caused by having two types named the same or a typedef named the same that points to a different type.
