### ISSUE TITLE
Unpackaging Undefined Byte Array in Structure Editor results in `undefined1` bytes, not `undefined bytes`

### ISSUE THREAD

**Issue by nmggithub** [NationalSecurityAgency/ghidra#6698]
**Describe the bug**
In many programs, when I use the Structure Editor, and create an `undefined[x]` component and then unpackage it, it creates `x` elements of the DataType `undefined`. This works well for me, as I can then take some `undefined` byte, redefine it as a larger DataType, and it will cover the bytes after it, avoiding shifting anything after it down. However, in many programs now, this "Unpackage Component" operation results in bytes of type `undefined1`, which do not have the same properties. Is there a setting I changed somewhere accidentally that causes this?

**To Reproduce**
1. Open the Structure Editor
2. Create a component of DataType `undefined[x]` (where `x` is some integer)
3. Right-click the component and select "Unpackage Component"
4. Observe that the component is unpackaged into `x` bytes of DataType `undefined1`.

**Expected behavior**
The component is unpackaged into `x` bytes of DataType `undefined`.

**Screenshots**
N/A

**Attachments**
N/A

**Environment (please complete the following information):**
 - OS: macOS 14.5
 - Java Version: 22.0.1
 - Ghidra Version: 11.0.3
 - Ghidra Origin: GitHub Releases ZIP

**Additional context**
This has been happening to me more often than it doesn't, and I apologize for any lack of details. For some programs, it works as expected, but for many it doesn't. This also seems to affect the "Insert Undefined Byte" feature, as it will insert an `undefined1` byte instead of an `undefined` byte in programs where this bug also occurs.

**Comment by ghidra1** [comment]
This is expected behavior for packed structures where use of `undefined` datatype is not permitted.

An `undefined[*]` datatype is considered a "defined" component type while the `undefined` type is not and is only permitted within non-packed structures to represent padding or unspecified components.   The `undefined1` datatype is used in the place of `undefined` for packed structures when components are explicitly specified but the datatype is unknown.  You probably should avoid using `undefined[*]` and use `undefined1[*]` in its place when you are reserving defined regions. 

You will notice that when transitioning from a non-packed to packed structure all `undefined` components are removed.

**Comment by nmggithub** [comment]
> You probably should avoid using undefined[*] and use undefined1[*] in its place when you are reserving defined regions.
I am curious as to why this is recommended, as `undefined1` bytes do not have the space-preserving behavior I described in my original issue.

**Comment by ghidra1** [comment]
Sorry, all I can say is that the `undefined` datatype serves a special purpose and an undefined-array does not.  Within a packed structure only "defined" components are supported and use of the "undefined" datatype is not.  The behavior of a packed and non-packed structure is quite different within the editor.  A packed structure is only intended to be used when the complete definition of the structure is known.

**Comment by nmggithub** [comment]
Good to know. Thank you!
