### ISSUE TITLE
PI (personal information) sanitization option for export (Ghidra Zipfiles)

### ISSUE THREAD

**Issue by subreption-research** [NationalSecurityAgency/ghidra#6716]
Currently whenever the current program is exported as a Ghidra Zipfile, certain information like path details and other tidbits are included without possibility of disabling their inclusion.

![image](https://github.com/user-attachments/assets/b8d40ef3-f785-49cc-8f89-7f35c4d8361a)

It would be helpful to provide an option in the dialog to sanitize these details, since most users are also likely unaware of the fact that the original path to the object files is included. This will often include usernames and/or local path information that might be sensitive.

The PI that would be beneficial to sanitize includes the following fields:

![image](https://github.com/user-attachments/assets/29b03ba4-5fc6-4616-ab96-97ed3ffc2849)

**Comment by ryanmkurtz** [comment]
Our team just discussed this and came to the conclusion that the only way to guarantee true sanitization with the Ghidra Zip File exporter is to use Ghidra on a sanitized machine/VM (i.e., generic sounding username).  You can go to `Edit -> Options for '<program>' -> Program Information` and sanitize the fields of interest there, but because the GZF exporter is exporting the entire database, it will not be guaranteed that a forensic examination of these fields will not recover the original values.  But, if you are just looking for a superficial "sanitization", then you could use this technique.

It was also recommended that you use the SARIF exporter, sanitize your strings in the resulting text file, and then share that or reimport it and export again as GZF.

**Comment by ryanmkurtz** [comment]
> Is this related to the way the database is internally handled? (ex. similar to the "slack space" created in SQLite databases when deletions or updates may not actually overwrite or erase previous data

Exactly.
