### ISSUE TITLE
Discrepancy Between CLI and GUI Decompilation Results for Calculated Function Addresses

### ISSUE THREAD

**Issue by jongchan988** [NationalSecurityAgency/ghidra#6728]
# Version Information
- ghidra_11.1_PUBLIC_20240607

# Issue Description
i encountered an issue where the calculation of an address using PTR_FUN_0003b1bc + 0xae0 does not seem to yield the expected results when analyzed via CLI and GUI in Ghidra. Below are the details of the problem:

- The symbol PTR_FUN_0003b1bc is located at address 0003b1bc, and the name suggests it's a function. However, it is just a label and not an actual function.
- The calculated address from 0003b1bc + 0xae0 results in 0003c1b4.
- The address 0003c1b4 does not contain or point to any function.
- On the other hand, in the GUI decompilation, this address corresponds to FUN_00020ff8.

# Steps Taken
- Verified that PTR_FUN_0003b1bc is correctly labeled at address 0003b1bc.
- Calculated the address with 0003b1bc + 0xae0 which results in 0003c1b4.
- Confirmed that there is no function at 0003c1b4 in CLI.
- However, in GUI, the function FUN_00020ff8 appears to be at the calculated address.

![image](https://github.com/user-attachments/assets/e4c4bbbf-cb1c-4de5-80c2-d27fa3ad3bff)

There appears to be a discrepancy between the CLI and GUI decompilation results in Ghidra. Specifically, the CLI decompilation does not yield the expected function at the calculated address, whereas the GUI decompilation shows the function FUN_00020ff8.

# Questions

i seek assistance from the Ghidra community to understand the following:
- Why is there a difference between CLI and GUI decompilation results?
- How can iensure consistent results across both CLI and GUI?

# Attachments
[libcms_util.zip](https://github.com/user-attachments/files/16262131/libcms_util.zip)

**Comment by igbecerra** [comment]
The results from your screenshots show a difference in decompiler output optimization. I can't really help much with that as I don't use `headless`, but I think you need to throw some arguments and scripts at it to make it decompile. It might be helpful to attach those too.

Otherwise, the code is *functionally* equivalent. The Ghidra GUI code is optimizing away all the pointer arithmetic and just showing the result, a call to `FUN_00020ff8`. The Ghidra Headless code is not hiding that, but you're just interpreting it wrong: `PTR_FUN_0003b1bc` is typed as a pointer and its *address* is, as you know, `0x0003b1bc`. But its *value* is `0x00020000`, which is what the Ghidra Headless code pointer arithmetic is using. That pointer's value plus `0xff8` gives us our final pointer to `0x00020ff8 => FUN_00020ff8`

As some example code (to check in a debugger).
```
void example(void)
{
    void *PTR_FUN_wherever = 0x00020000;
    void *test1 = (PTR_FUN_wherever + 0xff8); // == 0x00020ff8
    void *wrong = (&PTR_FUN_wherever + 0xff8); // In the original binary, 0x0003C1B4. Here, the variable will be placed who knows where...
}
```

**Comment by ryanmkurtz** [comment]
I am unable to reproduce any differences:

<img width="1324" alt="image" src="https://github.com/user-attachments/assets/84611d88-db70-46f2-9153-f3754071db04">

Are you sure you imported the same binary in the GUI as in headless?  What headless command did you use?
