### ISSUE TITLE
How to convert some external source of data into a format Ghidra can load?

### ISSUE THREAD

**Issue by sorenbug** [NationalSecurityAgency/ghidra#680]
There's already a disassembly of the project I want to decompile available, and I want to import it into Ghidra.

For example, if given the ASM file
```asm
ORG $008000
reset_start:
	SEI					;$008000	\ Disable IRQ
	STZ.w $4200				;$008001	 | Disable IRQ, NMI and joypad reading
	STZ.w $420C				;$008004	 | Disable HDMA
	STZ.w $420B				;$008007	 | Disable DMA
```
with the binary contents
```
78
9c 00 42
9c 0c 42
9c 0b 42
```
I want to write a program that produces output Ghidra can read as ![image](https://user-images.githubusercontent.com/7751296/59314557-a853d880-8c6a-11e9-92d9-404a022877cf.png)

What does the output I produce need to look like so that I can just import into Ghidra fairly plainly?

**Comment by emteere** [comment]
Just importing the disassembly will not get you decompilation.  You need to import the bytes and let Ghidra do the disassembly and attach the correct semantics to each instruction.
The simplest thing to do is just create a raw bytes file, and then import them at the right address and the right processor.  You can also write your file to IntelHex for a little better automatic loading at a particular address.

There is also a .xml/.bytes format that is used for saving some information, but it can be complex.  If you wanted all the comments and labels that might be the way to go.

**Comment by sorenbug** [comment]
It would take forever to disassemble in Ghidra; I have enough data to be able to output to a format usable in Ghidra myself. How do I use those formats?

**Comment by emteere** [comment]
What processor are you using?  6502? 65c816?  Ghidra must also support the processor.

You can supply information about where there are instructions, labels, function starts, comments, but Ghidra will need to disassemble.  But I think it is possible there is more of a mis-communication.  By disassemble, I do not mean reverse engineer (locating code, data, labeling, etc...).  I mean attaching semantics to every instruction and to do that ghidra must decode the instructions to know what semantics to attach.

If you want to import all your markup information, you can look at the exported .xml format.  There is an XML schema you can take a look at.  https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Features/Base/src/main/resources/PROGRAM.DTD.  This is probably more pain than you would like to endure.

I would again suggest dumping it to Intel Hex format to get the bytes into Ghidra in the right format.
Then since you have to dump the information from whatever is storing it, I would write a Ghidra Python or Java script to parse your storage of the information.  Applying labels, comments, locations of disasembly start locations,
Or split the difference, and dump your information to a simple marked up format, and then apply it with a simple ghidra script written in java or python, after the raw bytes have been loaded at the correct memory locations.

**Comment by sorenbug** [comment]
I'm using the 65816 plugin created by @achan1989 found [here](https://github.com/achan1989/ghidra-65816). However, it will take forever to manually disassemble and add comments for 512 KiB of data, especially when there's non-code segments strewn about the executable, I have XF, MF, EF flags to worry about for each code section, and I have to manually move comments from `; |\ Comment content` to `⎥⎤Coment content`.

I was planning on writing a Scala script to parse the ASM file I have (which will be fairly easy) and convert it into some sort of ADT which is easily output to/read by Ghidra. Honestly it would be fairly easy to write some sort of `xdotool`-calling macro for it from the Scala script if it weren't for the fact that there's 16 different ROM banks that all need to start at special locations.

**Comment by ryanmkurtz** [comment]
@sorenbug is this still an issue or can we close the ticket out?

**Comment by sorenbug** [comment]
I don't think it still is, but I'll open a new issue if I have more problems.
