### ISSUE TITLE
Cannot invoke "ghidra.framework.main.FrontEndService.addProjectListener(ghidra.framework.model.ProjectListener)" because "frontEnd" is null

### ISSUE THREAD

**Issue by sbrptdev2** [NationalSecurityAgency/ghidra#6937]
**Describe the bug**

I'm encountering this exception when closing the Ghidra process via exit menu, while developing an extension with Eclipse.
There is no indication to the actual source of the problem that I can see, and searching for occurrences of this exception yields nothing.

```
java.lang.NullPointerException: Cannot invoke "ghidra.framework.main.FrontEndService.addProjectListener(ghidra.framework.model.ProjectListener)" because "frontEnd" is null
java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "ghidra.framework.main.FrontEndService.addProjectListener(ghidra.framework.model.ProjectListener)" because "frontEnd" is null
	at ghidra.framework.plugintool.Plugin.cleanup(Plugin.java:288)
	at ghidra.framework.plugintool.PluginManager.dispose(PluginManager.java:105)
	at ghidra.framework.plugintool.PluginTool.dispose(PluginTool.java:515)
	at ghidra.framework.main.FrontEndTool.dispose(FrontEndTool.java:170)
	at ghidra.framework.plugintool.PluginTool.close(PluginTool.java:1212)
	at ghidra.framework.main.AppInfo.exitGhidra(AppInfo.java:49)
	at ghidra.framework.plugintool.PluginTool$1.actionPerformed(PluginTool.java:1010)
	at docking.DockingActionProxy.actionPerformed(DockingActionProxy.java:47)
	at docking.DockingActionPerformer.lambda$perform$0(DockingActionPerformer.java:73)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.NullPointerException: Cannot invoke "ghidra.framework.main.FrontEndService.addProjectListener(ghidra.framework.model.ProjectListener)" because "frontEnd" is null
	at ghidra.app.plugin.debug.DomainFolderChangesDisplayPlugin.dispose(DomainFolderChangesDisplayPlugin.java:63)
	at ghidra.framework.plugintool.Plugin.cleanup(Plugin.java:277)
	... 21 more

---------------------------------------------------
Build Date: 2024-Sep-16
Ghidra Version: 11.3
Java Home: /usr/lib/jvm/java-21-openjdk-amd64
JVM Version: Ubuntu 21.0.4
OS: Linux amd64
```

**Expected behavior**
Clean exit.

**Comment by dragonmacher** [comment]
Taking a peek at this trace, this code seems to have a bug in it (but this bug does not explain this stack trace):

```java
	@Override
	protected void dispose() {
		FrontEndService frontEnd = tool.getService(FrontEndService.class);
		frontEnd.addProjectListener(this);

		Project activeProject = tool.getProjectManager().getActiveProject();
		if (activeProject != null) {
			projectClosed(activeProject);
		}
	}
```

I believe the call to `addProjectListener()` should be `removeProjectListener()`


The code above does not expect the `frontEnd` to be null at the time of disposal.  I'm guessing that there is some other exception happening that is causing the front end to be cleared inside tool so that the call the `tool.getService()` is failing.

**Comment by dragonmacher** [comment]
You can enable logging for the ClassSearcher and Extension related packages to get more details on what is happening during the load process.  These packages have embedded trace() messages that you may find helpful.

Changing the log levels varies by development setup.     Are you running from a pull of the repo, using the source code inside of Eclipse?   Or are you building Ghidra from source code and then using that to write your own code?

**Comment by dragonmacher** [comment]
>  I do think we need more documentation for all the possible quirks and problems with the development environment. You obviously have become accustomed to these over the years and curated a significant amount of knowhow in dealing with them, but to outsiders these toolchain "heisenbugs" can be mistifying.

So true.  (Imagine how hard it is to keep all of this straight when you remember all the old ways of configuring and building that we have had over the decades.)  There was a point where this dev process was simple.  Things used to be  easy when all of the code lived in one Eclipse project, with a simple Ant build system.  As with software design, flexibility comes at a cost of understandability.  We are very flexible now.  So much  that it feels near impossible to keep the entirety of the system in your head.    Situations like yours are especially difficult for me, since I don't develop extensions regularly.   I agree that we should have much better documentation for the happy paths of scripting development, as well as some basic troubleshooting steps.

Not sure if you are running into this or not, but for me, Eclipse has become quite flaky over the years.  I pretty regularly get odd compile errors that eventually just go away.   Regarding your Plugin not being loaded, it seems like your path is correct, based on the traces.   I can't tell if you have all tracing on inside of the `ghidra.util.classfinder` package.  There are more fine-grained messages that will show the actually directories being processed.   Some things that may help (excuse me if they are already obvious to you; it sounds like you have done some of this):

- `gradle cleanEclipse eclipse` will ensure that your project and classpath files are created, are up to date with the directory contents, and can then be imported into Eclipse.
- If you already have imported the projects, and then use the gradle command again, you must refresh all of the projects inside of Eclipse by selecting your projects and pressing F5 or using the right-click menu and pressing 'Refresh'.  Eclipse is slow to pick up changes to the generated project files, so refreshing helps.
- You should be able to verify that your plugin class has been compiled and lives inside of your project's `bin` directory by using the Project Explorer window in Eclipse.
- If your plugin class name ends with `Plugin`, then it should get loaded as long as it is in the classpath (which the tracing should verify).  If needed, you can debug this using  `ClassSearcher.loadExtensionPoint()`, with conditional breakpoints for your class or even by altering the code and adding your own prints for when your class is encountered.
- If you see your Plugin class being loaded by the class searcher, then you may need to turn your plugin on via the GUI from the Code Browser tool's `File -> Configure` menu.   The easiest thing to do in that GUI is to click the plug icon on the toolbar to show all found Plugins, then use the filter to find yours in the list, ensuring it is checked.

**Comment by dragonmacher** [comment]
It seems like the issue is that Eclipse is not building your source for your project.  This could be that the project's source inclusions are not setup correctly.   Or, it could just be some flakiness of Eclipse, sadly.    The project structure looks good to me.   You can try deleting and re-importing the project (without deleting the contents) to see if that will force Eclipse to recompile.

Regarding the issues of running Ghidra, @ryanmkurtz is more up to speed with that.

**Comment by dragonmacher** [comment]
>  Eclipse is truly an enterprise class environment. All the frustration, none of the basic decency of telling you why it takes a piss when it does. Alas....

Indeed.  I do think Eclipse's best days are 15+ years ago.

**Comment by dragonmacher** [comment]
I'm assuming you want to open the `Debug` view, which is where the threads are shown, along with breakpoint controls (which area also in the main window toolbar).

Honestly, print statements are my usual go to, since we are heavily multithreaded.   

As mentioned before, I think there is some other initialization failure happening, which is polluting Ghidra's tear down process.

**Comment by dragonmacher** [comment]
It's quite possible that this is a latent issue that we have simply not encountered.   I don't recall, but I would expect that dependents would be disposed before their dependencies.    Even that could lead to arbitrary behavior if the dependency tree is complicated.   The odd thing to me in this case is that I would expect the Front End to be disposed last of all, since that is the main entry into the system.  But, it's possible that we do not have any special code to make this the case.

I will investigate more to see how this is all wired now.
