### ISSUE TITLE
Disassembler does not update when constructors with just a mnemonic are changed

### ISSUE THREAD

**Issue by rimwall** [NationalSecurityAgency/ghidra#6957]
**Describe the bug**
In modifying a language, I was testing very simple constructors with just a mnemonic (ie: no identifiers) in the display section. If the mnemonic of such a constructor is changed in the language spec files (or even if the constructor is removed entirely), the language recompiled, Ghidra restarted and the file reloaded, the disassembler does not update to reflect the changed mnemonic. Contrast this with what happens when the constructor has identifiers in the display section (like most constructors) - in this case the disassembler updates (or reports 'bad instruction' if the constructor has been removed).

Note that the decompiler does update for all cases. This appears to be a disassembler only issue.

**To Reproduce**
1. Start with a Ghidra file that is using a particular language and has been disassembled at any location, save and close down the file, close down Ghidra.

2. Edit the slaspec file to include a simple constructor with just a mnemonic in the display section. An example would be as follows. (whatever the existing constructor was for this bit pattern will need to be commented out):
`:b31R0	is op1=0; op3=9 { $(C) = (R0[31,1] == 1); }`

3. Save & recompile the updated processor language

4. Restart Ghidra, reopen the file from step 1 above. Update the disassembler so that it displays the b31R0 mnemonic where (in this example) there are matching instructions of 0x0[z] 0x9[z] where [z] can be any value. Save and close file. Close down Ghidra. 

5. Edit the slaspec file to change the simple constructor, such as:

```
:b31R0	is op12=0x00; op34=0x90 { $(C) = (R0[31,1] == 1); }
:b31R1	is op12=0x01; op34=0x91 { $(C) = (R1[31,1] == 1); }
:b31R2	is op12=0x02; op34=0x92 { $(C) = (R2[31,1] == 1); }
:b31R3	is op12=0x03; op34=0x93 { $(C) = (R3[31,1] == 1); }
:b31R4	is op12=0x04; op34=0x94 { $(C) = (R4[31,1] == 1); }
:b31R5	is op12=0x05; op34=0x95 { $(C) = (R5[31,1] == 1); }
:b31R6	is op12=0x06; op34=0x96 { $(C) = (R6[31,1] == 1); }
:b31R7	is op12=0x07; op34=0x97 { $(C) = (R7[31,1] == 1); }
:b31R8	is op12=0x08; op34=0x98 { $(C) = (R8[31,1] == 1); }
:b31R9	is op12=0x09; op34=0x99 { $(C) = (R9[31,1] == 1); }
:b31R10	is op12=0x0a; op34=0x9a { $(C) = (R10[31,1] == 1); }
:b31R11	is op12=0x0b; op34=0x9b { $(C) = (R11[31,1] == 1); }
:b31R12	is op12=0x0c; op34=0x9c { $(C) = (R12[31,1] == 1); }

```
These more specific mnemonics should display 0x00 0x90 as b31R0, and 0x01 0x91 as b31R1, and 0x02 0x92 as b31R2 and so on

6. Restart Ghidra, reopen the file from step 4 above. You should see that all instances of 0x0[z] 0x9[z] remain unchanged with a mnemonic of b31R0, and have not updated to reflect the new, more specific mnemonics. The only way to change the disassembler listing is to clear and then press 'D' for each instance of the wrong mnemonic. Save, close file. Close Ghidra.

7. Now remove all of the added mnemonics from the language. Do not uncomment out the original constructor that was commented out in step 2. Recompile the language.

8. Restart Ghidra, reopen the file from step 6 above. You should see that all mnemonics b31R[z] are still displayed, even though they have been deleted from the language.

**Expected behavior**
The disassembler listing should reflect the latest compiled version of the language. This happens for constructors that have identifiers in the display section.

**Screenshots**
I'm not sure screenshots will help much for this issue. This image is from Step 6 where the mnemonic has not updated to the correct one (should be b31R1):
![image](https://github.com/user-attachments/assets/1730924d-a1c9-4ebe-9834-6ba7e919d0ae)

**Attachments**
None.

**Environment (please complete the following information):**
 - OS: Windows 10 Home
 - Java Version: 21.0.4
 - Ghidra Version: 11.1.2
 - Ghidra Origin: official Ghidra download page 

**Additional context**
As a guess, it would appear the disassembler only updates the mnemonics for constructors that it needs to interrogate to display (ie: the ones with identifiers in the display section are updated but mnemonics without identifiers are not updated).

**Comment by rimwall** [comment]
Actually, the decompiler does get affected. Here are some screenshots showing the progression of changes as described in Step 6 above.

Starting point - instruction mnemonics are incorect and decompiler is incorrect (all if statements are unconditionally true)
![Step1](https://github.com/user-attachments/assets/7f4f7695-b4cc-4f68-92b0-f35864b0035f)

Next step - clear the incorrect instruction. Decompiler now reflects correct logic for this instruction.
![Step2](https://github.com/user-attachments/assets/940775ed-f429-42e1-83b8-29989fe3f087)

Next step - press D on the previously cleared instruction. Disassembler and Decompiler now correct (for just this instruction)
![Step3](https://github.com/user-attachments/assets/922d4fd6-7f23-48b0-b2de-a8d84553b9de)

A few steps later - 3 of the instructions have now been manually corrected and decompiler is getting better.
![Step4](https://github.com/user-attachments/assets/297ce8a0-6624-4873-bc68-61fe4ec75d76)

**Comment by emteere** [comment]
When experimenting or developing a processor, you can use the script **ReloadSleighLanguage** without exiting Ghidra.  This will cause your sleigh file to re-compile, reload, and will re-disassemble all your instructions.  This should have the result you want and you won't need to exit Ghidra.  This won't handle everything, for example is you mess with register locations, memory size, compiler spec, or other things that can't be fixed without re-starting. In general for things like you are doing it works well.

If you are changing the nature of instructions, say adding flow where it was just a pseudoOp with a fallthru before, you might want to have a set of non-disassembled bytes to test with.  There all sorts of fallout effects beyond just disassembly that can be affected.  It would be impossible to constantly find them all and fix them from a change. 
 Another example, references that have been computed, you might need to re-kick off analysis to fixup the fallout, and sometimes that isn't enough and you might as well reload the binary.
 
Or simply clear the bytes and re-disassemble.

There are some things that are done dynamically and some that are done only when needed.  You are seeing artifacts of the way a program is disassembled and stored, and the changes you are making.  Changing a sleigh file is not a normal thing you would do as you are reverse engineering, so it isn't done dynamically and can be expensive.  You wouldn't want a 70Meg binary to re-disassemble or even dynamically disassemble.  Ghidra needs to have instruction locations marked and all sorts of fallout from the existence of an instruction, like references.

Disassembly can be a little strange when you change a sleigh specification if you have already disassembled instructions, especially if you are experimenting.  You can get away with some changes; pcode semantics, minor visual changes, minor match pattern changes, even changing the mnemonic name.  As a rule you can't split a constructor or sub-constructor and expect things to go well for existing disassembly

**A rule you must follow if you don't want this behavior in existing programs is you must increase the minor version number in the <language>.ldefs file if you have caused any constructor or subconstructor to split.**  This will cause all instructions to re-disassemble when the existing program is next opened.  Not a good thing to do if you can help it, but sometimes necessary as in your case.  You wouldn't want to use this while experimenting.

There are some things you can get away with when modifying a program because of the way the already disassembled instructions are stored.  Each instruction disassembled and is given a prototype with a HASH that is shared among other instructions that have that hash.  As an example: there is only one "JMP 0x12345" prototype that is shared with all other "JMP 0x...."  instructions that have decoded to that same constructor.

Long way to say this is expected behavior when changing the disassembly rules with existing disassembly.

**Comment by rimwall** [comment]
Ok, thanks for the detailed explanation. Appreciate it.
