### ISSUE TITLE
DEX files not available for import on Batch Import of APKs, caching issue

### ISSUE THREAD

**Issue by leveled** [NationalSecurityAgency/ghidra#700]
**Describe the bug**
This issue crops up when I import an APK on one project, and attempt to open it again in another. I can import DEX (and their corresponding decompiled JAR/Class files) just fine the first time, but afterwards files from that APK will not be available for import. I believe this is a caching issue, as deleting the .ghidra folder in my home directory allows for imports to be made. Even if a project is deleted, or files from a project are deleted the issue still persists. 

**To Reproduce**
1. Create a new project
2. Open an APK (such as [this one](https://github.com/markushi/android-ui/blob/master/example.apk)) in Ghidra as a batch import file. Increase the depth and observe the availability of Java classes for import.
3. Create another project
4. Open the same APK as batch import, observe that Java classes are not available for import.

**Expected behavior**
Importing functionality should not depend on previous imports that have been performed. 

**Environment (please complete the following information):**
 - OS: macOS 10.14.5
 - Java Version: 12.0.1
 - Ghidra Version: 9.0.4

**Comment by dev747368** [comment]
It seems like you are saying that if you repeat the same batch import steps twice, the second time (in a new project) your batch import session will fail to find any .class files?

This seems pretty strange.  I would suggest using the "Open File System" to open the apk and drill down through the nested files to see if you can reach the .class files you were able to import previously.

Also, in the initial successful import session, the newly imported files will have a FSRL property that will tell you the "path" from the initial root file to the nested imported .class file.  That value might tell us something.

**Comment by dev747368** [comment]
Also, one thing to be on the look out for is the .dex file being opened as dex2smali instead of dex2jar.
Once the dex file is opened that way, subsequent attempts to open it will default to the already in-memory open filesystem, instead of prompting you to make a choice (if using the browser).
Simply closing any fs browser window that has that file system open, and then waiting ~30 seconds for it to be cleared from the cache will get you back to a fresh state.
Exiting ghidra and restarting would also do the same thing, but its a bit more extreme.
(btw, these mounted file systems are not tied to project files or any persistent cache files)

**Comment by dev747368** [comment]
I'm going to close this for now.  If you find any more info about your situation that looks like a bug, please update.
