### ISSUE TITLE
[PDB] Add a checkbox to use the current filename instead of the original one to import the .pdb file during initial analysis

### ISSUE THREAD

**Issue by SmileyAG** [NationalSecurityAgency/ghidra#7200]
**Is your feature request related to a problem? Please describe.**
You know, I have a lot of files that have the same name initially, but all of them belong to different versions. Instead of organizing them into separate folders, like `v1104/hl.dll`, `v1107/hl.dll`.
I decided to rename them to the corresponding names like `hl_v1104.dll` and `hl_v1107.dll` so that both of them could be in the same directory! This can be really handy instead of having multiple folders!

So, if we assume that you had files from compilation were named as `hl.dll` and `hl.pdb`, but then you decided to rename them to `hl_v1107.dll` and `hl_v1107.pdb`.
Then when importing the DLL into Ghidra, the file `hl_v1107.pdb` will be ignored, because Ghidra is trying to find the `hl.pdb` file, since it is embedded as the original name inside the DLL.

**Describe the solution you'd like**
In the menu for the initial analysis, in the `PDB Universal` setting, add this checkbox so that the current file name is used instead of the original one for import the `.pdb` file.

**Describe alternatives you've considered**
After the initial analysis, manually import the PDB file. 
I don't have so many of them that it could annoy me to do that each time, but in any case it would be nice to add the option.

**Additional context**
I mean the option should be added here in `PDB Universal` setting:

![checkbox](https://github.com/user-attachments/assets/b02f354b-d97a-4e75-a3cc-837b48a9823c)

**Comment by ghizard** [comment]
Do you find that the majority of the time that the true PDB for, say, abc.dll is abc.dll.pdb?
Is there is reason why you do not include the program filename extension in your scheme?

We are envisioning first checking for the original PDB filename whose name is embedded in the program, followed by alternative PDB filename(s) co-located with the program (possibly without the use of a checkbox).

It's possible that we could try multiple alternative names.  If the program is abc.dll, then try abc.dll.pdb followed by abc.pdb.  This second truncation has the issue of, say, having both abc.dll and abc.exe in a folder.  Also, what if one of these does or does not have a pdb.  Say abc.exe has abc.pdb, but we try to process abc.dll that has no PDB with that PDB.  Of course th guid and age won't match.  But your scheme doesn't work well with both files in the same folder.  Just wondering.

What's your input on: (1) seeing original PDB names without the program file extension (abc.pdb instead of abc.dll.pdb); (2) providing a solution with no checkbox; (3) trying multiple alternative names in abc.dll.pdb, abc.pdb order?
