### ISSUE TITLE
What CPU's does Ghidra want support for?

### ISSUE THREAD

**Issue by redfast00** [NationalSecurityAgency/ghidra#721]
From what point does a CPU architecture become eligible to be included in Ghidra?

For example, what about the [CRIS architecture](https://en.wikipedia.org/wiki/ETRAX_CRIS)? The vendor that produced these chips doesn't anymore, and the Linux kernel has stopped supporting it in 2018, but it can be compiled for in GCC.

What are the requirements for a CPU architecture to be included?

**Comment by emteere** [comment]
Any CPU is fair game, especially if there might be some device in existence that someone might need to inspect in a reverse engineering capacity.  You never know.

Someone just submitted an MCS-48 implementation, of which there is most likely no device left other than possibly museums.  I don't see any reason it shouldn't be included as long as it is complete and well done, which it appears to be.  We just haven't had time to fully review it and accept it.  It is a very small processor so it shouldn't need much. In another case someone implemented a Cold War era processor for learning and historical purposes.

That said, how much time is spent developing and then reviewing a processor for acceptance would be based on the general applicability of the processor.  A lightly used processor might not need to be as fully spec'ed out or reviewed as closely as an ARM or X86 processor.  For a processor that might not get much use, having more user pcode ops for things that are very seldom used would be acceptable.

The real issue is how to properly evaluate a processor module during and after development to include a source of trusted sample binaries.

**Comment by mumbel** [comment]
@redfast00  did you ever end up working on this?  @nihilus (sorry for the ping) looks like you have interest in this processor as well, do you think your IDA module could be scripted to SLEIGH

**Comment by redfast00** [comment]
@mumbel I did not
