### ISSUE TITLE
Possibly invalid Pcode generated for MUL instruction on x86:64

### ISSUE THREAD

**Issue by liona24** [NationalSecurityAgency/ghidra#7221]
**Describe the bug**
Looking at the generated Pcode for the MUL instruction on x86 I get the following:
```
0040100f 48 f7 e2        MUL        RDX
                         $U3ab80:16 = INT_ZEXT RAX
                         $U3ac00:16 = INT_ZEXT RDX
                         $U3ad00:16 = INT_MULT $U3ab80:16, $U3ac00:16
                         RDX = SUBPIECE $U3ad00:16, 8:4
                         RAX = SUBPIECE $U3ad00:16, 0:4
                         CF = INT_NOTEQUAL RDX, 0:8
                         OF = COPY CF
```

SUBPIECE seems invalid here, because it only selects the first 8 bytes of the result, 4 bytes into RDX, RAX each.

**To Reproduce**
.. decompile a MUL instruction with a REX prefix

**Expected behavior**

I would expect the subpiece instructions to look like this:
```
                         RDX = SUBPIECE $U3ad00:16, 16:8
                         RAX = SUBPIECE $U3ad00:16, 0:8
```

**Environment (please complete the following information):**
 - OS: Linux
 - Java Version: OpenJDK 17
 - Ghidra Version: 11.0.3
 - Ghidra Origin: official GitHub distro

**Comment by GhidorahRex** [comment]
It looks wrong, but it's actually doing the right thing, although I agree the format is weird.

`Result:RSize = SUBPIECE Input:ISize Offset:4` is how the SUBPIECE pcode is represented. You can test it with a 16-bit mul instruction and it will still say the size is 4 - because internally the pcode operation uses a 4-byte integer to represent the offset of a subpiece. Because this instruction writes the output directly to registers, the output size is not displayed on the pcode operation.
