### ISSUE TITLE
Another wrong decompilation (GBA)

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [NationalSecurityAgency/ghidra#7229]
![image](https://github.com/user-attachments/assets/55dc8c64-de63-4b08-86f7-273ac8d861b6)
should be `SpriteUtilCheckSamusNearSpriteLeftRight(0x100, 0x100)`
definition of function:
![image](https://github.com/user-attachments/assets/391ae4aa-7c8d-44c8-9523-8497f8bdc732)

**Comment by DualTachyon** [comment]
Go to the function "SpriteUtilCheckSamusNearSpriteLeftRight" decompilation. If it shows 2 parameters, then press "p" to commit the signature. Otherwise, right click the function name and choose "Edit Function Signature" to add the second parameter. Then press "p" to commit.

When you go back to the caller, you should see the correct display.

**Comment by H-A-M-G-E-R** [comment]
however there's another problem: how do i prevent r0 from changing to param_1 and r1 to param_2 after commiting?
![image](https://github.com/user-attachments/assets/9c6024e6-0655-419b-989e-02553d6c6aba)

**Comment by DualTachyon** [comment]
Click on each param, press L and rename.

**Comment by DualTachyon** [comment]
![image](https://github.com/user-attachments/assets/6ea62866-7e6f-4e38-850d-074a380e4c21)

**Comment by ryanmkurtz** [comment]
https://github.com/NationalSecurityAgency/ghidra/issues/7248#issuecomment-2520166024
