### ISSUE TITLE
Dumb lineswap in decompiler

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [NationalSecurityAgency/ghidra#7243]
![image](https://github.com/user-attachments/assets/19fdd9bf-e67f-456f-a26e-dfb7867e69cd)
Expected behavior: should decompile to
```
    uVar1 = gCurrentSprite.yPosition - 0x20 & 0xffff;
    wVar2 = gCurrentSprite.xPosition;
```

**Comment by DualTachyon** [comment]
The compiler is free to reorder instructions as it sees fit, you should not expect Ghidra to decompile assembly code to match exactly the order of your original code. It's both unreasonable and unlikely since the compiler can do things visually differently then the source code, yet still produce the exact same outcome/result.

**Comment by ryanmkurtz** [comment]
The Ghidra decompiler is expected to produce C-like code in whatever order it feels is optimal, while still maintaining correctness. If there are correctness issues, those should be opened in separate tickets.

**Comment by H-A-M-G-E-R** [comment]
What code is responsible for THIS???
