### ISSUE TITLE
BSim: Apply signature failed (Invalid calling convention name: __rustcall)

### ISSUE THREAD

**Issue by gemesa** [NationalSecurityAgency/ghidra#7310]
**Describe the bug**

When trying to apply BSim function signatures (collected from Rust AArch64 binaries) to other Rust AArch64 binaries I get the error `Apply signature failed (Invalid calling convention name: __rustcall)`.

**To Reproduce**

Prerequisites: auto-analyze the binary `rust-rayon2-nostrip` then generate BSim signatures and commit them to the BSim database.

```
$ ./support/analyzeHeadless ghidra://localhost/repo -import ~/git-repos/tmp/rust-rayon2/target/aarch64-unknown-linux-musl/release/rust-rayon2-nostrip -p
$ ./support/bsim generatesigs ghidra://localhost/repo/rust-rayon2-nostrip ~/git-repos/bsim-xml --bsim postgresql://localhost/repo --commit
```

In the Ghidra GUI:

0. Import and auto-analyze `rust-rayon2-strip`
1. Go to a function in the listing, for example `FUN_002299c8`
2. Right click: `BSim` --> `Search Function(s)`
3. Select a matching function from the table then right click: `Apply Signature`
4. See error `Apply signature failed (Invalid calling convention name: __rustcall)`

**Expected behavior**
Function signature is applied.

**Screenshots**

![image](https://github.com/user-attachments/assets/bdc95377-4593-4075-bf90-3d5d7ccc6bac)

![image](https://github.com/user-attachments/assets/80a35cfc-e249-4f9f-ac2f-6fc1c48d4147)

![image](https://github.com/user-attachments/assets/a474fe23-435b-4bbd-a2fc-a7abf8846c30)

**Attachments**
[rust-rayon2-strip.zip](https://github.com/user-attachments/files/18213259/rust-rayon2-strip.zip)
[rust-rayon2-nostrip.zip](https://github.com/user-attachments/files/18213260/rust-rayon2-nostrip.zip)

**Environment (please complete the following information):**
 - OS: Linux fedora 6.12.4-200.fc41.x86_64
 - Java Version: openjdk 21.0.4 2024-07-16 LTS
 - Ghidra Version: 11.3_DEV
 - Ghidra Origin: locally built from the GitHub repo without any changes (commit [8bbc1d054075d0626eba621b470077a17e3dc16a](https://github.com/NationalSecurityAgency/ghidra/commit/8bbc1d054075d0626eba621b470077a17e3dc16a))

**Additional context**
I think this might be related to #7298

**Comment by ghidra1** [comment]
This is caused by the fact that __rustcall convention is undefined - even in the original program which you ingested into BSim.  While it had been forced onto the function during DWARF analysis, you will note if you decompile such a function there will be an error indicating that the calling convention is undefined.  There are places in our code where using or propagating an undefined calling convention is not allowed (Example: creating a `FunctionDefinitionDataType`) in order to keep it contained.  We have added preliminary support to install a Rust compiler-spec extension for x86 which may get applied during import, however, this has not been done for any other processor.

**Comment by gemesa** [comment]
I see. As a workaround I will just apply the function name instead.

**Comment by ghidra1** [comment]
I will be putting in a fix that will allow the signature to be applied without the calling convention.
