### ISSUE TITLE
Are x86 protected mode segments supported?

### ISSUE THREAD

**Issue by stevecheckoway** [NationalSecurityAgency/ghidra#769]
I have some x86 firmware that I've been reversing in IDA that makes heavy use of protected mode segments.

By editing the output of the XML Exporter plugin, I can get each segment to be its own overlay memory section. E.g., something like
``` xml
        <MEMORY_SECTION NAME="s020" START_ADDR="s020::0x0" LENGTH="0x2000" PERMISSIONS="rw">
            <MEMORY_CONTENTS FILE_NAME="foo.bytes" FILE_OFFSET="0x0" LENGTH="2000" />
        </MEMORY_SECTION>
```
creates the overlay `s038` which gets me part of the way there. Data (and probably other) references don't point to the appropriate segments though.

Is there a good way to deal with x86's protected mode segments in Ghidra, including mapping from segment selectors in segment registers to memory sections? (I.e., setting `DS` to `0x20` and then `MOV EAX, [bar]` should be recognized as loading 4 bytes from `bar` in the `s20` section.)

**Comment by caheckman** [comment]
Recent changes in master (and in the 9.1 release when it comes out) provide support for protected mode addressing for 16-bit x86 code. The NE loader will use this by default, but you can force this "Protected Mode" variant for MZ (or for any loader). You don't need to create overlays in this case. The NE and MZ loaders should do a reasonable job of creating the segments, but if you need to create your own memory blocks or otherwise move memory around, you can use normal GUI or scripting and just enter segmented syntax (i.e. "1000:9ac0") addresses. Note that this should work editing the XML Exporter output using a single ':' to specify an address.

The "Protected Mode" variant assumes that segments don't overlap. Ghidra also provides a "Real Mode" x86 variant, which models the old DOS style segment selectors with potentially overlapping segments. This is currently the only option if segments overlap in a substantive way.

**Comment by stevecheckoway** [comment]
16-bit protected mode seems like an unusual choice. I don't think I've ever encountered that before. When using that with Ghirdra, how is the mapping between segment selectors and segments performed?

IDA has a poorly documented and somewhat fragile method of creating segments and selectors but once you get it right, it's smart about tracking changes to ds/es/fs/gs and making references to the appropriate segment. E.g.,
```
push ds
mov  eax, 0x28
mov ds, eax
mov edx, [0xaabbccdd]
pop ds
```
will correctly form a reference to the segment with selector 0x28 and after the `pop`, will go back to making data references to whatever segment `ds` was the selector for before that snippet.

Is there something analogous in Ghidra?

I definitely need 32-bit protected mode. There are some segments that overlap (e.g., one that maps to physical addresses), but those aren't important. Instead, there are a handful of non-overlapping code and data segments.

**Comment by caheckman** [comment]
Ah. Ghidra doesn't support segments in 32-bit code very well; the current SLEIGH language doesn't model segment selectors for memory accesses in 32-bit mode (only in 16-bit mode). A variant of the language would have to be created to get it to follow segments properly.

The 16-bit mode does track selector values through function bodies if you get the segments and selectors set up right.

**Comment by ryanmkurtz** [comment]
Looks like the primary question has been answered...closing.
