### ISSUE TITLE
6502 JMP indirect incorrectly disassembled

### ISSUE THREAD

**Issue by tautology0** [NationalSecurityAgency/ghidra#783]
**Describe the bug**
The way Ghidra represents an indirect JMP is misleading. An indirect JMP (0x6c) is where the CPU reads the contents of a memory location and then sets PC to that address. This is opposed to an absolute JMP (0x4c) which just jumps to the passed address.

This is often used to make look up tables which are often dynamic.

Ghidra tries to be clever and reads the memory location and puts in a link to the result; which causes it to be inconsistent.

For example (in the below, CLIV is set to 0x0208),
```
                            OSCLI
            fff7 6c 08 02        JMP        CLIV
```

Is an indirect JMP, which should be disassembled as JMP (CLIV); but is disassembled as a JMP to 0x0208 when it should be the address **at** 0x0208.

But this is inconsistent as it can sometimes return a variable to the actual destination:
```
                             OSBYTE                                          XREF[5]:     FUN_0fc2:0fcd(c), 

            fff4 6c 0a 02        JMP        offset FUN_e772
```
I can't work out a pattern of when it sets the destination to the indirect value or the absolute value.

This method makes it looks exactly the same as an absolute JMP:
```
            2292 4c 33 23        JMP        LAB_2333
```

This could cause misinterpretations in program flows and; if the program is using this for dynamic tables then will cause it to be wrong in many circumstances.

**To Reproduce**
Create binary file with at least:
4c 0a 02
6c 0a 02

Where 0x020a has a value.

**Expected behavior**
I'd expect an indirect JMP to disassemble using the indirect mode and an absolute JMP to use the absolute mode:
```
4c 0a 02        JMP        0x020a                          Absolute
6c 0a 02        JMP        (0x020a)                        Indirect
```

**Comment by GhidorahRex** [comment]
This is a formatting issue with the indirect jumps lacking the parentheses around the operand to represent the indirection. The actual behavior of the indirect jump instruction is correct, in that ghidra is correctly jumping to the address located at the memory location.

**Comment by tautology0** [comment]
As I said above, it sometimes does this, and sometimes it doesn't and leaves a pointer to the indirect address. I can't work out how it decides what to do.

IMO It should always use a pointer to the indirect address (e.g. to 0x0208, not to the contents of 0x0208) as this instruction is often used to make dynamic jump tables, which means that if you place the label at the contents of the memory location then it will only be correct for the value of the memory at disassembly time and will not reflect other changes.

If this was pointing to the address, then the reverse engineer can see this and makes notes accordingly. If this is pointing to the contents of the address, then the reverse engineer may incorrectly assume that it's always that value and waste time.

**Comment by tautology0** [comment]
Any ETA for what should be a simple fix? I've just wasted 2 hours wondering what code was doing, before I realised that this bug still hasn't been fix.

**Comment by emteere** [comment]
Apologies for not getting this into the baseline sooner.

There two things going on here.  The missing parens, and the computed address that hides the read address.
This has to do with trusting things in memory, which have a constant value, which there are ways of marking memory as constant, or volatile so that the memory will not be trusted.  Blocks of memory can also have this set R readonly or RW.

I do agree with you we should be displaying it differently.  I believe I'd rather see it this way:
JUMP (0x020A)=>LAB_0233
This would be an indication that there was a read, and that a value was loaded from memory and a reference to that location created.  Currently the primary reference the JUMP reference is displayed, and the secondary read is hidden and indicated by and "__" under the operand, so there is some indication this is occuring.

We may be able to get the syntax in soon but I hesitate changing the markup as a new release is imminent.
