### ISSUE TITLE
X86_64 overlapping register listing highlight

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#810]
Running 9.0.4

I'll come across instructions like `xor R13D,R13D` for example and then later instructions accessing just `R13`.  A wheel click on `R13D` will highlight both, but a wheel click on `R13` will only highlight `R13`. 

With the GPR this is not case, so may only effect the 64-bit mode-only GPR.

**Comment by mumbel** [comment]
```
PUSH R13
MOV EAX,R13D
POP R13
RET
PUSH RDX
MOV EAX,EDX
POP RDX
RET
```
Looked into this a bit more, and still makes no sense.  A simple dummy case, highlight works both ways with `RDX`, but not `R13`.  The register set and regex get built up in the same manner

`[R13, R13D, R13W, R13B]` `\QR13\E|\QR13\E|\QR13D\E|\QR13W\E|\QR13B\E`
`[R13D, R13, R13W, R13B]` `\QR13D\E|\QR13\E|\QR13D\E|\QR13W\E|\QR13B\E`

`[RDX, EDX, DX, DL, DH]` `\QRDX\E|\QRDX\E|\QEDX\E|\QDX\E|\QDL\E|\QDH\E`
`[EDX, RDX, DX, DL, DH]` `\QEDX\E|\QRDX\E|\QEDX\E|\QDX\E|\QDL\E|\QDH\E`

And the code flow looks similar, the only difference being `RSP` is not check in `isWriteOnly` for the `RDX` case

**Comment by ryanmkurtz** [comment]
I am stepping through this with the Eclipse debugger, and the problem seems to be in here:

https://github.com/NationalSecurityAgency/ghidra/blob/85e25af7e8f8407c74a0867dfeb6ec8f035fcdd6/Ghidra/Features/Base/src/main/java/ghidra/app/plugin/core/codebrowser/ListingHighlightProvider.java#L145-L154

https://github.com/NationalSecurityAgency/ghidra/blob/85e25af7e8f8407c74a0867dfeb6ec8f035fcdd6/Ghidra/Features/Base/src/main/java/ghidra/app/plugin/core/codebrowser/ListingHighlightProvider.java#L161-L175

In my case:
```
currentHighlightPattern = \QR15\E|\QR15\E|\QR15D\E|\QR15W\E|\QR15B\E
text = R15D,AX
start = 0
end = 2
```
`c` ends up being `'D'`, which causes it to return false.

I think the smaller r15 regex pattern should be moved to the end of the `currentHighlightPattern` regex, or we need to match on the longest pattern.  I don't really know this code though, so I have to verify with others...I'm not sure what else that would affect/break.

**Comment by ryanmkurtz** [comment]
I'm currently stepping thought this to try to figure out what's going wrong.  It's somewhere in here I think:

https://github.com/NationalSecurityAgency/ghidra/blob/85e25af7e8f8407c74a0867dfeb6ec8f035fcdd6/Ghidra/Features/Base/src/main/java/ghidra/app/plugin/core/codebrowser/ListingHighlightProvider.java#L145-L154

https://github.com/NationalSecurityAgency/ghidra/blob/85e25af7e8f8407c74a0867dfeb6ec8f035fcdd6/Ghidra/Features/Base/src/main/java/ghidra/app/plugin/core/codebrowser/ListingHighlightProvider.java#L161-L175

In my case:
```
currentHighlightPattern = \QR15\E|\QR15\E|\QR15D\E|\QR15W\E|\QR15B\E
text = R15D,AX
start = 0
end = 2
```
`c` ends up being `'D'`, which causes it to return false on the first iteration of the `matcher.find() `loop.  But then there end up being no more iterations, which seems wrong.

**Comment by ryanmkurtz** [comment]
I'm thinking the different parts of the regex just need to be grouped correctly.  The existence of the loop implies to me that each register should try to be matched.

**Comment by ryanmkurtz** [comment]
I am stepping through this with the Eclipse debugger, and the problem seems to be in here:

https://github.com/NationalSecurityAgency/ghidra/blob/85e25af7e8f8407c74a0867dfeb6ec8f035fcdd6/Ghidra/Features/Base/src/main/java/ghidra/app/plugin/core/codebrowser/ListingHighlightProvider.java#L145-L154

https://github.com/NationalSecurityAgency/ghidra/blob/85e25af7e8f8407c74a0867dfeb6ec8f035fcdd6/Ghidra/Features/Base/src/main/java/ghidra/app/plugin/core/codebrowser/ListingHighlightProvider.java#L161-L175

In my case:
```
currentHighlightPattern = \QR15\E|\QR15\E|\QR15D\E|\QR15W\E|\QR15B\E
text = R15D,AX
start = 0
end = 2
```
`c` ends up being `'D'`, which causes it to return false.

I think the smaller r15 regex pattern should be moved to the end of the `currentHighlightPattern` regex, or we need to match on the longest pattern.  I don't really know this code though, so I have to verify with others...I'm not sure what else that would affect/break.

**Comment by mumbel** [comment]
https://xkcd.com/1171/  
Thanks for tracing down down the issue, I skipped over this whole chunk when I was looking at it
