### ISSUE TITLE
x86: inconsistent offset output

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#829]
9.0.4, but probably 9.1.0 DEV
The current SLIEGH has inconsistent syntax when it comes to specifying offsets.  Ex:
```
MOV        qword ptr [RBX + 0x8],R15
MOV        qword ptr [0x450 + RBX],RSI
```
Is there reasoning behind this (nicer listing output/etc) or just how it happened to be coded.

Expecting
`offset = base + (index * scale) + displacement`

**Comment by emteere** [comment]
I believe the original thinking was that larger constants would most likely be memory locations, where smaller ones would be offsets.  I'm not against changing this.

We've also considered changing the offsets to be +/- in some of the instructions.  Again the original thinking was that the offset was mostly likely a memory location value.  The down-side is any memory location that has the high bit set would be shown as a negative value.  Probably not a big issue since a reference will be created over it.

In truth the issue would be a splitting of the sub-constructor and possibly constructor to handle the +/- display so you don't get [EAX + -0x7ffffff4] for an 0x8000000C address.
