### ISSUE TITLE
COMPUTED_CALL inside function causing FlowOverride CALL_RETURN to CALL_TERMINATOR at all function callsites – how to compensate?

### ISSUE THREAD

**Issue by tnballo** [NationalSecurityAgency/ghidra#889]
**Problem:**
Ghidra 9.0.4 is identifying Linux kernel (ARM, 4.4.138) `printk` as a function that does not return, thus _all_ `printk` callsite are marked `-- FlowOverride: CALL_RETURN (CALL_TERMINATOR)`. Both `printk`’s assembly and decompiler output have explicit returns. 

**Sample broken function callsite:**
![callsite](https://user-images.githubusercontent.com/24994892/62734408-fc730300-b9f6-11e9-9230-3be2008f713a.JPG)

**Function assembly and decompile:**
![function](https://user-images.githubusercontent.com/24994892/62734424-039a1100-b9f7-11e9-9aa8-3878b79c0e26.JPG)

**Assumed root cause:**
The instruction `blx r3` @ 0xc00622d4 – a `COMPUTED_CALL` that indexes into a table of function pointers, some of which may never return (in theory, only couple table entries are populated AFAIK). Ghidra can’t know in advance which function will get called – so this is not a bug, just something I need to compensate for.

**Fixes attempted, before running any auto-analysis (preventative):**
* Marking `printk` as a function that returns (`func.setNoReturn(False)` and GUI equivalent), in addition to setting a correct function signature. _Problem: this is undone by auto-analysis._
* Explicitly setting the register value of `r3` to a function that will return right before `blx r3`, to inform Ghidra that the FlowOverride is unnecessary. _Problem: this has no effect._

**Fixes attempted, after running any auto-analysis (retroactive):**
* Script that iterates printk callsites, undoes FlowOverride, and disassembles subsequent instructions. _Problem: next time auto-analysis is run, this work is undone – Ghidra reverts the callsites back to the original state (FlowOverride, missing disassembly)_.

**My goal:**
Get Ghidra to treat `printk` as a function that returns, have auto-analysis be able to diassemble instructions after all `printk` callsites.

**Comment by emteere** [comment]
Before analyzing you can turn off the Discover Non-Returning functions analyzer.  If you have non-returning functions, you can run the FixupNoReturn script after correct analysis of your switch table.

For identifying the real culprit, you can run the FixupNoReturn script to find the locations that indicate that printk is non-returning.  Usually it is some issue after more than one call to printk.  Possibly an instruction after a printk causes a incorrect flow.  The unknown call BLX R3 should not cause this behavior.

Do you have a location to download the same/similar pre-built kernel image?

**Comment by grant-h** [comment]
I'm having the exact same issue in a completely unrelated ARM32/Thumb binary. My call is also to a logging function with the signature:

![image](https://user-images.githubusercontent.com/3030665/66060644-005d6600-e50c-11e9-8a41-4f687d8596bc.png)

**The auto analysis determined that this function was non-returning** (??) which caused all 80,000+ calls to inherit flow overrides as seen below.

![image](https://user-images.githubusercontent.com/3030665/66060860-5c27ef00-e50c-11e9-802d-89ffcbe2f9af.png)

This is greatly hampering my ability to analyze the binary as every decompiled function with a call to `log_printf` has breaks due to the flow overrides. Also, when changing the function's flag from non-returning to returning GHIDRA does not kick off an auto-analysis that removes the non returning flow overrides from the call sites.

So I wrote a script to achieve this, similar to the OP's and I was able to disassemble after the call sites. But the moment I try to change the flow overrides, `log_printf` becomes non-returning again. In my script I've been experimenting with changing the flow overrides only on some call sites. This partially works except on some call sites that have non fall through flow directly following them.

The fix for me has been to disable the "non-returning functions" analyzer (it was unclear that I could disable this) and re-run my script on the affected call sites.

![image](https://user-images.githubusercontent.com/3030665/66063272-04d84d80-e511-11e9-87cf-c650ddaabef4.png)

**Comment by DogeWatch** [comment]
> Before analyzing you can turn off the Discover Non-Returning functions analyzer. If you have non-returning functions, you can run the FixupNoReturn script after correct analysis of your switch table.
> 
> For identifying the real culprit, you can run the FixupNoReturn script to find the locations that indicate that printk is non-returning. Usually it is some issue after more than one call to printk. Possibly an instruction after a printk causes a incorrect flow. The unknown call BLX R3 should not cause this behavior.
> 
> Do you have a location to download the same/similar pre-built kernel image?

how to turn off the Discover Non-Returning functions analyzer with analyzeHeadless ?

**Comment by tnballo** [comment]
Had forgotten about this issue, would like to close the loop.

@emteere - thanks, turning off discover of non-returning functions worked well enough for me (same approach as @grant-h). Unfortunately I don't have a same/similar kernel image I can share. 

@DogeWatch - at the time I was working on this, I was using the Jython API and provided the following Python script for `analyzeHeadless`'s `-preScript` flag:

```python
# Ensure starting with default
resetAllAnalysisOptions(currentProgram)

opts = {
    "ARM Aggressive Instruction Finder": "true",
    "Scalar Operand References": "true",
    "Non-Returning Functions - Discovered": "false"
}

for opt, val in opts.iteritems():
    setAnalysisOption(currentProgram, opt, val)
    assert(getCurrentAnalysisOptionsAndValues(currentProgram)[opt] == val)
    println("\'{}\' -> {}".format(opt, val))
```

If I were doing this today, I'd use the Java API to create an equivalent. I forget the details, but I recall it being more robust/supported.

**Closing this issue now since my original problem was fixed.**

**Comment by userse31** [comment]
Similar boat here! "MSG_HIGH", which is a Qualcomm BREW function analogous to printk(), does the same thing.

Unchecked "No Return" in the "Edit Thunk Function" dialog box for MSG_HIGH. I don't think it helped? Or maybe it is a little bit, but it's still doing this whole thing.

**Comment by colincaldwell1231-design** [comment]
Appreciate the info. If unchecking “No Return” didn’t fully help, there
might be something else influencing the analysis—worth digging deeper.
