### ISSUE TITLE
Disabling Specific Analyzers in Headless Analyzer

### ISSUE THREAD

**Issue by Qdjohnson42** [NationalSecurityAgency/ghidra#893]
I am new to using Ghidra. I am curious onto whether or not it is possible to disable specific analyzers while in Headless Analyze mode. I noticed it is possible when in GUI but cannot seem to figure out how to do it when analyzing headlessly. I am trying to run a python script as a post-script to extract specific function/instruction calls in a binary and would like to disable various analyzers to improve on processing time. Currently, some of the analyzers are taking a very, very long time to complete and majority of those analyzers I do not actually need in order to conduct my extraction (Like Decompiler Analyzer) but I am not sure how to disable them when I'm analyzing headless, if its possible.

**Comment by ryanmkurtz** [comment]
Check out [this](https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Features/Base/ghidra_scripts/GetAndSetAnalysisOptionsScript.java) script for an example of how you control analysis options from a script.  You will need to do this from a prescript, since postscripts run after analysis is complete.

**Comment by ryanmkurtz** [comment]
[Here](https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Features/FunctionID/ghidra_scripts/FunctionIDHeadlessPrescript.java) is a slightly better example for you, doing exactly what you want I think.
