### ISSUE TITLE
Disassemble feature removed tool

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#904]
9.0.4

I have no clue what I did and can't reproduce, so just labeling as question.

The code browser lost the ability to disassemble.  All references we're just gone, no menu items, no key bindings worked, the key bindings line items were not listed anymore in the key bindings settings screen.

I ended up deleting code browser and re-importing default tools.

The only thing I can think is I did some screen reorganizing and saved the tool, is there any chance a feature like disassemble just gets removed with that action?

**Comment by ryanmkurtz** [comment]
Sounds like the DecompilePlugin got removed.  I would have thought that bringing in a new CodeBrowser tool from Default Tools would have fixed it.  If you go to File --> Configure from your CodeBrowser, and then click the plug icon (Configure All Plugins), is DecompilePlugin checked?

**Comment by mumbel** [comment]
The 'import default tools' did fix it, sorry that wasn't clear.  I will check this though if I ever get into this state again, didn't think of looking there before blowing everything away

**Comment by ryanmkurtz** [comment]
Hmmm not sure why I mentioned the DecompilePlugin in my answer since you only mentioned disassemble.  In any event, if menu items and key bindings start disappearing, it usually means the corresponding plugin got removed somehow.  Sounds like you were probably talking about the DisassemblerPlugin, which provides the 'D' key bind.
