### ISSUE TITLE
XDG Base Directory Specification not followed

### ISSUE THREAD

**Issue by ghost** [NationalSecurityAgency/ghidra#908]
**Describe the bug**
Ghidra does not follow the [XDG Base Directories Specification.](https://wiki.archlinux.org/index.php/XDG_Base_Directory)

**To Reproduce**
1. Install ghidra
2. Run ghidra

**Expected behavior**
Following the XDG Base Directory Specification.

**Environment (please complete the following information):**
 - OS: Arch Linux
 - Java Version: 
 ```
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-b05)
OpenJDK 64-Bit Server VM (build 25.222-b05, mixed mode)
 ```
 - Ghidra Version: 8369ef12a28028a920b041c693ae75f75ffce807

**Comment by BilLOPGVkPPn8z0JGJhgiAGNo9YAqpk5ruChl0F** [comment]
The homepage claims support of Linux and macOS. Perhaps it would be useful to use tags to differentiate between various priority levels of bugs, rather than treating minor bugs as "enhancements". Not sure how the application's config directory is handled on Windows, but I hope it is with APPDIR, and not the same dotfolder which aren't even hidden on Windows.

**Comment by nsajko** [comment]
@billop To be fair, the specification has nothing to do with Linux (the kernel). So this is not a defect/bug.

But this is coming from someone who sometimes uses some Environment variables defined by the specification.

**Comment by billop** [comment]
Good point, I meant a mainstream linux distro, speaking of "Linux" as an OS. I assumed that Ghidra touting support for Linux meant that as well.

**Comment by hadess** [comment]
This is blocking my attempt at packaging Ghidra for Flatpak, as the application expects to be installed in a directory which is writable by the user, which is not going to be the case for Flatpak or system-installed software.

For reference: https://github.com/flathub/flathub/pull/1068

**Comment by ryanmkurtz** [comment]
How does XDG handle remote home directories?  If you are storing a lot of large cached files in ~/.cache/<app>, is there anything following the standard that will stop those files from being written to the remote location?

**Comment by Avamander** [comment]
@ryanmkurtz 
> How does XDG handle remote home directories?  If you are storing a lot of large cached files in ~/.cache/<app>, is there anything following the standard that will stop those files from being written to the remote location?

Safe to assume it's handled better in those setups than a random dotfolder in $HOME.

**Comment by ryanmkurtz** [comment]
Ghidra's cache directory is not in $HOME...

**Comment by ryanmkurtz** [comment]
Do be more clear, I'm asking if XDG offers something similar to %LOCALAPPDATA% in Windows.  We need to support "roaming profiles" and can't store large cached files in the user's home directory unless it can somehow be exempt from remote storage while in there like it can on Windows.  That's why Ghidra's cache directory is currently in the far-from-ideal temp directory on linux.

**Comment by nsajko** [comment]
@ryanmkurtz I don't know anything about Windows, but it sounds like you want XDG_CACHE_HOME. It's described on the Arch wiki page which Billop referenced in the original post above, and this seems to be the official reference: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

Basically, if I defined XDG_CACHE_HOME to be the name of a directory, Ghidra should put all cache files recursively within that directory.

**Comment by ryanmkurtz** [comment]
@nsajko, thanks, that is my understanding too.  And by default, that will be at `$HOME/.cache/Ghidra` for Linux users.  Now, if Ghidra gets deployed onto a network where people use network-mounted home directories, it will be a problem if $HOME/.cache/Ghidra gets copied to the network, as it can get quite large.  It would also be an issue to ask every user to set $XDG_CACHE_HOME to something outside of their home directory.   My main question is how does XDG address this use case?

**Comment by nsajko** [comment]
> Now, if Ghidra gets deployed onto a network where people use network-mounted home directories, it will be a problem if $HOME/.cache/Ghidra gets copied to the network, as it can get quite large. It would also be an issue to ask every user to set $XDG_CACHE_HOME to something outside of their home directory.

Presumably whoever deployed Ghidra would set the XDG_CACHE_HOME environment variable. Basic Unix usage as far as I see.

I'm not sure if you already know this, but in Unix (and Linux) environment variables commonly get inherited from the parent process, so it is enough to set the environment variable once in some config file. For example: `/etc/profile`, or `$HOME/.profile`, or it could be done with Systemd. Or you could set it specifically for Ghidra, with a wrapper script, for example.

In any case, I don't quite see what's the problem here.

**Comment by LCRERGO** [comment]
> 

Actually the distro maintainers do not assume that the XDG variables are set, what happens generally when you develop an application that follows the XDG specification is that they try to use the XDG variables if they are set, if not they use what should be "the default" location. e.g:
XDG_CACHE_HOME = $HOME/.cache

It should also be noted that there 5 directories/variables that are included in the XDG specification, but normally on most applications only XDG_CACHE_HOME, XDG_CONFIG_HOME and XDG_DATA_HOME are used. For more details on that I suggest [XDG Base Directory](https://wiki.archlinux.org/title/XDG_Base_Directory).

**Comment by sirus20x6** [comment]
Please follow xdg to the letter. There is no reason to clutter the home directory with this stuff.

**Comment by Jappie3** [comment]
Bumping this issue... it shouldn't be difficult to implement (check env var, otherwise default to the correct location - which is NOT ~/.ghidra) and the XDG spec should *really* be followed. Apps cluttering the home directory is extremely frustrating for end users.

**Comment by sirus20x6** [comment]
You know what. If I have time maybe I'll fix it and make a pull request.

**Comment by liff** [comment]
If it’s of any help, I’ve a [small experiment here](https://github.com/NationalSecurityAgency/ghidra/compare/Ghidra_10.3.1_build...liff:ghidra:03-xdg-basedir?expand=1). Only ever tested briefly on Linux.

**Comment by ryanmkurtz** [comment]
Marking this `Internal-only` because if we decide to implement it, we will want a consistent multi-platform solution and there are a lot of subtleties through the codebase that will have to be addressed.

**Comment by Avamander** [comment]
@ryanmkurtz XDG is only relevant for one platform though, just like for example `%appdata%` on Windows.

If anything, switching to XDG-BD is fixing a bug coming from the mistaken assumption the current approach is multiplatform.

**Comment by ryanmkurtz** [comment]
I know that it's only for Linux, but if we make a change, we will want to use the standard locations on all platforms, not just do something special for Linux (i.e., not create a `~./ghidra/` directory on macOS or Windows either).

We do not consider Ghidra creating a `~/.ghidra` directory a bug.  It is intended behavior.

**Comment by Adamcake** [comment]
Four years since this issue was opened. XDG isn't a very big spec folks, you can read it in about 5 minutes. All I see in this thread is you making excuses, none of which are anywhere near acceptable, and the combined time it took you to type all of them would probably be less than it would take to fix this.

**Comment by dragonmacher** [comment]
I imagine the big issue with this request is that it would require a solution tailored to each major platform we support.  Currently Ghidra uses 1 model that is the same for all OSes.  This makes working on the system simpler for the maintainers.   While implementing XDG may be simple enough, reworking this part of the system to have a cohesive model for all OSes is less so.

**Comment by ryanmkurtz** [comment]
I think changing the directories for each platform would be pretty quick and easy, as would be incorporating the XDG environment variables for Linux and possibly macOS.  There are non-obvious changes that would have to be made to these easy things though too: 

* Continue to support the legacy locations so an upgrade could find the old files
* Provide something in the GUI that would show the current location of all of these directories, maybe in the About window
* Provide a script that would wipe out all or some of these directories.  It's very convenient for the devs to tell people to just wipe out their `~/.ghidra` directory to fix certain issue or rule out others.  Since these locations would now be unpredictable...we'd need a script.
* Ensure we are no longer writing anything to the ghidra installation directory.  We have been slowly addressing this over the years, but certain things still do it, like the recompilation of the `.sla` files.  I am not sure if there are more things like that, but we'd have to fix each one individually.

So, not the hardest thing in the world to accomplish, but also not a quick change to some hardcoded paths either.  I'll bring this up again with the team though.

**Comment by Adamcake** [comment]
> Currently Ghidra uses 1 model that is the same for all OSes.
If Ghidra was coded under the mistaken assumption that there's a cross-platform data storage location, then that's the root of the issue. Start there and work upwards. It's APPDATA on Windows, XDG basedir on Linux, and I don't know what it is on MacOS but probably XDG too.

> Continue to support the legacy locations so an upgrade could find the old files
Ideally, software should just not have any code that writes to the home directory at all. But the way lots of people are solving the "legacy location" issue is by having an environment variable that tells it the location of its data folder, and default to `~/.ghidra` if that env var isn't set. This was an acceptable solution for Audacity, Python, and Git, just for a few examples, so I'd say it'd be an acceptable solution here too.

**Comment by ryanmkurtz** [comment]
I'm working on this now and have a question for people who actually use XDG.  For Ghidra's "user temp" and "user cache" directories, we have been putting them in `/tmp/<user>-Ghidra` on Linux.  In my branch this can now be overridden with `XDG_RUNTIME_DIR` and `XDG_CONFIG_HOME`, and will default to `java.io.tmpdir` and `$HOME/.config`  Typically, `java.io.tmpdir` will just be `/tmp`, so it seems necessary to incorporate the user's name into the subdirectory within `/tmp`.  Other times though, the directory may land within the user's home directory, making it redundant to include the user's name.  Ideally I wouldn't ever have to incorporate the user's name...I don't recall seeing this from other program's too often.  Does anyone know how directory isolation is achieved in practice when the specified locations are in common directories like `/tmp`?

**Comment by ryanmkurtz** [comment]
Thank you.  So is it an error to define `XDG_RUNTIME_DIR` to be in a subdirectory of `/tmp` that is owned by the user?  If so, what other directory meets the criteria of being automatically deleted when the system reboots?  

Or maybe we don't need to control Ghidra's temp usage via XDG, and just have it always use `java.io.tmpdir` with per-process calls to `Flies.createTempDirectory`?  Is that objectionable?

Also, generally speaking, if `XDG_CONFIG_HOME` gets set to something not user specific, is that considered a user-error (i.e., a case I don't need to worry about)?

**Comment by Adamcake** [comment]
My advice would be to get the value of `XDG_RUNTIME_DIR`, or if none is set then use the value of `java.io.tmpdir` instead; store the value and use it for any and all calls to File.createTempDirectory. That would be entirely fine. Temp directories should be specific to one Ghidra session, which makes them implicitly user-specific regardless of where they actually are.

Just out of interest, the value of XDG_RUNTIME_DIR on my system is `/run/user/1000`.

> generally speaking, if XDG_CONFIG_HOME gets set to something not user specific, is that considered a user-error (i.e., a case I don't need to worry about)?

Correct. The basedir spec defines XDG_CONFIG_HOME as: "the base directory relative to which **user-specific** configuration files should be stored". In fact, that's what the `_HOME` part means, it implies it will be inside the user's home directory. In general you can just assume these paths are correct and not do any validation on them (well not beyond reporting and exiting on i/o errors anyway.)

**Comment by ryanmkurtz** [comment]
Ok, thanks again!
