### ISSUE TITLE
MIPS/little/32 word definition

### ISSUE THREAD

**Issue by alexander-pick** [NationalSecurityAgency/ghidra#924]
I am working on a MIPS/little/32/default target at the moment. On Mips 32 a word is 32bit long:

byte(8 bits)
halfword (2 bytes)
**word (4 bytes)**

If I go to a data location and convert data to a word in Ghidra, it will create a 2 byte long dw. 

I use right click on the values, select "data" -> "word" to set the type .

Example result:
![ghidra_example](https://user-images.githubusercontent.com/656911/63359645-6384a600-c36d-11e9-8980-f85577948dd8.PNG)

But it should look like the dword:
![ghidra_example2](https://user-images.githubusercontent.com/656911/63359726-844cfb80-c36d-11e9-961f-ea3b38e6af34.PNG)

**Comment by alexander-pick** [comment]
Aside from the partly weird results with that, that should be CPU dependant. Defaulting words to 16 Bit is technical incorrect, misleading and a source for all kind of errors.

**Comment by astrelsky** [comment]
> Aside from the partly weird results with that, that should be CPU dependant. Defaulting words to 16 Bit is technical incorrect, misleading and a source for all kind of errors.

I do agree. I was just pointing out that it is working as intended by the developers. This could maybe be changed to an enhancement to make the size of halfword, word, and doubleword CPU dependant. However I'm sure the first question would be if there is a reason for not using an existing cou dependent integer such as short, int, long etc. My only thought as to why one would use the word types is if there is a struct defined with them.

**Comment by ghidra1** [comment]
As pointed out by @astrelsky Ghidra's **byte**, **word**, **dword** and **qword** types are all fixed-length and are architecture independent.  Corresponding to 1-byte, 2-bytes, 4-bytes and 8-bytes.  Additional fixed-length types also existing for other sizes (e.g., 3-bytes).  Only the C primitive types (e.g., char, int, etc.) are dynamically sized to reflect the data organization rules imposed by a compiler specification.  Due to the significant impact to existing user data it is unlikely the fixed-length nature of these datatypes will change within Ghidra.
