### ISSUE TITLE
Suspected incorrect FP stack variables in ARM

### ISSUE THREAD

**Issue by Hardcore-fs** [NationalSecurityAgency/ghidra#998]
**Describe the bug**
The stack variables indicated by the  ghidra  arm disassembler appear to be incorrect  on  file types (raw bin/ ELF )when compared to other disassemblers.

ghidra
![Ghidra](https://user-images.githubusercontent.com/1309004/64772963-1a96ca80-d584-11e9-8c00-f96991a6378c.jpeg)

Hopper
![hopper](https://user-images.githubusercontent.com/1309004/64773024-3bf7b680-d584-11e9-92aa-75f2e3674cc2.jpeg)

Shell storm
![shell-storm](https://user-images.githubusercontent.com/1309004/64773198-8416d900-d584-11e9-84ad-fbd882006447.jpeg)

**Comment by ghidra1** [comment]
If the shared fragment is not its' true entry point then it is unlikely that the frame pointer would be initialized from SP and frame-based stack references would not be placed during stack analysis.  If  stack references are being created then it is likely it is a true function and the other function's jumps to its' entry point should be overridden to a call/return.  The Shared Return Analyzer attempts to detect this condition and convert such jumps to another function.

In your Ghidra listing above I do not see a label where another function would have branched into the function shown as you describe. 

Based on your description (i.e., shared code fragment does not initialize frame pointer - function shown above does not represent this case), I would not expect to see stack variable references in the shared code fragment,  In such a case, you may need to rely on the Decompiler and avoid the use of the call/return overrides to the shared fragment function.

**Comment by Hardcore-fs** [comment]
The issue I think is this assumption that the  variables are "relative to  the SP", when clearly the FP is a separate pointer register that can be manipulated as such.....

The  Binary for the instructions is clearly explicit in the encoding of the offset, and to  try some convoluted system "to "reverse-calculate" some irrelevant pointer relationship, seems problematic.

To say for example that:
00003cd8 10000BE5               str        r0, [fp, var_10]
00003cdc 14100BE5               str        r1, [fp, var_14]
these two variables are related to  the SP based on some calculation of the SP register is just  causing problems..  an offset of  0x10 & 0x14 is still an offset to  FP and yes in a round about way an INITIAL SP  value ,but  does it still have  that relationship.. if partway thru the code FP is re-calculated?, let's not forget this is access FP relative not SP relative.


afterall this IS malware analysis

**Comment by ghidra1** [comment]
Stack references are only applied where the access can be traced back to the initial SP at the function entry point.  If FP is recalculated and is not based upon SP, then subsequent FP based accesses would not have stack references applied.  If FP was recalculated based upon SP (which can still be tracked to the initial SP) then that would be properly reflected in any subsequent stack references within the function's code flow.  Only those stack accesses that trace back to a specific stack location (as established at function entry point) will have a stack reference applied, although there are certainly limitations based upon code flow (e.g., loops, shared code, etc.).  Since the use of a frame pointer does not always apply, we have standardized on the use of stack references.  I understand the simplified interpretation that frame-based variable/reference markup could provide in some instances, however at this point we do not have a markup/reference mechanism to support it.  

BTW, it would be pretty simple to write a Ghidra script which could add a EOL comment corresponding to each stack reference, or rename variables, based upon the frame offset.  The script could utilize the CallDepthChangeInfo class to obtain the stack offset for FP at a given instruction to adjust the stack offset used for a reference (or referenced variable) at that address.

I hope this helps.  As the behavior concerns you have are not a bug and are as intended I am closing this issue out.
